// Code generated by go generate; DO NOT EDIT.

// Package iotsitewise holds the cloud control resources of the aws iotsitewise service.
package iotsitewise

type IamRole struct {
	Arn *string `json:"arn,omitempty"`
}

type IamUser struct {
	Arn *string `json:"arn,omitempty"`
}

type User struct {
	Id *string `json:"id,omitempty"`
}

type AccessPolicyIdentity struct {
	IamRole *IamRole `json:"IamRole,omitempty"`
	IamUser *IamUser `json:"IamUser,omitempty"`
	User    *User    `json:"User,omitempty"`
}

type Portal struct {
	Id *string `json:"id,omitempty"`
}

type Project struct {
	Id *string `json:"id,omitempty"`
}

type AccessPolicyResource struct {
	Portal  *Portal  `json:"Portal,omitempty"`
	Project *Project `json:"Project,omitempty"`
}

type AccessPolicy struct {
	AccessPolicyArn        *string               `json:"AccessPolicyArn,omitempty"`
	AccessPolicyId         *string               `json:"AccessPolicyId,omitempty"`
	AccessPolicyIdentity   *AccessPolicyIdentity `json:"AccessPolicyIdentity,omitempty"`
	AccessPolicyPermission *string               `json:"AccessPolicyPermission,omitempty"`
	AccessPolicyResource   *AccessPolicyResource `json:"AccessPolicyResource,omitempty"`
}

func (AccessPolicy) CloudJamType() string { return "AWS::IoTSiteWise::AccessPolicy" }

type AssetHierarchy struct {
	ChildAssetId *string `json:"ChildAssetId,omitempty"`
	ExternalId   *string `json:"ExternalId,omitempty"`
	Id           *string `json:"Id,omitempty"`
	LogicalId    *string `json:"LogicalId,omitempty"`
}

type AssetProperty struct {
	Alias             *string                         `json:"Alias,omitempty"`
	ExternalId        *string                         `json:"ExternalId,omitempty"`
	Id                *string                         `json:"Id,omitempty"`
	LogicalId         *string                         `json:"LogicalId,omitempty"`
	NotificationState *AssetPropertyNotificationState `json:"NotificationState,omitempty"`
	Unit              *string                         `json:"Unit,omitempty"`
}

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Asset struct {
	AssetArn         *string          `json:"AssetArn,omitempty"`
	AssetDescription *string          `json:"AssetDescription,omitempty"`
	AssetExternalId  *string          `json:"AssetExternalId,omitempty"`
	AssetHierarchies []AssetHierarchy `json:"AssetHierarchies,omitempty"`
	AssetId          *string          `json:"AssetId,omitempty"`
	AssetModelId     *string          `json:"AssetModelId,omitempty"`
	AssetName        *string          `json:"AssetName,omitempty"`
	AssetProperties  []AssetProperty  `json:"AssetProperties,omitempty"`
	Tags             []Tag            `json:"Tags,omitempty"`
}

func (Asset) CloudJamType() string { return "AWS::IoTSiteWise::Asset" }

type Attribute struct {
	DefaultValue *string `json:"DefaultValue,omitempty"`
}

type PropertyPathDefinition struct {
	Name *string `json:"Name,omitempty"`
}

type VariableValue struct {
	HierarchyExternalId *string                  `json:"HierarchyExternalId,omitempty"`
	HierarchyId         *string                  `json:"HierarchyId,omitempty"`
	HierarchyLogicalId  *string                  `json:"HierarchyLogicalId,omitempty"`
	PropertyExternalId  *string                  `json:"PropertyExternalId,omitempty"`
	PropertyId          *string                  `json:"PropertyId,omitempty"`
	PropertyLogicalId   *string                  `json:"PropertyLogicalId,omitempty"`
	PropertyPath        []PropertyPathDefinition `json:"PropertyPath,omitempty"`
}

type ExpressionVariable struct {
	Name  *string        `json:"Name,omitempty"`
	Value *VariableValue `json:"Value,omitempty"`
}

type TumblingWindow struct {
	Interval *string `json:"Interval,omitempty"`
	Offset   *string `json:"Offset,omitempty"`
}

type MetricWindow struct {
	Tumbling *TumblingWindow `json:"Tumbling,omitempty"`
}

type Metric struct {
	Expression *string              `json:"Expression,omitempty"`
	Variables  []ExpressionVariable `json:"Variables,omitempty"`
	Window     *MetricWindow        `json:"Window,omitempty"`
}

type Transform struct {
	Expression *string              `json:"Expression,omitempty"`
	Variables  []ExpressionVariable `json:"Variables,omitempty"`
}

type PropertyType struct {
	Attribute *Attribute `json:"Attribute,omitempty"`
	Metric    *Metric    `json:"Metric,omitempty"`
	Transform *Transform `json:"Transform,omitempty"`
	TypeName  *TypeName  `json:"TypeName,omitempty"`
}

type AssetModelProperty struct {
	DataType     *DataType     `json:"DataType,omitempty"`
	DataTypeSpec *DataTypeSpec `json:"DataTypeSpec,omitempty"`
	ExternalId   *string       `json:"ExternalId,omitempty"`
	Id           *string       `json:"Id,omitempty"`
	LogicalId    *string       `json:"LogicalId,omitempty"`
	Name         *string       `json:"Name,omitempty"`
	Type         *PropertyType `json:"Type,omitempty"`
	Unit         *string       `json:"Unit,omitempty"`
}

type AssetModelCompositeModel struct {
	ComposedAssetModelId                     *string              `json:"ComposedAssetModelId,omitempty"`
	CompositeModelProperties                 []AssetModelProperty `json:"CompositeModelProperties,omitempty"`
	Description                              *string              `json:"Description,omitempty"`
	ExternalId                               *string              `json:"ExternalId,omitempty"`
	Id                                       *string              `json:"Id,omitempty"`
	Name                                     *string              `json:"Name,omitempty"`
	ParentAssetModelCompositeModelExternalId *string              `json:"ParentAssetModelCompositeModelExternalId,omitempty"`
	Path                                     []string             `json:"Path,omitempty"`
	Type                                     *string              `json:"Type,omitempty"`
}

type AssetModelHierarchy struct {
	ChildAssetModelId *string `json:"ChildAssetModelId,omitempty"`
	ExternalId        *string `json:"ExternalId,omitempty"`
	Id                *string `json:"Id,omitempty"`
	LogicalId         *string `json:"LogicalId,omitempty"`
	Name              *string `json:"Name,omitempty"`
}

type EnforcedAssetModelInterfacePropertyMapping struct {
	AssetModelPropertyExternalId          *string `json:"AssetModelPropertyExternalId,omitempty"`
	AssetModelPropertyLogicalId           *string `json:"AssetModelPropertyLogicalId,omitempty"`
	InterfaceAssetModelPropertyExternalId *string `json:"InterfaceAssetModelPropertyExternalId,omitempty"`
}

type EnforcedAssetModelInterfaceRelationship struct {
	InterfaceAssetModelId *string                                      `json:"InterfaceAssetModelId,omitempty"`
	PropertyMappings      []EnforcedAssetModelInterfacePropertyMapping `json:"PropertyMappings,omitempty"`
}

type AssetModelTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type AssetModel struct {
	AssetModelArn                            *string                                   `json:"AssetModelArn,omitempty"`
	AssetModelCompositeModels                []AssetModelCompositeModel                `json:"AssetModelCompositeModels,omitempty"`
	AssetModelDescription                    *string                                   `json:"AssetModelDescription,omitempty"`
	AssetModelExternalId                     *string                                   `json:"AssetModelExternalId,omitempty"`
	AssetModelHierarchies                    []AssetModelHierarchy                     `json:"AssetModelHierarchies,omitempty"`
	AssetModelId                             *string                                   `json:"AssetModelId,omitempty"`
	AssetModelName                           *string                                   `json:"AssetModelName,omitempty"`
	AssetModelProperties                     []AssetModelProperty                      `json:"AssetModelProperties,omitempty"`
	AssetModelType                           *string                                   `json:"AssetModelType,omitempty"`
	EnforcedAssetModelInterfaceRelationships []EnforcedAssetModelInterfaceRelationship `json:"EnforcedAssetModelInterfaceRelationships,omitempty"`
	Tags                                     []AssetModelTag                           `json:"Tags,omitempty"`
}

func (AssetModel) CloudJamType() string { return "AWS::IoTSiteWise::AssetModel" }

type AnomalyDetectionComputationModelConfiguration struct {
	InputProperties *string `json:"InputProperties,omitempty"`
	ResultProperty  *string `json:"ResultProperty,omitempty"`
}

type ComputationModelConfiguration struct {
	AnomalyDetection *AnomalyDetectionComputationModelConfiguration `json:"AnomalyDetection,omitempty"`
}

type AssetModelPropertyBindingValue struct {
	AssetModelId *string `json:"AssetModelId,omitempty"`
	PropertyId   *string `json:"PropertyId,omitempty"`
}

type AssetPropertyBindingValue struct {
	AssetId    *string `json:"AssetId,omitempty"`
	PropertyId *string `json:"PropertyId,omitempty"`
}

type ComputationModelDataBindingValue struct {
	AssetModelProperty *AssetModelPropertyBindingValue    `json:"AssetModelProperty,omitempty"`
	AssetProperty      *AssetPropertyBindingValue         `json:"AssetProperty,omitempty"`
	List               []ComputationModelDataBindingValue `json:"List,omitempty"`
}

type ComputationModelTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type ComputationModel struct {
	ComputationModelArn           *string                                     `json:"ComputationModelArn,omitempty"`
	ComputationModelConfiguration *ComputationModelConfiguration              `json:"ComputationModelConfiguration,omitempty"`
	ComputationModelDataBinding   map[string]ComputationModelDataBindingValue `json:"ComputationModelDataBinding,omitempty"`
	ComputationModelDescription   *string                                     `json:"ComputationModelDescription,omitempty"`
	ComputationModelId            *string                                     `json:"ComputationModelId,omitempty"`
	ComputationModelName          *string                                     `json:"ComputationModelName,omitempty"`
	Tags                          []ComputationModelTag                       `json:"Tags,omitempty"`
}

func (ComputationModel) CloudJamType() string { return "AWS::IoTSiteWise::ComputationModel" }

type DashboardTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Dashboard struct {
	DashboardArn         *string        `json:"DashboardArn,omitempty"`
	DashboardDefinition  *string        `json:"DashboardDefinition,omitempty"`
	DashboardDescription *string        `json:"DashboardDescription,omitempty"`
	DashboardId          *string        `json:"DashboardId,omitempty"`
	DashboardName        *string        `json:"DashboardName,omitempty"`
	ProjectId            *string        `json:"ProjectId,omitempty"`
	Tags                 []DashboardTag `json:"Tags,omitempty"`
}

func (Dashboard) CloudJamType() string { return "AWS::IoTSiteWise::Dashboard" }

type KendraSourceDetail struct {
	KnowledgeBaseArn *string `json:"KnowledgeBaseArn,omitempty"`
	RoleArn          *string `json:"RoleArn,omitempty"`
}

type SourceDetail struct {
	Kendra *KendraSourceDetail `json:"Kendra,omitempty"`
}

type DatasetSource struct {
	SourceDetail *SourceDetail              `json:"SourceDetail,omitempty"`
	SourceFormat *DatasetSourceSourceFormat `json:"SourceFormat,omitempty"`
	SourceType   *DatasetSourceSourceType   `json:"SourceType,omitempty"`
}

type DatasetTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Dataset struct {
	DatasetArn         *string        `json:"DatasetArn,omitempty"`
	DatasetDescription *string        `json:"DatasetDescription,omitempty"`
	DatasetId          *string        `json:"DatasetId,omitempty"`
	DatasetName        *string        `json:"DatasetName,omitempty"`
	DatasetSource      *DatasetSource `json:"DatasetSource,omitempty"`
	Tags               []DatasetTag   `json:"Tags,omitempty"`
}

func (Dataset) CloudJamType() string { return "AWS::IoTSiteWise::Dataset" }

type GatewayCapabilitySummary struct {
	CapabilityConfiguration *string `json:"CapabilityConfiguration,omitempty"`
	CapabilityNamespace     *string `json:"CapabilityNamespace,omitempty"`
}

type GreengrassV2 struct {
	CoreDeviceOperatingSystem *GreengrassV2CoreDeviceOperatingSystem `json:"CoreDeviceOperatingSystem,omitempty"`
	CoreDeviceThingName       *string                                `json:"CoreDeviceThingName,omitempty"`
}

type SiemensIE struct {
	IotCoreThingName *string `json:"IotCoreThingName,omitempty"`
}

type GatewayPlatform struct {
	GreengrassV2 *GreengrassV2 `json:"GreengrassV2,omitempty"`
	SiemensIE    *SiemensIE    `json:"SiemensIE,omitempty"`
}

type GatewayTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Gateway struct {
	GatewayCapabilitySummaries []GatewayCapabilitySummary `json:"GatewayCapabilitySummaries,omitempty"`
	GatewayId                  *string                    `json:"GatewayId,omitempty"`
	GatewayName                *string                    `json:"GatewayName,omitempty"`
	GatewayPlatform            *GatewayPlatform           `json:"GatewayPlatform,omitempty"`
	GatewayVersion             *string                    `json:"GatewayVersion,omitempty"`
	Tags                       []GatewayTag               `json:"Tags,omitempty"`
}

func (Gateway) CloudJamType() string { return "AWS::IoTSiteWise::Gateway" }

type PortalPortalAlarms struct {
	AlarmRoleArn          *string `json:"AlarmRoleArn,omitempty"`
	NotificationLambdaArn *string `json:"NotificationLambdaArn,omitempty"`
}

type PortalTypeEntry struct {
	PortalTools []string `json:"PortalTools,omitempty"`
}

type PortalTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type PortalPortal struct {
	Alarms                  *PortalPortalAlarms        `json:"Alarms,omitempty"`
	NotificationSenderEmail *string                    `json:"NotificationSenderEmail,omitempty"`
	PortalArn               *string                    `json:"PortalArn,omitempty"`
	PortalAuthMode          *string                    `json:"PortalAuthMode,omitempty"`
	PortalClientId          *string                    `json:"PortalClientId,omitempty"`
	PortalContactEmail      *string                    `json:"PortalContactEmail,omitempty"`
	PortalDescription       *string                    `json:"PortalDescription,omitempty"`
	PortalId                *string                    `json:"PortalId,omitempty"`
	PortalName              *string                    `json:"PortalName,omitempty"`
	PortalStartUrl          *string                    `json:"PortalStartUrl,omitempty"`
	PortalType              *PortalPortalPortalType    `json:"PortalType,omitempty"`
	PortalTypeConfiguration map[string]PortalTypeEntry `json:"PortalTypeConfiguration,omitempty"`
	RoleArn                 *string                    `json:"RoleArn,omitempty"`
	Tags                    []PortalTag                `json:"Tags,omitempty"`
}

func (PortalPortal) CloudJamType() string { return "AWS::IoTSiteWise::Portal" }

type ProjectTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type ProjectProject struct {
	AssetIds           []string     `json:"AssetIds,omitempty"`
	PortalId           *string      `json:"PortalId,omitempty"`
	ProjectArn         *string      `json:"ProjectArn,omitempty"`
	ProjectDescription *string      `json:"ProjectDescription,omitempty"`
	ProjectId          *string      `json:"ProjectId,omitempty"`
	ProjectName        *string      `json:"ProjectName,omitempty"`
	Tags               []ProjectTag `json:"Tags,omitempty"`
}

func (ProjectProject) CloudJamType() string { return "AWS::IoTSiteWise::Project" }

type AssetPropertyNotificationState string

const (
	AssetPropertyNotificationStateENABLED  AssetPropertyNotificationState = "ENABLED"
	AssetPropertyNotificationStateDISABLED AssetPropertyNotificationState = "DISABLED"
)

type DataType string

const (
	DataTypeSTRING  DataType = "STRING"
	DataTypeINTEGER DataType = "INTEGER"
	DataTypeDOUBLE  DataType = "DOUBLE"
	DataTypeBOOLEAN DataType = "BOOLEAN"
	DataTypeSTRUCT  DataType = "STRUCT"
)

type DataTypeSpec string

const (
	DataTypeSpecAWSALARMSTATE DataTypeSpec = "AWS/ALARM_STATE"
)

type TypeName string

const (
	TypeNameMeasurement TypeName = "Measurement"
	TypeNameAttribute   TypeName = "Attribute"
	TypeNameTransform   TypeName = "Transform"
	TypeNameMetric      TypeName = "Metric"
)

type DatasetSourceSourceFormat string

const (
	DatasetSourceSourceFormatKNOWLEDGEBASE DatasetSourceSourceFormat = "KNOWLEDGE_BASE"
)

type DatasetSourceSourceType string

const (
	DatasetSourceSourceTypeKENDRA DatasetSourceSourceType = "KENDRA"
)

type GreengrassV2CoreDeviceOperatingSystem string

const (
	GreengrassV2CoreDeviceOperatingSystemLINUXAARCH64 GreengrassV2CoreDeviceOperatingSystem = "LINUX_AARCH64"
	GreengrassV2CoreDeviceOperatingSystemLINUXAMD64   GreengrassV2CoreDeviceOperatingSystem = "LINUX_AMD64"
	GreengrassV2CoreDeviceOperatingSystemWINDOWSAMD64 GreengrassV2CoreDeviceOperatingSystem = "WINDOWS_AMD64"
)

type PortalPortalPortalType string

const (
	PortalPortalPortalTypeSITEWISEPORTALV1 PortalPortalPortalType = "SITEWISE_PORTAL_V1"
	PortalPortalPortalTypeSITEWISEPORTALV2 PortalPortalPortalType = "SITEWISE_PORTAL_V2"
)
