// Code generated by go generate; DO NOT EDIT.

package aidevops

// The iam actions of the aws aidevops service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionAllowVendedLogDeliveryForResource  = "aidevops:AllowVendedLogDeliveryForResource"
	ActionAssociateService                   = "aidevops:AssociateService"
	ActionCreateAccessToken                  = "aidevops:CreateAccessToken"
	ActionCreateAgentSpace                   = "aidevops:CreateAgentSpace"
	ActionCreateAsset                        = "aidevops:CreateAsset"
	ActionCreateAssetFile                    = "aidevops:CreateAssetFile"
	ActionCreateBacklogTask                  = "aidevops:CreateBacklogTask"
	ActionCreateChat                         = "aidevops:CreateChat"
	ActionCreateKnowledgeItem                = "aidevops:CreateKnowledgeItem"
	ActionCreateOneTimeLoginSession          = "aidevops:CreateOneTimeLoginSession"
	ActionCreatePrivateConnection            = "aidevops:CreatePrivateConnection"
	ActionCreateTrigger                      = "aidevops:CreateTrigger"
	ActionDeleteAgentSpace                   = "aidevops:DeleteAgentSpace"
	ActionDeleteAsset                        = "aidevops:DeleteAsset"
	ActionDeleteAssetFile                    = "aidevops:DeleteAssetFile"
	ActionDeleteKnowledgeItem                = "aidevops:DeleteKnowledgeItem"
	ActionDeletePrivateConnection            = "aidevops:DeletePrivateConnection"
	ActionDeleteTrigger                      = "aidevops:DeleteTrigger"
	ActionDeregisterService                  = "aidevops:DeregisterService"
	ActionDescribePrivateConnection          = "aidevops:DescribePrivateConnection"
	ActionDescribeServices                   = "aidevops:DescribeServices"
	ActionDescribeSupportLevel               = "aidevops:DescribeSupportLevel"
	ActionDisableOperatorApp                 = "aidevops:DisableOperatorApp"
	ActionDisassociateService                = "aidevops:DisassociateService"
	ActionDiscoverTopology                   = "aidevops:DiscoverTopology"
	ActionEnableOperatorApp                  = "aidevops:EnableOperatorApp"
	ActionEndChatForCase                     = "aidevops:EndChatForCase"
	ActionGetAccessToken                     = "aidevops:GetAccessToken"
	ActionGetAccountUsage                    = "aidevops:GetAccountUsage"
	ActionGetAgentSpace                      = "aidevops:GetAgentSpace"
	ActionGetAsset                           = "aidevops:GetAsset"
	ActionGetAssetContent                    = "aidevops:GetAssetContent"
	ActionGetAssetFile                       = "aidevops:GetAssetFile"
	ActionGetAssociation                     = "aidevops:GetAssociation"
	ActionGetBacklogTask                     = "aidevops:GetBacklogTask"
	ActionGetKnowledgeItem                   = "aidevops:GetKnowledgeItem"
	ActionGetOperatorApp                     = "aidevops:GetOperatorApp"
	ActionGetRecommendation                  = "aidevops:GetRecommendation"
	ActionGetService                         = "aidevops:GetService"
	ActionGetTrigger                         = "aidevops:GetTrigger"
	ActionInitiateChatForCase                = "aidevops:InitiateChatForCase"
	ActionListAccessTokens                   = "aidevops:ListAccessTokens"
	ActionListAgentSpaces                    = "aidevops:ListAgentSpaces"
	ActionListAssetFiles                     = "aidevops:ListAssetFiles"
	ActionListAssetTypes                     = "aidevops:ListAssetTypes"
	ActionListAssetVersions                  = "aidevops:ListAssetVersions"
	ActionListAssets                         = "aidevops:ListAssets"
	ActionListAssociations                   = "aidevops:ListAssociations"
	ActionListBacklogTasks                   = "aidevops:ListBacklogTasks"
	ActionListChats                          = "aidevops:ListChats"
	ActionListExecutions                     = "aidevops:ListExecutions"
	ActionListGoals                          = "aidevops:ListGoals"
	ActionListJournalRecords                 = "aidevops:ListJournalRecords"
	ActionListKnowledgeItemVersions          = "aidevops:ListKnowledgeItemVersions"
	ActionListKnowledgeItems                 = "aidevops:ListKnowledgeItems"
	ActionListPendingMessages                = "aidevops:ListPendingMessages"
	ActionListPrivateConnections             = "aidevops:ListPrivateConnections"
	ActionListRecommendations                = "aidevops:ListRecommendations"
	ActionListServices                       = "aidevops:ListServices"
	ActionListTagsForResource                = "aidevops:ListTagsForResource"
	ActionListTriggers                       = "aidevops:ListTriggers"
	ActionListWebhooks                       = "aidevops:ListWebhooks"
	ActionRegisterService                    = "aidevops:RegisterService"
	ActionRevokeAccessToken                  = "aidevops:RevokeAccessToken"
	ActionRotateAccessToken                  = "aidevops:RotateAccessToken"
	ActionSearchServiceAccessibleResource    = "aidevops:SearchServiceAccessibleResource"
	ActionSendMessage                        = "aidevops:SendMessage"
	ActionTagResource                        = "aidevops:TagResource"
	ActionUntagResource                      = "aidevops:UntagResource"
	ActionUpdateAgentSpace                   = "aidevops:UpdateAgentSpace"
	ActionUpdateApprovalAction               = "aidevops:UpdateApprovalAction"
	ActionUpdateAsset                        = "aidevops:UpdateAsset"
	ActionUpdateAssetFile                    = "aidevops:UpdateAssetFile"
	ActionUpdateAssociation                  = "aidevops:UpdateAssociation"
	ActionUpdateBacklogTask                  = "aidevops:UpdateBacklogTask"
	ActionUpdateGoal                         = "aidevops:UpdateGoal"
	ActionUpdateKnowledgeItem                = "aidevops:UpdateKnowledgeItem"
	ActionUpdateOperatorAppIdpConfig         = "aidevops:UpdateOperatorAppIdpConfig"
	ActionUpdatePrivateConnectionCertificate = "aidevops:UpdatePrivateConnectionCertificate"
	ActionUpdateRecommendation               = "aidevops:UpdateRecommendation"
	ActionUpdateTrigger                      = "aidevops:UpdateTrigger"
	ActionValidateAwsAssociations            = "aidevops:ValidateAwsAssociations"
)

// ActionsList are the list actions, as classified by aws.
var ActionsList = []string{
	ActionListAccessTokens,
	ActionListAgentSpaces,
	ActionListAssetFiles,
	ActionListAssetTypes,
	ActionListAssetVersions,
	ActionListAssets,
	ActionListAssociations,
	ActionListBacklogTasks,
	ActionListChats,
	ActionListExecutions,
	ActionListGoals,
	ActionListJournalRecords,
	ActionListKnowledgeItemVersions,
	ActionListKnowledgeItems,
	ActionListPendingMessages,
	ActionListPrivateConnections,
	ActionListRecommendations,
	ActionListServices,
	ActionListTriggers,
	ActionListWebhooks,
}

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionDescribePrivateConnection,
	ActionDescribeServices,
	ActionGetAccessToken,
	ActionGetAccountUsage,
	ActionGetAgentSpace,
	ActionGetAsset,
	ActionGetAssetContent,
	ActionGetAssetFile,
	ActionGetAssociation,
	ActionGetBacklogTask,
	ActionGetKnowledgeItem,
	ActionGetOperatorApp,
	ActionGetRecommendation,
	ActionGetService,
	ActionGetTrigger,
	ActionListTagsForResource,
	ActionSearchServiceAccessibleResource,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionAssociateService,
	ActionCreateAccessToken,
	ActionCreateAgentSpace,
	ActionCreateAsset,
	ActionCreateAssetFile,
	ActionCreateBacklogTask,
	ActionCreateChat,
	ActionCreateKnowledgeItem,
	ActionCreateOneTimeLoginSession,
	ActionCreatePrivateConnection,
	ActionCreateTrigger,
	ActionDeleteAgentSpace,
	ActionDeleteAsset,
	ActionDeleteAssetFile,
	ActionDeleteKnowledgeItem,
	ActionDeletePrivateConnection,
	ActionDeleteTrigger,
	ActionDeregisterService,
	ActionDescribeSupportLevel,
	ActionDisableOperatorApp,
	ActionDisassociateService,
	ActionDiscoverTopology,
	ActionEnableOperatorApp,
	ActionEndChatForCase,
	ActionInitiateChatForCase,
	ActionRegisterService,
	ActionRevokeAccessToken,
	ActionRotateAccessToken,
	ActionSendMessage,
	ActionUpdateAgentSpace,
	ActionUpdateApprovalAction,
	ActionUpdateAsset,
	ActionUpdateAssetFile,
	ActionUpdateAssociation,
	ActionUpdateBacklogTask,
	ActionUpdateGoal,
	ActionUpdateKnowledgeItem,
	ActionUpdateOperatorAppIdpConfig,
	ActionUpdatePrivateConnectionCertificate,
	ActionUpdateRecommendation,
	ActionUpdateTrigger,
	ActionValidateAwsAssociations,
}

// ActionsPermissions are the permissions actions, as classified by aws.
var ActionsPermissions = []string{
	ActionAllowVendedLogDeliveryForResource,
}

// ActionsTagging are the tagging actions, as classified by aws.
var ActionsTagging = []string{
	ActionTagResource,
	ActionUntagResource,
}
