// Code generated by go generate; DO NOT EDIT.

// Package wafv2 holds the cloud control resources of the aws wafv2 service.
package wafv2

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type IPSet struct {
	Addresses        []string          `json:"Addresses,omitempty"`
	Arn              *string           `json:"Arn,omitempty"`
	Description      *string           `json:"Description,omitempty"`
	IPAddressVersion *IPAddressVersion `json:"IPAddressVersion,omitempty"`
	Id               *string           `json:"Id,omitempty"`
	Name             *string           `json:"Name,omitempty"`
	Scope            *Scope            `json:"Scope,omitempty"`
	Tags             []Tag             `json:"Tags,omitempty"`
}

func (IPSet) CloudJamType() string { return "AWS::WAFv2::IPSet" }

type ConditionActionCondition struct {
	Action *ConditionActionConditionAction `json:"Action,omitempty"`
}

type ConditionLabelNameCondition struct {
	LabelName *string `json:"LabelName,omitempty"`
}

type Condition struct {
	ActionCondition    *ConditionActionCondition    `json:"ActionCondition,omitempty"`
	LabelNameCondition *ConditionLabelNameCondition `json:"LabelNameCondition,omitempty"`
}

type Filter struct {
	Behavior    *FilterBehavior    `json:"Behavior,omitempty"`
	Conditions  []Condition        `json:"Conditions,omitempty"`
	Requirement *FilterRequirement `json:"Requirement,omitempty"`
}

type LoggingConfigurationLoggingFilter struct {
	DefaultBehavior *LoggingConfigurationLoggingFilterDefaultBehavior `json:"DefaultBehavior,omitempty"`
	Filters         []Filter                                          `json:"Filters,omitempty"`
}

type FieldToMatchSingleHeader struct {
	Name *string `json:"Name,omitempty"`
}

type FieldToMatch struct {
	Method       map[string]any            `json:"Method,omitempty"`
	QueryString  map[string]any            `json:"QueryString,omitempty"`
	SingleHeader *FieldToMatchSingleHeader `json:"SingleHeader,omitempty"`
	UriPath      map[string]any            `json:"UriPath,omitempty"`
}

type LoggingConfiguration struct {
	LogDestinationConfigs    []string                           `json:"LogDestinationConfigs,omitempty"`
	LoggingFilter            *LoggingConfigurationLoggingFilter `json:"LoggingFilter,omitempty"`
	ManagedByFirewallManager *bool                              `json:"ManagedByFirewallManager,omitempty"`
	RedactedFields           []FieldToMatch                     `json:"RedactedFields,omitempty"`
	ResourceArn              *string                            `json:"ResourceArn,omitempty"`
}

func (LoggingConfiguration) CloudJamType() string { return "AWS::WAFv2::LoggingConfiguration" }

type RegexPatternSetTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type RegexPatternSet struct {
	Arn                   *string               `json:"Arn,omitempty"`
	Description           *string               `json:"Description,omitempty"`
	Id                    *string               `json:"Id,omitempty"`
	Name                  *string               `json:"Name,omitempty"`
	RegularExpressionList []string              `json:"RegularExpressionList,omitempty"`
	Scope                 *RegexPatternSetScope `json:"Scope,omitempty"`
	Tags                  []RegexPatternSetTag  `json:"Tags,omitempty"`
}

func (RegexPatternSet) CloudJamType() string { return "AWS::WAFv2::RegexPatternSet" }

type LabelSummary struct {
	Name *string `json:"Name,omitempty"`
}

type CustomResponseBody struct {
	Content     *string              `json:"Content,omitempty"`
	ContentType *ResponseContentType `json:"ContentType,omitempty"`
}

type Price struct {
	Amount   *string         `json:"Amount,omitempty"`
	Currency *CryptoCurrency `json:"Currency,omitempty"`
}

type PaymentNetwork struct {
	Chain         *BlockchainChain `json:"Chain,omitempty"`
	Prices        []Price          `json:"Prices,omitempty"`
	WalletAddress *string          `json:"WalletAddress,omitempty"`
}

type CryptoConfig struct {
	PaymentNetworks []PaymentNetwork `json:"PaymentNetworks,omitempty"`
}

type MonetizationConfig struct {
	CryptoConfig *CryptoConfig `json:"CryptoConfig,omitempty"`
	CurrencyMode *CurrencyMode `json:"CurrencyMode,omitempty"`
}

type CustomHTTPHeader struct {
	Name  *string `json:"Name,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type CustomRequestHandling struct {
	InsertHeaders []CustomHTTPHeader `json:"InsertHeaders,omitempty"`
}

type AllowAction struct {
	CustomRequestHandling *CustomRequestHandling `json:"CustomRequestHandling,omitempty"`
}

type CustomResponse struct {
	CustomResponseBodyKey *string            `json:"CustomResponseBodyKey,omitempty"`
	ResponseCode          *int               `json:"ResponseCode,omitempty"`
	ResponseHeaders       []CustomHTTPHeader `json:"ResponseHeaders,omitempty"`
}

type BlockAction struct {
	CustomResponse *CustomResponse `json:"CustomResponse,omitempty"`
}

type CaptchaAction struct {
	CustomRequestHandling *CustomRequestHandling `json:"CustomRequestHandling,omitempty"`
}

type ChallengeAction struct {
	CustomRequestHandling *CustomRequestHandling `json:"CustomRequestHandling,omitempty"`
}

type CountAction struct {
	CustomRequestHandling *CustomRequestHandling `json:"CustomRequestHandling,omitempty"`
}

type MonetizeAction struct {
	PriceMultiplier *string `json:"PriceMultiplier,omitempty"`
}

type RuleAction struct {
	Allow     *AllowAction     `json:"Allow,omitempty"`
	Block     *BlockAction     `json:"Block,omitempty"`
	Captcha   *CaptchaAction   `json:"Captcha,omitempty"`
	Challenge *ChallengeAction `json:"Challenge,omitempty"`
	Count     *CountAction     `json:"Count,omitempty"`
	Monetize  *MonetizeAction  `json:"Monetize,omitempty"`
}

type ImmunityTimeProperty struct {
	ImmunityTime *int `json:"ImmunityTime,omitempty"`
}

type CaptchaConfig struct {
	ImmunityTimeProperty *ImmunityTimeProperty `json:"ImmunityTimeProperty,omitempty"`
}

type ChallengeConfig struct {
	ImmunityTimeProperty *ImmunityTimeProperty `json:"ImmunityTimeProperty,omitempty"`
}

type Label struct {
	Name *string `json:"Name,omitempty"`
}

type AndStatement struct {
	Statements []Statement `json:"Statements,omitempty"`
}

type ForwardedIPConfiguration struct {
	FallbackBehavior *ForwardedIPConfigurationFallbackBehavior `json:"FallbackBehavior,omitempty"`
	HeaderName       *string                                   `json:"HeaderName,omitempty"`
}

type AsnMatchStatement struct {
	AsnList           []int                     `json:"AsnList,omitempty"`
	ForwardedIPConfig *ForwardedIPConfiguration `json:"ForwardedIPConfig,omitempty"`
}

type Body struct {
	OversizeHandling *OversizeHandling `json:"OversizeHandling,omitempty"`
}

type CookieMatchPattern struct {
	All             map[string]any `json:"All,omitempty"`
	ExcludedCookies []string       `json:"ExcludedCookies,omitempty"`
	IncludedCookies []string       `json:"IncludedCookies,omitempty"`
}

type Cookies struct {
	MatchPattern     *CookieMatchPattern `json:"MatchPattern,omitempty"`
	MatchScope       *MapMatchScope      `json:"MatchScope,omitempty"`
	OversizeHandling *OversizeHandling   `json:"OversizeHandling,omitempty"`
}

type HeaderOrder struct {
	OversizeHandling *OversizeHandling `json:"OversizeHandling,omitempty"`
}

type HeaderMatchPattern struct {
	All             map[string]any `json:"All,omitempty"`
	ExcludedHeaders []string       `json:"ExcludedHeaders,omitempty"`
	IncludedHeaders []string       `json:"IncludedHeaders,omitempty"`
}

type Headers struct {
	MatchPattern     *HeaderMatchPattern `json:"MatchPattern,omitempty"`
	MatchScope       *MapMatchScope      `json:"MatchScope,omitempty"`
	OversizeHandling *OversizeHandling   `json:"OversizeHandling,omitempty"`
}

type JA3Fingerprint struct {
	FallbackBehavior *JA3FingerprintFallbackBehavior `json:"FallbackBehavior,omitempty"`
}

type JA4Fingerprint struct {
	FallbackBehavior *JA4FingerprintFallbackBehavior `json:"FallbackBehavior,omitempty"`
}

type JsonMatchPattern struct {
	All           map[string]any `json:"All,omitempty"`
	IncludedPaths []string       `json:"IncludedPaths,omitempty"`
}

type JsonBody struct {
	InvalidFallbackBehavior *BodyParsingFallbackBehavior `json:"InvalidFallbackBehavior,omitempty"`
	MatchPattern            *JsonMatchPattern            `json:"MatchPattern,omitempty"`
	MatchScope              *JsonMatchScope              `json:"MatchScope,omitempty"`
	OversizeHandling        *OversizeHandling            `json:"OversizeHandling,omitempty"`
}

type RuleGroupFieldToMatchSingleHeader struct {
	Name *string `json:"Name,omitempty"`
}

type RuleGroupFieldToMatchSingleQueryArgument struct {
	Name *string `json:"Name,omitempty"`
}

type UriFragment struct {
	FallbackBehavior *UriFragmentFallbackBehavior `json:"FallbackBehavior,omitempty"`
}

type RuleGroupFieldToMatch struct {
	AllQueryArguments   map[string]any                            `json:"AllQueryArguments,omitempty"`
	Body                *Body                                     `json:"Body,omitempty"`
	Cookies             *Cookies                                  `json:"Cookies,omitempty"`
	HeaderOrder         *HeaderOrder                              `json:"HeaderOrder,omitempty"`
	Headers             *Headers                                  `json:"Headers,omitempty"`
	JA3Fingerprint      *JA3Fingerprint                           `json:"JA3Fingerprint,omitempty"`
	JA4Fingerprint      *JA4Fingerprint                           `json:"JA4Fingerprint,omitempty"`
	JsonBody            *JsonBody                                 `json:"JsonBody,omitempty"`
	Method              map[string]any                            `json:"Method,omitempty"`
	QueryString         map[string]any                            `json:"QueryString,omitempty"`
	SingleHeader        *RuleGroupFieldToMatchSingleHeader        `json:"SingleHeader,omitempty"`
	SingleQueryArgument *RuleGroupFieldToMatchSingleQueryArgument `json:"SingleQueryArgument,omitempty"`
	UriFragment         *UriFragment                              `json:"UriFragment,omitempty"`
	UriPath             map[string]any                            `json:"UriPath,omitempty"`
}

type PreParseTextTransformation struct {
	Priority *int                            `json:"Priority,omitempty"`
	Type     *PreParseTextTransformationType `json:"Type,omitempty"`
}

type TextTransformation struct {
	Priority *int                    `json:"Priority,omitempty"`
	Type     *TextTransformationType `json:"Type,omitempty"`
}

type ByteMatchStatement struct {
	FieldToMatch                *RuleGroupFieldToMatch       `json:"FieldToMatch,omitempty"`
	PositionalConstraint        *PositionalConstraint        `json:"PositionalConstraint,omitempty"`
	PreParseTextTransformations []PreParseTextTransformation `json:"PreParseTextTransformations,omitempty"`
	SearchString                *string                      `json:"SearchString,omitempty"`
	SearchStringBase64          *string                      `json:"SearchStringBase64,omitempty"`
	TextTransformations         []TextTransformation         `json:"TextTransformations,omitempty"`
}

type GeoMatchStatement struct {
	CountryCodes      []string                  `json:"CountryCodes,omitempty"`
	ForwardedIPConfig *ForwardedIPConfiguration `json:"ForwardedIPConfig,omitempty"`
}

type IPSetForwardedIPConfiguration struct {
	FallbackBehavior *IPSetForwardedIPConfigurationFallbackBehavior `json:"FallbackBehavior,omitempty"`
	HeaderName       *string                                        `json:"HeaderName,omitempty"`
	Position         *IPSetForwardedIPConfigurationPosition         `json:"Position,omitempty"`
}

type IPSetReferenceStatement struct {
	Arn                    *string                        `json:"Arn,omitempty"`
	IPSetForwardedIPConfig *IPSetForwardedIPConfiguration `json:"IPSetForwardedIPConfig,omitempty"`
}

type LabelMatchStatement struct {
	Key   *string          `json:"Key,omitempty"`
	Scope *LabelMatchScope `json:"Scope,omitempty"`
}

type NotStatement struct {
	Statement *Statement `json:"Statement,omitempty"`
}

type OrStatement struct {
	Statements []Statement `json:"Statements,omitempty"`
}

type RateLimitCookie struct {
	Name                *string              `json:"Name,omitempty"`
	TextTransformations []TextTransformation `json:"TextTransformations,omitempty"`
}

type RateLimitHeader struct {
	Name                *string              `json:"Name,omitempty"`
	TextTransformations []TextTransformation `json:"TextTransformations,omitempty"`
}

type RateLimitJA3Fingerprint struct {
	FallbackBehavior *RateLimitJA3FingerprintFallbackBehavior `json:"FallbackBehavior,omitempty"`
}

type RateLimitJA4Fingerprint struct {
	FallbackBehavior *RateLimitJA4FingerprintFallbackBehavior `json:"FallbackBehavior,omitempty"`
}

type RateLimitLabelNamespace struct {
	Namespace *string `json:"Namespace,omitempty"`
}

type RateLimitQueryArgument struct {
	Name                *string              `json:"Name,omitempty"`
	TextTransformations []TextTransformation `json:"TextTransformations,omitempty"`
}

type RateLimitQueryString struct {
	TextTransformations []TextTransformation `json:"TextTransformations,omitempty"`
}

type RateLimitUriPath struct {
	TextTransformations []TextTransformation `json:"TextTransformations,omitempty"`
}

type RateBasedStatementCustomKey struct {
	ASN            map[string]any           `json:"ASN,omitempty"`
	Cookie         *RateLimitCookie         `json:"Cookie,omitempty"`
	ForwardedIP    map[string]any           `json:"ForwardedIP,omitempty"`
	HTTPMethod     map[string]any           `json:"HTTPMethod,omitempty"`
	Header         *RateLimitHeader         `json:"Header,omitempty"`
	IP             map[string]any           `json:"IP,omitempty"`
	JA3Fingerprint *RateLimitJA3Fingerprint `json:"JA3Fingerprint,omitempty"`
	JA4Fingerprint *RateLimitJA4Fingerprint `json:"JA4Fingerprint,omitempty"`
	LabelNamespace *RateLimitLabelNamespace `json:"LabelNamespace,omitempty"`
	QueryArgument  *RateLimitQueryArgument  `json:"QueryArgument,omitempty"`
	QueryString    *RateLimitQueryString    `json:"QueryString,omitempty"`
	UriPath        *RateLimitUriPath        `json:"UriPath,omitempty"`
}

type RateBasedStatement struct {
	AggregateKeyType    *RateBasedStatementAggregateKeyType `json:"AggregateKeyType,omitempty"`
	CustomKeys          []RateBasedStatementCustomKey       `json:"CustomKeys,omitempty"`
	EvaluationWindowSec *int                                `json:"EvaluationWindowSec,omitempty"`
	ForwardedIPConfig   *ForwardedIPConfiguration           `json:"ForwardedIPConfig,omitempty"`
	Limit               *int                                `json:"Limit,omitempty"`
	ScopeDownStatement  *Statement                          `json:"ScopeDownStatement,omitempty"`
}

type RegexMatchStatement struct {
	FieldToMatch                *RuleGroupFieldToMatch       `json:"FieldToMatch,omitempty"`
	PreParseTextTransformations []PreParseTextTransformation `json:"PreParseTextTransformations,omitempty"`
	RegexString                 *string                      `json:"RegexString,omitempty"`
	TextTransformations         []TextTransformation         `json:"TextTransformations,omitempty"`
}

type RegexPatternSetReferenceStatement struct {
	Arn                         *string                      `json:"Arn,omitempty"`
	FieldToMatch                *RuleGroupFieldToMatch       `json:"FieldToMatch,omitempty"`
	PreParseTextTransformations []PreParseTextTransformation `json:"PreParseTextTransformations,omitempty"`
	TextTransformations         []TextTransformation         `json:"TextTransformations,omitempty"`
}

type SizeConstraintStatement struct {
	ComparisonOperator          *SizeConstraintStatementComparisonOperator `json:"ComparisonOperator,omitempty"`
	FieldToMatch                *RuleGroupFieldToMatch                     `json:"FieldToMatch,omitempty"`
	PreParseTextTransformations []PreParseTextTransformation               `json:"PreParseTextTransformations,omitempty"`
	Size                        *float64                                   `json:"Size,omitempty"`
	TextTransformations         []TextTransformation                       `json:"TextTransformations,omitempty"`
}

type SqliMatchStatement struct {
	FieldToMatch                *RuleGroupFieldToMatch       `json:"FieldToMatch,omitempty"`
	PreParseTextTransformations []PreParseTextTransformation `json:"PreParseTextTransformations,omitempty"`
	SensitivityLevel            *SensitivityLevel            `json:"SensitivityLevel,omitempty"`
	TextTransformations         []TextTransformation         `json:"TextTransformations,omitempty"`
}

type XssMatchStatement struct {
	FieldToMatch                *RuleGroupFieldToMatch       `json:"FieldToMatch,omitempty"`
	PreParseTextTransformations []PreParseTextTransformation `json:"PreParseTextTransformations,omitempty"`
	TextTransformations         []TextTransformation         `json:"TextTransformations,omitempty"`
}

type Statement struct {
	AndStatement                      *AndStatement                      `json:"AndStatement,omitempty"`
	AsnMatchStatement                 *AsnMatchStatement                 `json:"AsnMatchStatement,omitempty"`
	ByteMatchStatement                *ByteMatchStatement                `json:"ByteMatchStatement,omitempty"`
	GeoMatchStatement                 *GeoMatchStatement                 `json:"GeoMatchStatement,omitempty"`
	IPSetReferenceStatement           *IPSetReferenceStatement           `json:"IPSetReferenceStatement,omitempty"`
	LabelMatchStatement               *LabelMatchStatement               `json:"LabelMatchStatement,omitempty"`
	NotStatement                      *NotStatement                      `json:"NotStatement,omitempty"`
	OrStatement                       *OrStatement                       `json:"OrStatement,omitempty"`
	RateBasedStatement                *RateBasedStatement                `json:"RateBasedStatement,omitempty"`
	RegexMatchStatement               *RegexMatchStatement               `json:"RegexMatchStatement,omitempty"`
	RegexPatternSetReferenceStatement *RegexPatternSetReferenceStatement `json:"RegexPatternSetReferenceStatement,omitempty"`
	SizeConstraintStatement           *SizeConstraintStatement           `json:"SizeConstraintStatement,omitempty"`
	SqliMatchStatement                *SqliMatchStatement                `json:"SqliMatchStatement,omitempty"`
	XssMatchStatement                 *XssMatchStatement                 `json:"XssMatchStatement,omitempty"`
}

type VisibilityConfig struct {
	CloudWatchMetricsEnabled *bool   `json:"CloudWatchMetricsEnabled,omitempty"`
	MetricName               *string `json:"MetricName,omitempty"`
	SampledRequestsEnabled   *bool   `json:"SampledRequestsEnabled,omitempty"`
}

type Rule struct {
	Action           *RuleAction       `json:"Action,omitempty"`
	CaptchaConfig    *CaptchaConfig    `json:"CaptchaConfig,omitempty"`
	ChallengeConfig  *ChallengeConfig  `json:"ChallengeConfig,omitempty"`
	Name             *string           `json:"Name,omitempty"`
	Priority         *int              `json:"Priority,omitempty"`
	RuleLabels       []Label           `json:"RuleLabels,omitempty"`
	Statement        *Statement        `json:"Statement,omitempty"`
	VisibilityConfig *VisibilityConfig `json:"VisibilityConfig,omitempty"`
}

type RuleGroupTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type RuleGroup struct {
	Arn                  *string                       `json:"Arn,omitempty"`
	AvailableLabels      []LabelSummary                `json:"AvailableLabels,omitempty"`
	Capacity             *int                          `json:"Capacity,omitempty"`
	ConsumedLabels       []LabelSummary                `json:"ConsumedLabels,omitempty"`
	CustomResponseBodies map[string]CustomResponseBody `json:"CustomResponseBodies,omitempty"`
	Description          *string                       `json:"Description,omitempty"`
	Id                   *string                       `json:"Id,omitempty"`
	LabelNamespace       *string                       `json:"LabelNamespace,omitempty"`
	MonetizationConfig   *MonetizationConfig           `json:"MonetizationConfig,omitempty"`
	Name                 *string                       `json:"Name,omitempty"`
	Rules                []Rule                        `json:"Rules,omitempty"`
	Scope                *RuleGroupScope               `json:"Scope,omitempty"`
	Tags                 []RuleGroupTag                `json:"Tags,omitempty"`
	VisibilityConfig     *VisibilityConfig             `json:"VisibilityConfig,omitempty"`
}

func (RuleGroup) CloudJamType() string { return "AWS::WAFv2::RuleGroup" }

type ApplicationAttribute struct {
	Name   *string  `json:"Name,omitempty"`
	Values []string `json:"Values,omitempty"`
}

type ApplicationConfig struct {
	Attributes []ApplicationAttribute `json:"Attributes,omitempty"`
}

type RequestBodyAssociatedResourceTypeConfig struct {
	DefaultSizeInspectionLimit *SizeInspectionLimit `json:"DefaultSizeInspectionLimit,omitempty"`
}

type AssociationConfig struct {
	RequestBody map[string]RequestBodyAssociatedResourceTypeConfig `json:"RequestBody,omitempty"`
}

type WebACLImmunityTimeProperty struct {
	ImmunityTime *int `json:"ImmunityTime,omitempty"`
}

type WebACLCaptchaConfig struct {
	ImmunityTimeProperty *WebACLImmunityTimeProperty `json:"ImmunityTimeProperty,omitempty"`
}

type WebACLChallengeConfig struct {
	ImmunityTimeProperty *WebACLImmunityTimeProperty `json:"ImmunityTimeProperty,omitempty"`
}

type WebACLCustomResponseBody struct {
	Content     *string                    `json:"Content,omitempty"`
	ContentType *WebACLResponseContentType `json:"ContentType,omitempty"`
}

type FieldToProtect struct {
	FieldKeys []string                 `json:"FieldKeys,omitempty"`
	FieldType *FieldToProtectFieldType `json:"FieldType,omitempty"`
}

type DataProtect struct {
	Action                  *DataProtectionAction `json:"Action,omitempty"`
	ExcludeRateBasedDetails *bool                 `json:"ExcludeRateBasedDetails,omitempty"`
	ExcludeRuleMatchDetails *bool                 `json:"ExcludeRuleMatchDetails,omitempty"`
	Field                   *FieldToProtect       `json:"Field,omitempty"`
}

type DataProtectionConfig struct {
	DataProtections []DataProtect `json:"DataProtections,omitempty"`
}

type WebACLCustomHTTPHeader struct {
	Name  *string `json:"Name,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type WebACLCustomRequestHandling struct {
	InsertHeaders []WebACLCustomHTTPHeader `json:"InsertHeaders,omitempty"`
}

type WebACLAllowAction struct {
	CustomRequestHandling *WebACLCustomRequestHandling `json:"CustomRequestHandling,omitempty"`
}

type WebACLCustomResponse struct {
	CustomResponseBodyKey *string                  `json:"CustomResponseBodyKey,omitempty"`
	ResponseCode          *int                     `json:"ResponseCode,omitempty"`
	ResponseHeaders       []WebACLCustomHTTPHeader `json:"ResponseHeaders,omitempty"`
}

type WebACLBlockAction struct {
	CustomResponse *WebACLCustomResponse `json:"CustomResponse,omitempty"`
}

type DefaultAction struct {
	Allow *WebACLAllowAction `json:"Allow,omitempty"`
	Block *WebACLBlockAction `json:"Block,omitempty"`
}

type WebACLPrice struct {
	Amount   *string               `json:"Amount,omitempty"`
	Currency *WebACLCryptoCurrency `json:"Currency,omitempty"`
}

type WebACLPaymentNetwork struct {
	Chain         *WebACLBlockchainChain `json:"Chain,omitempty"`
	Prices        []WebACLPrice          `json:"Prices,omitempty"`
	WalletAddress *string                `json:"WalletAddress,omitempty"`
}

type WebACLCryptoConfig struct {
	PaymentNetworks []WebACLPaymentNetwork `json:"PaymentNetworks,omitempty"`
}

type WebACLMonetizationConfig struct {
	CryptoConfig *WebACLCryptoConfig `json:"CryptoConfig,omitempty"`
	CurrencyMode *WebACLCurrencyMode `json:"CurrencyMode,omitempty"`
}

type OnSourceDDoSProtectionConfig struct {
	ALBLowReputationMode *OnSourceDDoSProtectionConfigALBLowReputationMode `json:"ALBLowReputationMode,omitempty"`
}

type WebACLCaptchaAction struct {
	CustomRequestHandling *WebACLCustomRequestHandling `json:"CustomRequestHandling,omitempty"`
}

type WebACLChallengeAction struct {
	CustomRequestHandling *WebACLCustomRequestHandling `json:"CustomRequestHandling,omitempty"`
}

type WebACLCountAction struct {
	CustomRequestHandling *WebACLCustomRequestHandling `json:"CustomRequestHandling,omitempty"`
}

type WebACLMonetizeAction struct {
	PriceMultiplier *string `json:"PriceMultiplier,omitempty"`
}

type WebACLRuleAction struct {
	Allow     *WebACLAllowAction     `json:"Allow,omitempty"`
	Block     *WebACLBlockAction     `json:"Block,omitempty"`
	Captcha   *WebACLCaptchaAction   `json:"Captcha,omitempty"`
	Challenge *WebACLChallengeAction `json:"Challenge,omitempty"`
	Count     *WebACLCountAction     `json:"Count,omitempty"`
	Monetize  *WebACLMonetizeAction  `json:"Monetize,omitempty"`
}

type OverrideAction struct {
	Count map[string]any `json:"Count,omitempty"`
	None  map[string]any `json:"None,omitempty"`
}

type WebACLLabel struct {
	Name *string `json:"Name,omitempty"`
}

type WebACLAndStatement struct {
	Statements []WebACLStatement `json:"Statements,omitempty"`
}

type WebACLForwardedIPConfiguration struct {
	FallbackBehavior *WebACLForwardedIPConfigurationFallbackBehavior `json:"FallbackBehavior,omitempty"`
	HeaderName       *string                                         `json:"HeaderName,omitempty"`
}

type WebACLAsnMatchStatement struct {
	AsnList           []int                           `json:"AsnList,omitempty"`
	ForwardedIPConfig *WebACLForwardedIPConfiguration `json:"ForwardedIPConfig,omitempty"`
}

type WebACLBody struct {
	OversizeHandling *WebACLOversizeHandling `json:"OversizeHandling,omitempty"`
}

type WebACLCookieMatchPattern struct {
	All             map[string]any `json:"All,omitempty"`
	ExcludedCookies []string       `json:"ExcludedCookies,omitempty"`
	IncludedCookies []string       `json:"IncludedCookies,omitempty"`
}

type WebACLCookies struct {
	MatchPattern     *WebACLCookieMatchPattern `json:"MatchPattern,omitempty"`
	MatchScope       *WebACLMapMatchScope      `json:"MatchScope,omitempty"`
	OversizeHandling *WebACLOversizeHandling   `json:"OversizeHandling,omitempty"`
}

type WebACLHeaderOrder struct {
	OversizeHandling *WebACLOversizeHandling `json:"OversizeHandling,omitempty"`
}

type WebACLHeaderMatchPattern struct {
	All             map[string]any `json:"All,omitempty"`
	ExcludedHeaders []string       `json:"ExcludedHeaders,omitempty"`
	IncludedHeaders []string       `json:"IncludedHeaders,omitempty"`
}

type WebACLHeaders struct {
	MatchPattern     *WebACLHeaderMatchPattern `json:"MatchPattern,omitempty"`
	MatchScope       *WebACLMapMatchScope      `json:"MatchScope,omitempty"`
	OversizeHandling *WebACLOversizeHandling   `json:"OversizeHandling,omitempty"`
}

type WebACLJA3Fingerprint struct {
	FallbackBehavior *WebACLJA3FingerprintFallbackBehavior `json:"FallbackBehavior,omitempty"`
}

type WebACLJA4Fingerprint struct {
	FallbackBehavior *WebACLJA4FingerprintFallbackBehavior `json:"FallbackBehavior,omitempty"`
}

type WebACLJsonMatchPattern struct {
	All           map[string]any `json:"All,omitempty"`
	IncludedPaths []string       `json:"IncludedPaths,omitempty"`
}

type WebACLJsonBody struct {
	InvalidFallbackBehavior *WebACLBodyParsingFallbackBehavior `json:"InvalidFallbackBehavior,omitempty"`
	MatchPattern            *WebACLJsonMatchPattern            `json:"MatchPattern,omitempty"`
	MatchScope              *WebACLJsonMatchScope              `json:"MatchScope,omitempty"`
	OversizeHandling        *WebACLOversizeHandling            `json:"OversizeHandling,omitempty"`
}

type WebACLFieldToMatchSingleHeader struct {
	Name *string `json:"Name,omitempty"`
}

type WebACLFieldToMatchSingleQueryArgument struct {
	Name *string `json:"Name,omitempty"`
}

type WebACLUriFragment struct {
	FallbackBehavior *WebACLUriFragmentFallbackBehavior `json:"FallbackBehavior,omitempty"`
}

type WebACLFieldToMatch struct {
	AllQueryArguments   map[string]any                         `json:"AllQueryArguments,omitempty"`
	Body                *WebACLBody                            `json:"Body,omitempty"`
	Cookies             *WebACLCookies                         `json:"Cookies,omitempty"`
	HeaderOrder         *WebACLHeaderOrder                     `json:"HeaderOrder,omitempty"`
	Headers             *WebACLHeaders                         `json:"Headers,omitempty"`
	JA3Fingerprint      *WebACLJA3Fingerprint                  `json:"JA3Fingerprint,omitempty"`
	JA4Fingerprint      *WebACLJA4Fingerprint                  `json:"JA4Fingerprint,omitempty"`
	JsonBody            *WebACLJsonBody                        `json:"JsonBody,omitempty"`
	Method              map[string]any                         `json:"Method,omitempty"`
	QueryString         map[string]any                         `json:"QueryString,omitempty"`
	SingleHeader        *WebACLFieldToMatchSingleHeader        `json:"SingleHeader,omitempty"`
	SingleQueryArgument *WebACLFieldToMatchSingleQueryArgument `json:"SingleQueryArgument,omitempty"`
	UriFragment         *WebACLUriFragment                     `json:"UriFragment,omitempty"`
	UriPath             map[string]any                         `json:"UriPath,omitempty"`
}

type WebACLPreParseTextTransformation struct {
	Priority *int                                  `json:"Priority,omitempty"`
	Type     *WebACLPreParseTextTransformationType `json:"Type,omitempty"`
}

type WebACLTextTransformation struct {
	Priority *int                          `json:"Priority,omitempty"`
	Type     *WebACLTextTransformationType `json:"Type,omitempty"`
}

type WebACLByteMatchStatement struct {
	FieldToMatch                *WebACLFieldToMatch                `json:"FieldToMatch,omitempty"`
	PositionalConstraint        *WebACLPositionalConstraint        `json:"PositionalConstraint,omitempty"`
	PreParseTextTransformations []WebACLPreParseTextTransformation `json:"PreParseTextTransformations,omitempty"`
	SearchString                *string                            `json:"SearchString,omitempty"`
	SearchStringBase64          *string                            `json:"SearchStringBase64,omitempty"`
	TextTransformations         []WebACLTextTransformation         `json:"TextTransformations,omitempty"`
}

type WebACLGeoMatchStatement struct {
	CountryCodes      []string                        `json:"CountryCodes,omitempty"`
	ForwardedIPConfig *WebACLForwardedIPConfiguration `json:"ForwardedIPConfig,omitempty"`
}

type WebACLIPSetForwardedIPConfiguration struct {
	FallbackBehavior *WebACLIPSetForwardedIPConfigurationFallbackBehavior `json:"FallbackBehavior,omitempty"`
	HeaderName       *string                                              `json:"HeaderName,omitempty"`
	Position         *WebACLIPSetForwardedIPConfigurationPosition         `json:"Position,omitempty"`
}

type WebACLIPSetReferenceStatement struct {
	Arn                    *string                              `json:"Arn,omitempty"`
	IPSetForwardedIPConfig *WebACLIPSetForwardedIPConfiguration `json:"IPSetForwardedIPConfig,omitempty"`
}

type WebACLLabelMatchStatement struct {
	Key   *string                `json:"Key,omitempty"`
	Scope *WebACLLabelMatchScope `json:"Scope,omitempty"`
}

type ExcludedRule struct {
	Name *string `json:"Name,omitempty"`
}

type FieldIdentifier struct {
	Identifier *string `json:"Identifier,omitempty"`
}

type RequestInspectionACFP struct {
	AddressFields     []FieldIdentifier                 `json:"AddressFields,omitempty"`
	EmailField        *FieldIdentifier                  `json:"EmailField,omitempty"`
	PasswordField     *FieldIdentifier                  `json:"PasswordField,omitempty"`
	PayloadType       *RequestInspectionACFPPayloadType `json:"PayloadType,omitempty"`
	PhoneNumberFields []FieldIdentifier                 `json:"PhoneNumberFields,omitempty"`
	UsernameField     *FieldIdentifier                  `json:"UsernameField,omitempty"`
}

type ResponseInspectionBodyContains struct {
	FailureStrings []string `json:"FailureStrings,omitempty"`
	SuccessStrings []string `json:"SuccessStrings,omitempty"`
}

type ResponseInspectionHeader struct {
	FailureValues []string `json:"FailureValues,omitempty"`
	Name          *string  `json:"Name,omitempty"`
	SuccessValues []string `json:"SuccessValues,omitempty"`
}

type ResponseInspectionJson struct {
	FailureValues []string `json:"FailureValues,omitempty"`
	Identifier    *string  `json:"Identifier,omitempty"`
	SuccessValues []string `json:"SuccessValues,omitempty"`
}

type ResponseInspectionStatusCode struct {
	FailureCodes []int `json:"FailureCodes,omitempty"`
	SuccessCodes []int `json:"SuccessCodes,omitempty"`
}

type ResponseInspection struct {
	BodyContains *ResponseInspectionBodyContains `json:"BodyContains,omitempty"`
	Header       *ResponseInspectionHeader       `json:"Header,omitempty"`
	Json         *ResponseInspectionJson         `json:"Json,omitempty"`
	StatusCode   *ResponseInspectionStatusCode   `json:"StatusCode,omitempty"`
}

type AWSManagedRulesACFPRuleSet struct {
	CreationPath         *string                `json:"CreationPath,omitempty"`
	EnableRegexInPath    *bool                  `json:"EnableRegexInPath,omitempty"`
	RegistrationPagePath *string                `json:"RegistrationPagePath,omitempty"`
	RequestInspection    *RequestInspectionACFP `json:"RequestInspection,omitempty"`
	ResponseInspection   *ResponseInspection    `json:"ResponseInspection,omitempty"`
}

type RequestInspection struct {
	PasswordField *FieldIdentifier              `json:"PasswordField,omitempty"`
	PayloadType   *RequestInspectionPayloadType `json:"PayloadType,omitempty"`
	UsernameField *FieldIdentifier              `json:"UsernameField,omitempty"`
}

type AWSManagedRulesATPRuleSet struct {
	EnableRegexInPath  *bool               `json:"EnableRegexInPath,omitempty"`
	LoginPath          *string             `json:"LoginPath,omitempty"`
	RequestInspection  *RequestInspection  `json:"RequestInspection,omitempty"`
	ResponseInspection *ResponseInspection `json:"ResponseInspection,omitempty"`
}

type Regex struct {
	RegexString *string `json:"RegexString,omitempty"`
}

type ClientSideAction struct {
	ExemptUriRegularExpressions []Regex           `json:"ExemptUriRegularExpressions,omitempty"`
	Sensitivity                 *SensitivityToAct `json:"Sensitivity,omitempty"`
	UsageOfAction               *UsageOfAction    `json:"UsageOfAction,omitempty"`
}

type ClientSideActionConfig struct {
	Challenge *ClientSideAction `json:"Challenge,omitempty"`
}

type AWSManagedRulesAntiDDoSRuleSet struct {
	ClientSideActionConfig *ClientSideActionConfig `json:"ClientSideActionConfig,omitempty"`
	SensitivityToBlock     *SensitivityToAct       `json:"SensitivityToBlock,omitempty"`
}

type AWSManagedRulesBotControlRuleSet struct {
	EnableMachineLearning *bool                                            `json:"EnableMachineLearning,omitempty"`
	InspectionLevel       *AWSManagedRulesBotControlRuleSetInspectionLevel `json:"InspectionLevel,omitempty"`
}

type ManagedRuleGroupConfig struct {
	AWSManagedRulesACFPRuleSet       *AWSManagedRulesACFPRuleSet        `json:"AWSManagedRulesACFPRuleSet,omitempty"`
	AWSManagedRulesATPRuleSet        *AWSManagedRulesATPRuleSet         `json:"AWSManagedRulesATPRuleSet,omitempty"`
	AWSManagedRulesAntiDDoSRuleSet   *AWSManagedRulesAntiDDoSRuleSet    `json:"AWSManagedRulesAntiDDoSRuleSet,omitempty"`
	AWSManagedRulesBotControlRuleSet *AWSManagedRulesBotControlRuleSet  `json:"AWSManagedRulesBotControlRuleSet,omitempty"`
	LoginPath                        *string                            `json:"LoginPath,omitempty"`
	PasswordField                    *FieldIdentifier                   `json:"PasswordField,omitempty"`
	PayloadType                      *ManagedRuleGroupConfigPayloadType `json:"PayloadType,omitempty"`
	UsernameField                    *FieldIdentifier                   `json:"UsernameField,omitempty"`
}

type RuleActionOverride struct {
	ActionToUse *WebACLRuleAction `json:"ActionToUse,omitempty"`
	Name        *string           `json:"Name,omitempty"`
}

type ManagedRuleGroupStatement struct {
	ExcludedRules           []ExcludedRule           `json:"ExcludedRules,omitempty"`
	ManagedRuleGroupConfigs []ManagedRuleGroupConfig `json:"ManagedRuleGroupConfigs,omitempty"`
	Name                    *string                  `json:"Name,omitempty"`
	RuleActionOverrides     []RuleActionOverride     `json:"RuleActionOverrides,omitempty"`
	ScopeDownStatement      *WebACLStatement         `json:"ScopeDownStatement,omitempty"`
	VendorName              *string                  `json:"VendorName,omitempty"`
	Version                 *string                  `json:"Version,omitempty"`
}

type WebACLNotStatement struct {
	Statement *WebACLStatement `json:"Statement,omitempty"`
}

type WebACLOrStatement struct {
	Statements []WebACLStatement `json:"Statements,omitempty"`
}

type WebACLRateLimitCookie struct {
	Name                *string                    `json:"Name,omitempty"`
	TextTransformations []WebACLTextTransformation `json:"TextTransformations,omitempty"`
}

type WebACLRateLimitHeader struct {
	Name                *string                    `json:"Name,omitempty"`
	TextTransformations []WebACLTextTransformation `json:"TextTransformations,omitempty"`
}

type WebACLRateLimitJA3Fingerprint struct {
	FallbackBehavior *WebACLRateLimitJA3FingerprintFallbackBehavior `json:"FallbackBehavior,omitempty"`
}

type WebACLRateLimitJA4Fingerprint struct {
	FallbackBehavior *WebACLRateLimitJA4FingerprintFallbackBehavior `json:"FallbackBehavior,omitempty"`
}

type WebACLRateLimitLabelNamespace struct {
	Namespace *string `json:"Namespace,omitempty"`
}

type WebACLRateLimitQueryArgument struct {
	Name                *string                    `json:"Name,omitempty"`
	TextTransformations []WebACLTextTransformation `json:"TextTransformations,omitempty"`
}

type WebACLRateLimitQueryString struct {
	TextTransformations []WebACLTextTransformation `json:"TextTransformations,omitempty"`
}

type WebACLRateLimitUriPath struct {
	TextTransformations []WebACLTextTransformation `json:"TextTransformations,omitempty"`
}

type WebACLRateBasedStatementCustomKey struct {
	ASN            map[string]any                 `json:"ASN,omitempty"`
	Cookie         *WebACLRateLimitCookie         `json:"Cookie,omitempty"`
	ForwardedIP    map[string]any                 `json:"ForwardedIP,omitempty"`
	HTTPMethod     map[string]any                 `json:"HTTPMethod,omitempty"`
	Header         *WebACLRateLimitHeader         `json:"Header,omitempty"`
	IP             map[string]any                 `json:"IP,omitempty"`
	JA3Fingerprint *WebACLRateLimitJA3Fingerprint `json:"JA3Fingerprint,omitempty"`
	JA4Fingerprint *WebACLRateLimitJA4Fingerprint `json:"JA4Fingerprint,omitempty"`
	LabelNamespace *WebACLRateLimitLabelNamespace `json:"LabelNamespace,omitempty"`
	QueryArgument  *WebACLRateLimitQueryArgument  `json:"QueryArgument,omitempty"`
	QueryString    *WebACLRateLimitQueryString    `json:"QueryString,omitempty"`
	UriPath        *WebACLRateLimitUriPath        `json:"UriPath,omitempty"`
}

type WebACLRateBasedStatement struct {
	AggregateKeyType    *WebACLRateBasedStatementAggregateKeyType `json:"AggregateKeyType,omitempty"`
	CustomKeys          []WebACLRateBasedStatementCustomKey       `json:"CustomKeys,omitempty"`
	EvaluationWindowSec *int                                      `json:"EvaluationWindowSec,omitempty"`
	ForwardedIPConfig   *WebACLForwardedIPConfiguration           `json:"ForwardedIPConfig,omitempty"`
	Limit               *int                                      `json:"Limit,omitempty"`
	ScopeDownStatement  *WebACLStatement                          `json:"ScopeDownStatement,omitempty"`
}

type WebACLRegexMatchStatement struct {
	FieldToMatch                *WebACLFieldToMatch                `json:"FieldToMatch,omitempty"`
	PreParseTextTransformations []WebACLPreParseTextTransformation `json:"PreParseTextTransformations,omitempty"`
	RegexString                 *string                            `json:"RegexString,omitempty"`
	TextTransformations         []WebACLTextTransformation         `json:"TextTransformations,omitempty"`
}

type WebACLRegexPatternSetReferenceStatement struct {
	Arn                         *string                            `json:"Arn,omitempty"`
	FieldToMatch                *WebACLFieldToMatch                `json:"FieldToMatch,omitempty"`
	PreParseTextTransformations []WebACLPreParseTextTransformation `json:"PreParseTextTransformations,omitempty"`
	TextTransformations         []WebACLTextTransformation         `json:"TextTransformations,omitempty"`
}

type RuleGroupReferenceStatement struct {
	Arn                 *string              `json:"Arn,omitempty"`
	ExcludedRules       []ExcludedRule       `json:"ExcludedRules,omitempty"`
	RuleActionOverrides []RuleActionOverride `json:"RuleActionOverrides,omitempty"`
}

type WebACLSizeConstraintStatement struct {
	ComparisonOperator          *WebACLSizeConstraintStatementComparisonOperator `json:"ComparisonOperator,omitempty"`
	FieldToMatch                *WebACLFieldToMatch                              `json:"FieldToMatch,omitempty"`
	PreParseTextTransformations []WebACLPreParseTextTransformation               `json:"PreParseTextTransformations,omitempty"`
	Size                        *float64                                         `json:"Size,omitempty"`
	TextTransformations         []WebACLTextTransformation                       `json:"TextTransformations,omitempty"`
}

type WebACLSqliMatchStatement struct {
	FieldToMatch                *WebACLFieldToMatch                `json:"FieldToMatch,omitempty"`
	PreParseTextTransformations []WebACLPreParseTextTransformation `json:"PreParseTextTransformations,omitempty"`
	SensitivityLevel            *WebACLSensitivityLevel            `json:"SensitivityLevel,omitempty"`
	TextTransformations         []WebACLTextTransformation         `json:"TextTransformations,omitempty"`
}

type WebACLXssMatchStatement struct {
	FieldToMatch                *WebACLFieldToMatch                `json:"FieldToMatch,omitempty"`
	PreParseTextTransformations []WebACLPreParseTextTransformation `json:"PreParseTextTransformations,omitempty"`
	TextTransformations         []WebACLTextTransformation         `json:"TextTransformations,omitempty"`
}

type WebACLStatement struct {
	AndStatement                      *WebACLAndStatement                      `json:"AndStatement,omitempty"`
	AsnMatchStatement                 *WebACLAsnMatchStatement                 `json:"AsnMatchStatement,omitempty"`
	ByteMatchStatement                *WebACLByteMatchStatement                `json:"ByteMatchStatement,omitempty"`
	GeoMatchStatement                 *WebACLGeoMatchStatement                 `json:"GeoMatchStatement,omitempty"`
	IPSetReferenceStatement           *WebACLIPSetReferenceStatement           `json:"IPSetReferenceStatement,omitempty"`
	LabelMatchStatement               *WebACLLabelMatchStatement               `json:"LabelMatchStatement,omitempty"`
	ManagedRuleGroupStatement         *ManagedRuleGroupStatement               `json:"ManagedRuleGroupStatement,omitempty"`
	NotStatement                      *WebACLNotStatement                      `json:"NotStatement,omitempty"`
	OrStatement                       *WebACLOrStatement                       `json:"OrStatement,omitempty"`
	RateBasedStatement                *WebACLRateBasedStatement                `json:"RateBasedStatement,omitempty"`
	RegexMatchStatement               *WebACLRegexMatchStatement               `json:"RegexMatchStatement,omitempty"`
	RegexPatternSetReferenceStatement *WebACLRegexPatternSetReferenceStatement `json:"RegexPatternSetReferenceStatement,omitempty"`
	RuleGroupReferenceStatement       *RuleGroupReferenceStatement             `json:"RuleGroupReferenceStatement,omitempty"`
	SizeConstraintStatement           *WebACLSizeConstraintStatement           `json:"SizeConstraintStatement,omitempty"`
	SqliMatchStatement                *WebACLSqliMatchStatement                `json:"SqliMatchStatement,omitempty"`
	XssMatchStatement                 *WebACLXssMatchStatement                 `json:"XssMatchStatement,omitempty"`
}

type WebACLVisibilityConfig struct {
	CloudWatchMetricsEnabled *bool   `json:"CloudWatchMetricsEnabled,omitempty"`
	MetricName               *string `json:"MetricName,omitempty"`
	SampledRequestsEnabled   *bool   `json:"SampledRequestsEnabled,omitempty"`
}

type WebACLRule struct {
	Action           *WebACLRuleAction       `json:"Action,omitempty"`
	CaptchaConfig    *WebACLCaptchaConfig    `json:"CaptchaConfig,omitempty"`
	ChallengeConfig  *WebACLChallengeConfig  `json:"ChallengeConfig,omitempty"`
	Name             *string                 `json:"Name,omitempty"`
	OverrideAction   *OverrideAction         `json:"OverrideAction,omitempty"`
	Priority         *int                    `json:"Priority,omitempty"`
	RuleLabels       []WebACLLabel           `json:"RuleLabels,omitempty"`
	Statement        *WebACLStatement        `json:"Statement,omitempty"`
	VisibilityConfig *WebACLVisibilityConfig `json:"VisibilityConfig,omitempty"`
}

type WebACLTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type WebACL struct {
	ApplicationConfig            *ApplicationConfig                  `json:"ApplicationConfig,omitempty"`
	Arn                          *string                             `json:"Arn,omitempty"`
	AssociationConfig            *AssociationConfig                  `json:"AssociationConfig,omitempty"`
	Capacity                     *int                                `json:"Capacity,omitempty"`
	CaptchaConfig                *WebACLCaptchaConfig                `json:"CaptchaConfig,omitempty"`
	ChallengeConfig              *WebACLChallengeConfig              `json:"ChallengeConfig,omitempty"`
	CustomResponseBodies         map[string]WebACLCustomResponseBody `json:"CustomResponseBodies,omitempty"`
	DataProtectionConfig         *DataProtectionConfig               `json:"DataProtectionConfig,omitempty"`
	DefaultAction                *DefaultAction                      `json:"DefaultAction,omitempty"`
	Description                  *string                             `json:"Description,omitempty"`
	Id                           *string                             `json:"Id,omitempty"`
	LabelNamespace               *string                             `json:"LabelNamespace,omitempty"`
	MonetizationConfig           *WebACLMonetizationConfig           `json:"MonetizationConfig,omitempty"`
	Name                         *string                             `json:"Name,omitempty"`
	OnSourceDDoSProtectionConfig *OnSourceDDoSProtectionConfig       `json:"OnSourceDDoSProtectionConfig,omitempty"`
	Rules                        []WebACLRule                        `json:"Rules,omitempty"`
	Scope                        *WebACLScope                        `json:"Scope,omitempty"`
	Tags                         []WebACLTag                         `json:"Tags,omitempty"`
	TokenDomains                 []string                            `json:"TokenDomains,omitempty"`
	VisibilityConfig             *WebACLVisibilityConfig             `json:"VisibilityConfig,omitempty"`
}

func (WebACL) CloudJamType() string { return "AWS::WAFv2::WebACL" }

type WebACLAssociation struct {
	ResourceArn *string `json:"ResourceArn,omitempty"`
	WebACLArn   *string `json:"WebACLArn,omitempty"`
}

func (WebACLAssociation) CloudJamType() string { return "AWS::WAFv2::WebACLAssociation" }

type IPAddressVersion string

const (
	IPAddressVersionIPV4 IPAddressVersion = "IPV4"
	IPAddressVersionIPV6 IPAddressVersion = "IPV6"
)

type Scope string

const (
	ScopeCLOUDFRONT Scope = "CLOUDFRONT"
	ScopeREGIONAL   Scope = "REGIONAL"
)

type LoggingConfigurationLoggingFilterDefaultBehavior string

const (
	LoggingConfigurationLoggingFilterDefaultBehaviorKEEP LoggingConfigurationLoggingFilterDefaultBehavior = "KEEP"
	LoggingConfigurationLoggingFilterDefaultBehaviorDROP LoggingConfigurationLoggingFilterDefaultBehavior = "DROP"
)

type FilterBehavior string

const (
	FilterBehaviorKEEP FilterBehavior = "KEEP"
	FilterBehaviorDROP FilterBehavior = "DROP"
)

type ConditionActionConditionAction string

const (
	ConditionActionConditionActionALLOW           ConditionActionConditionAction = "ALLOW"
	ConditionActionConditionActionBLOCK           ConditionActionConditionAction = "BLOCK"
	ConditionActionConditionActionCOUNT           ConditionActionConditionAction = "COUNT"
	ConditionActionConditionActionCAPTCHA         ConditionActionConditionAction = "CAPTCHA"
	ConditionActionConditionActionCHALLENGE       ConditionActionConditionAction = "CHALLENGE"
	ConditionActionConditionActionMONETIZE        ConditionActionConditionAction = "MONETIZE"
	ConditionActionConditionActionEXCLUDEDASCOUNT ConditionActionConditionAction = "EXCLUDED_AS_COUNT"
)

type FilterRequirement string

const (
	FilterRequirementMEETSALL FilterRequirement = "MEETS_ALL"
	FilterRequirementMEETSANY FilterRequirement = "MEETS_ANY"
)

type RegexPatternSetScope string

const (
	RegexPatternSetScopeCLOUDFRONT RegexPatternSetScope = "CLOUDFRONT"
	RegexPatternSetScopeREGIONAL   RegexPatternSetScope = "REGIONAL"
)

type ResponseContentType string

const (
	ResponseContentTypeTEXTPLAIN       ResponseContentType = "TEXT_PLAIN"
	ResponseContentTypeTEXTHTML        ResponseContentType = "TEXT_HTML"
	ResponseContentTypeAPPLICATIONJSON ResponseContentType = "APPLICATION_JSON"
)

type BlockchainChain string

const (
	BlockchainChainBASE         BlockchainChain = "BASE"
	BlockchainChainSOLANA       BlockchainChain = "SOLANA"
	BlockchainChainBASESEPOLIA  BlockchainChain = "BASE_SEPOLIA"
	BlockchainChainSOLANADEVNET BlockchainChain = "SOLANA_DEVNET"
)

type CryptoCurrency string

const (
	CryptoCurrencyUSDC CryptoCurrency = "USDC"
)

type CurrencyMode string

const (
	CurrencyModeREAL CurrencyMode = "REAL"
	CurrencyModeTEST CurrencyMode = "TEST"
)

type ForwardedIPConfigurationFallbackBehavior string

const (
	ForwardedIPConfigurationFallbackBehaviorMATCH   ForwardedIPConfigurationFallbackBehavior = "MATCH"
	ForwardedIPConfigurationFallbackBehaviorNOMATCH ForwardedIPConfigurationFallbackBehavior = "NO_MATCH"
)

type OversizeHandling string

const (
	OversizeHandlingCONTINUE OversizeHandling = "CONTINUE"
	OversizeHandlingMATCH    OversizeHandling = "MATCH"
	OversizeHandlingNOMATCH  OversizeHandling = "NO_MATCH"
)

type MapMatchScope string

const (
	MapMatchScopeALL   MapMatchScope = "ALL"
	MapMatchScopeKEY   MapMatchScope = "KEY"
	MapMatchScopeVALUE MapMatchScope = "VALUE"
)

type JA3FingerprintFallbackBehavior string

const (
	JA3FingerprintFallbackBehaviorMATCH   JA3FingerprintFallbackBehavior = "MATCH"
	JA3FingerprintFallbackBehaviorNOMATCH JA3FingerprintFallbackBehavior = "NO_MATCH"
)

type JA4FingerprintFallbackBehavior string

const (
	JA4FingerprintFallbackBehaviorMATCH   JA4FingerprintFallbackBehavior = "MATCH"
	JA4FingerprintFallbackBehaviorNOMATCH JA4FingerprintFallbackBehavior = "NO_MATCH"
)

type BodyParsingFallbackBehavior string

const (
	BodyParsingFallbackBehaviorMATCH            BodyParsingFallbackBehavior = "MATCH"
	BodyParsingFallbackBehaviorNOMATCH          BodyParsingFallbackBehavior = "NO_MATCH"
	BodyParsingFallbackBehaviorEVALUATEASSTRING BodyParsingFallbackBehavior = "EVALUATE_AS_STRING"
)

type JsonMatchScope string

const (
	JsonMatchScopeALL   JsonMatchScope = "ALL"
	JsonMatchScopeKEY   JsonMatchScope = "KEY"
	JsonMatchScopeVALUE JsonMatchScope = "VALUE"
)

type UriFragmentFallbackBehavior string

const (
	UriFragmentFallbackBehaviorMATCH   UriFragmentFallbackBehavior = "MATCH"
	UriFragmentFallbackBehaviorNOMATCH UriFragmentFallbackBehavior = "NO_MATCH"
)

type PositionalConstraint string

const (
	PositionalConstraintEXACTLY      PositionalConstraint = "EXACTLY"
	PositionalConstraintSTARTSWITH   PositionalConstraint = "STARTS_WITH"
	PositionalConstraintENDSWITH     PositionalConstraint = "ENDS_WITH"
	PositionalConstraintCONTAINS     PositionalConstraint = "CONTAINS"
	PositionalConstraintCONTAINSWORD PositionalConstraint = "CONTAINS_WORD"
)

type PreParseTextTransformationType string

const (
	PreParseTextTransformationTypeNONE                             PreParseTextTransformationType = "NONE"
	PreParseTextTransformationTypeURLDECODE                        PreParseTextTransformationType = "URL_DECODE"
	PreParseTextTransformationTypeURLDECODEUNI                     PreParseTextTransformationType = "URL_DECODE_UNI"
	PreParseTextTransformationTypeCOMBINEDUPLICATEQUERYARGSBYCOMMA PreParseTextTransformationType = "COMBINE_DUPLICATE_QUERY_ARGS_BY_COMMA"
	PreParseTextTransformationTypeREPLACESEMICOLONSWITHAMPERSANDS  PreParseTextTransformationType = "REPLACE_SEMICOLONS_WITH_AMPERSANDS"
)

type TextTransformationType string

const (
	TextTransformationTypeNONE               TextTransformationType = "NONE"
	TextTransformationTypeCOMPRESSWHITESPACE TextTransformationType = "COMPRESS_WHITE_SPACE"
	TextTransformationTypeHTMLENTITYDECODE   TextTransformationType = "HTML_ENTITY_DECODE"
	TextTransformationTypeLOWERCASE          TextTransformationType = "LOWERCASE"
	TextTransformationTypeCMDLINE            TextTransformationType = "CMD_LINE"
	TextTransformationTypeURLDECODE          TextTransformationType = "URL_DECODE"
	TextTransformationTypeBASE64DECODE       TextTransformationType = "BASE64_DECODE"
	TextTransformationTypeHEXDECODE          TextTransformationType = "HEX_DECODE"
	TextTransformationTypeMD5                TextTransformationType = "MD5"
	TextTransformationTypeREPLACECOMMENTS    TextTransformationType = "REPLACE_COMMENTS"
	TextTransformationTypeESCAPESEQDECODE    TextTransformationType = "ESCAPE_SEQ_DECODE"
	TextTransformationTypeSQLHEXDECODE       TextTransformationType = "SQL_HEX_DECODE"
	TextTransformationTypeCSSDECODE          TextTransformationType = "CSS_DECODE"
	TextTransformationTypeJSDECODE           TextTransformationType = "JS_DECODE"
	TextTransformationTypeNORMALIZEPATH      TextTransformationType = "NORMALIZE_PATH"
	TextTransformationTypeNORMALIZEPATHWIN   TextTransformationType = "NORMALIZE_PATH_WIN"
	TextTransformationTypeREMOVENULLS        TextTransformationType = "REMOVE_NULLS"
	TextTransformationTypeREPLACENULLS       TextTransformationType = "REPLACE_NULLS"
	TextTransformationTypeBASE64DECODEEXT    TextTransformationType = "BASE64_DECODE_EXT"
	TextTransformationTypeURLDECODEUNI       TextTransformationType = "URL_DECODE_UNI"
	TextTransformationTypeUTF8TOUNICODE      TextTransformationType = "UTF8_TO_UNICODE"
	TextTransformationTypeREMOVEWHITESPACE   TextTransformationType = "REMOVE_WHITESPACE"
	TextTransformationTypeTRIM               TextTransformationType = "TRIM"
	TextTransformationTypeTRIMLEFT           TextTransformationType = "TRIM_LEFT"
	TextTransformationTypeTRIMRIGHT          TextTransformationType = "TRIM_RIGHT"
	TextTransformationTypeREMOVECOMMENTSCHAR TextTransformationType = "REMOVE_COMMENTS_CHAR"
	TextTransformationTypeUPPERCASE          TextTransformationType = "UPPERCASE"
	TextTransformationTypeCMDLINEWIN         TextTransformationType = "CMD_LINE_WIN"
	TextTransformationTypeCMDLINEUNIX        TextTransformationType = "CMD_LINE_UNIX"
	TextTransformationTypeJSDECODEEXT        TextTransformationType = "JS_DECODE_EXT"
	TextTransformationTypeSHA256             TextTransformationType = "SHA256"
)

type IPSetForwardedIPConfigurationFallbackBehavior string

const (
	IPSetForwardedIPConfigurationFallbackBehaviorMATCH   IPSetForwardedIPConfigurationFallbackBehavior = "MATCH"
	IPSetForwardedIPConfigurationFallbackBehaviorNOMATCH IPSetForwardedIPConfigurationFallbackBehavior = "NO_MATCH"
)

type IPSetForwardedIPConfigurationPosition string

const (
	IPSetForwardedIPConfigurationPositionFIRST IPSetForwardedIPConfigurationPosition = "FIRST"
	IPSetForwardedIPConfigurationPositionLAST  IPSetForwardedIPConfigurationPosition = "LAST"
	IPSetForwardedIPConfigurationPositionANY   IPSetForwardedIPConfigurationPosition = "ANY"
)

type LabelMatchScope string

const (
	LabelMatchScopeLABEL     LabelMatchScope = "LABEL"
	LabelMatchScopeNAMESPACE LabelMatchScope = "NAMESPACE"
)

type RateBasedStatementAggregateKeyType string

const (
	RateBasedStatementAggregateKeyTypeIP          RateBasedStatementAggregateKeyType = "IP"
	RateBasedStatementAggregateKeyTypeFORWARDEDIP RateBasedStatementAggregateKeyType = "FORWARDED_IP"
	RateBasedStatementAggregateKeyTypeCONSTANT    RateBasedStatementAggregateKeyType = "CONSTANT"
	RateBasedStatementAggregateKeyTypeCUSTOMKEYS  RateBasedStatementAggregateKeyType = "CUSTOM_KEYS"
)

type RateLimitJA3FingerprintFallbackBehavior string

const (
	RateLimitJA3FingerprintFallbackBehaviorMATCH   RateLimitJA3FingerprintFallbackBehavior = "MATCH"
	RateLimitJA3FingerprintFallbackBehaviorNOMATCH RateLimitJA3FingerprintFallbackBehavior = "NO_MATCH"
)

type RateLimitJA4FingerprintFallbackBehavior string

const (
	RateLimitJA4FingerprintFallbackBehaviorMATCH   RateLimitJA4FingerprintFallbackBehavior = "MATCH"
	RateLimitJA4FingerprintFallbackBehaviorNOMATCH RateLimitJA4FingerprintFallbackBehavior = "NO_MATCH"
)

type SizeConstraintStatementComparisonOperator string

const (
	SizeConstraintStatementComparisonOperatorEQ SizeConstraintStatementComparisonOperator = "EQ"
	SizeConstraintStatementComparisonOperatorNE SizeConstraintStatementComparisonOperator = "NE"
	SizeConstraintStatementComparisonOperatorLE SizeConstraintStatementComparisonOperator = "LE"
	SizeConstraintStatementComparisonOperatorLT SizeConstraintStatementComparisonOperator = "LT"
	SizeConstraintStatementComparisonOperatorGE SizeConstraintStatementComparisonOperator = "GE"
	SizeConstraintStatementComparisonOperatorGT SizeConstraintStatementComparisonOperator = "GT"
)

type SensitivityLevel string

const (
	SensitivityLevelLOW  SensitivityLevel = "LOW"
	SensitivityLevelHIGH SensitivityLevel = "HIGH"
)

type RuleGroupScope string

const (
	RuleGroupScopeCLOUDFRONT RuleGroupScope = "CLOUDFRONT"
	RuleGroupScopeREGIONAL   RuleGroupScope = "REGIONAL"
)

type SizeInspectionLimit string

const (
	SizeInspectionLimitKB16 SizeInspectionLimit = "KB_16"
	SizeInspectionLimitKB32 SizeInspectionLimit = "KB_32"
	SizeInspectionLimitKB48 SizeInspectionLimit = "KB_48"
	SizeInspectionLimitKB64 SizeInspectionLimit = "KB_64"
)

type WebACLResponseContentType string

const (
	WebACLResponseContentTypeTEXTPLAIN       WebACLResponseContentType = "TEXT_PLAIN"
	WebACLResponseContentTypeTEXTHTML        WebACLResponseContentType = "TEXT_HTML"
	WebACLResponseContentTypeAPPLICATIONJSON WebACLResponseContentType = "APPLICATION_JSON"
)

type DataProtectionAction string

const (
	DataProtectionActionSUBSTITUTION DataProtectionAction = "SUBSTITUTION"
	DataProtectionActionHASH         DataProtectionAction = "HASH"
)

type FieldToProtectFieldType string

const (
	FieldToProtectFieldTypeSINGLEHEADER        FieldToProtectFieldType = "SINGLE_HEADER"
	FieldToProtectFieldTypeSINGLECOOKIE        FieldToProtectFieldType = "SINGLE_COOKIE"
	FieldToProtectFieldTypeSINGLEQUERYARGUMENT FieldToProtectFieldType = "SINGLE_QUERY_ARGUMENT"
	FieldToProtectFieldTypeQUERYSTRING         FieldToProtectFieldType = "QUERY_STRING"
	FieldToProtectFieldTypeBODY                FieldToProtectFieldType = "BODY"
)

type WebACLBlockchainChain string

const (
	WebACLBlockchainChainBASE         WebACLBlockchainChain = "BASE"
	WebACLBlockchainChainSOLANA       WebACLBlockchainChain = "SOLANA"
	WebACLBlockchainChainBASESEPOLIA  WebACLBlockchainChain = "BASE_SEPOLIA"
	WebACLBlockchainChainSOLANADEVNET WebACLBlockchainChain = "SOLANA_DEVNET"
)

type WebACLCryptoCurrency string

const (
	WebACLCryptoCurrencyUSDC WebACLCryptoCurrency = "USDC"
)

type WebACLCurrencyMode string

const (
	WebACLCurrencyModeREAL WebACLCurrencyMode = "REAL"
	WebACLCurrencyModeTEST WebACLCurrencyMode = "TEST"
)

type OnSourceDDoSProtectionConfigALBLowReputationMode string

const (
	OnSourceDDoSProtectionConfigALBLowReputationModeACTIVEUNDERDDOS OnSourceDDoSProtectionConfigALBLowReputationMode = "ACTIVE_UNDER_DDOS"
	OnSourceDDoSProtectionConfigALBLowReputationModeALWAYSON        OnSourceDDoSProtectionConfigALBLowReputationMode = "ALWAYS_ON"
)

type WebACLForwardedIPConfigurationFallbackBehavior string

const (
	WebACLForwardedIPConfigurationFallbackBehaviorMATCH   WebACLForwardedIPConfigurationFallbackBehavior = "MATCH"
	WebACLForwardedIPConfigurationFallbackBehaviorNOMATCH WebACLForwardedIPConfigurationFallbackBehavior = "NO_MATCH"
)

type WebACLOversizeHandling string

const (
	WebACLOversizeHandlingCONTINUE WebACLOversizeHandling = "CONTINUE"
	WebACLOversizeHandlingMATCH    WebACLOversizeHandling = "MATCH"
	WebACLOversizeHandlingNOMATCH  WebACLOversizeHandling = "NO_MATCH"
)

type WebACLMapMatchScope string

const (
	WebACLMapMatchScopeALL   WebACLMapMatchScope = "ALL"
	WebACLMapMatchScopeKEY   WebACLMapMatchScope = "KEY"
	WebACLMapMatchScopeVALUE WebACLMapMatchScope = "VALUE"
)

type WebACLJA3FingerprintFallbackBehavior string

const (
	WebACLJA3FingerprintFallbackBehaviorMATCH   WebACLJA3FingerprintFallbackBehavior = "MATCH"
	WebACLJA3FingerprintFallbackBehaviorNOMATCH WebACLJA3FingerprintFallbackBehavior = "NO_MATCH"
)

type WebACLJA4FingerprintFallbackBehavior string

const (
	WebACLJA4FingerprintFallbackBehaviorMATCH   WebACLJA4FingerprintFallbackBehavior = "MATCH"
	WebACLJA4FingerprintFallbackBehaviorNOMATCH WebACLJA4FingerprintFallbackBehavior = "NO_MATCH"
)

type WebACLBodyParsingFallbackBehavior string

const (
	WebACLBodyParsingFallbackBehaviorMATCH            WebACLBodyParsingFallbackBehavior = "MATCH"
	WebACLBodyParsingFallbackBehaviorNOMATCH          WebACLBodyParsingFallbackBehavior = "NO_MATCH"
	WebACLBodyParsingFallbackBehaviorEVALUATEASSTRING WebACLBodyParsingFallbackBehavior = "EVALUATE_AS_STRING"
)

type WebACLJsonMatchScope string

const (
	WebACLJsonMatchScopeALL   WebACLJsonMatchScope = "ALL"
	WebACLJsonMatchScopeKEY   WebACLJsonMatchScope = "KEY"
	WebACLJsonMatchScopeVALUE WebACLJsonMatchScope = "VALUE"
)

type WebACLUriFragmentFallbackBehavior string

const (
	WebACLUriFragmentFallbackBehaviorMATCH   WebACLUriFragmentFallbackBehavior = "MATCH"
	WebACLUriFragmentFallbackBehaviorNOMATCH WebACLUriFragmentFallbackBehavior = "NO_MATCH"
)

type WebACLPositionalConstraint string

const (
	WebACLPositionalConstraintEXACTLY      WebACLPositionalConstraint = "EXACTLY"
	WebACLPositionalConstraintSTARTSWITH   WebACLPositionalConstraint = "STARTS_WITH"
	WebACLPositionalConstraintENDSWITH     WebACLPositionalConstraint = "ENDS_WITH"
	WebACLPositionalConstraintCONTAINS     WebACLPositionalConstraint = "CONTAINS"
	WebACLPositionalConstraintCONTAINSWORD WebACLPositionalConstraint = "CONTAINS_WORD"
)

type WebACLPreParseTextTransformationType string

const (
	WebACLPreParseTextTransformationTypeNONE                             WebACLPreParseTextTransformationType = "NONE"
	WebACLPreParseTextTransformationTypeURLDECODE                        WebACLPreParseTextTransformationType = "URL_DECODE"
	WebACLPreParseTextTransformationTypeURLDECODEUNI                     WebACLPreParseTextTransformationType = "URL_DECODE_UNI"
	WebACLPreParseTextTransformationTypeCOMBINEDUPLICATEQUERYARGSBYCOMMA WebACLPreParseTextTransformationType = "COMBINE_DUPLICATE_QUERY_ARGS_BY_COMMA"
	WebACLPreParseTextTransformationTypeREPLACESEMICOLONSWITHAMPERSANDS  WebACLPreParseTextTransformationType = "REPLACE_SEMICOLONS_WITH_AMPERSANDS"
)

type WebACLTextTransformationType string

const (
	WebACLTextTransformationTypeNONE               WebACLTextTransformationType = "NONE"
	WebACLTextTransformationTypeCOMPRESSWHITESPACE WebACLTextTransformationType = "COMPRESS_WHITE_SPACE"
	WebACLTextTransformationTypeHTMLENTITYDECODE   WebACLTextTransformationType = "HTML_ENTITY_DECODE"
	WebACLTextTransformationTypeLOWERCASE          WebACLTextTransformationType = "LOWERCASE"
	WebACLTextTransformationTypeCMDLINE            WebACLTextTransformationType = "CMD_LINE"
	WebACLTextTransformationTypeURLDECODE          WebACLTextTransformationType = "URL_DECODE"
	WebACLTextTransformationTypeBASE64DECODE       WebACLTextTransformationType = "BASE64_DECODE"
	WebACLTextTransformationTypeHEXDECODE          WebACLTextTransformationType = "HEX_DECODE"
	WebACLTextTransformationTypeMD5                WebACLTextTransformationType = "MD5"
	WebACLTextTransformationTypeREPLACECOMMENTS    WebACLTextTransformationType = "REPLACE_COMMENTS"
	WebACLTextTransformationTypeESCAPESEQDECODE    WebACLTextTransformationType = "ESCAPE_SEQ_DECODE"
	WebACLTextTransformationTypeSQLHEXDECODE       WebACLTextTransformationType = "SQL_HEX_DECODE"
	WebACLTextTransformationTypeCSSDECODE          WebACLTextTransformationType = "CSS_DECODE"
	WebACLTextTransformationTypeJSDECODE           WebACLTextTransformationType = "JS_DECODE"
	WebACLTextTransformationTypeNORMALIZEPATH      WebACLTextTransformationType = "NORMALIZE_PATH"
	WebACLTextTransformationTypeNORMALIZEPATHWIN   WebACLTextTransformationType = "NORMALIZE_PATH_WIN"
	WebACLTextTransformationTypeREMOVENULLS        WebACLTextTransformationType = "REMOVE_NULLS"
	WebACLTextTransformationTypeREPLACENULLS       WebACLTextTransformationType = "REPLACE_NULLS"
	WebACLTextTransformationTypeBASE64DECODEEXT    WebACLTextTransformationType = "BASE64_DECODE_EXT"
	WebACLTextTransformationTypeURLDECODEUNI       WebACLTextTransformationType = "URL_DECODE_UNI"
	WebACLTextTransformationTypeUTF8TOUNICODE      WebACLTextTransformationType = "UTF8_TO_UNICODE"
	WebACLTextTransformationTypeREMOVEWHITESPACE   WebACLTextTransformationType = "REMOVE_WHITESPACE"
	WebACLTextTransformationTypeTRIM               WebACLTextTransformationType = "TRIM"
	WebACLTextTransformationTypeTRIMLEFT           WebACLTextTransformationType = "TRIM_LEFT"
	WebACLTextTransformationTypeTRIMRIGHT          WebACLTextTransformationType = "TRIM_RIGHT"
	WebACLTextTransformationTypeREMOVECOMMENTSCHAR WebACLTextTransformationType = "REMOVE_COMMENTS_CHAR"
	WebACLTextTransformationTypeUPPERCASE          WebACLTextTransformationType = "UPPERCASE"
	WebACLTextTransformationTypeCMDLINEWIN         WebACLTextTransformationType = "CMD_LINE_WIN"
	WebACLTextTransformationTypeCMDLINEUNIX        WebACLTextTransformationType = "CMD_LINE_UNIX"
	WebACLTextTransformationTypeJSDECODEEXT        WebACLTextTransformationType = "JS_DECODE_EXT"
	WebACLTextTransformationTypeSHA256             WebACLTextTransformationType = "SHA256"
)

type WebACLIPSetForwardedIPConfigurationFallbackBehavior string

const (
	WebACLIPSetForwardedIPConfigurationFallbackBehaviorMATCH   WebACLIPSetForwardedIPConfigurationFallbackBehavior = "MATCH"
	WebACLIPSetForwardedIPConfigurationFallbackBehaviorNOMATCH WebACLIPSetForwardedIPConfigurationFallbackBehavior = "NO_MATCH"
)

type WebACLIPSetForwardedIPConfigurationPosition string

const (
	WebACLIPSetForwardedIPConfigurationPositionFIRST WebACLIPSetForwardedIPConfigurationPosition = "FIRST"
	WebACLIPSetForwardedIPConfigurationPositionLAST  WebACLIPSetForwardedIPConfigurationPosition = "LAST"
	WebACLIPSetForwardedIPConfigurationPositionANY   WebACLIPSetForwardedIPConfigurationPosition = "ANY"
)

type WebACLLabelMatchScope string

const (
	WebACLLabelMatchScopeLABEL     WebACLLabelMatchScope = "LABEL"
	WebACLLabelMatchScopeNAMESPACE WebACLLabelMatchScope = "NAMESPACE"
)

type RequestInspectionACFPPayloadType string

const (
	RequestInspectionACFPPayloadTypeJSON        RequestInspectionACFPPayloadType = "JSON"
	RequestInspectionACFPPayloadTypeFORMENCODED RequestInspectionACFPPayloadType = "FORM_ENCODED"
)

type RequestInspectionPayloadType string

const (
	RequestInspectionPayloadTypeJSON        RequestInspectionPayloadType = "JSON"
	RequestInspectionPayloadTypeFORMENCODED RequestInspectionPayloadType = "FORM_ENCODED"
)

type SensitivityToAct string

const (
	SensitivityToActLOW    SensitivityToAct = "LOW"
	SensitivityToActMEDIUM SensitivityToAct = "MEDIUM"
	SensitivityToActHIGH   SensitivityToAct = "HIGH"
)

type UsageOfAction string

const (
	UsageOfActionENABLED  UsageOfAction = "ENABLED"
	UsageOfActionDISABLED UsageOfAction = "DISABLED"
)

type AWSManagedRulesBotControlRuleSetInspectionLevel string

const (
	AWSManagedRulesBotControlRuleSetInspectionLevelCOMMON   AWSManagedRulesBotControlRuleSetInspectionLevel = "COMMON"
	AWSManagedRulesBotControlRuleSetInspectionLevelTARGETED AWSManagedRulesBotControlRuleSetInspectionLevel = "TARGETED"
)

type ManagedRuleGroupConfigPayloadType string

const (
	ManagedRuleGroupConfigPayloadTypeJSON        ManagedRuleGroupConfigPayloadType = "JSON"
	ManagedRuleGroupConfigPayloadTypeFORMENCODED ManagedRuleGroupConfigPayloadType = "FORM_ENCODED"
)

type WebACLRateBasedStatementAggregateKeyType string

const (
	WebACLRateBasedStatementAggregateKeyTypeCONSTANT    WebACLRateBasedStatementAggregateKeyType = "CONSTANT"
	WebACLRateBasedStatementAggregateKeyTypeIP          WebACLRateBasedStatementAggregateKeyType = "IP"
	WebACLRateBasedStatementAggregateKeyTypeFORWARDEDIP WebACLRateBasedStatementAggregateKeyType = "FORWARDED_IP"
	WebACLRateBasedStatementAggregateKeyTypeCUSTOMKEYS  WebACLRateBasedStatementAggregateKeyType = "CUSTOM_KEYS"
)

type WebACLRateLimitJA3FingerprintFallbackBehavior string

const (
	WebACLRateLimitJA3FingerprintFallbackBehaviorMATCH   WebACLRateLimitJA3FingerprintFallbackBehavior = "MATCH"
	WebACLRateLimitJA3FingerprintFallbackBehaviorNOMATCH WebACLRateLimitJA3FingerprintFallbackBehavior = "NO_MATCH"
)

type WebACLRateLimitJA4FingerprintFallbackBehavior string

const (
	WebACLRateLimitJA4FingerprintFallbackBehaviorMATCH   WebACLRateLimitJA4FingerprintFallbackBehavior = "MATCH"
	WebACLRateLimitJA4FingerprintFallbackBehaviorNOMATCH WebACLRateLimitJA4FingerprintFallbackBehavior = "NO_MATCH"
)

type WebACLSizeConstraintStatementComparisonOperator string

const (
	WebACLSizeConstraintStatementComparisonOperatorEQ WebACLSizeConstraintStatementComparisonOperator = "EQ"
	WebACLSizeConstraintStatementComparisonOperatorNE WebACLSizeConstraintStatementComparisonOperator = "NE"
	WebACLSizeConstraintStatementComparisonOperatorLE WebACLSizeConstraintStatementComparisonOperator = "LE"
	WebACLSizeConstraintStatementComparisonOperatorLT WebACLSizeConstraintStatementComparisonOperator = "LT"
	WebACLSizeConstraintStatementComparisonOperatorGE WebACLSizeConstraintStatementComparisonOperator = "GE"
	WebACLSizeConstraintStatementComparisonOperatorGT WebACLSizeConstraintStatementComparisonOperator = "GT"
)

type WebACLSensitivityLevel string

const (
	WebACLSensitivityLevelLOW  WebACLSensitivityLevel = "LOW"
	WebACLSensitivityLevelHIGH WebACLSensitivityLevel = "HIGH"
)

type WebACLScope string

const (
	WebACLScopeCLOUDFRONT WebACLScope = "CLOUDFRONT"
	WebACLScopeREGIONAL   WebACLScope = "REGIONAL"
)
