// Code generated by go generate; DO NOT EDIT.

package iam

// The iam actions of the aws iam service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionAcceptDelegationRequest                       = "iam:AcceptDelegationRequest"
	ActionAddClientIDToOpenIDConnectProvider            = "iam:AddClientIDToOpenIDConnectProvider"
	ActionAddRoleToInstanceProfile                      = "iam:AddRoleToInstanceProfile"
	ActionAddUserToGroup                                = "iam:AddUserToGroup"
	ActionAssociateDelegationRequest                    = "iam:AssociateDelegationRequest"
	ActionAttachGroupPolicy                             = "iam:AttachGroupPolicy"
	ActionAttachRolePolicy                              = "iam:AttachRolePolicy"
	ActionAttachUserPolicy                              = "iam:AttachUserPolicy"
	ActionChangePassword                                = "iam:ChangePassword"
	ActionCreateAccessKey                               = "iam:CreateAccessKey"
	ActionCreateAccountAlias                            = "iam:CreateAccountAlias"
	ActionCreateDelegationRequest                       = "iam:CreateDelegationRequest"
	ActionCreateGroup                                   = "iam:CreateGroup"
	ActionCreateInstanceProfile                         = "iam:CreateInstanceProfile"
	ActionCreateLoginProfile                            = "iam:CreateLoginProfile"
	ActionCreateOpenIDConnectProvider                   = "iam:CreateOpenIDConnectProvider"
	ActionCreatePolicy                                  = "iam:CreatePolicy"
	ActionCreatePolicyVersion                           = "iam:CreatePolicyVersion"
	ActionCreateRole                                    = "iam:CreateRole"
	ActionCreateSAMLProvider                            = "iam:CreateSAMLProvider"
	ActionCreateServiceLinkedRole                       = "iam:CreateServiceLinkedRole"
	ActionCreateServiceSpecificCredential               = "iam:CreateServiceSpecificCredential"
	ActionCreateUser                                    = "iam:CreateUser"
	ActionCreateVirtualMFADevice                        = "iam:CreateVirtualMFADevice"
	ActionDeactivateMFADevice                           = "iam:DeactivateMFADevice"
	ActionDeleteAccessKey                               = "iam:DeleteAccessKey"
	ActionDeleteAccountAlias                            = "iam:DeleteAccountAlias"
	ActionDeleteAccountPasswordPolicy                   = "iam:DeleteAccountPasswordPolicy"
	ActionDeleteCloudFrontPublicKey                     = "iam:DeleteCloudFrontPublicKey"
	ActionDeleteGroup                                   = "iam:DeleteGroup"
	ActionDeleteGroupPolicy                             = "iam:DeleteGroupPolicy"
	ActionDeleteInstanceProfile                         = "iam:DeleteInstanceProfile"
	ActionDeleteLoginProfile                            = "iam:DeleteLoginProfile"
	ActionDeleteOpenIDConnectProvider                   = "iam:DeleteOpenIDConnectProvider"
	ActionDeletePolicy                                  = "iam:DeletePolicy"
	ActionDeletePolicyVersion                           = "iam:DeletePolicyVersion"
	ActionDeleteRole                                    = "iam:DeleteRole"
	ActionDeleteRolePermissionsBoundary                 = "iam:DeleteRolePermissionsBoundary"
	ActionDeleteRolePolicy                              = "iam:DeleteRolePolicy"
	ActionDeleteSAMLProvider                            = "iam:DeleteSAMLProvider"
	ActionDeleteSSHPublicKey                            = "iam:DeleteSSHPublicKey"
	ActionDeleteServerCertificate                       = "iam:DeleteServerCertificate"
	ActionDeleteServiceLinkedRole                       = "iam:DeleteServiceLinkedRole"
	ActionDeleteServiceSpecificCredential               = "iam:DeleteServiceSpecificCredential"
	ActionDeleteSigningCertificate                      = "iam:DeleteSigningCertificate"
	ActionDeleteUser                                    = "iam:DeleteUser"
	ActionDeleteUserPermissionsBoundary                 = "iam:DeleteUserPermissionsBoundary"
	ActionDeleteUserPolicy                              = "iam:DeleteUserPolicy"
	ActionDeleteVirtualMFADevice                        = "iam:DeleteVirtualMFADevice"
	ActionDetachGroupPolicy                             = "iam:DetachGroupPolicy"
	ActionDetachRolePolicy                              = "iam:DetachRolePolicy"
	ActionDetachUserPolicy                              = "iam:DetachUserPolicy"
	ActionDisableOrganizationsRootCredentialsManagement = "iam:DisableOrganizationsRootCredentialsManagement"
	ActionDisableOrganizationsRootSessions              = "iam:DisableOrganizationsRootSessions"
	ActionDisableOutboundWebIdentityFederation          = "iam:DisableOutboundWebIdentityFederation"
	ActionEnableMFADevice                               = "iam:EnableMFADevice"
	ActionEnableOrganizationsRootCredentialsManagement  = "iam:EnableOrganizationsRootCredentialsManagement"
	ActionEnableOrganizationsRootSessions               = "iam:EnableOrganizationsRootSessions"
	ActionEnableOutboundWebIdentityFederation           = "iam:EnableOutboundWebIdentityFederation"
	ActionGenerateCredentialReport                      = "iam:GenerateCredentialReport"
	ActionGenerateOrganizationsAccessReport             = "iam:GenerateOrganizationsAccessReport"
	ActionGenerateServiceLastAccessedDetails            = "iam:GenerateServiceLastAccessedDetails"
	ActionGetAccessKeyLastUsed                          = "iam:GetAccessKeyLastUsed"
	ActionGetAccountAuthorizationDetails                = "iam:GetAccountAuthorizationDetails"
	ActionGetAccountEmailAddress                        = "iam:GetAccountEmailAddress"
	ActionGetAccountName                                = "iam:GetAccountName"
	ActionGetAccountPasswordPolicy                      = "iam:GetAccountPasswordPolicy"
	ActionGetAccountSummary                             = "iam:GetAccountSummary"
	ActionGetCloudFrontPublicKey                        = "iam:GetCloudFrontPublicKey"
	ActionGetContextKeysForCustomPolicy                 = "iam:GetContextKeysForCustomPolicy"
	ActionGetContextKeysForPrincipalPolicy              = "iam:GetContextKeysForPrincipalPolicy"
	ActionGetCredentialReport                           = "iam:GetCredentialReport"
	ActionGetDelegationRequest                          = "iam:GetDelegationRequest"
	ActionGetGroup                                      = "iam:GetGroup"
	ActionGetGroupPolicy                                = "iam:GetGroupPolicy"
	ActionGetHumanReadableSummary                       = "iam:GetHumanReadableSummary"
	ActionGetInstanceProfile                            = "iam:GetInstanceProfile"
	ActionGetLoginProfile                               = "iam:GetLoginProfile"
	ActionGetMFADevice                                  = "iam:GetMFADevice"
	ActionGetOpenIDConnectProvider                      = "iam:GetOpenIDConnectProvider"
	ActionGetOrganizationsAccessReport                  = "iam:GetOrganizationsAccessReport"
	ActionGetOutboundWebIdentityFederationInfo          = "iam:GetOutboundWebIdentityFederationInfo"
	ActionGetPolicy                                     = "iam:GetPolicy"
	ActionGetPolicyVersion                              = "iam:GetPolicyVersion"
	ActionGetRole                                       = "iam:GetRole"
	ActionGetRolePolicy                                 = "iam:GetRolePolicy"
	ActionGetSAMLProvider                               = "iam:GetSAMLProvider"
	ActionGetSSHPublicKey                               = "iam:GetSSHPublicKey"
	ActionGetServerCertificate                          = "iam:GetServerCertificate"
	ActionGetServiceLastAccessedDetails                 = "iam:GetServiceLastAccessedDetails"
	ActionGetServiceLastAccessedDetailsWithEntities     = "iam:GetServiceLastAccessedDetailsWithEntities"
	ActionGetServiceLinkedRoleDeletionStatus            = "iam:GetServiceLinkedRoleDeletionStatus"
	ActionGetUser                                       = "iam:GetUser"
	ActionGetUserPolicy                                 = "iam:GetUserPolicy"
	ActionListAccessKeys                                = "iam:ListAccessKeys"
	ActionListAccountAliases                            = "iam:ListAccountAliases"
	ActionListAttachedGroupPolicies                     = "iam:ListAttachedGroupPolicies"
	ActionListAttachedRolePolicies                      = "iam:ListAttachedRolePolicies"
	ActionListAttachedUserPolicies                      = "iam:ListAttachedUserPolicies"
	ActionListCloudFrontPublicKeys                      = "iam:ListCloudFrontPublicKeys"
	ActionListDelegationRequests                        = "iam:ListDelegationRequests"
	ActionListEntitiesForPolicy                         = "iam:ListEntitiesForPolicy"
	ActionListGroupPolicies                             = "iam:ListGroupPolicies"
	ActionListGroups                                    = "iam:ListGroups"
	ActionListGroupsForUser                             = "iam:ListGroupsForUser"
	ActionListInstanceProfileTags                       = "iam:ListInstanceProfileTags"
	ActionListInstanceProfiles                          = "iam:ListInstanceProfiles"
	ActionListInstanceProfilesForRole                   = "iam:ListInstanceProfilesForRole"
	ActionListMFADeviceTags                             = "iam:ListMFADeviceTags"
	ActionListMFADevices                                = "iam:ListMFADevices"
	ActionListOpenIDConnectProviderTags                 = "iam:ListOpenIDConnectProviderTags"
	ActionListOpenIDConnectProviders                    = "iam:ListOpenIDConnectProviders"
	ActionListOrganizationsFeatures                     = "iam:ListOrganizationsFeatures"
	ActionListPolicies                                  = "iam:ListPolicies"
	ActionListPoliciesGrantingServiceAccess             = "iam:ListPoliciesGrantingServiceAccess"
	ActionListPolicyTags                                = "iam:ListPolicyTags"
	ActionListPolicyVersions                            = "iam:ListPolicyVersions"
	ActionListRolePolicies                              = "iam:ListRolePolicies"
	ActionListRoleTags                                  = "iam:ListRoleTags"
	ActionListRoles                                     = "iam:ListRoles"
	ActionListSAMLProviderTags                          = "iam:ListSAMLProviderTags"
	ActionListSAMLProviders                             = "iam:ListSAMLProviders"
	ActionListSSHPublicKeys                             = "iam:ListSSHPublicKeys"
	ActionListSTSRegionalEndpointsStatus                = "iam:ListSTSRegionalEndpointsStatus"
	ActionListServerCertificateTags                     = "iam:ListServerCertificateTags"
	ActionListServerCertificates                        = "iam:ListServerCertificates"
	ActionListServiceSpecificCredentials                = "iam:ListServiceSpecificCredentials"
	ActionListSigningCertificates                       = "iam:ListSigningCertificates"
	ActionListUserPolicies                              = "iam:ListUserPolicies"
	ActionListUserTags                                  = "iam:ListUserTags"
	ActionListUsers                                     = "iam:ListUsers"
	ActionListVirtualMFADevices                         = "iam:ListVirtualMFADevices"
	ActionPassRole                                      = "iam:PassRole"
	ActionPutGroupPolicy                                = "iam:PutGroupPolicy"
	ActionPutRolePermissionsBoundary                    = "iam:PutRolePermissionsBoundary"
	ActionPutRolePolicy                                 = "iam:PutRolePolicy"
	ActionPutUserPermissionsBoundary                    = "iam:PutUserPermissionsBoundary"
	ActionPutUserPolicy                                 = "iam:PutUserPolicy"
	ActionRejectDelegationRequest                       = "iam:RejectDelegationRequest"
	ActionRemoveClientIDFromOpenIDConnectProvider       = "iam:RemoveClientIDFromOpenIDConnectProvider"
	ActionRemoveRoleFromInstanceProfile                 = "iam:RemoveRoleFromInstanceProfile"
	ActionRemoveUserFromGroup                           = "iam:RemoveUserFromGroup"
	ActionResetServiceSpecificCredential                = "iam:ResetServiceSpecificCredential"
	ActionResyncMFADevice                               = "iam:ResyncMFADevice"
	ActionSendDelegationToken                           = "iam:SendDelegationToken"
	ActionSetDefaultPolicyVersion                       = "iam:SetDefaultPolicyVersion"
	ActionSetSTSRegionalEndpointStatus                  = "iam:SetSTSRegionalEndpointStatus"
	ActionSetSecurityTokenServicePreferences            = "iam:SetSecurityTokenServicePreferences"
	ActionSimulateCustomPolicy                          = "iam:SimulateCustomPolicy"
	ActionSimulatePrincipalPolicy                       = "iam:SimulatePrincipalPolicy"
	ActionTagInstanceProfile                            = "iam:TagInstanceProfile"
	ActionTagMFADevice                                  = "iam:TagMFADevice"
	ActionTagOpenIDConnectProvider                      = "iam:TagOpenIDConnectProvider"
	ActionTagPolicy                                     = "iam:TagPolicy"
	ActionTagRole                                       = "iam:TagRole"
	ActionTagSAMLProvider                               = "iam:TagSAMLProvider"
	ActionTagServerCertificate                          = "iam:TagServerCertificate"
	ActionTagUser                                       = "iam:TagUser"
	ActionUntagInstanceProfile                          = "iam:UntagInstanceProfile"
	ActionUntagMFADevice                                = "iam:UntagMFADevice"
	ActionUntagOpenIDConnectProvider                    = "iam:UntagOpenIDConnectProvider"
	ActionUntagPolicy                                   = "iam:UntagPolicy"
	ActionUntagRole                                     = "iam:UntagRole"
	ActionUntagSAMLProvider                             = "iam:UntagSAMLProvider"
	ActionUntagServerCertificate                        = "iam:UntagServerCertificate"
	ActionUntagUser                                     = "iam:UntagUser"
	ActionUpdateAccessKey                               = "iam:UpdateAccessKey"
	ActionUpdateAccountEmailAddress                     = "iam:UpdateAccountEmailAddress"
	ActionUpdateAccountName                             = "iam:UpdateAccountName"
	ActionUpdateAccountPasswordPolicy                   = "iam:UpdateAccountPasswordPolicy"
	ActionUpdateAssumeRolePolicy                        = "iam:UpdateAssumeRolePolicy"
	ActionUpdateCloudFrontPublicKey                     = "iam:UpdateCloudFrontPublicKey"
	ActionUpdateGroup                                   = "iam:UpdateGroup"
	ActionUpdateLoginProfile                            = "iam:UpdateLoginProfile"
	ActionUpdateOpenIDConnectProviderThumbprint         = "iam:UpdateOpenIDConnectProviderThumbprint"
	ActionUpdateRole                                    = "iam:UpdateRole"
	ActionUpdateRoleDescription                         = "iam:UpdateRoleDescription"
	ActionUpdateSAMLProvider                            = "iam:UpdateSAMLProvider"
	ActionUpdateSSHPublicKey                            = "iam:UpdateSSHPublicKey"
	ActionUpdateServerCertificate                       = "iam:UpdateServerCertificate"
	ActionUpdateServiceSpecificCredential               = "iam:UpdateServiceSpecificCredential"
	ActionUpdateSigningCertificate                      = "iam:UpdateSigningCertificate"
	ActionUpdateUser                                    = "iam:UpdateUser"
	ActionUploadCloudFrontPublicKey                     = "iam:UploadCloudFrontPublicKey"
	ActionUploadSSHPublicKey                            = "iam:UploadSSHPublicKey"
	ActionUploadServerCertificate                       = "iam:UploadServerCertificate"
	ActionUploadSigningCertificate                      = "iam:UploadSigningCertificate"
)

// ActionsList are the list actions, as classified by aws.
var ActionsList = []string{
	ActionGetAccountSummary,
	ActionGetLoginProfile,
	ActionListAccessKeys,
	ActionListAccountAliases,
	ActionListAttachedGroupPolicies,
	ActionListAttachedRolePolicies,
	ActionListAttachedUserPolicies,
	ActionListCloudFrontPublicKeys,
	ActionListDelegationRequests,
	ActionListEntitiesForPolicy,
	ActionListGroupPolicies,
	ActionListGroups,
	ActionListGroupsForUser,
	ActionListInstanceProfileTags,
	ActionListInstanceProfiles,
	ActionListInstanceProfilesForRole,
	ActionListMFADeviceTags,
	ActionListMFADevices,
	ActionListOpenIDConnectProviderTags,
	ActionListOpenIDConnectProviders,
	ActionListOrganizationsFeatures,
	ActionListPolicies,
	ActionListPoliciesGrantingServiceAccess,
	ActionListPolicyTags,
	ActionListPolicyVersions,
	ActionListRolePolicies,
	ActionListRoleTags,
	ActionListRoles,
	ActionListSAMLProviderTags,
	ActionListSAMLProviders,
	ActionListSSHPublicKeys,
	ActionListSTSRegionalEndpointsStatus,
	ActionListServerCertificateTags,
	ActionListServerCertificates,
	ActionListServiceSpecificCredentials,
	ActionListSigningCertificates,
	ActionListUserPolicies,
	ActionListUserTags,
	ActionListUsers,
	ActionListVirtualMFADevices,
}

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionGenerateCredentialReport,
	ActionGenerateOrganizationsAccessReport,
	ActionGenerateServiceLastAccessedDetails,
	ActionGetAccessKeyLastUsed,
	ActionGetAccountAuthorizationDetails,
	ActionGetAccountEmailAddress,
	ActionGetAccountName,
	ActionGetAccountPasswordPolicy,
	ActionGetCloudFrontPublicKey,
	ActionGetContextKeysForCustomPolicy,
	ActionGetContextKeysForPrincipalPolicy,
	ActionGetCredentialReport,
	ActionGetDelegationRequest,
	ActionGetGroup,
	ActionGetGroupPolicy,
	ActionGetHumanReadableSummary,
	ActionGetInstanceProfile,
	ActionGetMFADevice,
	ActionGetOpenIDConnectProvider,
	ActionGetOrganizationsAccessReport,
	ActionGetOutboundWebIdentityFederationInfo,
	ActionGetPolicy,
	ActionGetPolicyVersion,
	ActionGetRole,
	ActionGetRolePolicy,
	ActionGetSAMLProvider,
	ActionGetSSHPublicKey,
	ActionGetServerCertificate,
	ActionGetServiceLastAccessedDetails,
	ActionGetServiceLastAccessedDetailsWithEntities,
	ActionGetServiceLinkedRoleDeletionStatus,
	ActionGetUser,
	ActionGetUserPolicy,
	ActionSimulateCustomPolicy,
	ActionSimulatePrincipalPolicy,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionAcceptDelegationRequest,
	ActionAddClientIDToOpenIDConnectProvider,
	ActionAddRoleToInstanceProfile,
	ActionAddUserToGroup,
	ActionAssociateDelegationRequest,
	ActionChangePassword,
	ActionCreateAccessKey,
	ActionCreateAccountAlias,
	ActionCreateDelegationRequest,
	ActionCreateGroup,
	ActionCreateInstanceProfile,
	ActionCreateLoginProfile,
	ActionCreateOpenIDConnectProvider,
	ActionCreateRole,
	ActionCreateSAMLProvider,
	ActionCreateServiceLinkedRole,
	ActionCreateServiceSpecificCredential,
	ActionCreateUser,
	ActionCreateVirtualMFADevice,
	ActionDeactivateMFADevice,
	ActionDeleteAccessKey,
	ActionDeleteAccountAlias,
	ActionDeleteCloudFrontPublicKey,
	ActionDeleteGroup,
	ActionDeleteInstanceProfile,
	ActionDeleteLoginProfile,
	ActionDeleteOpenIDConnectProvider,
	ActionDeleteRole,
	ActionDeleteSAMLProvider,
	ActionDeleteSSHPublicKey,
	ActionDeleteServerCertificate,
	ActionDeleteServiceLinkedRole,
	ActionDeleteServiceSpecificCredential,
	ActionDeleteSigningCertificate,
	ActionDeleteUser,
	ActionDeleteVirtualMFADevice,
	ActionDisableOrganizationsRootCredentialsManagement,
	ActionDisableOrganizationsRootSessions,
	ActionDisableOutboundWebIdentityFederation,
	ActionEnableMFADevice,
	ActionEnableOrganizationsRootCredentialsManagement,
	ActionEnableOrganizationsRootSessions,
	ActionEnableOutboundWebIdentityFederation,
	ActionPassRole,
	ActionRejectDelegationRequest,
	ActionRemoveClientIDFromOpenIDConnectProvider,
	ActionRemoveRoleFromInstanceProfile,
	ActionRemoveUserFromGroup,
	ActionResetServiceSpecificCredential,
	ActionResyncMFADevice,
	ActionSendDelegationToken,
	ActionSetSTSRegionalEndpointStatus,
	ActionSetSecurityTokenServicePreferences,
	ActionUpdateAccessKey,
	ActionUpdateAccountEmailAddress,
	ActionUpdateAccountName,
	ActionUpdateAccountPasswordPolicy,
	ActionUpdateCloudFrontPublicKey,
	ActionUpdateGroup,
	ActionUpdateLoginProfile,
	ActionUpdateOpenIDConnectProviderThumbprint,
	ActionUpdateRole,
	ActionUpdateRoleDescription,
	ActionUpdateSAMLProvider,
	ActionUpdateSSHPublicKey,
	ActionUpdateServerCertificate,
	ActionUpdateServiceSpecificCredential,
	ActionUpdateSigningCertificate,
	ActionUpdateUser,
	ActionUploadCloudFrontPublicKey,
	ActionUploadSSHPublicKey,
	ActionUploadServerCertificate,
	ActionUploadSigningCertificate,
}

// ActionsPermissions are the permissions actions, as classified by aws.
var ActionsPermissions = []string{
	ActionAttachGroupPolicy,
	ActionAttachRolePolicy,
	ActionAttachUserPolicy,
	ActionCreatePolicy,
	ActionCreatePolicyVersion,
	ActionDeleteAccountPasswordPolicy,
	ActionDeleteGroupPolicy,
	ActionDeletePolicy,
	ActionDeletePolicyVersion,
	ActionDeleteRolePermissionsBoundary,
	ActionDeleteRolePolicy,
	ActionDeleteUserPermissionsBoundary,
	ActionDeleteUserPolicy,
	ActionDetachGroupPolicy,
	ActionDetachRolePolicy,
	ActionDetachUserPolicy,
	ActionPutGroupPolicy,
	ActionPutRolePermissionsBoundary,
	ActionPutRolePolicy,
	ActionPutUserPermissionsBoundary,
	ActionPutUserPolicy,
	ActionSetDefaultPolicyVersion,
	ActionUpdateAssumeRolePolicy,
}

// ActionsTagging are the tagging actions, as classified by aws.
var ActionsTagging = []string{
	ActionTagInstanceProfile,
	ActionTagMFADevice,
	ActionTagOpenIDConnectProvider,
	ActionTagPolicy,
	ActionTagRole,
	ActionTagSAMLProvider,
	ActionTagServerCertificate,
	ActionTagUser,
	ActionUntagInstanceProfile,
	ActionUntagMFADevice,
	ActionUntagOpenIDConnectProvider,
	ActionUntagPolicy,
	ActionUntagRole,
	ActionUntagSAMLProvider,
	ActionUntagServerCertificate,
	ActionUntagUser,
}

// The condition keys of the aws iam service.
const (
	ConditionKeyAWSServiceName                       = "iam:AWSServiceName"
	ConditionKeyAssociatedResourceArn                = "iam:AssociatedResourceArn"
	ConditionKeyDelegationDuration                   = "iam:DelegationDuration"
	ConditionKeyDelegationRequestOwner               = "iam:DelegationRequestOwner"
	ConditionKeyFIDOFIPS1402Certification            = "iam:FIDO-FIPS-140-2-certification"
	ConditionKeyFIDOFIPS1403Certification            = "iam:FIDO-FIPS-140-3-certification"
	ConditionKeyFIDOCertification                    = "iam:FIDO-certification"
	ConditionKeyNotificationChannel                  = "iam:NotificationChannel"
	ConditionKeyOrganizationsPolicyId                = "iam:OrganizationsPolicyId"
	ConditionKeyPassedToService                      = "iam:PassedToService"
	ConditionKeyPermissionsBoundary                  = "iam:PermissionsBoundary"
	ConditionKeyPolicyARN                            = "iam:PolicyARN"
	ConditionKeyRegisterSecurityKey                  = "iam:RegisterSecurityKey"
	ConditionKeyServiceSpecificCredentialAgeDays     = "iam:ServiceSpecificCredentialAgeDays"
	ConditionKeyServiceSpecificCredentialServiceName = "iam:ServiceSpecificCredentialServiceName"
	ConditionKeyTemplateArn                          = "iam:TemplateArn"
)

// The condition keys that take a value. They return a plain string, so wrap
// them in policy.Key when a condition wants a policy.ConditionKey.
func ConditionKeyResourceTagFor(value string) string { return "iam:ResourceTag/" + value }
