// Code generated by go generate; DO NOT EDIT.

package vpclatticesvcs

// The iam actions of the aws vpc-lattice-svcs service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionConnect = "vpc-lattice-svcs:Connect"
	ActionInvoke  = "vpc-lattice-svcs:Invoke"
)

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionConnect,
	ActionInvoke,
}

// The condition keys of the aws vpc-lattice-svcs service.
const (
	ConditionKeyPort                  = "vpc-lattice-svcs:Port"
	ConditionKeyRequestMethod         = "vpc-lattice-svcs:RequestMethod"
	ConditionKeyRequestPath           = "vpc-lattice-svcs:RequestPath"
	ConditionKeyServiceArn            = "vpc-lattice-svcs:ServiceArn"
	ConditionKeyServiceNetworkArn     = "vpc-lattice-svcs:ServiceNetworkArn"
	ConditionKeySourceVpc             = "vpc-lattice-svcs:SourceVpc"
	ConditionKeySourceVpcOwnerAccount = "vpc-lattice-svcs:SourceVpcOwnerAccount"
)

// The condition keys that take a value. They return a plain string, so wrap
// them in policy.Key when a condition wants a policy.ConditionKey.
func ConditionKeyRequestHeaderFor(value string) string {
	return "vpc-lattice-svcs:RequestHeader/" + value
}

func ConditionKeyRequestQueryStringFor(value string) string {
	return "vpc-lattice-svcs:RequestQueryString/" + value
}
