// Code generated by go generate; DO NOT EDIT.

// Package location holds the cloud control resources of the aws location service.
package location

type AndroidApp struct {
	CertificateFingerprint *string `json:"CertificateFingerprint,omitempty"`
	Package                *string `json:"Package,omitempty"`
}

type AppleApp struct {
	BundleId *string `json:"BundleId,omitempty"`
}

type ApiKeyRestrictions struct {
	AllowActions     []string     `json:"AllowActions,omitempty"`
	AllowAndroidApps []AndroidApp `json:"AllowAndroidApps,omitempty"`
	AllowAppleApps   []AppleApp   `json:"AllowAppleApps,omitempty"`
	AllowReferers    []string     `json:"AllowReferers,omitempty"`
	AllowResources   []string     `json:"AllowResources,omitempty"`
}

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type APIKey struct {
	Arn          *string             `json:"Arn,omitempty"`
	CreateTime   *string             `json:"CreateTime,omitempty"`
	Description  *string             `json:"Description,omitempty"`
	ExpireTime   *string             `json:"ExpireTime,omitempty"`
	ForceDelete  *bool               `json:"ForceDelete,omitempty"`
	ForceUpdate  *bool               `json:"ForceUpdate,omitempty"`
	KeyArn       *string             `json:"KeyArn,omitempty"`
	KeyName      *string             `json:"KeyName,omitempty"`
	NoExpiry     *bool               `json:"NoExpiry,omitempty"`
	Restrictions *ApiKeyRestrictions `json:"Restrictions,omitempty"`
	Tags         []Tag               `json:"Tags,omitempty"`
	UpdateTime   *string             `json:"UpdateTime,omitempty"`
}

func (APIKey) CloudControlType() string { return "AWS::Location::APIKey" }

type GeofenceCollectionTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type GeofenceCollection struct {
	Arn                   *string                 `json:"Arn,omitempty"`
	CollectionArn         *string                 `json:"CollectionArn,omitempty"`
	CollectionName        *string                 `json:"CollectionName,omitempty"`
	CreateTime            *string                 `json:"CreateTime,omitempty"`
	Description           *string                 `json:"Description,omitempty"`
	KmsKeyId              *string                 `json:"KmsKeyId,omitempty"`
	PricingPlan           *string                 `json:"PricingPlan,omitempty"`
	PricingPlanDataSource *string                 `json:"PricingPlanDataSource,omitempty"`
	Tags                  []GeofenceCollectionTag `json:"Tags,omitempty"`
	UpdateTime            *string                 `json:"UpdateTime,omitempty"`
}

func (GeofenceCollection) CloudControlType() string { return "AWS::Location::GeofenceCollection" }

type MapConfiguration struct {
	CustomLayers  []string `json:"CustomLayers,omitempty"`
	PoliticalView *string  `json:"PoliticalView,omitempty"`
	Style         *string  `json:"Style,omitempty"`
}

type MapTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Map struct {
	Arn           *string           `json:"Arn,omitempty"`
	Configuration *MapConfiguration `json:"Configuration,omitempty"`
	CreateTime    *string           `json:"CreateTime,omitempty"`
	Description   *string           `json:"Description,omitempty"`
	MapArn        *string           `json:"MapArn,omitempty"`
	MapName       *string           `json:"MapName,omitempty"`
	PricingPlan   *string           `json:"PricingPlan,omitempty"`
	Tags          []MapTag          `json:"Tags,omitempty"`
	UpdateTime    *string           `json:"UpdateTime,omitempty"`
}

func (Map) CloudControlType() string { return "AWS::Location::Map" }

type DataSourceConfiguration struct {
	IntendedUse *string `json:"IntendedUse,omitempty"`
}

type PlaceIndexTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type PlaceIndex struct {
	Arn                     *string                  `json:"Arn,omitempty"`
	CreateTime              *string                  `json:"CreateTime,omitempty"`
	DataSource              *string                  `json:"DataSource,omitempty"`
	DataSourceConfiguration *DataSourceConfiguration `json:"DataSourceConfiguration,omitempty"`
	Description             *string                  `json:"Description,omitempty"`
	IndexArn                *string                  `json:"IndexArn,omitempty"`
	IndexName               *string                  `json:"IndexName,omitempty"`
	PricingPlan             *string                  `json:"PricingPlan,omitempty"`
	Tags                    []PlaceIndexTag          `json:"Tags,omitempty"`
	UpdateTime              *string                  `json:"UpdateTime,omitempty"`
}

func (PlaceIndex) CloudControlType() string { return "AWS::Location::PlaceIndex" }

type RouteCalculatorTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type RouteCalculator struct {
	Arn            *string              `json:"Arn,omitempty"`
	CalculatorArn  *string              `json:"CalculatorArn,omitempty"`
	CalculatorName *string              `json:"CalculatorName,omitempty"`
	CreateTime     *string              `json:"CreateTime,omitempty"`
	DataSource     *string              `json:"DataSource,omitempty"`
	Description    *string              `json:"Description,omitempty"`
	PricingPlan    *string              `json:"PricingPlan,omitempty"`
	Tags           []RouteCalculatorTag `json:"Tags,omitempty"`
	UpdateTime     *string              `json:"UpdateTime,omitempty"`
}

func (RouteCalculator) CloudControlType() string { return "AWS::Location::RouteCalculator" }

type TrackerTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Tracker struct {
	Arn                           *string      `json:"Arn,omitempty"`
	CreateTime                    *string      `json:"CreateTime,omitempty"`
	Description                   *string      `json:"Description,omitempty"`
	EventBridgeEnabled            *bool        `json:"EventBridgeEnabled,omitempty"`
	KmsKeyEnableGeospatialQueries *bool        `json:"KmsKeyEnableGeospatialQueries,omitempty"`
	KmsKeyId                      *string      `json:"KmsKeyId,omitempty"`
	PositionFiltering             *string      `json:"PositionFiltering,omitempty"`
	PricingPlan                   *string      `json:"PricingPlan,omitempty"`
	PricingPlanDataSource         *string      `json:"PricingPlanDataSource,omitempty"`
	Tags                          []TrackerTag `json:"Tags,omitempty"`
	TrackerArn                    *string      `json:"TrackerArn,omitempty"`
	TrackerName                   *string      `json:"TrackerName,omitempty"`
	UpdateTime                    *string      `json:"UpdateTime,omitempty"`
}

func (Tracker) CloudControlType() string { return "AWS::Location::Tracker" }

type TrackerConsumer struct {
	ConsumerArn *string `json:"ConsumerArn,omitempty"`
	TrackerName *string `json:"TrackerName,omitempty"`
}

func (TrackerConsumer) CloudControlType() string { return "AWS::Location::TrackerConsumer" }
