# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  postgres:
    image: ghcr.io/documentdb/documentdb/documentdb-local:latest
    restart: always
    environment:
      - USERNAME=username
      - PASSWORD=password
      - PORT=10260
      - SKIP_INIT_DATA=true
      - DATA_PATH=/usr/documentdb/data
    volumes:
      - ./.database:/usr/documentdb/data:U
    ports:
      - 10260:10260

networks:
  default:
    name: cloudjam
