services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:17
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ferret
      POSTGRES_PASSWORD: ferret
    volumes:
      - ./.database:/var/lib/postgresql:U,Z

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2
    restart: always
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://ferret:ferret@postgres:5432/postgres
      FERRETDB_LISTEN_ADDR: "-"
      FERRETDB_LISTEN_UNIX: "/run/ferret/ferret.sock"
    volumes:
      - ./.sockets:/run/ferret:U,Z

networks:
  default:
    name: ferretdb