syntax = "proto3";

package v1.admin.user;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "v1/admin/user.proto";

option go_package = "codeberg.org/megakuul/cloudjam/pkg/api/v1/admin/user";

message GetRequest {
  string id = 1 [
    (buf.validate.field).ignore = IGNORE_IF_ZERO_VALUE,
    (buf.validate.field).string = {uuid: true}
  ];
}

message GetResponse {
  User user = 1;
}

message ListRequest {
  int32 limit = 1 [(buf.validate.field).int32 = {
    gt: 0
    lte: 100
  }];
  int32 offset = 2;
}

message ListResponse {
  repeated User users = 1;
}

message CreateRequest {
  User init = 1;
  google.protobuf.Timestamp expires = 2 [(buf.validate.field).timestamp.gt_now = true];
}

message CreateResponse {
  string code = 1;
}

message UpdateRequest {
  User mod = 1;
}

message UpdateResponse {}

message ResetPasswordRequest {
  string email = 1 [(buf.validate.field).string.email = true];
  google.protobuf.Timestamp expires = 2 [(buf.validate.field).timestamp.gt_now = true];
}

message ResetPasswordResponse {
  string code = 1;
}

message DeleteRequest {
  string id = 1 [(buf.validate.field).string = {uuid: true}];
}

message DeleteResponse {}

service UserService {
  rpc Get(GetRequest) returns (GetResponse);
  rpc List(ListRequest) returns (ListResponse);
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Update(UpdateRequest) returns (UpdateResponse);
  rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
}
