// Code generated by go generate; DO NOT EDIT.

package iotanalytics

// The iam actions of the aws iotanalytics service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionBatchPutMessage            = "iotanalytics:BatchPutMessage"
	ActionCancelPipelineReprocessing = "iotanalytics:CancelPipelineReprocessing"
	ActionCreateChannel              = "iotanalytics:CreateChannel"
	ActionCreateDataset              = "iotanalytics:CreateDataset"
	ActionCreateDatasetContent       = "iotanalytics:CreateDatasetContent"
	ActionCreateDatastore            = "iotanalytics:CreateDatastore"
	ActionCreatePipeline             = "iotanalytics:CreatePipeline"
	ActionDeleteChannel              = "iotanalytics:DeleteChannel"
	ActionDeleteDataset              = "iotanalytics:DeleteDataset"
	ActionDeleteDatasetContent       = "iotanalytics:DeleteDatasetContent"
	ActionDeleteDatastore            = "iotanalytics:DeleteDatastore"
	ActionDeletePipeline             = "iotanalytics:DeletePipeline"
	ActionDescribeChannel            = "iotanalytics:DescribeChannel"
	ActionDescribeDataset            = "iotanalytics:DescribeDataset"
	ActionDescribeDatastore          = "iotanalytics:DescribeDatastore"
	ActionDescribeLoggingOptions     = "iotanalytics:DescribeLoggingOptions"
	ActionDescribePipeline           = "iotanalytics:DescribePipeline"
	ActionGetDatasetContent          = "iotanalytics:GetDatasetContent"
	ActionListChannels               = "iotanalytics:ListChannels"
	ActionListDatasetContents        = "iotanalytics:ListDatasetContents"
	ActionListDatasets               = "iotanalytics:ListDatasets"
	ActionListDatastores             = "iotanalytics:ListDatastores"
	ActionListPipelines              = "iotanalytics:ListPipelines"
	ActionListTagsForResource        = "iotanalytics:ListTagsForResource"
	ActionPutLoggingOptions          = "iotanalytics:PutLoggingOptions"
	ActionRunPipelineActivity        = "iotanalytics:RunPipelineActivity"
	ActionSampleChannelData          = "iotanalytics:SampleChannelData"
	ActionStartPipelineReprocessing  = "iotanalytics:StartPipelineReprocessing"
	ActionTagResource                = "iotanalytics:TagResource"
	ActionUntagResource              = "iotanalytics:UntagResource"
	ActionUpdateChannel              = "iotanalytics:UpdateChannel"
	ActionUpdateDataset              = "iotanalytics:UpdateDataset"
	ActionUpdateDatastore            = "iotanalytics:UpdateDatastore"
	ActionUpdatePipeline             = "iotanalytics:UpdatePipeline"
)

// ActionsList are the list actions, as classified by aws.
var ActionsList = []string{
	ActionListChannels,
	ActionListDatasetContents,
	ActionListDatasets,
	ActionListDatastores,
	ActionListPipelines,
}

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionDescribeChannel,
	ActionDescribeDataset,
	ActionDescribeDatastore,
	ActionDescribeLoggingOptions,
	ActionDescribePipeline,
	ActionGetDatasetContent,
	ActionListTagsForResource,
	ActionRunPipelineActivity,
	ActionSampleChannelData,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionBatchPutMessage,
	ActionCancelPipelineReprocessing,
	ActionCreateChannel,
	ActionCreateDataset,
	ActionCreateDatasetContent,
	ActionCreateDatastore,
	ActionCreatePipeline,
	ActionDeleteChannel,
	ActionDeleteDataset,
	ActionDeleteDatasetContent,
	ActionDeleteDatastore,
	ActionDeletePipeline,
	ActionPutLoggingOptions,
	ActionStartPipelineReprocessing,
	ActionUpdateChannel,
	ActionUpdateDataset,
	ActionUpdateDatastore,
	ActionUpdatePipeline,
}

// ActionsTagging are the tagging actions, as classified by aws.
var ActionsTagging = []string{
	ActionTagResource,
	ActionUntagResource,
}

// The condition keys that take a value. They return a plain string, so wrap
// them in policy.Key when a condition wants a policy.ConditionKey.
func ConditionKeyResourceTagFor(value string) string { return "iotanalytics:ResourceTag/" + value }
