// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/cloud/provider.proto

package cloud

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Credentials   string                 `protobuf:"bytes,5,opt,name=credentials,proto3" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_v1_cloud_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_v1_cloud_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_v1_cloud_provider_proto_rawDescGZIP(), []int{0}
}

func (x *Provider) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Provider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Provider) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Provider) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Provider) GetCredentials() string {
	if x != nil {
		return x.Credentials
	}
	return ""
}

var File_v1_cloud_provider_proto protoreflect.FileDescriptor

const file_v1_cloud_provider_proto_rawDesc = "" +
	"\n" +
	"\x17v1/cloud/provider.proto\x12\bv1.cloud\x1a\x1bbuf/validate/validate.proto\"\xaa\x01\n" +
	"\bProvider\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\x04name\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x04\x18\x14R\x04name\x12+\n" +
	"\vdescription\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x00\x182R\vdescription\x12,\n" +
	"\vcredentials\x18\x05 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x00\x18\xe8\aR\vcredentialsB1Z/codeberg.org/megakuul/cloudjam/pkg/api/v1/cloudb\x06proto3"

var (
	file_v1_cloud_provider_proto_rawDescOnce sync.Once
	file_v1_cloud_provider_proto_rawDescData []byte
)

func file_v1_cloud_provider_proto_rawDescGZIP() []byte {
	file_v1_cloud_provider_proto_rawDescOnce.Do(func() {
		file_v1_cloud_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_cloud_provider_proto_rawDesc), len(file_v1_cloud_provider_proto_rawDesc)))
	})
	return file_v1_cloud_provider_proto_rawDescData
}

var file_v1_cloud_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_v1_cloud_provider_proto_goTypes = []any{
	(*Provider)(nil), // 0: v1.cloud.Provider
}
var file_v1_cloud_provider_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_cloud_provider_proto_init() }
func file_v1_cloud_provider_proto_init() {
	if File_v1_cloud_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_cloud_provider_proto_rawDesc), len(file_v1_cloud_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_cloud_provider_proto_goTypes,
		DependencyIndexes: file_v1_cloud_provider_proto_depIdxs,
		MessageInfos:      file_v1_cloud_provider_proto_msgTypes,
	}.Build()
	File_v1_cloud_provider_proto = out.File
	file_v1_cloud_provider_proto_goTypes = nil
	file_v1_cloud_provider_proto_depIdxs = nil
}
