syntax = "proto3";

package v1.play.game;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "v1/play/game.proto";

option go_package = "codeberg.org/megakuul/cloudjam/pkg/api/v1/play/game";

message GetRequest {
  string id = 1 [(buf.validate.field).string = {uuid: true}];
}

message GetResponse {
  Game game = 1;
}

message ListRequest {
  int32 limit = 1 [(buf.validate.field).int32 = {
    gt: 0
    lte: 100
  }];
}

message ListResponse {
  repeated Game games = 1;
}

message CreateRequest {
  Game init = 1;
}

message CreateResponse {}

message UpdateRequest {
  Game mod = 1;
}

message UpdateResponse {}

message DeleteRequest {
  string id = 1 [(buf.validate.field).string = {uuid: true}];
}

message DeleteResponse {}

service GameService {
  rpc Get(GetRequest) returns (GetResponse);
  rpc List(ListRequest) returns (ListResponse);
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Update(UpdateRequest) returns (UpdateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
}
