// Code generated by go generate; DO NOT EDIT.

package workspacesweb

// The iam actions of the aws workspaces-web service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionAssociateBrowserSettings              = "workspaces-web:AssociateBrowserSettings"
	ActionAssociateDataProtectionSettings       = "workspaces-web:AssociateDataProtectionSettings"
	ActionAssociateIpAccessSettings             = "workspaces-web:AssociateIpAccessSettings"
	ActionAssociateNetworkSettings              = "workspaces-web:AssociateNetworkSettings"
	ActionAssociateSessionLogger                = "workspaces-web:AssociateSessionLogger"
	ActionAssociateTrustStore                   = "workspaces-web:AssociateTrustStore"
	ActionAssociateUserAccessLoggingSettings    = "workspaces-web:AssociateUserAccessLoggingSettings"
	ActionAssociateUserSettings                 = "workspaces-web:AssociateUserSettings"
	ActionCreateBrowserSettings                 = "workspaces-web:CreateBrowserSettings"
	ActionCreateDataProtectionSettings          = "workspaces-web:CreateDataProtectionSettings"
	ActionCreateIdentityProvider                = "workspaces-web:CreateIdentityProvider"
	ActionCreateIpAccessSettings                = "workspaces-web:CreateIpAccessSettings"
	ActionCreateNetworkSettings                 = "workspaces-web:CreateNetworkSettings"
	ActionCreatePortal                          = "workspaces-web:CreatePortal"
	ActionCreateSessionLogger                   = "workspaces-web:CreateSessionLogger"
	ActionCreateTrustStore                      = "workspaces-web:CreateTrustStore"
	ActionCreateUserAccessLoggingSettings       = "workspaces-web:CreateUserAccessLoggingSettings"
	ActionCreateUserSettings                    = "workspaces-web:CreateUserSettings"
	ActionDeleteBrowserSettings                 = "workspaces-web:DeleteBrowserSettings"
	ActionDeleteDataProtectionSettings          = "workspaces-web:DeleteDataProtectionSettings"
	ActionDeleteIdentityProvider                = "workspaces-web:DeleteIdentityProvider"
	ActionDeleteIpAccessSettings                = "workspaces-web:DeleteIpAccessSettings"
	ActionDeleteNetworkSettings                 = "workspaces-web:DeleteNetworkSettings"
	ActionDeletePortal                          = "workspaces-web:DeletePortal"
	ActionDeleteSessionLogger                   = "workspaces-web:DeleteSessionLogger"
	ActionDeleteTrustStore                      = "workspaces-web:DeleteTrustStore"
	ActionDeleteUserAccessLoggingSettings       = "workspaces-web:DeleteUserAccessLoggingSettings"
	ActionDeleteUserSettings                    = "workspaces-web:DeleteUserSettings"
	ActionDisassociateBrowserSettings           = "workspaces-web:DisassociateBrowserSettings"
	ActionDisassociateDataProtectionSettings    = "workspaces-web:DisassociateDataProtectionSettings"
	ActionDisassociateIpAccessSettings          = "workspaces-web:DisassociateIpAccessSettings"
	ActionDisassociateNetworkSettings           = "workspaces-web:DisassociateNetworkSettings"
	ActionDisassociateSessionLogger             = "workspaces-web:DisassociateSessionLogger"
	ActionDisassociateTrustStore                = "workspaces-web:DisassociateTrustStore"
	ActionDisassociateUserAccessLoggingSettings = "workspaces-web:DisassociateUserAccessLoggingSettings"
	ActionDisassociateUserSettings              = "workspaces-web:DisassociateUserSettings"
	ActionExpireSession                         = "workspaces-web:ExpireSession"
	ActionGetBrowserSettings                    = "workspaces-web:GetBrowserSettings"
	ActionGetDataProtectionSettings             = "workspaces-web:GetDataProtectionSettings"
	ActionGetIdentityProvider                   = "workspaces-web:GetIdentityProvider"
	ActionGetIpAccessSettings                   = "workspaces-web:GetIpAccessSettings"
	ActionGetNetworkSettings                    = "workspaces-web:GetNetworkSettings"
	ActionGetPortal                             = "workspaces-web:GetPortal"
	ActionGetPortalServiceProviderMetadata      = "workspaces-web:GetPortalServiceProviderMetadata"
	ActionGetSession                            = "workspaces-web:GetSession"
	ActionGetSessionLogger                      = "workspaces-web:GetSessionLogger"
	ActionGetTrustStore                         = "workspaces-web:GetTrustStore"
	ActionGetTrustStoreCertificate              = "workspaces-web:GetTrustStoreCertificate"
	ActionGetUserAccessLoggingSettings          = "workspaces-web:GetUserAccessLoggingSettings"
	ActionGetUserSettings                       = "workspaces-web:GetUserSettings"
	ActionListBrowserSettings                   = "workspaces-web:ListBrowserSettings"
	ActionListDataProtectionSettings            = "workspaces-web:ListDataProtectionSettings"
	ActionListIdentityProviders                 = "workspaces-web:ListIdentityProviders"
	ActionListIpAccessSettings                  = "workspaces-web:ListIpAccessSettings"
	ActionListNetworkSettings                   = "workspaces-web:ListNetworkSettings"
	ActionListPortals                           = "workspaces-web:ListPortals"
	ActionListSessionLoggers                    = "workspaces-web:ListSessionLoggers"
	ActionListSessions                          = "workspaces-web:ListSessions"
	ActionListTagsForResource                   = "workspaces-web:ListTagsForResource"
	ActionListTrustStoreCertificates            = "workspaces-web:ListTrustStoreCertificates"
	ActionListTrustStores                       = "workspaces-web:ListTrustStores"
	ActionListUserAccessLoggingSettings         = "workspaces-web:ListUserAccessLoggingSettings"
	ActionListUserSettings                      = "workspaces-web:ListUserSettings"
	ActionTagResource                           = "workspaces-web:TagResource"
	ActionUntagResource                         = "workspaces-web:UntagResource"
	ActionUpdateBrowserSettings                 = "workspaces-web:UpdateBrowserSettings"
	ActionUpdateDataProtectionSettings          = "workspaces-web:UpdateDataProtectionSettings"
	ActionUpdateIdentityProvider                = "workspaces-web:UpdateIdentityProvider"
	ActionUpdateIpAccessSettings                = "workspaces-web:UpdateIpAccessSettings"
	ActionUpdateNetworkSettings                 = "workspaces-web:UpdateNetworkSettings"
	ActionUpdatePortal                          = "workspaces-web:UpdatePortal"
	ActionUpdateSessionLogger                   = "workspaces-web:UpdateSessionLogger"
	ActionUpdateTrustStore                      = "workspaces-web:UpdateTrustStore"
	ActionUpdateUserAccessLoggingSettings       = "workspaces-web:UpdateUserAccessLoggingSettings"
	ActionUpdateUserSettings                    = "workspaces-web:UpdateUserSettings"
)

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionGetBrowserSettings,
	ActionGetDataProtectionSettings,
	ActionGetIdentityProvider,
	ActionGetIpAccessSettings,
	ActionGetNetworkSettings,
	ActionGetPortal,
	ActionGetPortalServiceProviderMetadata,
	ActionGetSession,
	ActionGetSessionLogger,
	ActionGetTrustStore,
	ActionGetTrustStoreCertificate,
	ActionGetUserAccessLoggingSettings,
	ActionGetUserSettings,
	ActionListBrowserSettings,
	ActionListDataProtectionSettings,
	ActionListIdentityProviders,
	ActionListIpAccessSettings,
	ActionListNetworkSettings,
	ActionListPortals,
	ActionListSessionLoggers,
	ActionListSessions,
	ActionListTagsForResource,
	ActionListTrustStoreCertificates,
	ActionListTrustStores,
	ActionListUserAccessLoggingSettings,
	ActionListUserSettings,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionAssociateBrowserSettings,
	ActionAssociateDataProtectionSettings,
	ActionAssociateIpAccessSettings,
	ActionAssociateNetworkSettings,
	ActionAssociateSessionLogger,
	ActionAssociateTrustStore,
	ActionAssociateUserAccessLoggingSettings,
	ActionAssociateUserSettings,
	ActionCreateBrowserSettings,
	ActionCreateDataProtectionSettings,
	ActionCreateIdentityProvider,
	ActionCreateIpAccessSettings,
	ActionCreateNetworkSettings,
	ActionCreatePortal,
	ActionCreateSessionLogger,
	ActionCreateTrustStore,
	ActionCreateUserAccessLoggingSettings,
	ActionCreateUserSettings,
	ActionDeleteBrowserSettings,
	ActionDeleteDataProtectionSettings,
	ActionDeleteIdentityProvider,
	ActionDeleteIpAccessSettings,
	ActionDeleteNetworkSettings,
	ActionDeletePortal,
	ActionDeleteSessionLogger,
	ActionDeleteTrustStore,
	ActionDeleteUserAccessLoggingSettings,
	ActionDeleteUserSettings,
	ActionDisassociateBrowserSettings,
	ActionDisassociateDataProtectionSettings,
	ActionDisassociateIpAccessSettings,
	ActionDisassociateNetworkSettings,
	ActionDisassociateSessionLogger,
	ActionDisassociateTrustStore,
	ActionDisassociateUserAccessLoggingSettings,
	ActionDisassociateUserSettings,
	ActionExpireSession,
	ActionUpdateBrowserSettings,
	ActionUpdateDataProtectionSettings,
	ActionUpdateIdentityProvider,
	ActionUpdateIpAccessSettings,
	ActionUpdateNetworkSettings,
	ActionUpdatePortal,
	ActionUpdateSessionLogger,
	ActionUpdateTrustStore,
	ActionUpdateUserAccessLoggingSettings,
	ActionUpdateUserSettings,
}

// ActionsTagging are the tagging actions, as classified by aws.
var ActionsTagging = []string{
	ActionTagResource,
	ActionUntagResource,
}
