// Code generated by go generate; DO NOT EDIT.

// Package systemsmanagersap holds the cloud control resources of the aws systemsmanagersap service.
package systemsmanagersap

type ComponentInfo struct {
	ComponentType *string `json:"ComponentType,omitempty"`
	Ec2InstanceId *string `json:"Ec2InstanceId,omitempty"`
	Sid           *string `json:"Sid,omitempty"`
}

type Credential struct {
	CredentialType *string `json:"CredentialType,omitempty"`
	DatabaseName   *string `json:"DatabaseName,omitempty"`
	SecretId       *string `json:"SecretId,omitempty"`
}

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Application struct {
	ApplicationId     *string         `json:"ApplicationId,omitempty"`
	ApplicationType   *string         `json:"ApplicationType,omitempty"`
	Arn               *string         `json:"Arn,omitempty"`
	ComponentsInfo    []ComponentInfo `json:"ComponentsInfo,omitempty"`
	Credentials       []Credential    `json:"Credentials,omitempty"`
	DatabaseArn       *string         `json:"DatabaseArn,omitempty"`
	Instances         []string        `json:"Instances,omitempty"`
	SapInstanceNumber *string         `json:"SapInstanceNumber,omitempty"`
	Sid               *string         `json:"Sid,omitempty"`
	Tags              []Tag           `json:"Tags,omitempty"`
}

func (Application) CloudControlType() string { return "AWS::SystemsManagerSAP::Application" }
