syntax = "proto3";

package v1.cloud.definition;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "v1/cloud/definition.proto";

option go_package = "codeberg.org/megakuul/cloudjam/pkg/api/v1/cloud/definition";

message GetRequest {
  string provider_id = 1 [(buf.validate.field).string = {uuid: true}];
  string id = 2 [(buf.validate.field).string = {uuid: true}];
}

message GetResponse {
  Definition definition = 1;
}

message ListRequest {
  string provider_id = 1 [(buf.validate.field).string = {uuid: true}];
  int32 limit = 2 [(buf.validate.field).int32 = {
    gt: 0
    lte: 100
  }];
  string start_after = 3;
}

message ListResponse {
  repeated Definition definitions = 1;
}

message CreateRequest {
  Definition init = 1;
  CompressionMode compression = 2;
  bytes binary = 3 [(buf.validate.field).bytes.max_len = 50000000]; // 50 MB
}

message CreateResponse {
  string id = 1 [(buf.validate.field).string = {uuid: true}];
}

message UpdateRequest {
  Definition mod = 1;
  CompressionMode compression = 2;
  bytes binary = 3 [(buf.validate.field).bytes.max_len = 50000000]; // 50 MB
}

message UpdateResponse {}

message DeleteRequest {
  string provider_id = 1 [(buf.validate.field).string = {uuid: true}];
  string id = 2 [(buf.validate.field).string = {uuid: true}];
}

message DeleteResponse {}

service DefinitionService {
  rpc Get(GetRequest) returns (GetResponse);
  rpc List(ListRequest) returns (ListResponse);
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Update(UpdateRequest) returns (UpdateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
}
