// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: v1/play/challenge/challenge.proto

package challengeconnect

import (
	challenge "codeberg.org/megakuul/cloudjam/pkg/api/v1/play/challenge"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ChallengeServiceName is the fully-qualified name of the ChallengeService service.
	ChallengeServiceName = "v1.play.challenge.ChallengeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChallengeServiceGetProcedure is the fully-qualified name of the ChallengeService's Get RPC.
	ChallengeServiceGetProcedure = "/v1.play.challenge.ChallengeService/Get"
	// ChallengeServiceListProcedure is the fully-qualified name of the ChallengeService's List RPC.
	ChallengeServiceListProcedure = "/v1.play.challenge.ChallengeService/List"
	// ChallengeServiceCreateProcedure is the fully-qualified name of the ChallengeService's Create RPC.
	ChallengeServiceCreateProcedure = "/v1.play.challenge.ChallengeService/Create"
	// ChallengeServiceUpdateProcedure is the fully-qualified name of the ChallengeService's Update RPC.
	ChallengeServiceUpdateProcedure = "/v1.play.challenge.ChallengeService/Update"
	// ChallengeServiceDeleteProcedure is the fully-qualified name of the ChallengeService's Delete RPC.
	ChallengeServiceDeleteProcedure = "/v1.play.challenge.ChallengeService/Delete"
	// ChallengeServiceStartProcedure is the fully-qualified name of the ChallengeService's Start RPC.
	ChallengeServiceStartProcedure = "/v1.play.challenge.ChallengeService/Start"
	// ChallengeServiceCredentialsProcedure is the fully-qualified name of the ChallengeService's
	// Credentials RPC.
	ChallengeServiceCredentialsProcedure = "/v1.play.challenge.ChallengeService/Credentials"
	// ChallengeServiceUncoverClueProcedure is the fully-qualified name of the ChallengeService's
	// UncoverClue RPC.
	ChallengeServiceUncoverClueProcedure = "/v1.play.challenge.ChallengeService/UncoverClue"
)

// ChallengeServiceClient is a client for the v1.play.challenge.ChallengeService service.
type ChallengeServiceClient interface {
	Get(context.Context, *connect.Request[challenge.GetRequest]) (*connect.Response[challenge.GetResponse], error)
	List(context.Context, *connect.Request[challenge.ListRequest]) (*connect.Response[challenge.ListResponse], error)
	Create(context.Context, *connect.Request[challenge.CreateRequest]) (*connect.Response[challenge.CreateResponse], error)
	Update(context.Context, *connect.Request[challenge.UpdateRequest]) (*connect.Response[challenge.UpdateResponse], error)
	Delete(context.Context, *connect.Request[challenge.DeleteRequest]) (*connect.Response[challenge.DeleteResponse], error)
	Start(context.Context, *connect.Request[challenge.StartRequest]) (*connect.Response[challenge.StartResponse], error)
	Credentials(context.Context, *connect.Request[challenge.CredentialsRequest]) (*connect.Response[challenge.CredentialsResponse], error)
	UncoverClue(context.Context, *connect.Request[challenge.UncoverClueRequest]) (*connect.Response[challenge.UncoverClueResponse], error)
}

// NewChallengeServiceClient constructs a client for the v1.play.challenge.ChallengeService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChallengeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChallengeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	challengeServiceMethods := challenge.File_v1_play_challenge_challenge_proto.Services().ByName("ChallengeService").Methods()
	return &challengeServiceClient{
		get: connect.NewClient[challenge.GetRequest, challenge.GetResponse](
			httpClient,
			baseURL+ChallengeServiceGetProcedure,
			connect.WithSchema(challengeServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[challenge.ListRequest, challenge.ListResponse](
			httpClient,
			baseURL+ChallengeServiceListProcedure,
			connect.WithSchema(challengeServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		create: connect.NewClient[challenge.CreateRequest, challenge.CreateResponse](
			httpClient,
			baseURL+ChallengeServiceCreateProcedure,
			connect.WithSchema(challengeServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[challenge.UpdateRequest, challenge.UpdateResponse](
			httpClient,
			baseURL+ChallengeServiceUpdateProcedure,
			connect.WithSchema(challengeServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[challenge.DeleteRequest, challenge.DeleteResponse](
			httpClient,
			baseURL+ChallengeServiceDeleteProcedure,
			connect.WithSchema(challengeServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		start: connect.NewClient[challenge.StartRequest, challenge.StartResponse](
			httpClient,
			baseURL+ChallengeServiceStartProcedure,
			connect.WithSchema(challengeServiceMethods.ByName("Start")),
			connect.WithClientOptions(opts...),
		),
		credentials: connect.NewClient[challenge.CredentialsRequest, challenge.CredentialsResponse](
			httpClient,
			baseURL+ChallengeServiceCredentialsProcedure,
			connect.WithSchema(challengeServiceMethods.ByName("Credentials")),
			connect.WithClientOptions(opts...),
		),
		uncoverClue: connect.NewClient[challenge.UncoverClueRequest, challenge.UncoverClueResponse](
			httpClient,
			baseURL+ChallengeServiceUncoverClueProcedure,
			connect.WithSchema(challengeServiceMethods.ByName("UncoverClue")),
			connect.WithClientOptions(opts...),
		),
	}
}

// challengeServiceClient implements ChallengeServiceClient.
type challengeServiceClient struct {
	get         *connect.Client[challenge.GetRequest, challenge.GetResponse]
	list        *connect.Client[challenge.ListRequest, challenge.ListResponse]
	create      *connect.Client[challenge.CreateRequest, challenge.CreateResponse]
	update      *connect.Client[challenge.UpdateRequest, challenge.UpdateResponse]
	delete      *connect.Client[challenge.DeleteRequest, challenge.DeleteResponse]
	start       *connect.Client[challenge.StartRequest, challenge.StartResponse]
	credentials *connect.Client[challenge.CredentialsRequest, challenge.CredentialsResponse]
	uncoverClue *connect.Client[challenge.UncoverClueRequest, challenge.UncoverClueResponse]
}

// Get calls v1.play.challenge.ChallengeService.Get.
func (c *challengeServiceClient) Get(ctx context.Context, req *connect.Request[challenge.GetRequest]) (*connect.Response[challenge.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// List calls v1.play.challenge.ChallengeService.List.
func (c *challengeServiceClient) List(ctx context.Context, req *connect.Request[challenge.ListRequest]) (*connect.Response[challenge.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Create calls v1.play.challenge.ChallengeService.Create.
func (c *challengeServiceClient) Create(ctx context.Context, req *connect.Request[challenge.CreateRequest]) (*connect.Response[challenge.CreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Update calls v1.play.challenge.ChallengeService.Update.
func (c *challengeServiceClient) Update(ctx context.Context, req *connect.Request[challenge.UpdateRequest]) (*connect.Response[challenge.UpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls v1.play.challenge.ChallengeService.Delete.
func (c *challengeServiceClient) Delete(ctx context.Context, req *connect.Request[challenge.DeleteRequest]) (*connect.Response[challenge.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// Start calls v1.play.challenge.ChallengeService.Start.
func (c *challengeServiceClient) Start(ctx context.Context, req *connect.Request[challenge.StartRequest]) (*connect.Response[challenge.StartResponse], error) {
	return c.start.CallUnary(ctx, req)
}

// Credentials calls v1.play.challenge.ChallengeService.Credentials.
func (c *challengeServiceClient) Credentials(ctx context.Context, req *connect.Request[challenge.CredentialsRequest]) (*connect.Response[challenge.CredentialsResponse], error) {
	return c.credentials.CallUnary(ctx, req)
}

// UncoverClue calls v1.play.challenge.ChallengeService.UncoverClue.
func (c *challengeServiceClient) UncoverClue(ctx context.Context, req *connect.Request[challenge.UncoverClueRequest]) (*connect.Response[challenge.UncoverClueResponse], error) {
	return c.uncoverClue.CallUnary(ctx, req)
}

// ChallengeServiceHandler is an implementation of the v1.play.challenge.ChallengeService service.
type ChallengeServiceHandler interface {
	Get(context.Context, *connect.Request[challenge.GetRequest]) (*connect.Response[challenge.GetResponse], error)
	List(context.Context, *connect.Request[challenge.ListRequest]) (*connect.Response[challenge.ListResponse], error)
	Create(context.Context, *connect.Request[challenge.CreateRequest]) (*connect.Response[challenge.CreateResponse], error)
	Update(context.Context, *connect.Request[challenge.UpdateRequest]) (*connect.Response[challenge.UpdateResponse], error)
	Delete(context.Context, *connect.Request[challenge.DeleteRequest]) (*connect.Response[challenge.DeleteResponse], error)
	Start(context.Context, *connect.Request[challenge.StartRequest]) (*connect.Response[challenge.StartResponse], error)
	Credentials(context.Context, *connect.Request[challenge.CredentialsRequest]) (*connect.Response[challenge.CredentialsResponse], error)
	UncoverClue(context.Context, *connect.Request[challenge.UncoverClueRequest]) (*connect.Response[challenge.UncoverClueResponse], error)
}

// NewChallengeServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChallengeServiceHandler(svc ChallengeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	challengeServiceMethods := challenge.File_v1_play_challenge_challenge_proto.Services().ByName("ChallengeService").Methods()
	challengeServiceGetHandler := connect.NewUnaryHandler(
		ChallengeServiceGetProcedure,
		svc.Get,
		connect.WithSchema(challengeServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	challengeServiceListHandler := connect.NewUnaryHandler(
		ChallengeServiceListProcedure,
		svc.List,
		connect.WithSchema(challengeServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	challengeServiceCreateHandler := connect.NewUnaryHandler(
		ChallengeServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(challengeServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	challengeServiceUpdateHandler := connect.NewUnaryHandler(
		ChallengeServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(challengeServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	challengeServiceDeleteHandler := connect.NewUnaryHandler(
		ChallengeServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(challengeServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	challengeServiceStartHandler := connect.NewUnaryHandler(
		ChallengeServiceStartProcedure,
		svc.Start,
		connect.WithSchema(challengeServiceMethods.ByName("Start")),
		connect.WithHandlerOptions(opts...),
	)
	challengeServiceCredentialsHandler := connect.NewUnaryHandler(
		ChallengeServiceCredentialsProcedure,
		svc.Credentials,
		connect.WithSchema(challengeServiceMethods.ByName("Credentials")),
		connect.WithHandlerOptions(opts...),
	)
	challengeServiceUncoverClueHandler := connect.NewUnaryHandler(
		ChallengeServiceUncoverClueProcedure,
		svc.UncoverClue,
		connect.WithSchema(challengeServiceMethods.ByName("UncoverClue")),
		connect.WithHandlerOptions(opts...),
	)
	return "/v1.play.challenge.ChallengeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChallengeServiceGetProcedure:
			challengeServiceGetHandler.ServeHTTP(w, r)
		case ChallengeServiceListProcedure:
			challengeServiceListHandler.ServeHTTP(w, r)
		case ChallengeServiceCreateProcedure:
			challengeServiceCreateHandler.ServeHTTP(w, r)
		case ChallengeServiceUpdateProcedure:
			challengeServiceUpdateHandler.ServeHTTP(w, r)
		case ChallengeServiceDeleteProcedure:
			challengeServiceDeleteHandler.ServeHTTP(w, r)
		case ChallengeServiceStartProcedure:
			challengeServiceStartHandler.ServeHTTP(w, r)
		case ChallengeServiceCredentialsProcedure:
			challengeServiceCredentialsHandler.ServeHTTP(w, r)
		case ChallengeServiceUncoverClueProcedure:
			challengeServiceUncoverClueHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChallengeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChallengeServiceHandler struct{}

func (UnimplementedChallengeServiceHandler) Get(context.Context, *connect.Request[challenge.GetRequest]) (*connect.Response[challenge.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.play.challenge.ChallengeService.Get is not implemented"))
}

func (UnimplementedChallengeServiceHandler) List(context.Context, *connect.Request[challenge.ListRequest]) (*connect.Response[challenge.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.play.challenge.ChallengeService.List is not implemented"))
}

func (UnimplementedChallengeServiceHandler) Create(context.Context, *connect.Request[challenge.CreateRequest]) (*connect.Response[challenge.CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.play.challenge.ChallengeService.Create is not implemented"))
}

func (UnimplementedChallengeServiceHandler) Update(context.Context, *connect.Request[challenge.UpdateRequest]) (*connect.Response[challenge.UpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.play.challenge.ChallengeService.Update is not implemented"))
}

func (UnimplementedChallengeServiceHandler) Delete(context.Context, *connect.Request[challenge.DeleteRequest]) (*connect.Response[challenge.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.play.challenge.ChallengeService.Delete is not implemented"))
}

func (UnimplementedChallengeServiceHandler) Start(context.Context, *connect.Request[challenge.StartRequest]) (*connect.Response[challenge.StartResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.play.challenge.ChallengeService.Start is not implemented"))
}

func (UnimplementedChallengeServiceHandler) Credentials(context.Context, *connect.Request[challenge.CredentialsRequest]) (*connect.Response[challenge.CredentialsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.play.challenge.ChallengeService.Credentials is not implemented"))
}

func (UnimplementedChallengeServiceHandler) UncoverClue(context.Context, *connect.Request[challenge.UncoverClueRequest]) (*connect.Response[challenge.UncoverClueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("v1.play.challenge.ChallengeService.UncoverClue is not implemented"))
}
