// Code generated by go generate; DO NOT EDIT.

// Package finspace holds the cloud control resources of the aws finspace service.
package finspace

type FederationParametersAttributeMapItem struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type FederationParameters struct {
	ApplicationCallBackURL *string                                `json:"ApplicationCallBackURL,omitempty"`
	AttributeMap           []FederationParametersAttributeMapItem `json:"AttributeMap,omitempty"`
	FederationProviderName *string                                `json:"FederationProviderName,omitempty"`
	FederationURN          *string                                `json:"FederationURN,omitempty"`
	SamlMetadataDocument   *string                                `json:"SamlMetadataDocument,omitempty"`
	SamlMetadataURL        *string                                `json:"SamlMetadataURL,omitempty"`
}

type SuperuserParameters struct {
	EmailAddress *string `json:"EmailAddress,omitempty"`
	FirstName    *string `json:"FirstName,omitempty"`
	LastName     *string `json:"LastName,omitempty"`
}

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Environment struct {
	AwsAccountId              *string               `json:"AwsAccountId,omitempty"`
	DataBundles               []string              `json:"DataBundles,omitempty"`
	DedicatedServiceAccountId *string               `json:"DedicatedServiceAccountId,omitempty"`
	Description               *string               `json:"Description,omitempty"`
	EnvironmentArn            *string               `json:"EnvironmentArn,omitempty"`
	EnvironmentId             *string               `json:"EnvironmentId,omitempty"`
	EnvironmentUrl            *string               `json:"EnvironmentUrl,omitempty"`
	FederationMode            *string               `json:"FederationMode,omitempty"`
	FederationParameters      *FederationParameters `json:"FederationParameters,omitempty"`
	KmsKeyId                  *string               `json:"KmsKeyId,omitempty"`
	Name                      *string               `json:"Name,omitempty"`
	SageMakerStudioDomainUrl  *string               `json:"SageMakerStudioDomainUrl,omitempty"`
	Status                    *string               `json:"Status,omitempty"`
	SuperuserParameters       *SuperuserParameters  `json:"SuperuserParameters,omitempty"`
	Tags                      []Tag                 `json:"Tags,omitempty"`
}

func (Environment) CloudControlType() string { return "AWS::FinSpace::Environment" }
