// Code generated by go generate; DO NOT EDIT.

package iqpermission

// The iam actions of the aws iq-permission service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionApproveAccessGrant        = "iq-permission:ApproveAccessGrant"
	ActionApprovePermissionRequest  = "iq-permission:ApprovePermissionRequest"
	ActionAssumePermissionRole      = "iq-permission:AssumePermissionRole"
	ActionCreatePermissionRequest   = "iq-permission:CreatePermissionRequest"
	ActionGetPermissionRequest      = "iq-permission:GetPermissionRequest"
	ActionListPermissionRequests    = "iq-permission:ListPermissionRequests"
	ActionRejectPermissionRequest   = "iq-permission:RejectPermissionRequest"
	ActionRevokePermissionRequest   = "iq-permission:RevokePermissionRequest"
	ActionWithdrawPermissionRequest = "iq-permission:WithdrawPermissionRequest"
)

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionGetPermissionRequest,
	ActionListPermissionRequests,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionApproveAccessGrant,
	ActionApprovePermissionRequest,
	ActionAssumePermissionRole,
	ActionCreatePermissionRequest,
	ActionRejectPermissionRequest,
	ActionRevokePermissionRequest,
	ActionWithdrawPermissionRequest,
}
