// Code generated by go generate; DO NOT EDIT.

package interconnect

// The iam actions of the aws interconnect service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionAcceptConnectionProposal   = "interconnect:AcceptConnectionProposal"
	ActionCreateConnection           = "interconnect:CreateConnection"
	ActionDeleteConnection           = "interconnect:DeleteConnection"
	ActionDescribeConnectionProposal = "interconnect:DescribeConnectionProposal"
	ActionGetConnection              = "interconnect:GetConnection"
	ActionGetEnvironment             = "interconnect:GetEnvironment"
	ActionListAttachPoints           = "interconnect:ListAttachPoints"
	ActionListConnections            = "interconnect:ListConnections"
	ActionListEnvironments           = "interconnect:ListEnvironments"
	ActionListTagsForResource        = "interconnect:ListTagsForResource"
	ActionTagResource                = "interconnect:TagResource"
	ActionUntagResource              = "interconnect:UntagResource"
	ActionUpdateConnection           = "interconnect:UpdateConnection"
)

// ActionsList are the list actions, as classified by aws.
var ActionsList = []string{
	ActionListConnections,
	ActionListEnvironments,
}

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionDescribeConnectionProposal,
	ActionGetConnection,
	ActionGetEnvironment,
	ActionListAttachPoints,
	ActionListTagsForResource,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionAcceptConnectionProposal,
	ActionCreateConnection,
	ActionDeleteConnection,
	ActionUpdateConnection,
}

// ActionsTagging are the tagging actions, as classified by aws.
var ActionsTagging = []string{
	ActionTagResource,
	ActionUntagResource,
}
