// Code generated by go generate; DO NOT EDIT.

package appstudio

// The iam actions of the aws appstudio service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionGetAccountStatus           = "appstudio:GetAccountStatus"
	ActionGetEnablementJobStatus     = "appstudio:GetEnablementJobStatus"
	ActionStartEnablementJob         = "appstudio:StartEnablementJob"
	ActionStartRollbackEnablementJob = "appstudio:StartRollbackEnablementJob"
	ActionStartTeamDeployment        = "appstudio:StartTeamDeployment"
)

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionGetAccountStatus,
	ActionGetEnablementJobStatus,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionStartEnablementJob,
	ActionStartRollbackEnablementJob,
	ActionStartTeamDeployment,
}
