// Code generated by go generate; DO NOT EDIT.

package scn

// The iam actions of the aws scn service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionAssignAdminPermissionsToUser      = "scn:AssignAdminPermissionsToUser"
	ActionCreateBillOfMaterialsImportJob    = "scn:CreateBillOfMaterialsImportJob"
	ActionCreateDataIntegrationFlow         = "scn:CreateDataIntegrationFlow"
	ActionCreateDataLakeDataset             = "scn:CreateDataLakeDataset"
	ActionCreateDataLakeNamespace           = "scn:CreateDataLakeNamespace"
	ActionCreateInstance                    = "scn:CreateInstance"
	ActionCreateSSOApplication              = "scn:CreateSSOApplication"
	ActionDeleteDataIntegrationFlow         = "scn:DeleteDataIntegrationFlow"
	ActionDeleteDataLakeDataset             = "scn:DeleteDataLakeDataset"
	ActionDeleteDataLakeNamespace           = "scn:DeleteDataLakeNamespace"
	ActionDeleteInstance                    = "scn:DeleteInstance"
	ActionDeleteSSOApplication              = "scn:DeleteSSOApplication"
	ActionDescribeInstance                  = "scn:DescribeInstance"
	ActionGetBillOfMaterialsImportJob       = "scn:GetBillOfMaterialsImportJob"
	ActionGetDataIntegrationEvent           = "scn:GetDataIntegrationEvent"
	ActionGetDataIntegrationFlow            = "scn:GetDataIntegrationFlow"
	ActionGetDataIntegrationFlowExecution   = "scn:GetDataIntegrationFlowExecution"
	ActionGetDataLakeDataset                = "scn:GetDataLakeDataset"
	ActionGetDataLakeNamespace              = "scn:GetDataLakeNamespace"
	ActionGetInstance                       = "scn:GetInstance"
	ActionListAdminUsers                    = "scn:ListAdminUsers"
	ActionListDataIntegrationEvents         = "scn:ListDataIntegrationEvents"
	ActionListDataIntegrationFlowExecutions = "scn:ListDataIntegrationFlowExecutions"
	ActionListDataIntegrationFlows          = "scn:ListDataIntegrationFlows"
	ActionListDataLakeDatasets              = "scn:ListDataLakeDatasets"
	ActionListDataLakeNamespaces            = "scn:ListDataLakeNamespaces"
	ActionListInstances                     = "scn:ListInstances"
	ActionListTagsForResource               = "scn:ListTagsForResource"
	ActionRemoveAdminPermissionsForUser     = "scn:RemoveAdminPermissionsForUser"
	ActionSendDataIntegrationEvent          = "scn:SendDataIntegrationEvent"
	ActionTagResource                       = "scn:TagResource"
	ActionUntagResource                     = "scn:UntagResource"
	ActionUpdateDataIntegrationFlow         = "scn:UpdateDataIntegrationFlow"
	ActionUpdateDataLakeDataset             = "scn:UpdateDataLakeDataset"
	ActionUpdateDataLakeNamespace           = "scn:UpdateDataLakeNamespace"
	ActionUpdateInstance                    = "scn:UpdateInstance"
)

// ActionsList are the list actions, as classified by aws.
var ActionsList = []string{
	ActionListAdminUsers,
	ActionListDataIntegrationEvents,
	ActionListDataIntegrationFlowExecutions,
	ActionListDataIntegrationFlows,
	ActionListDataLakeDatasets,
	ActionListDataLakeNamespaces,
	ActionListInstances,
	ActionListTagsForResource,
}

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionDescribeInstance,
	ActionGetBillOfMaterialsImportJob,
	ActionGetDataIntegrationEvent,
	ActionGetDataIntegrationFlow,
	ActionGetDataIntegrationFlowExecution,
	ActionGetDataLakeDataset,
	ActionGetDataLakeNamespace,
	ActionGetInstance,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionAssignAdminPermissionsToUser,
	ActionCreateBillOfMaterialsImportJob,
	ActionCreateDataIntegrationFlow,
	ActionCreateDataLakeDataset,
	ActionCreateDataLakeNamespace,
	ActionCreateInstance,
	ActionCreateSSOApplication,
	ActionDeleteDataIntegrationFlow,
	ActionDeleteDataLakeDataset,
	ActionDeleteDataLakeNamespace,
	ActionDeleteInstance,
	ActionDeleteSSOApplication,
	ActionRemoveAdminPermissionsForUser,
	ActionSendDataIntegrationEvent,
	ActionUpdateDataIntegrationFlow,
	ActionUpdateDataLakeDataset,
	ActionUpdateDataLakeNamespace,
	ActionUpdateInstance,
}

// ActionsTagging are the tagging actions, as classified by aws.
var ActionsTagging = []string{
	ActionTagResource,
	ActionUntagResource,
}
