// Code generated by go generate; DO NOT EDIT.

// Package pipes holds the cloud control resources of the aws pipes service.
package pipes

import "encoding/json"

type PipeEnrichmentHttpParameters struct {
	HeaderParameters      map[string]string `json:"HeaderParameters,omitempty"`
	PathParameterValues   []string          `json:"PathParameterValues,omitempty"`
	QueryStringParameters map[string]string `json:"QueryStringParameters,omitempty"`
}

type PipeEnrichmentParameters struct {
	HttpParameters *PipeEnrichmentHttpParameters `json:"HttpParameters,omitempty"`
	InputTemplate  *string                       `json:"InputTemplate,omitempty"`
}

type CloudwatchLogsLogDestination struct {
	LogGroupArn *string `json:"LogGroupArn,omitempty"`
}

type FirehoseLogDestination struct {
	DeliveryStreamArn *string `json:"DeliveryStreamArn,omitempty"`
}

type S3LogDestination struct {
	BucketName   *string `json:"BucketName,omitempty"`
	BucketOwner  *string `json:"BucketOwner,omitempty"`
	OutputFormat *string `json:"OutputFormat,omitempty"`
	Prefix       *string `json:"Prefix,omitempty"`
}

type PipeLogConfiguration struct {
	CloudwatchLogsLogDestination *CloudwatchLogsLogDestination `json:"CloudwatchLogsLogDestination,omitempty"`
	FirehoseLogDestination       *FirehoseLogDestination       `json:"FirehoseLogDestination,omitempty"`
	IncludeExecutionData         []string                      `json:"IncludeExecutionData,omitempty"`
	Level                        *string                       `json:"Level,omitempty"`
	S3LogDestination             *S3LogDestination             `json:"S3LogDestination,omitempty"`
}

type PipeSourceActiveMQBrokerParameters struct {
	BatchSize                      *int            `json:"BatchSize,omitempty"`
	Credentials                    json.RawMessage `json:"Credentials,omitempty"`
	MaximumBatchingWindowInSeconds *int            `json:"MaximumBatchingWindowInSeconds,omitempty"`
	QueueName                      *string         `json:"QueueName,omitempty"`
}

type DeadLetterConfig struct {
	Arn *string `json:"Arn,omitempty"`
}

type PipeSourceDynamoDBStreamParameters struct {
	BatchSize                      *int              `json:"BatchSize,omitempty"`
	DeadLetterConfig               *DeadLetterConfig `json:"DeadLetterConfig,omitempty"`
	MaximumBatchingWindowInSeconds *int              `json:"MaximumBatchingWindowInSeconds,omitempty"`
	MaximumRecordAgeInSeconds      *int              `json:"MaximumRecordAgeInSeconds,omitempty"`
	MaximumRetryAttempts           *int              `json:"MaximumRetryAttempts,omitempty"`
	OnPartialBatchItemFailure      *string           `json:"OnPartialBatchItemFailure,omitempty"`
	ParallelizationFactor          *int              `json:"ParallelizationFactor,omitempty"`
	StartingPosition               *string           `json:"StartingPosition,omitempty"`
}

type Filter struct {
	Pattern *string `json:"Pattern,omitempty"`
}

type FilterCriteria struct {
	Filters []Filter `json:"Filters,omitempty"`
}

type PipeSourceKinesisStreamParameters struct {
	BatchSize                      *int              `json:"BatchSize,omitempty"`
	DeadLetterConfig               *DeadLetterConfig `json:"DeadLetterConfig,omitempty"`
	MaximumBatchingWindowInSeconds *int              `json:"MaximumBatchingWindowInSeconds,omitempty"`
	MaximumRecordAgeInSeconds      *int              `json:"MaximumRecordAgeInSeconds,omitempty"`
	MaximumRetryAttempts           *int              `json:"MaximumRetryAttempts,omitempty"`
	OnPartialBatchItemFailure      *string           `json:"OnPartialBatchItemFailure,omitempty"`
	ParallelizationFactor          *int              `json:"ParallelizationFactor,omitempty"`
	StartingPosition               *string           `json:"StartingPosition,omitempty"`
	StartingPositionTimestamp      *string           `json:"StartingPositionTimestamp,omitempty"`
}

type PipeSourceManagedStreamingKafkaParameters struct {
	BatchSize                      *int            `json:"BatchSize,omitempty"`
	ConsumerGroupID                *string         `json:"ConsumerGroupID,omitempty"`
	Credentials                    json.RawMessage `json:"Credentials,omitempty"`
	MaximumBatchingWindowInSeconds *int            `json:"MaximumBatchingWindowInSeconds,omitempty"`
	StartingPosition               *string         `json:"StartingPosition,omitempty"`
	TopicName                      *string         `json:"TopicName,omitempty"`
}

type PipeSourceRabbitMQBrokerParameters struct {
	BatchSize                      *int            `json:"BatchSize,omitempty"`
	Credentials                    json.RawMessage `json:"Credentials,omitempty"`
	MaximumBatchingWindowInSeconds *int            `json:"MaximumBatchingWindowInSeconds,omitempty"`
	QueueName                      *string         `json:"QueueName,omitempty"`
	VirtualHost                    *string         `json:"VirtualHost,omitempty"`
}

type SelfManagedKafkaAccessConfigurationVpc struct {
	SecurityGroup []string `json:"SecurityGroup,omitempty"`
	Subnets       []string `json:"Subnets,omitempty"`
}

type PipeSourceSelfManagedKafkaParameters struct {
	AdditionalBootstrapServers     []string                                `json:"AdditionalBootstrapServers,omitempty"`
	BatchSize                      *int                                    `json:"BatchSize,omitempty"`
	ConsumerGroupID                *string                                 `json:"ConsumerGroupID,omitempty"`
	Credentials                    json.RawMessage                         `json:"Credentials,omitempty"`
	MaximumBatchingWindowInSeconds *int                                    `json:"MaximumBatchingWindowInSeconds,omitempty"`
	ServerRootCaCertificate        *string                                 `json:"ServerRootCaCertificate,omitempty"`
	StartingPosition               *string                                 `json:"StartingPosition,omitempty"`
	TopicName                      *string                                 `json:"TopicName,omitempty"`
	Vpc                            *SelfManagedKafkaAccessConfigurationVpc `json:"Vpc,omitempty"`
}

type PipeSourceSqsQueueParameters struct {
	BatchSize                      *int `json:"BatchSize,omitempty"`
	MaximumBatchingWindowInSeconds *int `json:"MaximumBatchingWindowInSeconds,omitempty"`
}

type PipeSourceParameters struct {
	ActiveMQBrokerParameters        *PipeSourceActiveMQBrokerParameters        `json:"ActiveMQBrokerParameters,omitempty"`
	DynamoDBStreamParameters        *PipeSourceDynamoDBStreamParameters        `json:"DynamoDBStreamParameters,omitempty"`
	FilterCriteria                  *FilterCriteria                            `json:"FilterCriteria,omitempty"`
	KinesisStreamParameters         *PipeSourceKinesisStreamParameters         `json:"KinesisStreamParameters,omitempty"`
	ManagedStreamingKafkaParameters *PipeSourceManagedStreamingKafkaParameters `json:"ManagedStreamingKafkaParameters,omitempty"`
	RabbitMQBrokerParameters        *PipeSourceRabbitMQBrokerParameters        `json:"RabbitMQBrokerParameters,omitempty"`
	SelfManagedKafkaParameters      *PipeSourceSelfManagedKafkaParameters      `json:"SelfManagedKafkaParameters,omitempty"`
	SqsQueueParameters              *PipeSourceSqsQueueParameters              `json:"SqsQueueParameters,omitempty"`
}

type BatchArrayProperties struct {
	Size *int `json:"Size,omitempty"`
}

type BatchEnvironmentVariable struct {
	Name  *string `json:"Name,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type BatchResourceRequirement struct {
	Type  *string `json:"Type,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type BatchContainerOverrides struct {
	Command              []string                   `json:"Command,omitempty"`
	Environment          []BatchEnvironmentVariable `json:"Environment,omitempty"`
	InstanceType         *string                    `json:"InstanceType,omitempty"`
	ResourceRequirements []BatchResourceRequirement `json:"ResourceRequirements,omitempty"`
}

type BatchJobDependency struct {
	JobId *string `json:"JobId,omitempty"`
	Type  *string `json:"Type,omitempty"`
}

type BatchRetryStrategy struct {
	Attempts *int `json:"Attempts,omitempty"`
}

type PipeTargetBatchJobParameters struct {
	ArrayProperties    *BatchArrayProperties    `json:"ArrayProperties,omitempty"`
	ContainerOverrides *BatchContainerOverrides `json:"ContainerOverrides,omitempty"`
	DependsOn          []BatchJobDependency     `json:"DependsOn,omitempty"`
	JobDefinition      *string                  `json:"JobDefinition,omitempty"`
	JobName            *string                  `json:"JobName,omitempty"`
	Parameters         map[string]string        `json:"Parameters,omitempty"`
	RetryStrategy      *BatchRetryStrategy      `json:"RetryStrategy,omitempty"`
}

type PipeTargetCloudWatchLogsParameters struct {
	LogStreamName *string `json:"LogStreamName,omitempty"`
	Timestamp     *string `json:"Timestamp,omitempty"`
}

type CapacityProviderStrategyItem struct {
	Base             *int    `json:"Base,omitempty"`
	CapacityProvider *string `json:"CapacityProvider,omitempty"`
	Weight           *int    `json:"Weight,omitempty"`
}

type AwsVpcConfiguration struct {
	AssignPublicIp *string  `json:"AssignPublicIp,omitempty"`
	SecurityGroups []string `json:"SecurityGroups,omitempty"`
	Subnets        []string `json:"Subnets,omitempty"`
}

type NetworkConfiguration struct {
	AwsvpcConfiguration *AwsVpcConfiguration `json:"AwsvpcConfiguration,omitempty"`
}

type EcsEnvironmentVariable struct {
	Name  *string `json:"Name,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type EcsEnvironmentFile struct {
	Type  *string `json:"Type,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type EcsResourceRequirement struct {
	Type  *string `json:"Type,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type EcsContainerOverride struct {
	Command              []string                 `json:"Command,omitempty"`
	Cpu                  *int                     `json:"Cpu,omitempty"`
	Environment          []EcsEnvironmentVariable `json:"Environment,omitempty"`
	EnvironmentFiles     []EcsEnvironmentFile     `json:"EnvironmentFiles,omitempty"`
	Memory               *int                     `json:"Memory,omitempty"`
	MemoryReservation    *int                     `json:"MemoryReservation,omitempty"`
	Name                 *string                  `json:"Name,omitempty"`
	ResourceRequirements []EcsResourceRequirement `json:"ResourceRequirements,omitempty"`
}

type EcsEphemeralStorage struct {
	SizeInGiB *int `json:"SizeInGiB,omitempty"`
}

type EcsInferenceAcceleratorOverride struct {
	DeviceName *string `json:"DeviceName,omitempty"`
	DeviceType *string `json:"DeviceType,omitempty"`
}

type EcsTaskOverride struct {
	ContainerOverrides            []EcsContainerOverride            `json:"ContainerOverrides,omitempty"`
	Cpu                           *string                           `json:"Cpu,omitempty"`
	EphemeralStorage              *EcsEphemeralStorage              `json:"EphemeralStorage,omitempty"`
	ExecutionRoleArn              *string                           `json:"ExecutionRoleArn,omitempty"`
	InferenceAcceleratorOverrides []EcsInferenceAcceleratorOverride `json:"InferenceAcceleratorOverrides,omitempty"`
	Memory                        *string                           `json:"Memory,omitempty"`
	TaskRoleArn                   *string                           `json:"TaskRoleArn,omitempty"`
}

type PlacementConstraint struct {
	Expression *string `json:"Expression,omitempty"`
	Type       *string `json:"Type,omitempty"`
}

type PlacementStrategy struct {
	Field *string `json:"Field,omitempty"`
	Type  *string `json:"Type,omitempty"`
}

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type PipeTargetEcsTaskParameters struct {
	CapacityProviderStrategy []CapacityProviderStrategyItem `json:"CapacityProviderStrategy,omitempty"`
	EnableECSManagedTags     *bool                          `json:"EnableECSManagedTags,omitempty"`
	EnableExecuteCommand     *bool                          `json:"EnableExecuteCommand,omitempty"`
	Group                    *string                        `json:"Group,omitempty"`
	LaunchType               *string                        `json:"LaunchType,omitempty"`
	NetworkConfiguration     *NetworkConfiguration          `json:"NetworkConfiguration,omitempty"`
	Overrides                *EcsTaskOverride               `json:"Overrides,omitempty"`
	PlacementConstraints     []PlacementConstraint          `json:"PlacementConstraints,omitempty"`
	PlacementStrategy        []PlacementStrategy            `json:"PlacementStrategy,omitempty"`
	PlatformVersion          *string                        `json:"PlatformVersion,omitempty"`
	PropagateTags            *string                        `json:"PropagateTags,omitempty"`
	ReferenceId              *string                        `json:"ReferenceId,omitempty"`
	Tags                     []Tag                          `json:"Tags,omitempty"`
	TaskCount                *int                           `json:"TaskCount,omitempty"`
	TaskDefinitionArn        *string                        `json:"TaskDefinitionArn,omitempty"`
}

type PipeTargetEventBridgeEventBusParameters struct {
	DetailType *string  `json:"DetailType,omitempty"`
	EndpointId *string  `json:"EndpointId,omitempty"`
	Resources  []string `json:"Resources,omitempty"`
	Source     *string  `json:"Source,omitempty"`
	Time       *string  `json:"Time,omitempty"`
}

type PipeTargetHttpParameters struct {
	HeaderParameters      map[string]string `json:"HeaderParameters,omitempty"`
	PathParameterValues   []string          `json:"PathParameterValues,omitempty"`
	QueryStringParameters map[string]string `json:"QueryStringParameters,omitempty"`
}

type PipeTargetKinesisStreamParameters struct {
	PartitionKey *string `json:"PartitionKey,omitempty"`
}

type PipeTargetLambdaFunctionParameters struct {
	InvocationType *string `json:"InvocationType,omitempty"`
}

type PipeTargetRedshiftDataParameters struct {
	Database         *string  `json:"Database,omitempty"`
	DbUser           *string  `json:"DbUser,omitempty"`
	SecretManagerArn *string  `json:"SecretManagerArn,omitempty"`
	Sqls             []string `json:"Sqls,omitempty"`
	StatementName    *string  `json:"StatementName,omitempty"`
	WithEvent        *bool    `json:"WithEvent,omitempty"`
}

type SageMakerPipelineParameter struct {
	Name  *string `json:"Name,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type PipeTargetSageMakerPipelineParameters struct {
	PipelineParameterList []SageMakerPipelineParameter `json:"PipelineParameterList,omitempty"`
}

type PipeTargetSqsQueueParameters struct {
	MessageDeduplicationId *string `json:"MessageDeduplicationId,omitempty"`
	MessageGroupId         *string `json:"MessageGroupId,omitempty"`
}

type PipeTargetStateMachineParameters struct {
	InvocationType *string `json:"InvocationType,omitempty"`
}

type DimensionMapping struct {
	DimensionName      *string `json:"DimensionName,omitempty"`
	DimensionValue     *string `json:"DimensionValue,omitempty"`
	DimensionValueType *string `json:"DimensionValueType,omitempty"`
}

type MultiMeasureAttributeMapping struct {
	MeasureValue              *string `json:"MeasureValue,omitempty"`
	MeasureValueType          *string `json:"MeasureValueType,omitempty"`
	MultiMeasureAttributeName *string `json:"MultiMeasureAttributeName,omitempty"`
}

type MultiMeasureMapping struct {
	MultiMeasureAttributeMappings []MultiMeasureAttributeMapping `json:"MultiMeasureAttributeMappings,omitempty"`
	MultiMeasureName              *string                        `json:"MultiMeasureName,omitempty"`
}

type SingleMeasureMapping struct {
	MeasureName      *string `json:"MeasureName,omitempty"`
	MeasureValue     *string `json:"MeasureValue,omitempty"`
	MeasureValueType *string `json:"MeasureValueType,omitempty"`
}

type PipeTargetTimestreamParameters struct {
	DimensionMappings     []DimensionMapping     `json:"DimensionMappings,omitempty"`
	EpochTimeUnit         *string                `json:"EpochTimeUnit,omitempty"`
	MultiMeasureMappings  []MultiMeasureMapping  `json:"MultiMeasureMappings,omitempty"`
	SingleMeasureMappings []SingleMeasureMapping `json:"SingleMeasureMappings,omitempty"`
	TimeFieldType         *string                `json:"TimeFieldType,omitempty"`
	TimeValue             *string                `json:"TimeValue,omitempty"`
	TimestampFormat       *string                `json:"TimestampFormat,omitempty"`
	VersionValue          *string                `json:"VersionValue,omitempty"`
}

type PipeTargetParameters struct {
	BatchJobParameters                 *PipeTargetBatchJobParameters            `json:"BatchJobParameters,omitempty"`
	CloudWatchLogsParameters           *PipeTargetCloudWatchLogsParameters      `json:"CloudWatchLogsParameters,omitempty"`
	EcsTaskParameters                  *PipeTargetEcsTaskParameters             `json:"EcsTaskParameters,omitempty"`
	EventBridgeEventBusParameters      *PipeTargetEventBridgeEventBusParameters `json:"EventBridgeEventBusParameters,omitempty"`
	HttpParameters                     *PipeTargetHttpParameters                `json:"HttpParameters,omitempty"`
	InputTemplate                      *string                                  `json:"InputTemplate,omitempty"`
	KinesisStreamParameters            *PipeTargetKinesisStreamParameters       `json:"KinesisStreamParameters,omitempty"`
	LambdaFunctionParameters           *PipeTargetLambdaFunctionParameters      `json:"LambdaFunctionParameters,omitempty"`
	RedshiftDataParameters             *PipeTargetRedshiftDataParameters        `json:"RedshiftDataParameters,omitempty"`
	SageMakerPipelineParameters        *PipeTargetSageMakerPipelineParameters   `json:"SageMakerPipelineParameters,omitempty"`
	SqsQueueParameters                 *PipeTargetSqsQueueParameters            `json:"SqsQueueParameters,omitempty"`
	StepFunctionStateMachineParameters *PipeTargetStateMachineParameters        `json:"StepFunctionStateMachineParameters,omitempty"`
	TimestreamParameters               *PipeTargetTimestreamParameters          `json:"TimestreamParameters,omitempty"`
}

type Pipe struct {
	Arn                  *string                   `json:"Arn,omitempty"`
	CreationTime         *string                   `json:"CreationTime,omitempty"`
	CurrentState         *string                   `json:"CurrentState,omitempty"`
	Description          *string                   `json:"Description,omitempty"`
	DesiredState         *string                   `json:"DesiredState,omitempty"`
	Enrichment           *string                   `json:"Enrichment,omitempty"`
	EnrichmentParameters *PipeEnrichmentParameters `json:"EnrichmentParameters,omitempty"`
	KmsKeyIdentifier     *string                   `json:"KmsKeyIdentifier,omitempty"`
	LastModifiedTime     *string                   `json:"LastModifiedTime,omitempty"`
	LogConfiguration     *PipeLogConfiguration     `json:"LogConfiguration,omitempty"`
	Name                 *string                   `json:"Name,omitempty"`
	RoleArn              *string                   `json:"RoleArn,omitempty"`
	Source               *string                   `json:"Source,omitempty"`
	SourceParameters     *PipeSourceParameters     `json:"SourceParameters,omitempty"`
	StateReason          *string                   `json:"StateReason,omitempty"`
	Tags                 map[string]string         `json:"Tags,omitempty"`
	Target               *string                   `json:"Target,omitempty"`
	TargetParameters     *PipeTargetParameters     `json:"TargetParameters,omitempty"`
}

func (Pipe) CloudControlType() string { return "AWS::Pipes::Pipe" }
