// Code generated by go generate; DO NOT EDIT.

// Package ivs holds the cloud control resources of the aws ivs service.
package ivs

type MultitrackInputConfiguration struct {
	Enabled           *bool   `json:"Enabled,omitempty"`
	MaximumResolution *string `json:"MaximumResolution,omitempty"`
	Policy            *string `json:"Policy,omitempty"`
}

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Channel struct {
	Arn                          *string                       `json:"Arn,omitempty"`
	Authorized                   *bool                         `json:"Authorized,omitempty"`
	ContainerFormat              *string                       `json:"ContainerFormat,omitempty"`
	IngestEndpoint               *string                       `json:"IngestEndpoint,omitempty"`
	InsecureIngest               *bool                         `json:"InsecureIngest,omitempty"`
	LatencyMode                  *string                       `json:"LatencyMode,omitempty"`
	MultitrackInputConfiguration *MultitrackInputConfiguration `json:"MultitrackInputConfiguration,omitempty"`
	Name                         *string                       `json:"Name,omitempty"`
	PlaybackUrl                  *string                       `json:"PlaybackUrl,omitempty"`
	Preset                       *string                       `json:"Preset,omitempty"`
	RecordingConfigurationArn    *string                       `json:"RecordingConfigurationArn,omitempty"`
	Tags                         []Tag                         `json:"Tags,omitempty"`
	Type                         *string                       `json:"Type,omitempty"`
}

func (Channel) CloudControlType() string { return "AWS::IVS::Channel" }

type EncoderConfigurationTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type EncoderConfigurationVideo struct {
	Bitrate   *int     `json:"Bitrate,omitempty"`
	Framerate *float64 `json:"Framerate,omitempty"`
	Height    *int     `json:"Height,omitempty"`
	Width     *int     `json:"Width,omitempty"`
}

type EncoderConfiguration struct {
	Arn   *string                    `json:"Arn,omitempty"`
	Name  *string                    `json:"Name,omitempty"`
	Tags  []EncoderConfigurationTag  `json:"Tags,omitempty"`
	Video *EncoderConfigurationVideo `json:"Video,omitempty"`
}

func (EncoderConfiguration) CloudControlType() string { return "AWS::IVS::EncoderConfiguration" }

type IngestConfigurationTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type IngestConfiguration struct {
	Arn            *string                  `json:"Arn,omitempty"`
	IngestProtocol *string                  `json:"IngestProtocol,omitempty"`
	InsecureIngest *bool                    `json:"InsecureIngest,omitempty"`
	Name           *string                  `json:"Name,omitempty"`
	ParticipantId  *string                  `json:"ParticipantId,omitempty"`
	StageArn       *string                  `json:"StageArn,omitempty"`
	State          *string                  `json:"State,omitempty"`
	StreamKey      *string                  `json:"StreamKey,omitempty"`
	Tags           []IngestConfigurationTag `json:"Tags,omitempty"`
	UserId         *string                  `json:"UserId,omitempty"`
}

func (IngestConfiguration) CloudControlType() string { return "AWS::IVS::IngestConfiguration" }

type PlaybackKeyPairTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type PlaybackKeyPair struct {
	Arn               *string              `json:"Arn,omitempty"`
	Fingerprint       *string              `json:"Fingerprint,omitempty"`
	Name              *string              `json:"Name,omitempty"`
	PublicKeyMaterial *string              `json:"PublicKeyMaterial,omitempty"`
	Tags              []PlaybackKeyPairTag `json:"Tags,omitempty"`
}

func (PlaybackKeyPair) CloudControlType() string { return "AWS::IVS::PlaybackKeyPair" }

type PlaybackRestrictionPolicyTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type PlaybackRestrictionPolicy struct {
	AllowedCountries              []string                       `json:"AllowedCountries,omitempty"`
	AllowedOrigins                []string                       `json:"AllowedOrigins,omitempty"`
	Arn                           *string                        `json:"Arn,omitempty"`
	EnableStrictOriginEnforcement *bool                          `json:"EnableStrictOriginEnforcement,omitempty"`
	Name                          *string                        `json:"Name,omitempty"`
	Tags                          []PlaybackRestrictionPolicyTag `json:"Tags,omitempty"`
}

func (PlaybackRestrictionPolicy) CloudControlType() string {
	return "AWS::IVS::PlaybackRestrictionPolicy"
}

type PublicKeyTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type PublicKey struct {
	Arn               *string        `json:"Arn,omitempty"`
	Fingerprint       *string        `json:"Fingerprint,omitempty"`
	Name              *string        `json:"Name,omitempty"`
	PublicKeyMaterial *string        `json:"PublicKeyMaterial,omitempty"`
	Tags              []PublicKeyTag `json:"Tags,omitempty"`
}

func (PublicKey) CloudControlType() string { return "AWS::IVS::PublicKey" }

type S3DestinationConfiguration struct {
	BucketName *string `json:"BucketName,omitempty"`
}

type DestinationConfiguration struct {
	S3 *S3DestinationConfiguration `json:"S3,omitempty"`
}

type RenditionConfiguration struct {
	RenditionSelection *string  `json:"RenditionSelection,omitempty"`
	Renditions         []string `json:"Renditions,omitempty"`
}

type RecordingConfigurationTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type ThumbnailConfiguration struct {
	RecordingMode         *string  `json:"RecordingMode,omitempty"`
	Resolution            *string  `json:"Resolution,omitempty"`
	Storage               []string `json:"Storage,omitempty"`
	TargetIntervalSeconds *int     `json:"TargetIntervalSeconds,omitempty"`
}

type RecordingConfiguration struct {
	Arn                             *string                     `json:"Arn,omitempty"`
	DestinationConfiguration        *DestinationConfiguration   `json:"DestinationConfiguration,omitempty"`
	Name                            *string                     `json:"Name,omitempty"`
	RecordingReconnectWindowSeconds *int                        `json:"RecordingReconnectWindowSeconds,omitempty"`
	RenditionConfiguration          *RenditionConfiguration     `json:"RenditionConfiguration,omitempty"`
	State                           *string                     `json:"State,omitempty"`
	Tags                            []RecordingConfigurationTag `json:"Tags,omitempty"`
	ThumbnailConfiguration          *ThumbnailConfiguration     `json:"ThumbnailConfiguration,omitempty"`
}

func (RecordingConfiguration) CloudControlType() string { return "AWS::IVS::RecordingConfiguration" }

type ParticipantRecordingHlsConfiguration struct {
	TargetSegmentDurationSeconds *int `json:"TargetSegmentDurationSeconds,omitempty"`
}

type HlsConfiguration struct {
	ParticipantRecordingHlsConfiguration *ParticipantRecordingHlsConfiguration `json:"ParticipantRecordingHlsConfiguration,omitempty"`
}

type StageThumbnailConfigurationParticipantThumbnailConfiguration struct {
	RecordingMode         *string  `json:"RecordingMode,omitempty"`
	Storage               []string `json:"Storage,omitempty"`
	TargetIntervalSeconds *int     `json:"TargetIntervalSeconds,omitempty"`
}

type StageThumbnailConfiguration struct {
	ParticipantThumbnailConfiguration *StageThumbnailConfigurationParticipantThumbnailConfiguration `json:"ParticipantThumbnailConfiguration,omitempty"`
}

type AutoParticipantRecordingConfiguration struct {
	HlsConfiguration                *HlsConfiguration            `json:"HlsConfiguration,omitempty"`
	MediaTypes                      []string                     `json:"MediaTypes,omitempty"`
	RecordingReconnectWindowSeconds *int                         `json:"RecordingReconnectWindowSeconds,omitempty"`
	StorageConfigurationArn         *string                      `json:"StorageConfigurationArn,omitempty"`
	ThumbnailConfiguration          *StageThumbnailConfiguration `json:"ThumbnailConfiguration,omitempty"`
}

type StageTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Stage struct {
	ActiveSessionId                       *string                                `json:"ActiveSessionId,omitempty"`
	Arn                                   *string                                `json:"Arn,omitempty"`
	AutoParticipantRecordingConfiguration *AutoParticipantRecordingConfiguration `json:"AutoParticipantRecordingConfiguration,omitempty"`
	Name                                  *string                                `json:"Name,omitempty"`
	Tags                                  []StageTag                             `json:"Tags,omitempty"`
}

func (Stage) CloudControlType() string { return "AWS::IVS::Stage" }

type S3StorageConfiguration struct {
	BucketName *string `json:"BucketName,omitempty"`
}

type StorageConfigurationTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type StorageConfiguration struct {
	Arn  *string                   `json:"Arn,omitempty"`
	Name *string                   `json:"Name,omitempty"`
	S3   *S3StorageConfiguration   `json:"S3,omitempty"`
	Tags []StorageConfigurationTag `json:"Tags,omitempty"`
}

func (StorageConfiguration) CloudControlType() string { return "AWS::IVS::StorageConfiguration" }

type StreamKeyTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type StreamKey struct {
	Arn        *string        `json:"Arn,omitempty"`
	ChannelArn *string        `json:"ChannelArn,omitempty"`
	Tags       []StreamKeyTag `json:"Tags,omitempty"`
	Value      *string        `json:"Value,omitempty"`
}

func (StreamKey) CloudControlType() string { return "AWS::IVS::StreamKey" }
