syntax = "proto3";

package v1.admin.system;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

option go_package = "codeberg.org/megakuul/cloudjam/pkg/api/v1/admin/system";

message Log {
  google.protobuf.Timestamp timestamp = 1;
  string level = 2;
  string message = 3;
  map<string, string> labels = 4;
}

message ScanLogsRequest {
  google.protobuf.Timestamp from = 1;
  google.protobuf.Timestamp to = 2;
  string level = 3;
  int32 limit = 4 [(buf.validate.field).int32 = {
    gt: 0
    lte: 100
  }];
}

message ScanLogsResponse {
  repeated Log logs = 1;
}

message RequestWindow {
  google.protobuf.Timestamp start = 1;
  int64 count = 2;
  int64 latency = 3;
}

// what a cursed name xD
message AggregateRequestsRequest {
  google.protobuf.Timestamp from = 1;
  google.protobuf.Timestamp to = 2;
  string endpoint = 3;
}

message AggregateRequestsResponse {
  repeated RequestWindow request_windows = 1;
}

service SystemService {
  rpc ScanLogs(ScanLogsRequest) returns (ScanLogsResponse);
  rpc AggregateRequests(AggregateRequestsRequest) returns (AggregateRequestsResponse);
}
