syntax = "proto3";

package v1.admin.system;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

option go_package = "codeberg.org/megakuul/cloudjam/pkg/api/v1/admin/system";

message Log {
  google.protobuf.Timestamp timestamp = 1;
  string level = 2;
  string message = 3;
  string system = 4;
  string service = 5;
}

message ScanLogsRequest {
  google.protobuf.Timestamp from = 1;
  google.protobuf.Timestamp to = 2;
  string system = 3;
  string service = 4;
  int32 limit = 5 [(buf.validate.field).int32 = {
    gt: 0
    lte: 100
  }];
}

message ScanLogsResponse {
  repeated Log logs = 1;
}

message Request {
  google.protobuf.Timestamp timestamp = 1;
  int64 latency = 2;
  string endpoint = 3;
  string source = 4;
}

message ScanRequestsRequest {
  google.protobuf.Timestamp from = 1;
  google.protobuf.Timestamp to = 2;
  string endpoint = 3;
  int32 limit = 4 [(buf.validate.field).int32 = {
    gt: 0
    lte: 100
  }];
}

message ScanRequestsResponse {
  repeated Request requests = 1;
}

enum AggregateWindow {
  Minute = 0;
  Hour = 1;
  Day = 2;
  Month = 3;
}

message EndpointLatency {
  string endpoint = 1;
  repeated google.protobuf.Timestamp time = 2;
  repeated int64 latency = 3;
}

message AggregateLatencyRequest {
  AggregateWindow window = 1;
  google.protobuf.Timestamp from = 2;
  google.protobuf.Timestamp to = 3;
}

message AggregateLatencyResponse {
  map<string, EndpointLatency> endpoints = 1;
}

message EndpointHits {
  string endpoint = 1;
  repeated google.protobuf.Timestamp time = 2;
  repeated int64 count = 3;
}

message AggregateHitsRequest {
  AggregateWindow window = 1;
  google.protobuf.Timestamp from = 2;
  google.protobuf.Timestamp to = 3;
}

message AggregateHitsResponse {
  map<string, EndpointHits> endpoints = 1;
}

service SystemService {
  rpc ScanLogs(ScanLogsRequest) returns (ScanLogsResponse);
  rpc ScanRequests(ScanRequestsRequest) returns (ScanRequestsResponse);
  rpc AggregateLatency(AggregateLatencyRequest) returns (AggregateLatencyResponse);
  rpc AggregateHits(AggregateHitsRequest) returns (AggregateHitsResponse);
}
