// Code generated by go generate; DO NOT EDIT.

// Package synthetics holds the cloud control resources of the aws synthetics service.
package synthetics

type S3Encryption struct {
	EncryptionMode *string `json:"EncryptionMode,omitempty"`
	KmsKeyArn      *string `json:"KmsKeyArn,omitempty"`
}

type ArtifactConfig struct {
	S3Encryption *S3Encryption `json:"S3Encryption,omitempty"`
}

type BrowserConfig struct {
	BrowserType *BrowserType `json:"BrowserType,omitempty"`
}

type Dependency struct {
	Reference *string         `json:"Reference,omitempty"`
	Type      *DependencyType `json:"Type,omitempty"`
}

type Code struct {
	BlueprintTypes    []string     `json:"BlueprintTypes,omitempty"`
	Dependencies      []Dependency `json:"Dependencies,omitempty"`
	Handler           *string      `json:"Handler,omitempty"`
	S3Bucket          *string      `json:"S3Bucket,omitempty"`
	S3Key             *string      `json:"S3Key,omitempty"`
	S3ObjectVersion   *string      `json:"S3ObjectVersion,omitempty"`
	Script            *string      `json:"Script,omitempty"`
	SourceLocationArn *string      `json:"SourceLocationArn,omitempty"`
}

type ReplicaReplicationStatus struct {
	State *string `json:"State,omitempty"`
}

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type VPCConfig struct {
	Ipv6AllowedForDualStack *bool    `json:"Ipv6AllowedForDualStack,omitempty"`
	SecurityGroupIds        []string `json:"SecurityGroupIds,omitempty"`
	SubnetIds               []string `json:"SubnetIds,omitempty"`
	VpcId                   *string  `json:"VpcId,omitempty"`
}

type Replica struct {
	CanaryState              *string                   `json:"CanaryState,omitempty"`
	KmsKeyArn                *string                   `json:"KmsKeyArn,omitempty"`
	LastModified             *float64                  `json:"LastModified,omitempty"`
	Location                 *string                   `json:"Location,omitempty"`
	ReplicationStatus        *ReplicaReplicationStatus `json:"ReplicationStatus,omitempty"`
	ResourcesToReplicateTags []ResourceToTag           `json:"ResourcesToReplicateTags,omitempty"`
	Tags                     []Tag                     `json:"Tags,omitempty"`
	VpcConfig                *VPCConfig                `json:"VpcConfig,omitempty"`
}

type RunConfig struct {
	ActiveTracing        *bool             `json:"ActiveTracing,omitempty"`
	EnvironmentVariables map[string]string `json:"EnvironmentVariables,omitempty"`
	EphemeralStorage     *int              `json:"EphemeralStorage,omitempty"`
	MemoryInMB           *int              `json:"MemoryInMB,omitempty"`
	TimeoutInSeconds     *int              `json:"TimeoutInSeconds,omitempty"`
}

type RetryConfig struct {
	MaxRetries *int `json:"MaxRetries,omitempty"`
}

type Schedule struct {
	DurationInSeconds *string      `json:"DurationInSeconds,omitempty"`
	Expression        *string      `json:"Expression,omitempty"`
	RetryConfig       *RetryConfig `json:"RetryConfig,omitempty"`
}

type BaseScreenshot struct {
	IgnoreCoordinates []string `json:"IgnoreCoordinates,omitempty"`
	ScreenshotName    *string  `json:"ScreenshotName,omitempty"`
}

type VisualReference struct {
	BaseCanaryRunId *string          `json:"BaseCanaryRunId,omitempty"`
	BaseScreenshots []BaseScreenshot `json:"BaseScreenshots,omitempty"`
	BrowserType     *BrowserType     `json:"BrowserType,omitempty"`
}

type Canary struct {
	ArtifactConfig                        *ArtifactConfig                   `json:"ArtifactConfig,omitempty"`
	ArtifactS3Location                    *string                           `json:"ArtifactS3Location,omitempty"`
	BrowserConfigs                        []BrowserConfig                   `json:"BrowserConfigs,omitempty"`
	Code                                  *Code                             `json:"Code,omitempty"`
	DeleteLambdaResourcesOnCanaryDeletion *bool                             `json:"DeleteLambdaResourcesOnCanaryDeletion,omitempty"`
	DryRunAndUpdate                       *bool                             `json:"DryRunAndUpdate,omitempty"`
	ExecutionRoleArn                      *string                           `json:"ExecutionRoleArn,omitempty"`
	FailureRetentionPeriod                *int                              `json:"FailureRetentionPeriod,omitempty"`
	Id                                    *string                           `json:"Id,omitempty"`
	KmsKeyArn                             *string                           `json:"KmsKeyArn,omitempty"`
	Name                                  *string                           `json:"Name,omitempty"`
	ProvisionedResourceCleanup            *CanaryProvisionedResourceCleanup `json:"ProvisionedResourceCleanup,omitempty"`
	Replicas                              []Replica                         `json:"Replicas,omitempty"`
	ResourcesToReplicateTags              []ResourceToTag                   `json:"ResourcesToReplicateTags,omitempty"`
	RunConfig                             *RunConfig                        `json:"RunConfig,omitempty"`
	RuntimeVersion                        *string                           `json:"RuntimeVersion,omitempty"`
	Schedule                              *Schedule                         `json:"Schedule,omitempty"`
	StartCanaryAfterCreation              *bool                             `json:"StartCanaryAfterCreation,omitempty"`
	State                                 *string                           `json:"State,omitempty"`
	SuccessRetentionPeriod                *int                              `json:"SuccessRetentionPeriod,omitempty"`
	Tags                                  []Tag                             `json:"Tags,omitempty"`
	VPCConfig                             *VPCConfig                        `json:"VPCConfig,omitempty"`
	VisualReference                       *VisualReference                  `json:"VisualReference,omitempty"`
	VisualReferences                      []VisualReference                 `json:"VisualReferences,omitempty"`
}

func (Canary) CloudJamType() string { return "AWS::Synthetics::Canary" }

type GroupTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Group struct {
	Id           *string    `json:"Id,omitempty"`
	Name         *string    `json:"Name,omitempty"`
	ResourceArns []string   `json:"ResourceArns,omitempty"`
	Tags         []GroupTag `json:"Tags,omitempty"`
}

func (Group) CloudJamType() string { return "AWS::Synthetics::Group" }

type BrowserType string

const (
	BrowserTypeCHROME  BrowserType = "CHROME"
	BrowserTypeFIREFOX BrowserType = "FIREFOX"
)

type DependencyType string

const (
	DependencyTypeLambdaLayer DependencyType = "LambdaLayer"
)

type CanaryProvisionedResourceCleanup string

const (
	CanaryProvisionedResourceCleanupAUTOMATIC CanaryProvisionedResourceCleanup = "AUTOMATIC"
	CanaryProvisionedResourceCleanupOFF       CanaryProvisionedResourceCleanup = "OFF"
)

type ResourceToTag string

const (
	ResourceToTagLambdaFunction ResourceToTag = "lambda-function"
)
