// Code generated by go generate; DO NOT EDIT.

// Package ses holds the cloud control resources of the aws ses service.
package ses

import "encoding/json"

type ArchivingOptions struct {
	ArchiveArn *string `json:"ArchiveArn,omitempty"`
}

type DeliveryOptions struct {
	MaxDeliverySeconds *float64 `json:"MaxDeliverySeconds,omitempty"`
	SendingPoolName    *string  `json:"SendingPoolName,omitempty"`
	TlsPolicy          *string  `json:"TlsPolicy,omitempty"`
}

type ReputationOptions struct {
	ReputationMetricsEnabled *bool `json:"ReputationMetricsEnabled,omitempty"`
}

type SendingOptions struct {
	SendingEnabled *bool `json:"SendingEnabled,omitempty"`
}

type SuppressionOptionsValidationOptionsConditionThresholdOverallConfidenceThreshold struct {
	ConfidenceVerdictThreshold *string `json:"ConfidenceVerdictThreshold,omitempty"`
}

type SuppressionOptionsValidationOptionsConditionThreshold struct {
	ConditionThresholdEnabled  *string                                                                          `json:"ConditionThresholdEnabled,omitempty"`
	OverallConfidenceThreshold *SuppressionOptionsValidationOptionsConditionThresholdOverallConfidenceThreshold `json:"OverallConfidenceThreshold,omitempty"`
}

type SuppressionOptionsValidationOptions struct {
	ConditionThreshold *SuppressionOptionsValidationOptionsConditionThreshold `json:"ConditionThreshold,omitempty"`
}

type SuppressionOptions struct {
	SuppressedReasons []string                             `json:"SuppressedReasons,omitempty"`
	ValidationOptions *SuppressionOptionsValidationOptions `json:"ValidationOptions,omitempty"`
}

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type TrackingOptions struct {
	CustomRedirectDomain *string `json:"CustomRedirectDomain,omitempty"`
	HttpsPolicy          *string `json:"HttpsPolicy,omitempty"`
}

type DashboardOptions struct {
	EngagementMetrics *string `json:"EngagementMetrics,omitempty"`
}

type GuardianOptions struct {
	OptimizedSharedDelivery *string `json:"OptimizedSharedDelivery,omitempty"`
}

type VdmOptions struct {
	DashboardOptions *DashboardOptions `json:"DashboardOptions,omitempty"`
	GuardianOptions  *GuardianOptions  `json:"GuardianOptions,omitempty"`
}

type ConfigurationSet struct {
	ArchivingOptions   *ArchivingOptions   `json:"ArchivingOptions,omitempty"`
	DeliveryOptions    *DeliveryOptions    `json:"DeliveryOptions,omitempty"`
	Name               *string             `json:"Name,omitempty"`
	ReputationOptions  *ReputationOptions  `json:"ReputationOptions,omitempty"`
	SendingOptions     *SendingOptions     `json:"SendingOptions,omitempty"`
	SuppressionOptions *SuppressionOptions `json:"SuppressionOptions,omitempty"`
	Tags               []Tag               `json:"Tags,omitempty"`
	TrackingOptions    *TrackingOptions    `json:"TrackingOptions,omitempty"`
	VdmOptions         *VdmOptions         `json:"VdmOptions,omitempty"`
}

func (ConfigurationSet) CloudControlType() string { return "AWS::SES::ConfigurationSet" }

type DimensionConfiguration struct {
	DefaultDimensionValue *string `json:"DefaultDimensionValue,omitempty"`
	DimensionName         *string `json:"DimensionName,omitempty"`
	DimensionValueSource  *string `json:"DimensionValueSource,omitempty"`
}

type CloudWatchDestination struct {
	DimensionConfigurations []DimensionConfiguration `json:"DimensionConfigurations,omitempty"`
}

type EventBridgeDestination struct {
	EventBusArn *string `json:"EventBusArn,omitempty"`
}

type KinesisFirehoseDestination struct {
	DeliveryStreamARN *string `json:"DeliveryStreamARN,omitempty"`
	IAMRoleARN        *string `json:"IAMRoleARN,omitempty"`
}

type SnsDestination struct {
	TopicARN *string `json:"TopicARN,omitempty"`
}

type EventDestination struct {
	CloudWatchDestination      *CloudWatchDestination      `json:"CloudWatchDestination,omitempty"`
	Enabled                    *bool                       `json:"Enabled,omitempty"`
	EventBridgeDestination     *EventBridgeDestination     `json:"EventBridgeDestination,omitempty"`
	KinesisFirehoseDestination *KinesisFirehoseDestination `json:"KinesisFirehoseDestination,omitempty"`
	MatchingEventTypes         []string                    `json:"MatchingEventTypes,omitempty"`
	Name                       *string                     `json:"Name,omitempty"`
	SnsDestination             *SnsDestination             `json:"SnsDestination,omitempty"`
}

type ConfigurationSetEventDestination struct {
	ConfigurationSetName *string           `json:"ConfigurationSetName,omitempty"`
	EventDestination     *EventDestination `json:"EventDestination,omitempty"`
	Id                   *string           `json:"Id,omitempty"`
}

func (ConfigurationSetEventDestination) CloudControlType() string {
	return "AWS::SES::ConfigurationSetEventDestination"
}

type ContactListTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Topic struct {
	DefaultSubscriptionStatus *string `json:"DefaultSubscriptionStatus,omitempty"`
	Description               *string `json:"Description,omitempty"`
	DisplayName               *string `json:"DisplayName,omitempty"`
	TopicName                 *string `json:"TopicName,omitempty"`
}

type ContactList struct {
	ContactListName *string          `json:"ContactListName,omitempty"`
	Description     *string          `json:"Description,omitempty"`
	Tags            []ContactListTag `json:"Tags,omitempty"`
	Topics          []Topic          `json:"Topics,omitempty"`
}

func (ContactList) CloudControlType() string { return "AWS::SES::ContactList" }

type CustomVerificationEmailTemplateTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type CustomVerificationEmailTemplate struct {
	FailureRedirectionURL *string                              `json:"FailureRedirectionURL,omitempty"`
	FromEmailAddress      *string                              `json:"FromEmailAddress,omitempty"`
	SuccessRedirectionURL *string                              `json:"SuccessRedirectionURL,omitempty"`
	Tags                  []CustomVerificationEmailTemplateTag `json:"Tags,omitempty"`
	TemplateContent       *string                              `json:"TemplateContent,omitempty"`
	TemplateName          *string                              `json:"TemplateName,omitempty"`
	TemplateSubject       *string                              `json:"TemplateSubject,omitempty"`
}

func (CustomVerificationEmailTemplate) CloudControlType() string {
	return "AWS::SES::CustomVerificationEmailTemplate"
}

type DedicatedIpPoolTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type DedicatedIpPool struct {
	PoolName    *string              `json:"PoolName,omitempty"`
	ScalingMode *string              `json:"ScalingMode,omitempty"`
	Tags        []DedicatedIpPoolTag `json:"Tags,omitempty"`
}

func (DedicatedIpPool) CloudControlType() string { return "AWS::SES::DedicatedIpPool" }

type ConfigurationSetAttributes struct {
	ConfigurationSetName *string `json:"ConfigurationSetName,omitempty"`
}

type DkimAttributes struct {
	SigningEnabled *bool `json:"SigningEnabled,omitempty"`
}

type DkimSigningAttributes struct {
	DomainSigningPrivateKey *string `json:"DomainSigningPrivateKey,omitempty"`
	DomainSigningSelector   *string `json:"DomainSigningSelector,omitempty"`
	NextSigningKeyLength    *string `json:"NextSigningKeyLength,omitempty"`
}

type FeedbackAttributes struct {
	EmailForwardingEnabled *bool `json:"EmailForwardingEnabled,omitempty"`
}

type MailFromAttributes struct {
	BehaviorOnMxFailure *string `json:"BehaviorOnMxFailure,omitempty"`
	MailFromDomain      *string `json:"MailFromDomain,omitempty"`
}

type EmailIdentityTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type EmailIdentity struct {
	ConfigurationSetAttributes *ConfigurationSetAttributes `json:"ConfigurationSetAttributes,omitempty"`
	DkimAttributes             *DkimAttributes             `json:"DkimAttributes,omitempty"`
	DkimDNSTokenName1          *string                     `json:"DkimDNSTokenName1,omitempty"`
	DkimDNSTokenName2          *string                     `json:"DkimDNSTokenName2,omitempty"`
	DkimDNSTokenName3          *string                     `json:"DkimDNSTokenName3,omitempty"`
	DkimDNSTokenValue1         *string                     `json:"DkimDNSTokenValue1,omitempty"`
	DkimDNSTokenValue2         *string                     `json:"DkimDNSTokenValue2,omitempty"`
	DkimDNSTokenValue3         *string                     `json:"DkimDNSTokenValue3,omitempty"`
	DkimSigningAttributes      *DkimSigningAttributes      `json:"DkimSigningAttributes,omitempty"`
	EmailIdentity              *string                     `json:"EmailIdentity,omitempty"`
	FeedbackAttributes         *FeedbackAttributes         `json:"FeedbackAttributes,omitempty"`
	MailFromAttributes         *MailFromAttributes         `json:"MailFromAttributes,omitempty"`
	Tags                       []EmailIdentityTag          `json:"Tags,omitempty"`
}

func (EmailIdentity) CloudControlType() string { return "AWS::SES::EmailIdentity" }

type MailManagerAddonInstanceTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type MailManagerAddonInstance struct {
	AddonInstanceArn    *string                       `json:"AddonInstanceArn,omitempty"`
	AddonInstanceId     *string                       `json:"AddonInstanceId,omitempty"`
	AddonName           *string                       `json:"AddonName,omitempty"`
	AddonSubscriptionId *string                       `json:"AddonSubscriptionId,omitempty"`
	Tags                []MailManagerAddonInstanceTag `json:"Tags,omitempty"`
}

func (MailManagerAddonInstance) CloudControlType() string {
	return "AWS::SES::MailManagerAddonInstance"
}

type MailManagerAddonSubscriptionTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type MailManagerAddonSubscription struct {
	AddonName            *string                           `json:"AddonName,omitempty"`
	AddonSubscriptionArn *string                           `json:"AddonSubscriptionArn,omitempty"`
	AddonSubscriptionId  *string                           `json:"AddonSubscriptionId,omitempty"`
	Tags                 []MailManagerAddonSubscriptionTag `json:"Tags,omitempty"`
}

func (MailManagerAddonSubscription) CloudControlType() string {
	return "AWS::SES::MailManagerAddonSubscription"
}

type MailManagerAddressListTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type MailManagerAddressList struct {
	AddressListArn  *string                     `json:"AddressListArn,omitempty"`
	AddressListId   *string                     `json:"AddressListId,omitempty"`
	AddressListName *string                     `json:"AddressListName,omitempty"`
	Tags            []MailManagerAddressListTag `json:"Tags,omitempty"`
}

func (MailManagerAddressList) CloudControlType() string { return "AWS::SES::MailManagerAddressList" }

type MailManagerArchiveTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type MailManagerArchive struct {
	ArchiveArn   *string                 `json:"ArchiveArn,omitempty"`
	ArchiveId    *string                 `json:"ArchiveId,omitempty"`
	ArchiveName  *string                 `json:"ArchiveName,omitempty"`
	ArchiveState *string                 `json:"ArchiveState,omitempty"`
	KmsKeyArn    *string                 `json:"KmsKeyArn,omitempty"`
	Retention    json.RawMessage         `json:"Retention,omitempty"`
	Tags         []MailManagerArchiveTag `json:"Tags,omitempty"`
}

func (MailManagerArchive) CloudControlType() string { return "AWS::SES::MailManagerArchive" }

type MailManagerIngressPointTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type MailManagerIngressPoint struct {
	ARecord                   *string                      `json:"ARecord,omitempty"`
	IngressPointArn           *string                      `json:"IngressPointArn,omitempty"`
	IngressPointConfiguration json.RawMessage              `json:"IngressPointConfiguration,omitempty"`
	IngressPointId            *string                      `json:"IngressPointId,omitempty"`
	IngressPointName          *string                      `json:"IngressPointName,omitempty"`
	NetworkConfiguration      json.RawMessage              `json:"NetworkConfiguration,omitempty"`
	RuleSetId                 *string                      `json:"RuleSetId,omitempty"`
	Status                    *string                      `json:"Status,omitempty"`
	StatusToUpdate            *string                      `json:"StatusToUpdate,omitempty"`
	Tags                      []MailManagerIngressPointTag `json:"Tags,omitempty"`
	TlsPolicy                 *string                      `json:"TlsPolicy,omitempty"`
	TrafficPolicyId           *string                      `json:"TrafficPolicyId,omitempty"`
	Type                      *string                      `json:"Type,omitempty"`
}

func (MailManagerIngressPoint) CloudControlType() string { return "AWS::SES::MailManagerIngressPoint" }

type MailManagerRelayTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type MailManagerRelay struct {
	Authentication json.RawMessage       `json:"Authentication,omitempty"`
	RelayArn       *string               `json:"RelayArn,omitempty"`
	RelayId        *string               `json:"RelayId,omitempty"`
	RelayName      *string               `json:"RelayName,omitempty"`
	ServerName     *string               `json:"ServerName,omitempty"`
	ServerPort     *float64              `json:"ServerPort,omitempty"`
	Tags           []MailManagerRelayTag `json:"Tags,omitempty"`
}

func (MailManagerRelay) CloudControlType() string { return "AWS::SES::MailManagerRelay" }

type Rule struct {
	Actions    []json.RawMessage `json:"Actions,omitempty"`
	Conditions []json.RawMessage `json:"Conditions,omitempty"`
	Name       *string           `json:"Name,omitempty"`
	Unless     []json.RawMessage `json:"Unless,omitempty"`
}

type MailManagerRuleSetTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type MailManagerRuleSet struct {
	RuleSetArn  *string                 `json:"RuleSetArn,omitempty"`
	RuleSetId   *string                 `json:"RuleSetId,omitempty"`
	RuleSetName *string                 `json:"RuleSetName,omitempty"`
	Rules       []Rule                  `json:"Rules,omitempty"`
	Tags        []MailManagerRuleSetTag `json:"Tags,omitempty"`
}

func (MailManagerRuleSet) CloudControlType() string { return "AWS::SES::MailManagerRuleSet" }

type PolicyStatement struct {
	Action     *string           `json:"Action,omitempty"`
	Conditions []json.RawMessage `json:"Conditions,omitempty"`
}

type MailManagerTrafficPolicyTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type MailManagerTrafficPolicy struct {
	DefaultAction       *string                       `json:"DefaultAction,omitempty"`
	MaxMessageSizeBytes *float64                      `json:"MaxMessageSizeBytes,omitempty"`
	PolicyStatements    []PolicyStatement             `json:"PolicyStatements,omitempty"`
	Tags                []MailManagerTrafficPolicyTag `json:"Tags,omitempty"`
	TrafficPolicyArn    *string                       `json:"TrafficPolicyArn,omitempty"`
	TrafficPolicyId     *string                       `json:"TrafficPolicyId,omitempty"`
	TrafficPolicyName   *string                       `json:"TrafficPolicyName,omitempty"`
}

func (MailManagerTrafficPolicy) CloudControlType() string {
	return "AWS::SES::MailManagerTrafficPolicy"
}

type RouteDetailsItem struct {
	Region *string `json:"Region,omitempty"`
}

type Details struct {
	RouteDetails []RouteDetailsItem `json:"RouteDetails,omitempty"`
}

type MultiRegionEndpointTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type MultiRegionEndpoint struct {
	Details      *Details                 `json:"Details,omitempty"`
	EndpointName *string                  `json:"EndpointName,omitempty"`
	Tags         []MultiRegionEndpointTag `json:"Tags,omitempty"`
}

func (MultiRegionEndpoint) CloudControlType() string { return "AWS::SES::MultiRegionEndpoint" }

type IpFilter struct {
	Cidr   *string `json:"Cidr,omitempty"`
	Policy *string `json:"Policy,omitempty"`
}

type Filter struct {
	IpFilter *IpFilter `json:"IpFilter,omitempty"`
	Name     *string   `json:"Name,omitempty"`
}

type ReceiptFilter struct {
	Filter *Filter `json:"Filter,omitempty"`
	Id     *string `json:"Id,omitempty"`
}

func (ReceiptFilter) CloudControlType() string { return "AWS::SES::ReceiptFilter" }

type AddHeaderAction struct {
	HeaderName  *string `json:"HeaderName,omitempty"`
	HeaderValue *string `json:"HeaderValue,omitempty"`
}

type BounceAction struct {
	Message       *string `json:"Message,omitempty"`
	Sender        *string `json:"Sender,omitempty"`
	SmtpReplyCode *string `json:"SmtpReplyCode,omitempty"`
	StatusCode    *string `json:"StatusCode,omitempty"`
	TopicArn      *string `json:"TopicArn,omitempty"`
}

type ConnectAction struct {
	IAMRoleARN  *string `json:"IAMRoleARN,omitempty"`
	InstanceARN *string `json:"InstanceARN,omitempty"`
}

type LambdaAction struct {
	FunctionArn    *string `json:"FunctionArn,omitempty"`
	InvocationType *string `json:"InvocationType,omitempty"`
	TopicArn       *string `json:"TopicArn,omitempty"`
}

type S3Action struct {
	BucketName      *string `json:"BucketName,omitempty"`
	IamRoleArn      *string `json:"IamRoleArn,omitempty"`
	KmsKeyArn       *string `json:"KmsKeyArn,omitempty"`
	ObjectKeyPrefix *string `json:"ObjectKeyPrefix,omitempty"`
	TopicArn        *string `json:"TopicArn,omitempty"`
}

type SNSAction struct {
	Encoding *string `json:"Encoding,omitempty"`
	TopicArn *string `json:"TopicArn,omitempty"`
}

type StopAction struct {
	Scope    *string `json:"Scope,omitempty"`
	TopicArn *string `json:"TopicArn,omitempty"`
}

type WorkmailAction struct {
	OrganizationArn *string `json:"OrganizationArn,omitempty"`
	TopicArn        *string `json:"TopicArn,omitempty"`
}

type Action struct {
	AddHeaderAction *AddHeaderAction `json:"AddHeaderAction,omitempty"`
	BounceAction    *BounceAction    `json:"BounceAction,omitempty"`
	ConnectAction   *ConnectAction   `json:"ConnectAction,omitempty"`
	LambdaAction    *LambdaAction    `json:"LambdaAction,omitempty"`
	S3Action        *S3Action        `json:"S3Action,omitempty"`
	SNSAction       *SNSAction       `json:"SNSAction,omitempty"`
	StopAction      *StopAction      `json:"StopAction,omitempty"`
	WorkmailAction  *WorkmailAction  `json:"WorkmailAction,omitempty"`
}

type ReceiptRuleRule struct {
	Actions     []Action `json:"Actions,omitempty"`
	Enabled     *bool    `json:"Enabled,omitempty"`
	Name        *string  `json:"Name,omitempty"`
	Recipients  []string `json:"Recipients,omitempty"`
	ScanEnabled *bool    `json:"ScanEnabled,omitempty"`
	TlsPolicy   *string  `json:"TlsPolicy,omitempty"`
}

type ReceiptRule struct {
	After       *string          `json:"After,omitempty"`
	Id          *string          `json:"Id,omitempty"`
	Rule        *ReceiptRuleRule `json:"Rule,omitempty"`
	RuleSetName *string          `json:"RuleSetName,omitempty"`
}

func (ReceiptRule) CloudControlType() string { return "AWS::SES::ReceiptRule" }

type ReceiptRuleSet struct {
	Id          *string `json:"Id,omitempty"`
	RuleSetName *string `json:"RuleSetName,omitempty"`
}

func (ReceiptRuleSet) CloudControlType() string { return "AWS::SES::ReceiptRuleSet" }

type TemplateTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type TemplateTemplate struct {
	HtmlPart     *string `json:"HtmlPart,omitempty"`
	SubjectPart  *string `json:"SubjectPart,omitempty"`
	TemplateName *string `json:"TemplateName,omitempty"`
	TextPart     *string `json:"TextPart,omitempty"`
}

type Template struct {
	Id       *string           `json:"Id,omitempty"`
	Tags     []TemplateTag     `json:"Tags,omitempty"`
	Template *TemplateTemplate `json:"Template,omitempty"`
}

func (Template) CloudControlType() string { return "AWS::SES::Template" }

type ResourceAssociation struct {
	ResourceArn *string `json:"ResourceArn,omitempty"`
}

type TenantTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Tenant struct {
	Arn                  *string               `json:"Arn,omitempty"`
	ResourceAssociations []ResourceAssociation `json:"ResourceAssociations,omitempty"`
	Tags                 []TenantTag           `json:"Tags,omitempty"`
	TenantName           *string               `json:"TenantName,omitempty"`
}

func (Tenant) CloudControlType() string { return "AWS::SES::Tenant" }

type DashboardAttributes struct {
	EngagementMetrics *string `json:"EngagementMetrics,omitempty"`
}

type GuardianAttributes struct {
	OptimizedSharedDelivery *string `json:"OptimizedSharedDelivery,omitempty"`
}

type VdmAttributes struct {
	DashboardAttributes     *DashboardAttributes `json:"DashboardAttributes,omitempty"`
	GuardianAttributes      *GuardianAttributes  `json:"GuardianAttributes,omitempty"`
	VdmAttributesResourceId *string              `json:"VdmAttributesResourceId,omitempty"`
}

func (VdmAttributes) CloudControlType() string { return "AWS::SES::VdmAttributes" }
