// Code generated by go generate; DO NOT EDIT.

// Package bcm holds the cloud control resources of the aws bcm service.
package bcm

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type GraphDisplayConfig struct {
	VisualType *VisualType `json:"VisualType,omitempty"`
}

type DisplayConfig struct {
	Graph map[string]GraphDisplayConfig `json:"Graph,omitempty"`
	Table map[string]any                `json:"Table,omitempty"`
}

type CostCategoryValues struct {
	Key          *string       `json:"Key,omitempty"`
	MatchOptions []MatchOption `json:"MatchOptions,omitempty"`
	Values       []string      `json:"Values,omitempty"`
}

type DimensionValues struct {
	Key          *Dimension    `json:"Key,omitempty"`
	MatchOptions []MatchOption `json:"MatchOptions,omitempty"`
	Values       []string      `json:"Values,omitempty"`
}

type TagValues struct {
	Key          *string       `json:"Key,omitempty"`
	MatchOptions []MatchOption `json:"MatchOptions,omitempty"`
	Values       []string      `json:"Values,omitempty"`
}

type CostAndUsageExpression struct {
	And            []CostAndUsageExpression `json:"And,omitempty"`
	CostCategories *CostCategoryValues      `json:"CostCategories,omitempty"`
	Dimensions     *DimensionValues         `json:"Dimensions,omitempty"`
	Not            *CostAndUsageExpression  `json:"Not,omitempty"`
	Or             []CostAndUsageExpression `json:"Or,omitempty"`
	Tags           *TagValues               `json:"Tags,omitempty"`
}

type GroupDefinition struct {
	Key  *string              `json:"Key,omitempty"`
	Type *GroupDefinitionType `json:"Type,omitempty"`
}

type DateTimeValue struct {
	Type  *DateTimeType `json:"Type,omitempty"`
	Value *string       `json:"Value,omitempty"`
}

type DateTimeRange struct {
	EndTime   *DateTimeValue `json:"EndTime,omitempty"`
	StartTime *DateTimeValue `json:"StartTime,omitempty"`
}

type CostAndUsageQuery struct {
	Filter      *CostAndUsageExpression `json:"Filter,omitempty"`
	Granularity *Granularity            `json:"Granularity,omitempty"`
	GroupBy     []GroupDefinition       `json:"GroupBy,omitempty"`
	Metrics     []MetricName            `json:"Metrics,omitempty"`
	TimeRange   *DateTimeRange          `json:"TimeRange,omitempty"`
}

type Expression struct {
	And            []Expression        `json:"And,omitempty"`
	CostCategories *CostCategoryValues `json:"CostCategories,omitempty"`
	Dimensions     *DimensionValues    `json:"Dimensions,omitempty"`
	Not            *Expression         `json:"Not,omitempty"`
	Tags           *TagValues          `json:"Tags,omitempty"`
}

type ReservationCoverageQuery struct {
	Filter      *Expression       `json:"Filter,omitempty"`
	Granularity *Granularity      `json:"Granularity,omitempty"`
	GroupBy     []GroupDefinition `json:"GroupBy,omitempty"`
	Metrics     []MetricName      `json:"Metrics,omitempty"`
	TimeRange   *DateTimeRange    `json:"TimeRange,omitempty"`
}

type ReservationUtilizationQuery struct {
	Filter      *Expression       `json:"Filter,omitempty"`
	Granularity *Granularity      `json:"Granularity,omitempty"`
	GroupBy     []GroupDefinition `json:"GroupBy,omitempty"`
	TimeRange   *DateTimeRange    `json:"TimeRange,omitempty"`
}

type SavingsPlansCoverageQuery struct {
	Filter      *Expression       `json:"Filter,omitempty"`
	Granularity *Granularity      `json:"Granularity,omitempty"`
	GroupBy     []GroupDefinition `json:"GroupBy,omitempty"`
	Metrics     []MetricName      `json:"Metrics,omitempty"`
	TimeRange   *DateTimeRange    `json:"TimeRange,omitempty"`
}

type SavingsPlansUtilizationQuery struct {
	Filter      *Expression    `json:"Filter,omitempty"`
	Granularity *Granularity   `json:"Granularity,omitempty"`
	TimeRange   *DateTimeRange `json:"TimeRange,omitempty"`
}

type QueryParameters struct {
	CostAndUsage            *CostAndUsageQuery            `json:"CostAndUsage,omitempty"`
	ReservationCoverage     *ReservationCoverageQuery     `json:"ReservationCoverage,omitempty"`
	ReservationUtilization  *ReservationUtilizationQuery  `json:"ReservationUtilization,omitempty"`
	SavingsPlansCoverage    *SavingsPlansCoverageQuery    `json:"SavingsPlansCoverage,omitempty"`
	SavingsPlansUtilization *SavingsPlansUtilizationQuery `json:"SavingsPlansUtilization,omitempty"`
}

type WidgetConfig struct {
	DisplayConfig   *DisplayConfig   `json:"DisplayConfig,omitempty"`
	QueryParameters *QueryParameters `json:"QueryParameters,omitempty"`
}

type Widget struct {
	Configs          []WidgetConfig `json:"Configs,omitempty"`
	Description      *string        `json:"Description,omitempty"`
	Height           *int           `json:"Height,omitempty"`
	HorizontalOffset *int           `json:"HorizontalOffset,omitempty"`
	Title            *string        `json:"Title,omitempty"`
	Width            *int           `json:"Width,omitempty"`
}

type Dashboard struct {
	Arn         *string        `json:"Arn,omitempty"`
	CreatedAt   *string        `json:"CreatedAt,omitempty"`
	Description *string        `json:"Description,omitempty"`
	Name        *string        `json:"Name,omitempty"`
	Tags        []Tag          `json:"Tags,omitempty"`
	Type        *DashboardType `json:"Type,omitempty"`
	UpdatedAt   *string        `json:"UpdatedAt,omitempty"`
	Widgets     []Widget       `json:"Widgets,omitempty"`
}

func (Dashboard) CloudControlType() string { return "AWS::BCM::Dashboard" }

type DashboardType string

const (
	DashboardTypeCUSTOM DashboardType = "CUSTOM"
)

type VisualType string

const (
	VisualTypeLINE  VisualType = "LINE"
	VisualTypeBAR   VisualType = "BAR"
	VisualTypeSTACK VisualType = "STACK"
)

type MatchOption string

const (
	MatchOptionEQUALS             MatchOption = "EQUALS"
	MatchOptionABSENT             MatchOption = "ABSENT"
	MatchOptionSTARTSWITH         MatchOption = "STARTS_WITH"
	MatchOptionENDSWITH           MatchOption = "ENDS_WITH"
	MatchOptionCONTAINS           MatchOption = "CONTAINS"
	MatchOptionGREATERTHANOREQUAL MatchOption = "GREATER_THAN_OR_EQUAL"
	MatchOptionCASESENSITIVE      MatchOption = "CASE_SENSITIVE"
	MatchOptionCASEINSENSITIVE    MatchOption = "CASE_INSENSITIVE"
)

type Dimension string

const (
	DimensionAZ                 Dimension = "AZ"
	DimensionINSTANCETYPE       Dimension = "INSTANCE_TYPE"
	DimensionLINKEDACCOUNT      Dimension = "LINKED_ACCOUNT"
	DimensionOPERATION          Dimension = "OPERATION"
	DimensionPURCHASETYPE       Dimension = "PURCHASE_TYPE"
	DimensionREGION             Dimension = "REGION"
	DimensionSERVICE            Dimension = "SERVICE"
	DimensionUSAGETYPE          Dimension = "USAGE_TYPE"
	DimensionUSAGETYPEGROUP     Dimension = "USAGE_TYPE_GROUP"
	DimensionRECORDTYPE         Dimension = "RECORD_TYPE"
	DimensionOPERATINGSYSTEM    Dimension = "OPERATING_SYSTEM"
	DimensionTENANCY            Dimension = "TENANCY"
	DimensionSCOPE              Dimension = "SCOPE"
	DimensionPLATFORM           Dimension = "PLATFORM"
	DimensionSUBSCRIPTIONID     Dimension = "SUBSCRIPTION_ID"
	DimensionLEGALENTITYNAME    Dimension = "LEGAL_ENTITY_NAME"
	DimensionDEPLOYMENTOPTION   Dimension = "DEPLOYMENT_OPTION"
	DimensionDATABASEENGINE     Dimension = "DATABASE_ENGINE"
	DimensionCACHEENGINE        Dimension = "CACHE_ENGINE"
	DimensionINSTANCETYPEFAMILY Dimension = "INSTANCE_TYPE_FAMILY"
	DimensionBILLINGENTITY      Dimension = "BILLING_ENTITY"
	DimensionRESERVATIONID      Dimension = "RESERVATION_ID"
	DimensionRESOURCEID         Dimension = "RESOURCE_ID"
	DimensionSAVINGSPLANSTYPE   Dimension = "SAVINGS_PLANS_TYPE"
	DimensionTAGKEY             Dimension = "TAG_KEY"
	DimensionCOSTCATEGORYNAME   Dimension = "COST_CATEGORY_NAME"
)

type Granularity string

const (
	GranularityHOURLY  Granularity = "HOURLY"
	GranularityDAILY   Granularity = "DAILY"
	GranularityMONTHLY Granularity = "MONTHLY"
)

type GroupDefinitionType string

const (
	GroupDefinitionTypeDIMENSION    GroupDefinitionType = "DIMENSION"
	GroupDefinitionTypeTAG          GroupDefinitionType = "TAG"
	GroupDefinitionTypeCOSTCATEGORY GroupDefinitionType = "COST_CATEGORY"
)

type MetricName string

const (
	MetricNameAmortizedCost              MetricName = "AmortizedCost"
	MetricNameBlendedCost                MetricName = "BlendedCost"
	MetricNameNetAmortizedCost           MetricName = "NetAmortizedCost"
	MetricNameNetUnblendedCost           MetricName = "NetUnblendedCost"
	MetricNameNormalizedUsageAmount      MetricName = "NormalizedUsageAmount"
	MetricNameUnblendedCost              MetricName = "UnblendedCost"
	MetricNameUsageQuantity              MetricName = "UsageQuantity"
	MetricNameSpendCoveredBySavingsPlans MetricName = "SpendCoveredBySavingsPlans"
	MetricNameHour                       MetricName = "Hour"
	MetricNameUnit                       MetricName = "Unit"
	MetricNameCost                       MetricName = "Cost"
)

type DateTimeType string

const (
	DateTimeTypeABSOLUTE DateTimeType = "ABSOLUTE"
	DateTimeTypeRELATIVE DateTimeType = "RELATIVE"
)
