// Code generated by go generate; DO NOT EDIT.

// Package glue holds the cloud control resources of the aws glue service.
package glue

import "encoding/json"

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Blueprint struct {
	Arn               *string `json:"Arn,omitempty"`
	BlueprintLocation *string `json:"BlueprintLocation,omitempty"`
	CreatedOn         *string `json:"CreatedOn,omitempty"`
	Description       *string `json:"Description,omitempty"`
	LastModifiedOn    *string `json:"LastModifiedOn,omitempty"`
	Name              *string `json:"Name,omitempty"`
	ParameterSpec     *string `json:"ParameterSpec,omitempty"`
	Status            *string `json:"Status,omitempty"`
	Tags              []Tag   `json:"Tags,omitempty"`
}

func (Blueprint) CloudControlType() string { return "AWS::Glue::Blueprint" }

type DataLakeAccessProperties struct {
	AllowFullTableExternalDataAccess *string `json:"AllowFullTableExternalDataAccess,omitempty"`
	CatalogType                      *string `json:"CatalogType,omitempty"`
	DataLakeAccess                   *bool   `json:"DataLakeAccess,omitempty"`
	DataTransferRole                 *string `json:"DataTransferRole,omitempty"`
	KmsKey                           *string `json:"KmsKey,omitempty"`
	ManagedWorkgroupName             *string `json:"ManagedWorkgroupName,omitempty"`
	ManagedWorkgroupStatus           *string `json:"ManagedWorkgroupStatus,omitempty"`
	RedshiftDatabaseName             *string `json:"RedshiftDatabaseName,omitempty"`
}

type CatalogProperties struct {
	CustomProperties         map[string]string         `json:"CustomProperties,omitempty"`
	DataLakeAccessProperties *DataLakeAccessProperties `json:"DataLakeAccessProperties,omitempty"`
}

type DataLakePrincipal struct {
	DataLakePrincipalIdentifier *string `json:"DataLakePrincipalIdentifier,omitempty"`
}

type PrincipalPermissions struct {
	Permissions []string           `json:"Permissions,omitempty"`
	Principal   *DataLakePrincipal `json:"Principal,omitempty"`
}

type FederatedCatalog struct {
	ConnectionName *string `json:"ConnectionName,omitempty"`
	Identifier     *string `json:"Identifier,omitempty"`
}

type CatalogTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type TargetRedshiftCatalog struct {
	CatalogArn *string `json:"CatalogArn,omitempty"`
}

type Catalog struct {
	AllowFullTableExternalDataAccess             *string                `json:"AllowFullTableExternalDataAccess,omitempty"`
	CatalogId                                    *string                `json:"CatalogId,omitempty"`
	CatalogProperties                            *CatalogProperties     `json:"CatalogProperties,omitempty"`
	CreateDatabaseDefaultPermissions             []PrincipalPermissions `json:"CreateDatabaseDefaultPermissions,omitempty"`
	CreateTableDefaultPermissions                []PrincipalPermissions `json:"CreateTableDefaultPermissions,omitempty"`
	CreateTime                                   *int                   `json:"CreateTime,omitempty"`
	Description                                  *string                `json:"Description,omitempty"`
	FederatedCatalog                             *FederatedCatalog      `json:"FederatedCatalog,omitempty"`
	Name                                         *string                `json:"Name,omitempty"`
	OverwriteChildResourcePermissionsWithDefault *string                `json:"OverwriteChildResourcePermissionsWithDefault,omitempty"`
	Parameters                                   map[string]string      `json:"Parameters,omitempty"`
	ResourceArn                                  *string                `json:"ResourceArn,omitempty"`
	Tags                                         []CatalogTag           `json:"Tags,omitempty"`
	TargetRedshiftCatalog                        *TargetRedshiftCatalog `json:"TargetRedshiftCatalog,omitempty"`
	UpdateTime                                   *int                   `json:"UpdateTime,omitempty"`
}

func (Catalog) CloudControlType() string { return "AWS::Glue::Catalog" }

type CsvClassifier struct {
	AllowSingleColumn        *bool    `json:"AllowSingleColumn,omitempty"`
	ContainsCustomDatatype   []string `json:"ContainsCustomDatatype,omitempty"`
	ContainsHeader           *string  `json:"ContainsHeader,omitempty"`
	CustomDatatypeConfigured *bool    `json:"CustomDatatypeConfigured,omitempty"`
	Delimiter                *string  `json:"Delimiter,omitempty"`
	DisableValueTrimming     *bool    `json:"DisableValueTrimming,omitempty"`
	Header                   []string `json:"Header,omitempty"`
	Name                     *string  `json:"Name,omitempty"`
	QuoteSymbol              *string  `json:"QuoteSymbol,omitempty"`
}

type GrokClassifier struct {
	Classification *string `json:"Classification,omitempty"`
	CustomPatterns *string `json:"CustomPatterns,omitempty"`
	GrokPattern    *string `json:"GrokPattern,omitempty"`
	Name           *string `json:"Name,omitempty"`
}

type JsonClassifier struct {
	JsonPath *string `json:"JsonPath,omitempty"`
	Name     *string `json:"Name,omitempty"`
}

type XMLClassifier struct {
	Classification *string `json:"Classification,omitempty"`
	Name           *string `json:"Name,omitempty"`
	RowTag         *string `json:"RowTag,omitempty"`
}

type Classifier struct {
	CsvClassifier  *CsvClassifier  `json:"CsvClassifier,omitempty"`
	GrokClassifier *GrokClassifier `json:"GrokClassifier,omitempty"`
	Id             *string         `json:"Id,omitempty"`
	JsonClassifier *JsonClassifier `json:"JsonClassifier,omitempty"`
	XMLClassifier  *XMLClassifier  `json:"XMLClassifier,omitempty"`
}

func (Classifier) CloudControlType() string { return "AWS::Glue::Classifier" }

type BasicAuthenticationCredentials struct {
	Password *string `json:"Password,omitempty"`
	Username *string `json:"Username,omitempty"`
}

type AuthorizationCodeProperties struct {
	AuthorizationCode *string `json:"AuthorizationCode,omitempty"`
	RedirectUri       *string `json:"RedirectUri,omitempty"`
}

type OAuth2ClientApplication struct {
	AWSManagedClientApplicationReference *string `json:"AWSManagedClientApplicationReference,omitempty"`
	UserManagedClientApplicationClientId *string `json:"UserManagedClientApplicationClientId,omitempty"`
}

type OAuth2Credentials struct {
	AccessToken                              *string `json:"AccessToken,omitempty"`
	JwtToken                                 *string `json:"JwtToken,omitempty"`
	RefreshToken                             *string `json:"RefreshToken,omitempty"`
	UserManagedClientApplicationClientSecret *string `json:"UserManagedClientApplicationClientSecret,omitempty"`
}

type OAuth2PropertiesInput struct {
	AuthorizationCodeProperties *AuthorizationCodeProperties `json:"AuthorizationCodeProperties,omitempty"`
	OAuth2ClientApplication     *OAuth2ClientApplication     `json:"OAuth2ClientApplication,omitempty"`
	OAuth2Credentials           *OAuth2Credentials           `json:"OAuth2Credentials,omitempty"`
	OAuth2GrantType             *string                      `json:"OAuth2GrantType,omitempty"`
	TokenUrl                    *string                      `json:"TokenUrl,omitempty"`
	TokenUrlParametersMap       map[string]any               `json:"TokenUrlParametersMap,omitempty"`
}

type AuthenticationConfigurationInput struct {
	AuthenticationType              *string                         `json:"AuthenticationType,omitempty"`
	BasicAuthenticationCredentials  *BasicAuthenticationCredentials `json:"BasicAuthenticationCredentials,omitempty"`
	CustomAuthenticationCredentials map[string]any                  `json:"CustomAuthenticationCredentials,omitempty"`
	KmsKeyArn                       *string                         `json:"KmsKeyArn,omitempty"`
	OAuth2Properties                *OAuth2PropertiesInput          `json:"OAuth2Properties,omitempty"`
	SecretArn                       *string                         `json:"SecretArn,omitempty"`
}

type PhysicalConnectionRequirements struct {
	AvailabilityZone    *string  `json:"AvailabilityZone,omitempty"`
	SecurityGroupIdList []string `json:"SecurityGroupIdList,omitempty"`
	SubnetId            *string  `json:"SubnetId,omitempty"`
}

type ConnectionInput struct {
	AthenaProperties               map[string]any                    `json:"AthenaProperties,omitempty"`
	AuthenticationConfiguration    *AuthenticationConfigurationInput `json:"AuthenticationConfiguration,omitempty"`
	ConnectionProperties           map[string]any                    `json:"ConnectionProperties,omitempty"`
	ConnectionType                 *string                           `json:"ConnectionType,omitempty"`
	Description                    *string                           `json:"Description,omitempty"`
	MatchCriteria                  []string                          `json:"MatchCriteria,omitempty"`
	Name                           *string                           `json:"Name,omitempty"`
	PhysicalConnectionRequirements *PhysicalConnectionRequirements   `json:"PhysicalConnectionRequirements,omitempty"`
	PythonProperties               map[string]any                    `json:"PythonProperties,omitempty"`
	SparkProperties                map[string]any                    `json:"SparkProperties,omitempty"`
	ValidateCredentials            *bool                             `json:"ValidateCredentials,omitempty"`
	ValidateForComputeEnvironments []string                          `json:"ValidateForComputeEnvironments,omitempty"`
}

type Connection struct {
	CatalogId       *string          `json:"CatalogId,omitempty"`
	ConnectionInput *ConnectionInput `json:"ConnectionInput,omitempty"`
	Id              *string          `json:"Id,omitempty"`
}

func (Connection) CloudControlType() string { return "AWS::Glue::Connection" }

type LakeFormationConfiguration struct {
	AccountId                   *string `json:"AccountId,omitempty"`
	UseLakeFormationCredentials *bool   `json:"UseLakeFormationCredentials,omitempty"`
}

type RecrawlPolicy struct {
	RecrawlBehavior *string `json:"RecrawlBehavior,omitempty"`
}

type Schedule struct {
	ScheduleExpression *string `json:"ScheduleExpression,omitempty"`
}

type SchemaChangePolicy struct {
	DeleteBehavior *string `json:"DeleteBehavior,omitempty"`
	UpdateBehavior *string `json:"UpdateBehavior,omitempty"`
}

type CatalogTarget struct {
	ConnectionName   *string  `json:"ConnectionName,omitempty"`
	DatabaseName     *string  `json:"DatabaseName,omitempty"`
	DlqEventQueueArn *string  `json:"DlqEventQueueArn,omitempty"`
	EventQueueArn    *string  `json:"EventQueueArn,omitempty"`
	Tables           []string `json:"Tables,omitempty"`
}

type DeltaTarget struct {
	ConnectionName         *string  `json:"ConnectionName,omitempty"`
	CreateNativeDeltaTable *bool    `json:"CreateNativeDeltaTable,omitempty"`
	DeltaTables            []string `json:"DeltaTables,omitempty"`
	WriteManifest          *bool    `json:"WriteManifest,omitempty"`
}

type DynamoDBTarget struct {
	Path     *string  `json:"Path,omitempty"`
	ScanAll  *bool    `json:"ScanAll,omitempty"`
	ScanRate *float64 `json:"ScanRate,omitempty"`
}

type HudiTarget struct {
	ConnectionName        *string  `json:"ConnectionName,omitempty"`
	Exclusions            []string `json:"Exclusions,omitempty"`
	MaximumTraversalDepth *int     `json:"MaximumTraversalDepth,omitempty"`
	Paths                 []string `json:"Paths,omitempty"`
}

type IcebergTarget struct {
	ConnectionName        *string  `json:"ConnectionName,omitempty"`
	Exclusions            []string `json:"Exclusions,omitempty"`
	MaximumTraversalDepth *int     `json:"MaximumTraversalDepth,omitempty"`
	Paths                 []string `json:"Paths,omitempty"`
}

type JdbcTarget struct {
	ConnectionName           *string  `json:"ConnectionName,omitempty"`
	EnableAdditionalMetadata []string `json:"EnableAdditionalMetadata,omitempty"`
	Exclusions               []string `json:"Exclusions,omitempty"`
	Path                     *string  `json:"Path,omitempty"`
}

type MongoDBTarget struct {
	ConnectionName *string `json:"ConnectionName,omitempty"`
	Path           *string `json:"Path,omitempty"`
}

type S3Target struct {
	ConnectionName   *string  `json:"ConnectionName,omitempty"`
	DlqEventQueueArn *string  `json:"DlqEventQueueArn,omitempty"`
	EventQueueArn    *string  `json:"EventQueueArn,omitempty"`
	Exclusions       []string `json:"Exclusions,omitempty"`
	Path             *string  `json:"Path,omitempty"`
	SampleSize       *int     `json:"SampleSize,omitempty"`
}

type Targets struct {
	CatalogTargets  []CatalogTarget  `json:"CatalogTargets,omitempty"`
	DeltaTargets    []DeltaTarget    `json:"DeltaTargets,omitempty"`
	DynamoDBTargets []DynamoDBTarget `json:"DynamoDBTargets,omitempty"`
	HudiTargets     []HudiTarget     `json:"HudiTargets,omitempty"`
	IcebergTargets  []IcebergTarget  `json:"IcebergTargets,omitempty"`
	JdbcTargets     []JdbcTarget     `json:"JdbcTargets,omitempty"`
	MongoDBTargets  []MongoDBTarget  `json:"MongoDBTargets,omitempty"`
	S3Targets       []S3Target       `json:"S3Targets,omitempty"`
}

type Crawler struct {
	Classifiers                  []string                    `json:"Classifiers,omitempty"`
	Configuration                *string                     `json:"Configuration,omitempty"`
	CrawlerSecurityConfiguration *string                     `json:"CrawlerSecurityConfiguration,omitempty"`
	DatabaseName                 *string                     `json:"DatabaseName,omitempty"`
	Description                  *string                     `json:"Description,omitempty"`
	LakeFormationConfiguration   *LakeFormationConfiguration `json:"LakeFormationConfiguration,omitempty"`
	Name                         *string                     `json:"Name,omitempty"`
	RecrawlPolicy                *RecrawlPolicy              `json:"RecrawlPolicy,omitempty"`
	Role                         *string                     `json:"Role,omitempty"`
	Schedule                     *Schedule                   `json:"Schedule,omitempty"`
	SchemaChangePolicy           *SchemaChangePolicy         `json:"SchemaChangePolicy,omitempty"`
	TablePrefix                  *string                     `json:"TablePrefix,omitempty"`
	Tags                         map[string]any              `json:"Tags,omitempty"`
	Targets                      *Targets                    `json:"Targets,omitempty"`
}

func (Crawler) CloudControlType() string { return "AWS::Glue::Crawler" }

type CustomEntityType struct {
	ContextWords []string       `json:"ContextWords,omitempty"`
	Id           *string        `json:"Id,omitempty"`
	Name         *string        `json:"Name,omitempty"`
	RegexString  *string        `json:"RegexString,omitempty"`
	Tags         map[string]any `json:"Tags,omitempty"`
}

func (CustomEntityType) CloudControlType() string { return "AWS::Glue::CustomEntityType" }

type ConnectionPasswordEncryption struct {
	KmsKeyId                          *string `json:"KmsKeyId,omitempty"`
	ReturnConnectionPasswordEncrypted *bool   `json:"ReturnConnectionPasswordEncrypted,omitempty"`
}

type EncryptionAtRest struct {
	CatalogEncryptionMode        *string `json:"CatalogEncryptionMode,omitempty"`
	CatalogEncryptionServiceRole *string `json:"CatalogEncryptionServiceRole,omitempty"`
	SseAwsKmsKeyId               *string `json:"SseAwsKmsKeyId,omitempty"`
}

type DataCatalogEncryptionSettingsDataCatalogEncryptionSettings struct {
	ConnectionPasswordEncryption *ConnectionPasswordEncryption `json:"ConnectionPasswordEncryption,omitempty"`
	EncryptionAtRest             *EncryptionAtRest             `json:"EncryptionAtRest,omitempty"`
}

type DataCatalogEncryptionSettings struct {
	CatalogId                     *string                                                     `json:"CatalogId,omitempty"`
	DataCatalogEncryptionSettings *DataCatalogEncryptionSettingsDataCatalogEncryptionSettings `json:"DataCatalogEncryptionSettings,omitempty"`
}

func (DataCatalogEncryptionSettings) CloudControlType() string {
	return "AWS::Glue::DataCatalogEncryptionSettings"
}

type DataQualityTargetTable struct {
	DatabaseName *string `json:"DatabaseName,omitempty"`
	TableName    *string `json:"TableName,omitempty"`
}

type DataQualityRuleset struct {
	ClientToken *string                 `json:"ClientToken,omitempty"`
	Description *string                 `json:"Description,omitempty"`
	Id          *string                 `json:"Id,omitempty"`
	Name        *string                 `json:"Name,omitempty"`
	Ruleset     *string                 `json:"Ruleset,omitempty"`
	Tags        map[string]any          `json:"Tags,omitempty"`
	TargetTable *DataQualityTargetTable `json:"TargetTable,omitempty"`
}

func (DataQualityRuleset) CloudControlType() string { return "AWS::Glue::DataQualityRuleset" }

type DatabaseDataLakePrincipal struct {
	DataLakePrincipalIdentifier *string `json:"DataLakePrincipalIdentifier,omitempty"`
}

type PrincipalPrivileges struct {
	Permissions []string                   `json:"Permissions,omitempty"`
	Principal   *DatabaseDataLakePrincipal `json:"Principal,omitempty"`
}

type FederatedDatabase struct {
	ConnectionName *string `json:"ConnectionName,omitempty"`
	Identifier     *string `json:"Identifier,omitempty"`
}

type DatabaseIdentifier struct {
	CatalogId    *string `json:"CatalogId,omitempty"`
	DatabaseName *string `json:"DatabaseName,omitempty"`
	Region       *string `json:"Region,omitempty"`
}

type DatabaseInput struct {
	CreateTableDefaultPermissions []PrincipalPrivileges `json:"CreateTableDefaultPermissions,omitempty"`
	Description                   *string               `json:"Description,omitempty"`
	FederatedDatabase             *FederatedDatabase    `json:"FederatedDatabase,omitempty"`
	LocationUri                   *string               `json:"LocationUri,omitempty"`
	Name                          *string               `json:"Name,omitempty"`
	Parameters                    map[string]any        `json:"Parameters,omitempty"`
	TargetDatabase                *DatabaseIdentifier   `json:"TargetDatabase,omitempty"`
}

type Database struct {
	CatalogId     *string        `json:"CatalogId,omitempty"`
	DatabaseInput *DatabaseInput `json:"DatabaseInput,omitempty"`
	DatabaseName  *string        `json:"DatabaseName,omitempty"`
}

func (Database) CloudControlType() string { return "AWS::Glue::Database" }

type DevEndpoint struct {
	Arguments             map[string]any `json:"Arguments,omitempty"`
	EndpointName          *string        `json:"EndpointName,omitempty"`
	ExtraJarsS3Path       *string        `json:"ExtraJarsS3Path,omitempty"`
	ExtraPythonLibsS3Path *string        `json:"ExtraPythonLibsS3Path,omitempty"`
	GlueVersion           *string        `json:"GlueVersion,omitempty"`
	Id                    *string        `json:"Id,omitempty"`
	NumberOfNodes         *int           `json:"NumberOfNodes,omitempty"`
	NumberOfWorkers       *int           `json:"NumberOfWorkers,omitempty"`
	PublicKey             *string        `json:"PublicKey,omitempty"`
	PublicKeys            []string       `json:"PublicKeys,omitempty"`
	RoleArn               *string        `json:"RoleArn,omitempty"`
	SecurityConfiguration *string        `json:"SecurityConfiguration,omitempty"`
	SecurityGroupIds      []string       `json:"SecurityGroupIds,omitempty"`
	SubnetId              *string        `json:"SubnetId,omitempty"`
	Tags                  map[string]any `json:"Tags,omitempty"`
	WorkerType            *string        `json:"WorkerType,omitempty"`
}

func (DevEndpoint) CloudControlType() string { return "AWS::Glue::DevEndpoint" }

type IdentityCenterConfiguration struct {
	AccountId                     *string  `json:"AccountId,omitempty"`
	ApplicationArn                *string  `json:"ApplicationArn,omitempty"`
	InstanceArn                   *string  `json:"InstanceArn,omitempty"`
	Scopes                        []string `json:"Scopes,omitempty"`
	UserBackgroundSessionsEnabled *bool    `json:"UserBackgroundSessionsEnabled,omitempty"`
}

func (IdentityCenterConfiguration) CloudControlType() string {
	return "AWS::Glue::IdentityCenterConfiguration"
}

type IntegrationConfig struct {
	ContinuousSync   *bool             `json:"ContinuousSync,omitempty"`
	RefreshInterval  *string           `json:"RefreshInterval,omitempty"`
	SourceProperties map[string]string `json:"SourceProperties,omitempty"`
}

type IntegrationTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Integration struct {
	AdditionalEncryptionContext map[string]string  `json:"AdditionalEncryptionContext,omitempty"`
	CreateTime                  *string            `json:"CreateTime,omitempty"`
	DataFilter                  *string            `json:"DataFilter,omitempty"`
	Description                 *string            `json:"Description,omitempty"`
	IntegrationArn              *string            `json:"IntegrationArn,omitempty"`
	IntegrationConfig           *IntegrationConfig `json:"IntegrationConfig,omitempty"`
	IntegrationName             *string            `json:"IntegrationName,omitempty"`
	KmsKeyId                    *string            `json:"KmsKeyId,omitempty"`
	SourceArn                   *string            `json:"SourceArn,omitempty"`
	Status                      *string            `json:"Status,omitempty"`
	Tags                        []IntegrationTag   `json:"Tags,omitempty"`
	TargetArn                   *string            `json:"TargetArn,omitempty"`
}

func (Integration) CloudControlType() string { return "AWS::Glue::Integration" }

type IntegrationResourcePropertySourceProcessingProperties struct {
	RoleArn *string `json:"RoleArn,omitempty"`
}

type IntegrationResourcePropertyTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type IntegrationResourcePropertyTargetProcessingProperties struct {
	ConnectionName *string `json:"ConnectionName,omitempty"`
	EventBusArn    *string `json:"EventBusArn,omitempty"`
	KmsArn         *string `json:"KmsArn,omitempty"`
	RoleArn        *string `json:"RoleArn,omitempty"`
}

type IntegrationResourceProperty struct {
	ResourceArn                *string                                                `json:"ResourceArn,omitempty"`
	ResourcePropertyArn        *string                                                `json:"ResourcePropertyArn,omitempty"`
	SourceProcessingProperties *IntegrationResourcePropertySourceProcessingProperties `json:"SourceProcessingProperties,omitempty"`
	Tags                       []IntegrationResourcePropertyTag                       `json:"Tags,omitempty"`
	TargetProcessingProperties *IntegrationResourcePropertyTargetProcessingProperties `json:"TargetProcessingProperties,omitempty"`
}

func (IntegrationResourceProperty) CloudControlType() string {
	return "AWS::Glue::IntegrationResourceProperty"
}

type JobCommand struct {
	Name           *string `json:"Name,omitempty"`
	PythonVersion  *string `json:"PythonVersion,omitempty"`
	Runtime        *string `json:"Runtime,omitempty"`
	ScriptLocation *string `json:"ScriptLocation,omitempty"`
}

type ConnectionsList struct {
	Connections []string `json:"Connections,omitempty"`
}

type ExecutionProperty struct {
	MaxConcurrentRuns *float64 `json:"MaxConcurrentRuns,omitempty"`
}

type NotificationProperty struct {
	NotifyDelayAfter *int `json:"NotifyDelayAfter,omitempty"`
}

type Job struct {
	AllocatedCapacity       *float64              `json:"AllocatedCapacity,omitempty"`
	Command                 *JobCommand           `json:"Command,omitempty"`
	Connections             *ConnectionsList      `json:"Connections,omitempty"`
	DefaultArguments        map[string]any        `json:"DefaultArguments,omitempty"`
	Description             *string               `json:"Description,omitempty"`
	ExecutionClass          *string               `json:"ExecutionClass,omitempty"`
	ExecutionProperty       *ExecutionProperty    `json:"ExecutionProperty,omitempty"`
	GlueVersion             *string               `json:"GlueVersion,omitempty"`
	JobMode                 *string               `json:"JobMode,omitempty"`
	JobRunQueuingEnabled    *bool                 `json:"JobRunQueuingEnabled,omitempty"`
	LogUri                  *string               `json:"LogUri,omitempty"`
	MaintenanceWindow       *string               `json:"MaintenanceWindow,omitempty"`
	MaxCapacity             *float64              `json:"MaxCapacity,omitempty"`
	MaxRetries              *float64              `json:"MaxRetries,omitempty"`
	Name                    *string               `json:"Name,omitempty"`
	NonOverridableArguments map[string]any        `json:"NonOverridableArguments,omitempty"`
	NotificationProperty    *NotificationProperty `json:"NotificationProperty,omitempty"`
	NumberOfWorkers         *int                  `json:"NumberOfWorkers,omitempty"`
	Role                    *string               `json:"Role,omitempty"`
	SecurityConfiguration   *string               `json:"SecurityConfiguration,omitempty"`
	Tags                    map[string]any        `json:"Tags,omitempty"`
	Timeout                 *int                  `json:"Timeout,omitempty"`
	WorkerType              *string               `json:"WorkerType,omitempty"`
}

func (Job) CloudControlType() string { return "AWS::Glue::Job" }

type GlueTables struct {
	CatalogId      *string `json:"CatalogId,omitempty"`
	ConnectionName *string `json:"ConnectionName,omitempty"`
	DatabaseName   *string `json:"DatabaseName,omitempty"`
	TableName      *string `json:"TableName,omitempty"`
}

type InputRecordTables struct {
	GlueTables []GlueTables `json:"GlueTables,omitempty"`
}

type MLUserDataEncryption struct {
	KmsKeyId                 *string `json:"KmsKeyId,omitempty"`
	MLUserDataEncryptionMode *string `json:"MLUserDataEncryptionMode,omitempty"`
}

type TransformEncryption struct {
	MLUserDataEncryption             *MLUserDataEncryption `json:"MLUserDataEncryption,omitempty"`
	TaskRunSecurityConfigurationName *string               `json:"TaskRunSecurityConfigurationName,omitempty"`
}

type FindMatchesParameters struct {
	AccuracyCostTradeoff    *float64 `json:"AccuracyCostTradeoff,omitempty"`
	EnforceProvidedLabels   *bool    `json:"EnforceProvidedLabels,omitempty"`
	PrecisionRecallTradeoff *float64 `json:"PrecisionRecallTradeoff,omitempty"`
	PrimaryKeyColumnName    *string  `json:"PrimaryKeyColumnName,omitempty"`
}

type TransformParameters struct {
	FindMatchesParameters *FindMatchesParameters `json:"FindMatchesParameters,omitempty"`
	TransformType         *string                `json:"TransformType,omitempty"`
}

type MLTransform struct {
	Description         *string              `json:"Description,omitempty"`
	GlueVersion         *string              `json:"GlueVersion,omitempty"`
	Id                  *string              `json:"Id,omitempty"`
	InputRecordTables   *InputRecordTables   `json:"InputRecordTables,omitempty"`
	MaxCapacity         *float64             `json:"MaxCapacity,omitempty"`
	MaxRetries          *int                 `json:"MaxRetries,omitempty"`
	Name                *string              `json:"Name,omitempty"`
	NumberOfWorkers     *int                 `json:"NumberOfWorkers,omitempty"`
	Role                *string              `json:"Role,omitempty"`
	Tags                map[string]any       `json:"Tags,omitempty"`
	Timeout             *int                 `json:"Timeout,omitempty"`
	TransformEncryption *TransformEncryption `json:"TransformEncryption,omitempty"`
	TransformParameters *TransformParameters `json:"TransformParameters,omitempty"`
	WorkerType          *string              `json:"WorkerType,omitempty"`
}

func (MLTransform) CloudControlType() string { return "AWS::Glue::MLTransform" }

type Column struct {
	Comment *string `json:"Comment,omitempty"`
	Name    *string `json:"Name,omitempty"`
	Type    *string `json:"Type,omitempty"`
}

type SchemaId struct {
	RegistryName *string `json:"RegistryName,omitempty"`
	SchemaArn    *string `json:"SchemaArn,omitempty"`
	SchemaName   *string `json:"SchemaName,omitempty"`
}

type SchemaReference struct {
	SchemaId            *SchemaId `json:"SchemaId,omitempty"`
	SchemaVersionId     *string   `json:"SchemaVersionId,omitempty"`
	SchemaVersionNumber *int      `json:"SchemaVersionNumber,omitempty"`
}

type SerdeInfo struct {
	Name                 *string        `json:"Name,omitempty"`
	Parameters           map[string]any `json:"Parameters,omitempty"`
	SerializationLibrary *string        `json:"SerializationLibrary,omitempty"`
}

type SkewedInfo struct {
	SkewedColumnNames             []string       `json:"SkewedColumnNames,omitempty"`
	SkewedColumnValueLocationMaps map[string]any `json:"SkewedColumnValueLocationMaps,omitempty"`
	SkewedColumnValues            []string       `json:"SkewedColumnValues,omitempty"`
}

type Order struct {
	Column    *string `json:"Column,omitempty"`
	SortOrder *int    `json:"SortOrder,omitempty"`
}

type StorageDescriptor struct {
	BucketColumns          []string         `json:"BucketColumns,omitempty"`
	Columns                []Column         `json:"Columns,omitempty"`
	Compressed             *bool            `json:"Compressed,omitempty"`
	InputFormat            *string          `json:"InputFormat,omitempty"`
	Location               *string          `json:"Location,omitempty"`
	NumberOfBuckets        *int             `json:"NumberOfBuckets,omitempty"`
	OutputFormat           *string          `json:"OutputFormat,omitempty"`
	Parameters             map[string]any   `json:"Parameters,omitempty"`
	SchemaReference        *SchemaReference `json:"SchemaReference,omitempty"`
	SerdeInfo              *SerdeInfo       `json:"SerdeInfo,omitempty"`
	SkewedInfo             *SkewedInfo      `json:"SkewedInfo,omitempty"`
	SortColumns            []Order          `json:"SortColumns,omitempty"`
	StoredAsSubDirectories *bool            `json:"StoredAsSubDirectories,omitempty"`
}

type PartitionInput struct {
	Parameters        map[string]any     `json:"Parameters,omitempty"`
	StorageDescriptor *StorageDescriptor `json:"StorageDescriptor,omitempty"`
	Values            []string           `json:"Values,omitempty"`
}

type Partition struct {
	CatalogId      *string         `json:"CatalogId,omitempty"`
	DatabaseName   *string         `json:"DatabaseName,omitempty"`
	Id             *string         `json:"Id,omitempty"`
	PartitionInput *PartitionInput `json:"PartitionInput,omitempty"`
	TableName      *string         `json:"TableName,omitempty"`
}

func (Partition) CloudControlType() string { return "AWS::Glue::Partition" }

type RegistryTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Registry struct {
	Arn         *string       `json:"Arn,omitempty"`
	Description *string       `json:"Description,omitempty"`
	Name        *string       `json:"Name,omitempty"`
	Tags        []RegistryTag `json:"Tags,omitempty"`
}

func (Registry) CloudControlType() string { return "AWS::Glue::Registry" }

type SchemaVersion struct {
	IsLatest      *bool `json:"IsLatest,omitempty"`
	VersionNumber *int  `json:"VersionNumber,omitempty"`
}

type SchemaRegistry struct {
	Arn  *string `json:"Arn,omitempty"`
	Name *string `json:"Name,omitempty"`
}

type SchemaTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Schema struct {
	Arn                    *string         `json:"Arn,omitempty"`
	CheckpointVersion      *SchemaVersion  `json:"CheckpointVersion,omitempty"`
	Compatibility          *string         `json:"Compatibility,omitempty"`
	DataFormat             *string         `json:"DataFormat,omitempty"`
	Description            *string         `json:"Description,omitempty"`
	InitialSchemaVersionId *string         `json:"InitialSchemaVersionId,omitempty"`
	Name                   *string         `json:"Name,omitempty"`
	Registry               *SchemaRegistry `json:"Registry,omitempty"`
	SchemaDefinition       *string         `json:"SchemaDefinition,omitempty"`
	Tags                   []SchemaTag     `json:"Tags,omitempty"`
}

func (Schema) CloudControlType() string { return "AWS::Glue::Schema" }

type SchemaVersionSchema struct {
	RegistryName *string `json:"RegistryName,omitempty"`
	SchemaArn    *string `json:"SchemaArn,omitempty"`
	SchemaName   *string `json:"SchemaName,omitempty"`
}

type SchemaVersionSchemaVersion struct {
	Schema           *SchemaVersionSchema `json:"Schema,omitempty"`
	SchemaDefinition *string              `json:"SchemaDefinition,omitempty"`
	VersionId        *string              `json:"VersionId,omitempty"`
}

func (SchemaVersionSchemaVersion) CloudControlType() string { return "AWS::Glue::SchemaVersion" }

type SchemaVersionMetadata struct {
	Key             *string `json:"Key,omitempty"`
	SchemaVersionId *string `json:"SchemaVersionId,omitempty"`
	Value           *string `json:"Value,omitempty"`
}

func (SchemaVersionMetadata) CloudControlType() string { return "AWS::Glue::SchemaVersionMetadata" }

type CloudWatchEncryption struct {
	CloudWatchEncryptionMode *string `json:"CloudWatchEncryptionMode,omitempty"`
	KmsKeyArn                *string `json:"KmsKeyArn,omitempty"`
}

type JobBookmarksEncryption struct {
	JobBookmarksEncryptionMode *string `json:"JobBookmarksEncryptionMode,omitempty"`
	KmsKeyArn                  *string `json:"KmsKeyArn,omitempty"`
}

type S3Encryption struct {
	KmsKeyArn        *string `json:"KmsKeyArn,omitempty"`
	S3EncryptionMode *string `json:"S3EncryptionMode,omitempty"`
}

type EncryptionConfiguration struct {
	CloudWatchEncryption   *CloudWatchEncryption   `json:"CloudWatchEncryption,omitempty"`
	JobBookmarksEncryption *JobBookmarksEncryption `json:"JobBookmarksEncryption,omitempty"`
	S3Encryptions          []S3Encryption          `json:"S3Encryptions,omitempty"`
}

type SecurityConfiguration struct {
	EncryptionConfiguration *EncryptionConfiguration `json:"EncryptionConfiguration,omitempty"`
	Id                      *string                  `json:"Id,omitempty"`
	Name                    *string                  `json:"Name,omitempty"`
}

func (SecurityConfiguration) CloudControlType() string { return "AWS::Glue::SecurityConfiguration" }

type IcebergPartitionField struct {
	FieldId   *int    `json:"FieldId,omitempty"`
	Name      *string `json:"Name,omitempty"`
	SourceId  *int    `json:"SourceId,omitempty"`
	Transform *string `json:"Transform,omitempty"`
}

type IcebergPartitionSpec struct {
	Fields []IcebergPartitionField `json:"Fields,omitempty"`
	SpecId *int                    `json:"SpecId,omitempty"`
}

type IcebergStructField struct {
	Doc      *string `json:"Doc,omitempty"`
	Id       *int    `json:"Id,omitempty"`
	Name     *string `json:"Name,omitempty"`
	Required *bool   `json:"Required,omitempty"`
	Type     *string `json:"Type,omitempty"`
}

type IcebergSchema struct {
	Fields             []IcebergStructField `json:"Fields,omitempty"`
	IdentifierFieldIds []int                `json:"IdentifierFieldIds,omitempty"`
	SchemaId           *int                 `json:"SchemaId,omitempty"`
	Type               *string              `json:"Type,omitempty"`
}

type IcebergSortField struct {
	Direction *string `json:"Direction,omitempty"`
	NullOrder *string `json:"NullOrder,omitempty"`
	SourceId  *int    `json:"SourceId,omitempty"`
	Transform *string `json:"Transform,omitempty"`
}

type IcebergSortOrder struct {
	Fields  []IcebergSortField `json:"Fields,omitempty"`
	OrderId *int               `json:"OrderId,omitempty"`
}

type IcebergTableInput struct {
	Location      *string               `json:"Location,omitempty"`
	PartitionSpec *IcebergPartitionSpec `json:"PartitionSpec,omitempty"`
	Properties    map[string]any        `json:"Properties,omitempty"`
	Schema        *IcebergSchema        `json:"Schema,omitempty"`
	WriteOrder    *IcebergSortOrder     `json:"WriteOrder,omitempty"`
}

type IcebergInput struct {
	IcebergTableInput *IcebergTableInput `json:"IcebergTableInput,omitempty"`
	MetadataOperation map[string]any     `json:"MetadataOperation,omitempty"`
	Version           *string            `json:"Version,omitempty"`
}

type OpenTableFormatInput struct {
	IcebergInput *IcebergInput `json:"IcebergInput,omitempty"`
}

type TableColumn struct {
	Comment *string `json:"Comment,omitempty"`
	Name    *string `json:"Name,omitempty"`
	Type    *string `json:"Type,omitempty"`
}

type TableSchemaId struct {
	RegistryName *string `json:"RegistryName,omitempty"`
	SchemaArn    *string `json:"SchemaArn,omitempty"`
	SchemaName   *string `json:"SchemaName,omitempty"`
}

type TableSchemaReference struct {
	SchemaId            *TableSchemaId `json:"SchemaId,omitempty"`
	SchemaVersionId     *string        `json:"SchemaVersionId,omitempty"`
	SchemaVersionNumber *int           `json:"SchemaVersionNumber,omitempty"`
}

type TableSerdeInfo struct {
	Name                 *string        `json:"Name,omitempty"`
	Parameters           map[string]any `json:"Parameters,omitempty"`
	SerializationLibrary *string        `json:"SerializationLibrary,omitempty"`
}

type TableSkewedInfo struct {
	SkewedColumnNames             []string       `json:"SkewedColumnNames,omitempty"`
	SkewedColumnValueLocationMaps map[string]any `json:"SkewedColumnValueLocationMaps,omitempty"`
	SkewedColumnValues            []string       `json:"SkewedColumnValues,omitempty"`
}

type TableOrder struct {
	Column    *string `json:"Column,omitempty"`
	SortOrder *int    `json:"SortOrder,omitempty"`
}

type TableStorageDescriptor struct {
	BucketColumns          []string              `json:"BucketColumns,omitempty"`
	Columns                []TableColumn         `json:"Columns,omitempty"`
	Compressed             *bool                 `json:"Compressed,omitempty"`
	InputFormat            *string               `json:"InputFormat,omitempty"`
	Location               *string               `json:"Location,omitempty"`
	NumberOfBuckets        *int                  `json:"NumberOfBuckets,omitempty"`
	OutputFormat           *string               `json:"OutputFormat,omitempty"`
	Parameters             map[string]any        `json:"Parameters,omitempty"`
	SchemaReference        *TableSchemaReference `json:"SchemaReference,omitempty"`
	SerdeInfo              *TableSerdeInfo       `json:"SerdeInfo,omitempty"`
	SkewedInfo             *TableSkewedInfo      `json:"SkewedInfo,omitempty"`
	SortColumns            []TableOrder          `json:"SortColumns,omitempty"`
	StoredAsSubDirectories *bool                 `json:"StoredAsSubDirectories,omitempty"`
}

type TableIdentifier struct {
	CatalogId    *string `json:"CatalogId,omitempty"`
	DatabaseName *string `json:"DatabaseName,omitempty"`
	Name         *string `json:"Name,omitempty"`
	Region       *string `json:"Region,omitempty"`
}

type ViewRepresentation struct {
	Dialect              *string `json:"Dialect,omitempty"`
	DialectVersion       *string `json:"DialectVersion,omitempty"`
	ValidationConnection *string `json:"ValidationConnection,omitempty"`
	ViewExpandedText     *string `json:"ViewExpandedText,omitempty"`
	ViewOriginalText     *string `json:"ViewOriginalText,omitempty"`
}

type ViewDefinition struct {
	Definer         *string              `json:"Definer,omitempty"`
	IsProtected     *bool                `json:"IsProtected,omitempty"`
	Representations []ViewRepresentation `json:"Representations,omitempty"`
	SubObjects      []string             `json:"SubObjects,omitempty"`
}

type TableInput struct {
	Description       *string                 `json:"Description,omitempty"`
	Name              *string                 `json:"Name,omitempty"`
	Owner             *string                 `json:"Owner,omitempty"`
	Parameters        map[string]any          `json:"Parameters,omitempty"`
	PartitionKeys     []TableColumn           `json:"PartitionKeys,omitempty"`
	Retention         *int                    `json:"Retention,omitempty"`
	StorageDescriptor *TableStorageDescriptor `json:"StorageDescriptor,omitempty"`
	TableType         *string                 `json:"TableType,omitempty"`
	TargetTable       *TableIdentifier        `json:"TargetTable,omitempty"`
	ViewDefinition    *ViewDefinition         `json:"ViewDefinition,omitempty"`
	ViewExpandedText  *string                 `json:"ViewExpandedText,omitempty"`
	ViewOriginalText  *string                 `json:"ViewOriginalText,omitempty"`
}

type Table struct {
	CatalogId            *string               `json:"CatalogId,omitempty"`
	DatabaseName         *string               `json:"DatabaseName,omitempty"`
	Id                   *string               `json:"Id,omitempty"`
	Name                 *string               `json:"Name,omitempty"`
	OpenTableFormatInput *OpenTableFormatInput `json:"OpenTableFormatInput,omitempty"`
	TableInput           *TableInput           `json:"TableInput,omitempty"`
}

func (Table) CloudControlType() string { return "AWS::Glue::Table" }

type IcebergCompactionConfiguration struct {
	DeleteFileThreshold *int    `json:"DeleteFileThreshold,omitempty"`
	MinInputFiles       *int    `json:"MinInputFiles,omitempty"`
	Strategy            *string `json:"Strategy,omitempty"`
}

type CompactionConfiguration struct {
	IcebergConfiguration *IcebergCompactionConfiguration `json:"IcebergConfiguration,omitempty"`
}

type IcebergConfiguration struct {
	Location                        *string `json:"Location,omitempty"`
	OrphanFileRetentionPeriodInDays *int    `json:"OrphanFileRetentionPeriodInDays,omitempty"`
}

type OrphanFileDeletionConfiguration struct {
	IcebergConfiguration *IcebergConfiguration `json:"IcebergConfiguration,omitempty"`
}

type IcebergRetentionConfiguration struct {
	CleanExpiredFiles             *bool `json:"CleanExpiredFiles,omitempty"`
	NumberOfSnapshotsToRetain     *int  `json:"NumberOfSnapshotsToRetain,omitempty"`
	SnapshotRetentionPeriodInDays *int  `json:"SnapshotRetentionPeriodInDays,omitempty"`
}

type RetentionConfiguration struct {
	IcebergConfiguration *IcebergRetentionConfiguration `json:"IcebergConfiguration,omitempty"`
}

type VpcConfiguration struct {
	GlueConnectionName *string `json:"GlueConnectionName,omitempty"`
}

type TableOptimizerConfiguration struct {
	CompactionConfiguration         *CompactionConfiguration         `json:"CompactionConfiguration,omitempty"`
	Enabled                         *bool                            `json:"Enabled,omitempty"`
	OrphanFileDeletionConfiguration *OrphanFileDeletionConfiguration `json:"OrphanFileDeletionConfiguration,omitempty"`
	RetentionConfiguration          *RetentionConfiguration          `json:"RetentionConfiguration,omitempty"`
	RoleArn                         *string                          `json:"RoleArn,omitempty"`
	VpcConfiguration                *VpcConfiguration                `json:"VpcConfiguration,omitempty"`
}

type TableOptimizer struct {
	CatalogId                   *string                      `json:"CatalogId,omitempty"`
	DatabaseName                *string                      `json:"DatabaseName,omitempty"`
	Id                          *string                      `json:"Id,omitempty"`
	TableName                   *string                      `json:"TableName,omitempty"`
	TableOptimizerConfiguration *TableOptimizerConfiguration `json:"TableOptimizerConfiguration,omitempty"`
	Type                        *string                      `json:"Type,omitempty"`
}

func (TableOptimizer) CloudControlType() string { return "AWS::Glue::TableOptimizer" }

type TriggerNotificationProperty struct {
	NotifyDelayAfter *int `json:"NotifyDelayAfter,omitempty"`
}

type Action struct {
	Arguments             map[string]any               `json:"Arguments,omitempty"`
	CrawlerName           *string                      `json:"CrawlerName,omitempty"`
	JobName               *string                      `json:"JobName,omitempty"`
	NotificationProperty  *TriggerNotificationProperty `json:"NotificationProperty,omitempty"`
	SecurityConfiguration *string                      `json:"SecurityConfiguration,omitempty"`
	Timeout               *int                         `json:"Timeout,omitempty"`
}

type EventBatchingCondition struct {
	BatchSize   *int `json:"BatchSize,omitempty"`
	BatchWindow *int `json:"BatchWindow,omitempty"`
}

type Condition struct {
	CrawlState      *string `json:"CrawlState,omitempty"`
	CrawlerName     *string `json:"CrawlerName,omitempty"`
	JobName         *string `json:"JobName,omitempty"`
	LogicalOperator *string `json:"LogicalOperator,omitempty"`
	State           *string `json:"State,omitempty"`
}

type Predicate struct {
	Conditions []Condition `json:"Conditions,omitempty"`
	Logical    *string     `json:"Logical,omitempty"`
}

type Trigger struct {
	Actions                []Action                `json:"Actions,omitempty"`
	Description            *string                 `json:"Description,omitempty"`
	EventBatchingCondition *EventBatchingCondition `json:"EventBatchingCondition,omitempty"`
	Name                   *string                 `json:"Name,omitempty"`
	Predicate              *Predicate              `json:"Predicate,omitempty"`
	Schedule               *string                 `json:"Schedule,omitempty"`
	StartOnCreation        *bool                   `json:"StartOnCreation,omitempty"`
	Tags                   map[string]any          `json:"Tags,omitempty"`
	Type                   *string                 `json:"Type,omitempty"`
	WorkflowName           *string                 `json:"WorkflowName,omitempty"`
}

func (Trigger) CloudControlType() string { return "AWS::Glue::Trigger" }

type ProfileConfiguration struct {
	JobConfiguration     json.RawMessage `json:"JobConfiguration,omitempty"`
	SessionConfiguration json.RawMessage `json:"SessionConfiguration,omitempty"`
}

type UsageProfileTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type UsageProfile struct {
	Configuration *ProfileConfiguration `json:"Configuration,omitempty"`
	CreatedOn     *string               `json:"CreatedOn,omitempty"`
	Description   *string               `json:"Description,omitempty"`
	Name          *string               `json:"Name,omitempty"`
	Tags          []UsageProfileTag     `json:"Tags,omitempty"`
}

func (UsageProfile) CloudControlType() string { return "AWS::Glue::UsageProfile" }

type ResourceUri struct {
	ResourceType *string `json:"ResourceType,omitempty"`
	Uri          *string `json:"Uri,omitempty"`
}

type UserDefinedFunction struct {
	Arn          *string       `json:"Arn,omitempty"`
	ClassName    *string       `json:"ClassName,omitempty"`
	DatabaseName *string       `json:"DatabaseName,omitempty"`
	FunctionName *string       `json:"FunctionName,omitempty"`
	FunctionType *string       `json:"FunctionType,omitempty"`
	OwnerName    *string       `json:"OwnerName,omitempty"`
	OwnerType    *string       `json:"OwnerType,omitempty"`
	ResourceUris []ResourceUri `json:"ResourceUris,omitempty"`
}

func (UserDefinedFunction) CloudControlType() string { return "AWS::Glue::UserDefinedFunction" }

type Workflow struct {
	DefaultRunProperties map[string]any `json:"DefaultRunProperties,omitempty"`
	Description          *string        `json:"Description,omitempty"`
	Id                   *string        `json:"Id,omitempty"`
	MaxConcurrentRuns    *int           `json:"MaxConcurrentRuns,omitempty"`
	Name                 *string        `json:"Name,omitempty"`
	Tags                 map[string]any `json:"Tags,omitempty"`
}

func (Workflow) CloudControlType() string { return "AWS::Glue::Workflow" }
