syntax = "proto3";

package v1.game.team;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "v1/game/team.proto";

option go_package = "codeberg.org/megakuul/cloudjam/pkg/api/v1/game/team";

message GetRequest {
  string game_id = 1 [(buf.validate.field).string = {uuid: true}];
  string id = 2 [(buf.validate.field).string = {uuid: true}];
}

message GetResponse {
  Team account = 1;
}

message ListRequest {
  string game_id = 1 [(buf.validate.field).string = {uuid: true}];
  int32 limit = 2 [(buf.validate.field).int32 = {
    gt: 0
    lte: 100
  }];
}

message ListResponse {
  repeated Team accounts = 1;
}

message CreateRequest {
  Team init = 1;
}

message CreateResponse {}

message UpdateRequest {
  Team mod = 1;
}

message UpdateResponse {}

message DeleteRequest {
  string id = 1 [(buf.validate.field).string = {uuid: true}];
}

message DeleteResponse {}

service TeamService {
  rpc Get(GetRequest) returns (GetResponse);
  rpc List(ListRequest) returns (ListResponse);
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Update(UpdateRequest) returns (UpdateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
}
