// Code generated by go generate; DO NOT EDIT.

package ivs

// The iam actions of the aws ivs service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionBatchGetChannel                   = "ivs:BatchGetChannel"
	ActionBatchGetStreamKey                 = "ivs:BatchGetStreamKey"
	ActionBatchStartViewerSessionRevocation = "ivs:BatchStartViewerSessionRevocation"
	ActionCreateAdConfiguration             = "ivs:CreateAdConfiguration"
	ActionCreateChannel                     = "ivs:CreateChannel"
	ActionCreateEncoderConfiguration        = "ivs:CreateEncoderConfiguration"
	ActionCreateIngestConfiguration         = "ivs:CreateIngestConfiguration"
	ActionCreateParticipantToken            = "ivs:CreateParticipantToken"
	ActionCreatePlaybackRestrictionPolicy   = "ivs:CreatePlaybackRestrictionPolicy"
	ActionCreateRecordingConfiguration      = "ivs:CreateRecordingConfiguration"
	ActionCreateStage                       = "ivs:CreateStage"
	ActionCreateStorageConfiguration        = "ivs:CreateStorageConfiguration"
	ActionCreateStreamKey                   = "ivs:CreateStreamKey"
	ActionDeleteAdConfiguration             = "ivs:DeleteAdConfiguration"
	ActionDeleteChannel                     = "ivs:DeleteChannel"
	ActionDeleteEncoderConfiguration        = "ivs:DeleteEncoderConfiguration"
	ActionDeleteIngestConfiguration         = "ivs:DeleteIngestConfiguration"
	ActionDeletePlaybackKeyPair             = "ivs:DeletePlaybackKeyPair"
	ActionDeletePlaybackRestrictionPolicy   = "ivs:DeletePlaybackRestrictionPolicy"
	ActionDeletePublicKey                   = "ivs:DeletePublicKey"
	ActionDeleteRecordingConfiguration      = "ivs:DeleteRecordingConfiguration"
	ActionDeleteStage                       = "ivs:DeleteStage"
	ActionDeleteStorageConfiguration        = "ivs:DeleteStorageConfiguration"
	ActionDeleteStreamKey                   = "ivs:DeleteStreamKey"
	ActionDisconnectParticipant             = "ivs:DisconnectParticipant"
	ActionGetAdConfiguration                = "ivs:GetAdConfiguration"
	ActionGetChannel                        = "ivs:GetChannel"
	ActionGetComposition                    = "ivs:GetComposition"
	ActionGetEncoderConfiguration           = "ivs:GetEncoderConfiguration"
	ActionGetIngestConfiguration            = "ivs:GetIngestConfiguration"
	ActionGetParticipant                    = "ivs:GetParticipant"
	ActionGetPlaybackKeyPair                = "ivs:GetPlaybackKeyPair"
	ActionGetPlaybackRestrictionPolicy      = "ivs:GetPlaybackRestrictionPolicy"
	ActionGetPublicKey                      = "ivs:GetPublicKey"
	ActionGetRecordingConfiguration         = "ivs:GetRecordingConfiguration"
	ActionGetStage                          = "ivs:GetStage"
	ActionGetStageSession                   = "ivs:GetStageSession"
	ActionGetStorageConfiguration           = "ivs:GetStorageConfiguration"
	ActionGetStream                         = "ivs:GetStream"
	ActionGetStreamKey                      = "ivs:GetStreamKey"
	ActionGetStreamSession                  = "ivs:GetStreamSession"
	ActionImportPlaybackKeyPair             = "ivs:ImportPlaybackKeyPair"
	ActionImportPublicKey                   = "ivs:ImportPublicKey"
	ActionInsertAdBreak                     = "ivs:InsertAdBreak"
	ActionListAdConfigurations              = "ivs:ListAdConfigurations"
	ActionListChannels                      = "ivs:ListChannels"
	ActionListCompositions                  = "ivs:ListCompositions"
	ActionListEncoderConfigurations         = "ivs:ListEncoderConfigurations"
	ActionListIngestConfigurations          = "ivs:ListIngestConfigurations"
	ActionListParticipantEvents             = "ivs:ListParticipantEvents"
	ActionListParticipantReplicas           = "ivs:ListParticipantReplicas"
	ActionListParticipants                  = "ivs:ListParticipants"
	ActionListPlaybackKeyPairs              = "ivs:ListPlaybackKeyPairs"
	ActionListPlaybackRestrictionPolicies   = "ivs:ListPlaybackRestrictionPolicies"
	ActionListPublicKeys                    = "ivs:ListPublicKeys"
	ActionListRecordingConfigurations       = "ivs:ListRecordingConfigurations"
	ActionListStageSessions                 = "ivs:ListStageSessions"
	ActionListStages                        = "ivs:ListStages"
	ActionListStorageConfigurations         = "ivs:ListStorageConfigurations"
	ActionListStreamKeys                    = "ivs:ListStreamKeys"
	ActionListStreamSessions                = "ivs:ListStreamSessions"
	ActionListStreams                       = "ivs:ListStreams"
	ActionListTagsForResource               = "ivs:ListTagsForResource"
	ActionPutMetadata                       = "ivs:PutMetadata"
	ActionStartComposition                  = "ivs:StartComposition"
	ActionStartParticipantReplication       = "ivs:StartParticipantReplication"
	ActionStartViewerSessionRevocation      = "ivs:StartViewerSessionRevocation"
	ActionStopComposition                   = "ivs:StopComposition"
	ActionStopParticipantReplication        = "ivs:StopParticipantReplication"
	ActionStopStream                        = "ivs:StopStream"
	ActionTagResource                       = "ivs:TagResource"
	ActionUntagResource                     = "ivs:UntagResource"
	ActionUpdateAdConfiguration             = "ivs:UpdateAdConfiguration"
	ActionUpdateChannel                     = "ivs:UpdateChannel"
	ActionUpdateIngestConfiguration         = "ivs:UpdateIngestConfiguration"
	ActionUpdatePlaybackRestrictionPolicy   = "ivs:UpdatePlaybackRestrictionPolicy"
	ActionUpdateStage                       = "ivs:UpdateStage"
)

// ActionsList are the list actions, as classified by aws.
var ActionsList = []string{
	ActionListAdConfigurations,
	ActionListChannels,
	ActionListCompositions,
	ActionListEncoderConfigurations,
	ActionListIngestConfigurations,
	ActionListParticipantEvents,
	ActionListParticipantReplicas,
	ActionListParticipants,
	ActionListPlaybackKeyPairs,
	ActionListPlaybackRestrictionPolicies,
	ActionListPublicKeys,
	ActionListRecordingConfigurations,
	ActionListStageSessions,
	ActionListStages,
	ActionListStorageConfigurations,
	ActionListStreamKeys,
	ActionListStreamSessions,
	ActionListStreams,
}

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionBatchGetChannel,
	ActionBatchGetStreamKey,
	ActionGetAdConfiguration,
	ActionGetChannel,
	ActionGetComposition,
	ActionGetEncoderConfiguration,
	ActionGetIngestConfiguration,
	ActionGetParticipant,
	ActionGetPlaybackKeyPair,
	ActionGetPlaybackRestrictionPolicy,
	ActionGetPublicKey,
	ActionGetRecordingConfiguration,
	ActionGetStage,
	ActionGetStageSession,
	ActionGetStorageConfiguration,
	ActionGetStream,
	ActionGetStreamKey,
	ActionGetStreamSession,
	ActionListTagsForResource,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionBatchStartViewerSessionRevocation,
	ActionCreateAdConfiguration,
	ActionCreateChannel,
	ActionCreateEncoderConfiguration,
	ActionCreateIngestConfiguration,
	ActionCreateParticipantToken,
	ActionCreatePlaybackRestrictionPolicy,
	ActionCreateRecordingConfiguration,
	ActionCreateStage,
	ActionCreateStorageConfiguration,
	ActionCreateStreamKey,
	ActionDeleteAdConfiguration,
	ActionDeleteChannel,
	ActionDeleteEncoderConfiguration,
	ActionDeleteIngestConfiguration,
	ActionDeletePlaybackKeyPair,
	ActionDeletePlaybackRestrictionPolicy,
	ActionDeletePublicKey,
	ActionDeleteRecordingConfiguration,
	ActionDeleteStage,
	ActionDeleteStorageConfiguration,
	ActionDeleteStreamKey,
	ActionDisconnectParticipant,
	ActionImportPlaybackKeyPair,
	ActionImportPublicKey,
	ActionInsertAdBreak,
	ActionPutMetadata,
	ActionStartComposition,
	ActionStartParticipantReplication,
	ActionStartViewerSessionRevocation,
	ActionStopComposition,
	ActionStopParticipantReplication,
	ActionStopStream,
	ActionUpdateAdConfiguration,
	ActionUpdateChannel,
	ActionUpdateIngestConfiguration,
	ActionUpdatePlaybackRestrictionPolicy,
	ActionUpdateStage,
}

// ActionsTagging are the tagging actions, as classified by aws.
var ActionsTagging = []string{
	ActionTagResource,
	ActionUntagResource,
}
