syntax = "proto3";

package v1.play;

import "buf/validate/validate.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

option go_package = "codeberg.org/megakuul/cloudjam/pkg/api/v1/play";

message ScoreEvent {
  google.protobuf.Timestamp timestamp = 1;
  string text = 2;
  double change = 3;
}

message Challenge {
  string scope = 1;
  string game_id = 2 [(buf.validate.field).string = {uuid: true}];
  string id = 3 [(buf.validate.field).string = {uuid: true}];
  string team_id = 4 [(buf.validate.field).string = {uuid: true}];
  string definition_provider_id = 5 [(buf.validate.field).string = {uuid: true}];
  string definition_id = 6 [(buf.validate.field).string = {uuid: true}];

  string title = 7;
  repeated string description = 8;
  map<string, string> assets = 9;
  map<string, string> clues = 10;
  repeated string errors = 11;
  repeated ScoreEvent score_events = 12;
  google.protobuf.Duration duration = 13;
}
