syntax = "proto3";

package v1.cloud.account;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "v1/cloud/account.proto";

option go_package = "codeberg.org/megakuul/cloudjam/pkg/api/v1/cloud/account";

message GetRequest {
  string provider = 1 [(buf.validate.field).string = {uuid: true}];
  string id = 2 [(buf.validate.field).string = {uuid: true}];
}

message GetResponse {
  Account account = 1;
}

message ListRequest {
  string provider = 1 [(buf.validate.field).string = {uuid: true}];
  int32 limit = 2 [(buf.validate.field).int32 = {
    gt: 0
    lte: 100
  }];
  string start_after = 3;
}

message ListResponse {
  repeated Account accounts = 1;
}

message UpdateRequest {
  Account mod = 1;
}

message UpdateResponse {}

service AccountService {
  rpc Get(GetRequest) returns (GetResponse);
  rpc List(ListRequest) returns (ListResponse);
  rpc Update(UpdateRequest) returns (UpdateResponse);
}
