syntax = "proto3";

package v1.admin;

import "buf/validate/validate.proto";

option go_package = "codeberg.org/megakuul/cloudjam/pkg/api/v1/admin";

message Permission {
  repeated string action_exprs = 1 [
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.max_items = 10
  ];
}

message Role {
  string id = 1;
  string name = 2 [
    (buf.validate.field).string.min_len = 4,
    (buf.validate.field).string.max_len = 20
  ];
  string description = 3 [
    (buf.validate.field).string.min_len = 0,
    (buf.validate.field).string.max_len = 50
  ];
  bool builtin = 4;
  map<string, Permission> permissions = 5 [
    (buf.validate.field).repeated.min_items = 1,
    (buf.validate.field).repeated.max_items = 20
  ];
  string scope = 6;
}
