syntax = "proto3";

package v1.admin;

import "buf/validate/validate.proto";

option go_package = "codeberg.org/megakuul/cloudjam/pkg/api/v1/admin";

message User {
  string scope = 1;
  string id = 2;
  string pub_id = 3;
  string username = 4 [
    (buf.validate.field).string.min_len = 4,
    (buf.validate.field).string.max_len = 20
  ];
  string description = 5 [
    (buf.validate.field).string.min_len = 0,
    (buf.validate.field).string.max_len = 50
  ];
  string organization = 6 [(buf.validate.field).string.max_len = 20];
  string email = 7 [(buf.validate.field).string.email = true];
  int64 created_at = 8;
  double score = 9;
  double max_score = 10;
  int64 streak = 11;
  int64 max_streak = 12;
  bool privileged = 13;
  string role = 14;
}
