// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: v1/admin/role.proto

package admin

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Builtin       bool                   `protobuf:"varint,5,opt,name=builtin,proto3" json:"builtin,omitempty"`
	Permissions   map[string]string      `protobuf:"bytes,6,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_v1_admin_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_v1_admin_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_v1_admin_role_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetBuiltin() bool {
	if x != nil {
		return x.Builtin
	}
	return false
}

func (x *Role) GetPermissions() map[string]string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_v1_admin_role_proto protoreflect.FileDescriptor

const file_v1_admin_role_proto_rawDesc = "" +
	"\n" +
	"\x13v1/admin/role.proto\x12\bv1.admin\x1a\x1bbuf/validate/validate.proto\"\xbd\x02\n" +
	"\x04Role\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\x04name\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x04\x18\x14R\x04name\x12+\n" +
	"\vdescription\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x00\x182R\vdescription\x12\x18\n" +
	"\abuiltin\x18\x05 \x01(\bR\abuiltin\x12i\n" +
	"\vpermissions\x18\x06 \x03(\v2\x1f.v1.admin.Role.PermissionsEntryB&\xbaH#\x9a\x01 \b\x01\x10\x14*\x1ar\x18\x10\x01\x18d2\x12^[a-zA-Z0-9,*/.]+$R\vpermissions\x1a>\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B1Z/codeberg.org/megakuul/cloudjam/pkg/api/v1/adminb\x06proto3"

var (
	file_v1_admin_role_proto_rawDescOnce sync.Once
	file_v1_admin_role_proto_rawDescData []byte
)

func file_v1_admin_role_proto_rawDescGZIP() []byte {
	file_v1_admin_role_proto_rawDescOnce.Do(func() {
		file_v1_admin_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_admin_role_proto_rawDesc), len(file_v1_admin_role_proto_rawDesc)))
	})
	return file_v1_admin_role_proto_rawDescData
}

var file_v1_admin_role_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_admin_role_proto_goTypes = []any{
	(*Role)(nil), // 0: v1.admin.Role
	nil,          // 1: v1.admin.Role.PermissionsEntry
}
var file_v1_admin_role_proto_depIdxs = []int32{
	1, // 0: v1.admin.Role.permissions:type_name -> v1.admin.Role.PermissionsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_admin_role_proto_init() }
func file_v1_admin_role_proto_init() {
	if File_v1_admin_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_admin_role_proto_rawDesc), len(file_v1_admin_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_admin_role_proto_goTypes,
		DependencyIndexes: file_v1_admin_role_proto_depIdxs,
		MessageInfos:      file_v1_admin_role_proto_msgTypes,
	}.Build()
	File_v1_admin_role_proto = out.File
	file_v1_admin_role_proto_goTypes = nil
	file_v1_admin_role_proto_depIdxs = nil
}
