// Code generated by go generate; DO NOT EDIT.

// Package kinesisvideo holds the cloud control resources of the aws kinesisvideo service.
package kinesisvideo

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type SignalingChannel struct {
	Arn               *string               `json:"Arn,omitempty"`
	MessageTtlSeconds *int                  `json:"MessageTtlSeconds,omitempty"`
	Name              *string               `json:"Name,omitempty"`
	Tags              []Tag                 `json:"Tags,omitempty"`
	Type              *SignalingChannelType `json:"Type,omitempty"`
}

func (SignalingChannel) CloudControlType() string { return "AWS::KinesisVideo::SignalingChannel" }

type StreamStorageConfiguration struct {
	DefaultStorageTier *StreamStorageConfigurationDefaultStorageTier `json:"DefaultStorageTier,omitempty"`
}

type StreamTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Stream struct {
	Arn                        *string                     `json:"Arn,omitempty"`
	DataRetentionInHours       *int                        `json:"DataRetentionInHours,omitempty"`
	DeviceName                 *string                     `json:"DeviceName,omitempty"`
	KmsKeyId                   *string                     `json:"KmsKeyId,omitempty"`
	MediaType                  *string                     `json:"MediaType,omitempty"`
	Name                       *string                     `json:"Name,omitempty"`
	StreamStorageConfiguration *StreamStorageConfiguration `json:"StreamStorageConfiguration,omitempty"`
	Tags                       []StreamTag                 `json:"Tags,omitempty"`
}

func (Stream) CloudControlType() string { return "AWS::KinesisVideo::Stream" }

type SignalingChannelType string

const (
	SignalingChannelTypeSINGLEMASTER SignalingChannelType = "SINGLE_MASTER"
)

type StreamStorageConfigurationDefaultStorageTier string

const (
	StreamStorageConfigurationDefaultStorageTierHOT  StreamStorageConfigurationDefaultStorageTier = "HOT"
	StreamStorageConfigurationDefaultStorageTierWARM StreamStorageConfigurationDefaultStorageTier = "WARM"
)
