syntax = "proto3";

package v1.cloud;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

option go_package = "codeberg.org/megakuul/cloudjam/pkg/api/v1/cloud";

enum AccountState {
  // NotCreated means the account metadata is there but the provisioning process did not start.
  // In this state it is forbidden to perform ANY action on the provider.
  NotCreated = 0;
  // Provisioning means the account is currently being created by an asynchron provider action.
  // In this state it is forbidden to perform ANY action on the provider.
  Provisioning = 1;
  // Ready means the account is currently ready in the pool and can be used for a challenge.
  Ready = 2;
  // Running means the account is currently running (bzw. bound to a challenge).
  // In this state it is forbidden to perform ANY action on the provider as long as the providers bound_until property is not expired.
  Running = 3;
  // Evicting means the account is currently cleaned by an asynchron provider action.
  // In this state it is forbidden to perform ANY action on the provider.
  Evicting = 4;
  // Corrupted means an asynchron provider action on the account failed. Manual intervention is required!
  // In this state it is forbidden to perform ANY action on the provider.
  Corrupted = 5;
  // Disabled means the account is locked and will transition into deleting state as soon as the provider is ready.
  // In this state it is forbidden to perform ANY action on the provider.
  Disabled = 6;
  // Deleting means the providers async deletion mechanism is working.
  // In this state it is forbidden to perform ANY action on the provider.
  Deleting = 7;
}

message Account {
  string scope = 1;
  string provider_id = 2 [(buf.validate.field).string = {uuid: true}];
  string id = 3;

  string target_id = 4;
  string name = 5 [
    (buf.validate.field).string.min_len = 4,
    (buf.validate.field).string.max_len = 20
  ];
  string description = 6 [
    (buf.validate.field).string.min_len = 0,
    (buf.validate.field).string.max_len = 50
  ];
  AccountState state = 7;
  google.protobuf.Timestamp bound_until = 8;
  string error = 9;
}
