// Code generated by go generate; DO NOT EDIT.

// Package servicecatalog holds the cloud control resources of the aws servicecatalog service.
package servicecatalog

type AcceptedPortfolioShare struct {
	AcceptLanguage *string `json:"AcceptLanguage,omitempty"`
	PortfolioId    *string `json:"PortfolioId,omitempty"`
}

func (AcceptedPortfolioShare) CloudControlType() string {
	return "AWS::ServiceCatalog::AcceptedPortfolioShare"
}

type ProvisioningArtifactPropertiesInfo struct {
	ImportFromPhysicalId *string `json:"ImportFromPhysicalId,omitempty"`
	LoadTemplateFromURL  *string `json:"LoadTemplateFromURL,omitempty"`
}

type ProvisioningArtifactProperties struct {
	Description               *string                             `json:"Description,omitempty"`
	DisableTemplateValidation *bool                               `json:"DisableTemplateValidation,omitempty"`
	Info                      *ProvisioningArtifactPropertiesInfo `json:"Info,omitempty"`
	Name                      *string                             `json:"Name,omitempty"`
	Type                      *string                             `json:"Type,omitempty"`
}

type CodeStarParameters struct {
	ArtifactPath  *string `json:"ArtifactPath,omitempty"`
	Branch        *string `json:"Branch,omitempty"`
	ConnectionArn *string `json:"ConnectionArn,omitempty"`
	Repository    *string `json:"Repository,omitempty"`
}

type SourceConnectionConnectionParameters struct {
	CodeStar *CodeStarParameters `json:"CodeStar,omitempty"`
}

type SourceConnection struct {
	ConnectionParameters *SourceConnectionConnectionParameters `json:"ConnectionParameters,omitempty"`
	Type                 *string                               `json:"Type,omitempty"`
}

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type CloudFormationProduct struct {
	AcceptLanguage                 *string                          `json:"AcceptLanguage,omitempty"`
	Description                    *string                          `json:"Description,omitempty"`
	Distributor                    *string                          `json:"Distributor,omitempty"`
	Id                             *string                          `json:"Id,omitempty"`
	Name                           *string                          `json:"Name,omitempty"`
	Owner                          *string                          `json:"Owner,omitempty"`
	ProductName                    *string                          `json:"ProductName,omitempty"`
	ProductType                    *string                          `json:"ProductType,omitempty"`
	ProvisioningArtifactIds        *string                          `json:"ProvisioningArtifactIds,omitempty"`
	ProvisioningArtifactNames      *string                          `json:"ProvisioningArtifactNames,omitempty"`
	ProvisioningArtifactParameters []ProvisioningArtifactProperties `json:"ProvisioningArtifactParameters,omitempty"`
	ReplaceProvisioningArtifacts   *bool                            `json:"ReplaceProvisioningArtifacts,omitempty"`
	SourceConnection               *SourceConnection                `json:"SourceConnection,omitempty"`
	SupportDescription             *string                          `json:"SupportDescription,omitempty"`
	SupportEmail                   *string                          `json:"SupportEmail,omitempty"`
	SupportUrl                     *string                          `json:"SupportUrl,omitempty"`
	Tags                           []Tag                            `json:"Tags,omitempty"`
}

func (CloudFormationProduct) CloudControlType() string {
	return "AWS::ServiceCatalog::CloudFormationProduct"
}

type ProvisioningParameter struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type ProvisioningPreferences struct {
	StackSetAccounts                   []string `json:"StackSetAccounts,omitempty"`
	StackSetFailureToleranceCount      *int     `json:"StackSetFailureToleranceCount,omitempty"`
	StackSetFailureTolerancePercentage *int     `json:"StackSetFailureTolerancePercentage,omitempty"`
	StackSetMaxConcurrencyCount        *int     `json:"StackSetMaxConcurrencyCount,omitempty"`
	StackSetMaxConcurrencyPercentage   *int     `json:"StackSetMaxConcurrencyPercentage,omitempty"`
	StackSetOperationType              *string  `json:"StackSetOperationType,omitempty"`
	StackSetRegions                    []string `json:"StackSetRegions,omitempty"`
}

type CloudFormationProvisionedProductTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type CloudFormationProvisionedProduct struct {
	AcceptLanguage           *string                               `json:"AcceptLanguage,omitempty"`
	CloudformationStackArn   *string                               `json:"CloudformationStackArn,omitempty"`
	NotificationArns         []string                              `json:"NotificationArns,omitempty"`
	Outputs                  map[string]string                     `json:"Outputs,omitempty"`
	PathId                   *string                               `json:"PathId,omitempty"`
	PathName                 *string                               `json:"PathName,omitempty"`
	ProductId                *string                               `json:"ProductId,omitempty"`
	ProductName              *string                               `json:"ProductName,omitempty"`
	ProvisionedProductId     *string                               `json:"ProvisionedProductId,omitempty"`
	ProvisionedProductName   *string                               `json:"ProvisionedProductName,omitempty"`
	ProvisioningArtifactId   *string                               `json:"ProvisioningArtifactId,omitempty"`
	ProvisioningArtifactName *string                               `json:"ProvisioningArtifactName,omitempty"`
	ProvisioningParameters   []ProvisioningParameter               `json:"ProvisioningParameters,omitempty"`
	ProvisioningPreferences  *ProvisioningPreferences              `json:"ProvisioningPreferences,omitempty"`
	RecordId                 *string                               `json:"RecordId,omitempty"`
	Tags                     []CloudFormationProvisionedProductTag `json:"Tags,omitempty"`
}

func (CloudFormationProvisionedProduct) CloudControlType() string {
	return "AWS::ServiceCatalog::CloudFormationProvisionedProduct"
}

type LaunchNotificationConstraint struct {
	AcceptLanguage   *string  `json:"AcceptLanguage,omitempty"`
	Description      *string  `json:"Description,omitempty"`
	Id               *string  `json:"Id,omitempty"`
	NotificationArns []string `json:"NotificationArns,omitempty"`
	PortfolioId      *string  `json:"PortfolioId,omitempty"`
	ProductId        *string  `json:"ProductId,omitempty"`
}

func (LaunchNotificationConstraint) CloudControlType() string {
	return "AWS::ServiceCatalog::LaunchNotificationConstraint"
}

type LaunchRoleConstraint struct {
	AcceptLanguage *string `json:"AcceptLanguage,omitempty"`
	Description    *string `json:"Description,omitempty"`
	Id             *string `json:"Id,omitempty"`
	LocalRoleName  *string `json:"LocalRoleName,omitempty"`
	PortfolioId    *string `json:"PortfolioId,omitempty"`
	ProductId      *string `json:"ProductId,omitempty"`
	RoleArn        *string `json:"RoleArn,omitempty"`
}

func (LaunchRoleConstraint) CloudControlType() string {
	return "AWS::ServiceCatalog::LaunchRoleConstraint"
}

type LaunchTemplateConstraint struct {
	AcceptLanguage *string `json:"AcceptLanguage,omitempty"`
	Description    *string `json:"Description,omitempty"`
	Id             *string `json:"Id,omitempty"`
	PortfolioId    *string `json:"PortfolioId,omitempty"`
	ProductId      *string `json:"ProductId,omitempty"`
	Rules          *string `json:"Rules,omitempty"`
}

func (LaunchTemplateConstraint) CloudControlType() string {
	return "AWS::ServiceCatalog::LaunchTemplateConstraint"
}

type PortfolioTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Portfolio struct {
	AcceptLanguage *string        `json:"AcceptLanguage,omitempty"`
	Description    *string        `json:"Description,omitempty"`
	DisplayName    *string        `json:"DisplayName,omitempty"`
	Id             *string        `json:"Id,omitempty"`
	PortfolioName  *string        `json:"PortfolioName,omitempty"`
	ProviderName   *string        `json:"ProviderName,omitempty"`
	Tags           []PortfolioTag `json:"Tags,omitempty"`
}

func (Portfolio) CloudControlType() string { return "AWS::ServiceCatalog::Portfolio" }

type PortfolioPrincipalAssociation struct {
	AcceptLanguage *string `json:"AcceptLanguage,omitempty"`
	PortfolioId    *string `json:"PortfolioId,omitempty"`
	PrincipalARN   *string `json:"PrincipalARN,omitempty"`
	PrincipalType  *string `json:"PrincipalType,omitempty"`
}

func (PortfolioPrincipalAssociation) CloudControlType() string {
	return "AWS::ServiceCatalog::PortfolioPrincipalAssociation"
}

type PortfolioProductAssociation struct {
	AcceptLanguage    *string `json:"AcceptLanguage,omitempty"`
	PortfolioId       *string `json:"PortfolioId,omitempty"`
	ProductId         *string `json:"ProductId,omitempty"`
	SourcePortfolioId *string `json:"SourcePortfolioId,omitempty"`
}

func (PortfolioProductAssociation) CloudControlType() string {
	return "AWS::ServiceCatalog::PortfolioProductAssociation"
}

type PortfolioShare struct {
	AcceptLanguage  *string `json:"AcceptLanguage,omitempty"`
	AccountId       *string `json:"AccountId,omitempty"`
	PortfolioId     *string `json:"PortfolioId,omitempty"`
	ShareTagOptions *bool   `json:"ShareTagOptions,omitempty"`
}

func (PortfolioShare) CloudControlType() string { return "AWS::ServiceCatalog::PortfolioShare" }

type ResourceUpdateConstraint struct {
	AcceptLanguage                *string `json:"AcceptLanguage,omitempty"`
	Description                   *string `json:"Description,omitempty"`
	Id                            *string `json:"Id,omitempty"`
	PortfolioId                   *string `json:"PortfolioId,omitempty"`
	ProductId                     *string `json:"ProductId,omitempty"`
	TagUpdateOnProvisionedProduct *string `json:"TagUpdateOnProvisionedProduct,omitempty"`
}

func (ResourceUpdateConstraint) CloudControlType() string {
	return "AWS::ServiceCatalog::ResourceUpdateConstraint"
}

type DefinitionParameter struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type ServiceAction struct {
	AcceptLanguage *string               `json:"AcceptLanguage,omitempty"`
	Definition     []DefinitionParameter `json:"Definition,omitempty"`
	DefinitionType *string               `json:"DefinitionType,omitempty"`
	Description    *string               `json:"Description,omitempty"`
	Id             *string               `json:"Id,omitempty"`
	Name           *string               `json:"Name,omitempty"`
}

func (ServiceAction) CloudControlType() string { return "AWS::ServiceCatalog::ServiceAction" }

type ServiceActionAssociation struct {
	ProductId              *string `json:"ProductId,omitempty"`
	ProvisioningArtifactId *string `json:"ProvisioningArtifactId,omitempty"`
	ServiceActionId        *string `json:"ServiceActionId,omitempty"`
}

func (ServiceActionAssociation) CloudControlType() string {
	return "AWS::ServiceCatalog::ServiceActionAssociation"
}

type StackSetConstraint struct {
	AcceptLanguage       *string  `json:"AcceptLanguage,omitempty"`
	AccountList          []string `json:"AccountList,omitempty"`
	AdminRole            *string  `json:"AdminRole,omitempty"`
	Description          *string  `json:"Description,omitempty"`
	ExecutionRole        *string  `json:"ExecutionRole,omitempty"`
	Id                   *string  `json:"Id,omitempty"`
	PortfolioId          *string  `json:"PortfolioId,omitempty"`
	ProductId            *string  `json:"ProductId,omitempty"`
	RegionList           []string `json:"RegionList,omitempty"`
	StackInstanceControl *string  `json:"StackInstanceControl,omitempty"`
}

func (StackSetConstraint) CloudControlType() string { return "AWS::ServiceCatalog::StackSetConstraint" }

type TagOption struct {
	Active *bool   `json:"Active,omitempty"`
	Id     *string `json:"Id,omitempty"`
	Key    *string `json:"Key,omitempty"`
	Value  *string `json:"Value,omitempty"`
}

func (TagOption) CloudControlType() string { return "AWS::ServiceCatalog::TagOption" }

type TagOptionAssociation struct {
	ResourceId  *string `json:"ResourceId,omitempty"`
	TagOptionId *string `json:"TagOptionId,omitempty"`
}

func (TagOptionAssociation) CloudControlType() string {
	return "AWS::ServiceCatalog::TagOptionAssociation"
}
