// Code generated by go generate; DO NOT EDIT.

// Package logs holds the cloud control resources of the aws logs service.
package logs

import "encoding/json"

type AccountPolicy struct {
	AccountId         *string                  `json:"AccountId,omitempty"`
	PolicyDocument    *string                  `json:"PolicyDocument,omitempty"`
	PolicyName        *string                  `json:"PolicyName,omitempty"`
	PolicyType        *AccountPolicyPolicyType `json:"PolicyType,omitempty"`
	Scope             *AccountPolicyScope      `json:"Scope,omitempty"`
	SelectionCriteria *string                  `json:"SelectionCriteria,omitempty"`
}

func (AccountPolicy) Type() string { return "AWS::Logs::AccountPolicy" }

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Delivery struct {
	Arn                        *string  `json:"Arn,omitempty"`
	DeliveryDestinationArn     *string  `json:"DeliveryDestinationArn,omitempty"`
	DeliveryDestinationType    *string  `json:"DeliveryDestinationType,omitempty"`
	DeliveryId                 *string  `json:"DeliveryId,omitempty"`
	DeliverySourceName         *string  `json:"DeliverySourceName,omitempty"`
	FieldDelimiter             *string  `json:"FieldDelimiter,omitempty"`
	RecordFields               []string `json:"RecordFields,omitempty"`
	S3EnableHiveCompatiblePath *bool    `json:"S3EnableHiveCompatiblePath,omitempty"`
	S3SuffixPath               *string  `json:"S3SuffixPath,omitempty"`
	Tags                       []Tag    `json:"Tags,omitempty"`
}

func (Delivery) Type() string { return "AWS::Logs::Delivery" }

type DestinationPolicy struct {
	DeliveryDestinationName   *string        `json:"DeliveryDestinationName,omitempty"`
	DeliveryDestinationPolicy map[string]any `json:"DeliveryDestinationPolicy,omitempty"`
}

type DeliveryDestinationTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type DeliveryDestination struct {
	Arn                       *string                  `json:"Arn,omitempty"`
	DeliveryDestinationPolicy *DestinationPolicy       `json:"DeliveryDestinationPolicy,omitempty"`
	DeliveryDestinationType   *string                  `json:"DeliveryDestinationType,omitempty"`
	DestinationResourceArn    *string                  `json:"DestinationResourceArn,omitempty"`
	Name                      *string                  `json:"Name,omitempty"`
	OutputFormat              *string                  `json:"OutputFormat,omitempty"`
	Tags                      []DeliveryDestinationTag `json:"Tags,omitempty"`
}

func (DeliveryDestination) Type() string { return "AWS::Logs::DeliveryDestination" }

type DeliverySourceTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type DeliverySource struct {
	Arn                         *string                     `json:"Arn,omitempty"`
	DeliverySourceConfiguration map[string]string           `json:"DeliverySourceConfiguration,omitempty"`
	LogType                     *string                     `json:"LogType,omitempty"`
	Name                        *string                     `json:"Name,omitempty"`
	ResourceArn                 *string                     `json:"ResourceArn,omitempty"`
	ResourceArns                []string                    `json:"ResourceArns,omitempty"`
	Service                     *string                     `json:"Service,omitempty"`
	Status                      *DeliverySourceStatus       `json:"Status,omitempty"`
	StatusReason                *DeliverySourceStatusReason `json:"StatusReason,omitempty"`
	Tags                        []DeliverySourceTag         `json:"Tags,omitempty"`
}

func (DeliverySource) Type() string { return "AWS::Logs::DeliverySource" }

type DestinationTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Destination struct {
	Arn               *string          `json:"Arn,omitempty"`
	DestinationName   *string          `json:"DestinationName,omitempty"`
	DestinationPolicy *string          `json:"DestinationPolicy,omitempty"`
	RoleArn           *string          `json:"RoleArn,omitempty"`
	Tags              []DestinationTag `json:"Tags,omitempty"`
	TargetArn         *string          `json:"TargetArn,omitempty"`
}

func (Destination) Type() string { return "AWS::Logs::Destination" }

type OpenSearchResourceConfig struct {
	ApplicationARN            *string  `json:"ApplicationARN,omitempty"`
	DashboardViewerPrincipals []string `json:"DashboardViewerPrincipals,omitempty"`
	DataSourceRoleArn         *string  `json:"DataSourceRoleArn,omitempty"`
	KmsKeyArn                 *string  `json:"KmsKeyArn,omitempty"`
	RetentionDays             *int     `json:"RetentionDays,omitempty"`
}

type IntegrationResourceConfig struct {
	OpenSearchResourceConfig *OpenSearchResourceConfig `json:"OpenSearchResourceConfig,omitempty"`
}

type Integration struct {
	IntegrationName   *string                       `json:"IntegrationName,omitempty"`
	IntegrationStatus *IntegrationIntegrationStatus `json:"IntegrationStatus,omitempty"`
	IntegrationType   *IntegrationIntegrationType   `json:"IntegrationType,omitempty"`
	ResourceConfig    *IntegrationResourceConfig    `json:"ResourceConfig,omitempty"`
}

func (Integration) Type() string { return "AWS::Logs::Integration" }

type LogAnomalyDetector struct {
	AccountId             *string                                `json:"AccountId,omitempty"`
	AnomalyDetectorArn    *string                                `json:"AnomalyDetectorArn,omitempty"`
	AnomalyDetectorStatus *string                                `json:"AnomalyDetectorStatus,omitempty"`
	AnomalyVisibilityTime *float64                               `json:"AnomalyVisibilityTime,omitempty"`
	CreationTimeStamp     *float64                               `json:"CreationTimeStamp,omitempty"`
	DetectorName          *string                                `json:"DetectorName,omitempty"`
	EvaluationFrequency   *LogAnomalyDetectorEvaluationFrequency `json:"EvaluationFrequency,omitempty"`
	FilterPattern         *string                                `json:"FilterPattern,omitempty"`
	KmsKeyId              *string                                `json:"KmsKeyId,omitempty"`
	LastModifiedTimeStamp *float64                               `json:"LastModifiedTimeStamp,omitempty"`
	LogGroupArnList       []string                               `json:"LogGroupArnList,omitempty"`
}

func (LogAnomalyDetector) Type() string { return "AWS::Logs::LogAnomalyDetector" }

type LogGroupTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type LogGroup struct {
	Arn                              *string                `json:"Arn,omitempty"`
	BearerTokenAuthenticationEnabled *bool                  `json:"BearerTokenAuthenticationEnabled,omitempty"`
	DataProtectionPolicy             map[string]any         `json:"DataProtectionPolicy,omitempty"`
	DeletionProtectionEnabled        *bool                  `json:"DeletionProtectionEnabled,omitempty"`
	FieldIndexPolicies               []map[string]any       `json:"FieldIndexPolicies,omitempty"`
	KmsKeyId                         *string                `json:"KmsKeyId,omitempty"`
	LogGroupClass                    *LogGroupLogGroupClass `json:"LogGroupClass,omitempty"`
	LogGroupName                     *string                `json:"LogGroupName,omitempty"`
	ResourcePolicyDocument           map[string]any         `json:"ResourcePolicyDocument,omitempty"`
	RetentionInDays                  *int                   `json:"RetentionInDays,omitempty"`
	Tags                             []LogGroupTag          `json:"Tags,omitempty"`
}

func (LogGroup) Type() string { return "AWS::Logs::LogGroup" }

type LogStream struct {
	LogGroupName  *string `json:"LogGroupName,omitempty"`
	LogStreamName *string `json:"LogStreamName,omitempty"`
}

func (LogStream) Type() string { return "AWS::Logs::LogStream" }

type Dimension struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type MetricTransformation struct {
	DefaultValue    *float64                  `json:"DefaultValue,omitempty"`
	Dimensions      []Dimension               `json:"Dimensions,omitempty"`
	MetricName      *string                   `json:"MetricName,omitempty"`
	MetricNamespace *string                   `json:"MetricNamespace,omitempty"`
	MetricValue     *string                   `json:"MetricValue,omitempty"`
	Unit            *MetricTransformationUnit `json:"Unit,omitempty"`
}

type MetricFilter struct {
	ApplyOnTransformedLogs    *bool                  `json:"ApplyOnTransformedLogs,omitempty"`
	EmitSystemFieldDimensions []string               `json:"EmitSystemFieldDimensions,omitempty"`
	FieldSelectionCriteria    *string                `json:"FieldSelectionCriteria,omitempty"`
	FilterName                *string                `json:"FilterName,omitempty"`
	FilterPattern             *string                `json:"FilterPattern,omitempty"`
	LogGroupName              *string                `json:"LogGroupName,omitempty"`
	MetricTransformations     []MetricTransformation `json:"MetricTransformations,omitempty"`
}

func (MetricFilter) Type() string { return "AWS::Logs::MetricFilter" }

type QueryParameter struct {
	DefaultValue *string `json:"DefaultValue,omitempty"`
	Description  *string `json:"Description,omitempty"`
	Name         *string `json:"Name,omitempty"`
}

type QueryDefinition struct {
	LogGroupNames     []LogGroup                    `json:"LogGroupNames,omitempty"`
	Name              *string                       `json:"Name,omitempty"`
	Parameters        []QueryParameter              `json:"Parameters,omitempty"`
	QueryDefinitionId *string                       `json:"QueryDefinitionId,omitempty"`
	QueryLanguage     *QueryDefinitionQueryLanguage `json:"QueryLanguage,omitempty"`
	QueryString       *string                       `json:"QueryString,omitempty"`
}

func (QueryDefinition) Type() string { return "AWS::Logs::QueryDefinition" }

type ResourcePolicy struct {
	PolicyDocument json.RawMessage `json:"PolicyDocument,omitempty"`
	PolicyName     *string         `json:"PolicyName,omitempty"`
}

func (ResourcePolicy) Type() string { return "AWS::Logs::ResourcePolicy" }

type S3Configuration struct {
	DestinationIdentifier *string `json:"DestinationIdentifier,omitempty"`
	RoleArn               *string `json:"RoleArn,omitempty"`
}

type DestinationConfiguration struct {
	S3Configuration *S3Configuration `json:"S3Configuration,omitempty"`
}

type ScheduledQueryTagsItem struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type ScheduledQuery struct {
	CreationTime             *float64                           `json:"CreationTime,omitempty"`
	Description              *string                            `json:"Description,omitempty"`
	DestinationConfiguration *DestinationConfiguration          `json:"DestinationConfiguration,omitempty"`
	ExecutionRoleArn         *string                            `json:"ExecutionRoleArn,omitempty"`
	LastExecutionStatus      *ScheduledQueryLastExecutionStatus `json:"LastExecutionStatus,omitempty"`
	LastTriggeredTime        *float64                           `json:"LastTriggeredTime,omitempty"`
	LastUpdatedTime          *float64                           `json:"LastUpdatedTime,omitempty"`
	LogGroupIdentifiers      []string                           `json:"LogGroupIdentifiers,omitempty"`
	Name                     *string                            `json:"Name,omitempty"`
	QueryLanguage            *string                            `json:"QueryLanguage,omitempty"`
	QueryString              *string                            `json:"QueryString,omitempty"`
	ScheduleEndTime          *float64                           `json:"ScheduleEndTime,omitempty"`
	ScheduleExpression       *string                            `json:"ScheduleExpression,omitempty"`
	ScheduleStartTime        *float64                           `json:"ScheduleStartTime,omitempty"`
	ScheduledQueryArn        *string                            `json:"ScheduledQueryArn,omitempty"`
	StartTimeOffset          *int                               `json:"StartTimeOffset,omitempty"`
	State                    *ScheduledQueryState               `json:"State,omitempty"`
	Tags                     []ScheduledQueryTagsItem           `json:"Tags,omitempty"`
	Timezone                 *string                            `json:"Timezone,omitempty"`
}

func (ScheduledQuery) Type() string { return "AWS::Logs::ScheduledQuery" }

type SubscriptionFilter struct {
	ApplyOnTransformedLogs *bool                           `json:"ApplyOnTransformedLogs,omitempty"`
	DestinationArn         *string                         `json:"DestinationArn,omitempty"`
	Distribution           *SubscriptionFilterDistribution `json:"Distribution,omitempty"`
	EmitSystemFields       []string                        `json:"EmitSystemFields,omitempty"`
	FieldSelectionCriteria *string                         `json:"FieldSelectionCriteria,omitempty"`
	FilterName             *string                         `json:"FilterName,omitempty"`
	FilterPattern          *string                         `json:"FilterPattern,omitempty"`
	LogGroupName           *string                         `json:"LogGroupName,omitempty"`
	RoleArn                *string                         `json:"RoleArn,omitempty"`
}

func (SubscriptionFilter) Type() string { return "AWS::Logs::SubscriptionFilter" }

type AddKeyEntry struct {
	Key               *string `json:"Key,omitempty"`
	OverwriteIfExists *bool   `json:"OverwriteIfExists,omitempty"`
	Value             *string `json:"Value,omitempty"`
}

type ProcessorAddKeys struct {
	Entries []AddKeyEntry `json:"Entries,omitempty"`
}

type CopyValueEntry struct {
	OverwriteIfExists *bool   `json:"OverwriteIfExists,omitempty"`
	Source            *string `json:"Source,omitempty"`
	Target            *string `json:"Target,omitempty"`
}

type ProcessorCopyValue struct {
	Entries []CopyValueEntry `json:"Entries,omitempty"`
}

type ProcessorCsv struct {
	Columns        []string `json:"Columns,omitempty"`
	Delimiter      *string  `json:"Delimiter,omitempty"`
	QuoteCharacter *string  `json:"QuoteCharacter,omitempty"`
	Source         *string  `json:"Source,omitempty"`
}

type ProcessorDateTimeConverter struct {
	Locale         *string  `json:"Locale,omitempty"`
	MatchPatterns  []string `json:"MatchPatterns,omitempty"`
	Source         *string  `json:"Source,omitempty"`
	SourceTimezone *string  `json:"SourceTimezone,omitempty"`
	Target         *string  `json:"Target,omitempty"`
	TargetFormat   *string  `json:"TargetFormat,omitempty"`
	TargetTimezone *string  `json:"TargetTimezone,omitempty"`
}

type ProcessorDeleteKeys struct {
	WithKeys []string `json:"WithKeys,omitempty"`
}

type ProcessorGrok struct {
	Match  *string `json:"Match,omitempty"`
	Source *string `json:"Source,omitempty"`
}

type ProcessorListToMap struct {
	Flatten          *bool                               `json:"Flatten,omitempty"`
	FlattenedElement *ProcessorListToMapFlattenedElement `json:"FlattenedElement,omitempty"`
	Key              *string                             `json:"Key,omitempty"`
	Source           *string                             `json:"Source,omitempty"`
	Target           *string                             `json:"Target,omitempty"`
	ValueKey         *string                             `json:"ValueKey,omitempty"`
}

type ProcessorLowerCaseString struct {
	WithKeys []string `json:"WithKeys,omitempty"`
}

type MoveKeyEntry struct {
	OverwriteIfExists *bool   `json:"OverwriteIfExists,omitempty"`
	Source            *string `json:"Source,omitempty"`
	Target            *string `json:"Target,omitempty"`
}

type ProcessorMoveKeys struct {
	Entries []MoveKeyEntry `json:"Entries,omitempty"`
}

type ParseCloudfront struct {
	Source *string `json:"Source,omitempty"`
}

type ProcessorParseJSON struct {
	Destination *string `json:"Destination,omitempty"`
	Source      *string `json:"Source,omitempty"`
}

type ProcessorParseKeyValue struct {
	Destination       *string `json:"Destination,omitempty"`
	FieldDelimiter    *string `json:"FieldDelimiter,omitempty"`
	KeyPrefix         *string `json:"KeyPrefix,omitempty"`
	KeyValueDelimiter *string `json:"KeyValueDelimiter,omitempty"`
	NonMatchValue     *string `json:"NonMatchValue,omitempty"`
	OverwriteIfExists *bool   `json:"OverwriteIfExists,omitempty"`
	Source            *string `json:"Source,omitempty"`
}

type ParsePostgres struct {
	Source *string `json:"Source,omitempty"`
}

type ParseRoute53 struct {
	Source *string `json:"Source,omitempty"`
}

type ParseToOCSF struct {
	EventSource    *EventSource `json:"EventSource,omitempty"`
	MappingVersion *string      `json:"MappingVersion,omitempty"`
	OcsfVersion    *OcsfVersion `json:"OcsfVersion,omitempty"`
	Source         *string      `json:"Source,omitempty"`
}

type ParseVPC struct {
	Source *string `json:"Source,omitempty"`
}

type ParseWAF struct {
	Source *string `json:"Source,omitempty"`
}

type RenameKeyEntry struct {
	Key               *string `json:"Key,omitempty"`
	OverwriteIfExists *bool   `json:"OverwriteIfExists,omitempty"`
	RenameTo          *string `json:"RenameTo,omitempty"`
}

type ProcessorRenameKeys struct {
	Entries []RenameKeyEntry `json:"Entries,omitempty"`
}

type SplitStringEntry struct {
	Delimiter *string `json:"Delimiter,omitempty"`
	Source    *string `json:"Source,omitempty"`
}

type ProcessorSplitString struct {
	Entries []SplitStringEntry `json:"Entries,omitempty"`
}

type SubstituteStringEntry struct {
	From   *string `json:"From,omitempty"`
	Source *string `json:"Source,omitempty"`
	To     *string `json:"To,omitempty"`
}

type ProcessorSubstituteString struct {
	Entries []SubstituteStringEntry `json:"Entries,omitempty"`
}

type ProcessorTrimString struct {
	WithKeys []string `json:"WithKeys,omitempty"`
}

type TypeConverterEntry struct {
	Key  *string                 `json:"Key,omitempty"`
	Type *TypeConverterEntryType `json:"Type,omitempty"`
}

type ProcessorTypeConverter struct {
	Entries []TypeConverterEntry `json:"Entries,omitempty"`
}

type ProcessorUpperCaseString struct {
	WithKeys []string `json:"WithKeys,omitempty"`
}

type Processor struct {
	AddKeys           *ProcessorAddKeys           `json:"AddKeys,omitempty"`
	CopyValue         *ProcessorCopyValue         `json:"CopyValue,omitempty"`
	Csv               *ProcessorCsv               `json:"Csv,omitempty"`
	DateTimeConverter *ProcessorDateTimeConverter `json:"DateTimeConverter,omitempty"`
	DeleteKeys        *ProcessorDeleteKeys        `json:"DeleteKeys,omitempty"`
	Grok              *ProcessorGrok              `json:"Grok,omitempty"`
	ListToMap         *ProcessorListToMap         `json:"ListToMap,omitempty"`
	LowerCaseString   *ProcessorLowerCaseString   `json:"LowerCaseString,omitempty"`
	MoveKeys          *ProcessorMoveKeys          `json:"MoveKeys,omitempty"`
	ParseCloudfront   *ParseCloudfront            `json:"ParseCloudfront,omitempty"`
	ParseJSON         *ProcessorParseJSON         `json:"ParseJSON,omitempty"`
	ParseKeyValue     *ProcessorParseKeyValue     `json:"ParseKeyValue,omitempty"`
	ParsePostgres     *ParsePostgres              `json:"ParsePostgres,omitempty"`
	ParseRoute53      *ParseRoute53               `json:"ParseRoute53,omitempty"`
	ParseToOCSF       *ParseToOCSF                `json:"ParseToOCSF,omitempty"`
	ParseVPC          *ParseVPC                   `json:"ParseVPC,omitempty"`
	ParseWAF          *ParseWAF                   `json:"ParseWAF,omitempty"`
	RenameKeys        *ProcessorRenameKeys        `json:"RenameKeys,omitempty"`
	SplitString       *ProcessorSplitString       `json:"SplitString,omitempty"`
	SubstituteString  *ProcessorSubstituteString  `json:"SubstituteString,omitempty"`
	TrimString        *ProcessorTrimString        `json:"TrimString,omitempty"`
	TypeConverter     *ProcessorTypeConverter     `json:"TypeConverter,omitempty"`
	UpperCaseString   *ProcessorUpperCaseString   `json:"UpperCaseString,omitempty"`
}

type Transformer struct {
	LogGroupIdentifier *string     `json:"LogGroupIdentifier,omitempty"`
	TransformerConfig  []Processor `json:"TransformerConfig,omitempty"`
}

func (Transformer) Type() string { return "AWS::Logs::Transformer" }

type AccountPolicyPolicyType string

const (
	AccountPolicyPolicyTypeDATAPROTECTIONPOLICY     AccountPolicyPolicyType = "DATA_PROTECTION_POLICY"
	AccountPolicyPolicyTypeSUBSCRIPTIONFILTERPOLICY AccountPolicyPolicyType = "SUBSCRIPTION_FILTER_POLICY"
	AccountPolicyPolicyTypeFIELDINDEXPOLICY         AccountPolicyPolicyType = "FIELD_INDEX_POLICY"
	AccountPolicyPolicyTypeTRANSFORMERPOLICY        AccountPolicyPolicyType = "TRANSFORMER_POLICY"
	AccountPolicyPolicyTypeMETRICEXTRACTIONPOLICY   AccountPolicyPolicyType = "METRIC_EXTRACTION_POLICY"
)

type AccountPolicyScope string

const (
	AccountPolicyScopeALL AccountPolicyScope = "ALL"
)

type DeliverySourceStatus string

const (
	DeliverySourceStatusACTIVE   DeliverySourceStatus = "ACTIVE"
	DeliverySourceStatusINACTIVE DeliverySourceStatus = "INACTIVE"
)

type DeliverySourceStatusReason string

const (
	DeliverySourceStatusReasonRESOURCEDELETED DeliverySourceStatusReason = "RESOURCE_DELETED"
)

type IntegrationIntegrationStatus string

const (
	IntegrationIntegrationStatusPROVISIONING IntegrationIntegrationStatus = "PROVISIONING"
	IntegrationIntegrationStatusACTIVE       IntegrationIntegrationStatus = "ACTIVE"
	IntegrationIntegrationStatusFAILED       IntegrationIntegrationStatus = "FAILED"
)

type IntegrationIntegrationType string

const (
	IntegrationIntegrationTypeOPENSEARCH IntegrationIntegrationType = "OPENSEARCH"
)

type LogAnomalyDetectorEvaluationFrequency string

const (
	LogAnomalyDetectorEvaluationFrequencyFIVEMIN    LogAnomalyDetectorEvaluationFrequency = "FIVE_MIN"
	LogAnomalyDetectorEvaluationFrequencyTENMIN     LogAnomalyDetectorEvaluationFrequency = "TEN_MIN"
	LogAnomalyDetectorEvaluationFrequencyFIFTEENMIN LogAnomalyDetectorEvaluationFrequency = "FIFTEEN_MIN"
	LogAnomalyDetectorEvaluationFrequencyTHIRTYMIN  LogAnomalyDetectorEvaluationFrequency = "THIRTY_MIN"
	LogAnomalyDetectorEvaluationFrequencyONEHOUR    LogAnomalyDetectorEvaluationFrequency = "ONE_HOUR"
)

type LogGroupLogGroupClass string

const (
	LogGroupLogGroupClassSTANDARD         LogGroupLogGroupClass = "STANDARD"
	LogGroupLogGroupClassINFREQUENTACCESS LogGroupLogGroupClass = "INFREQUENT_ACCESS"
	LogGroupLogGroupClassDELIVERY         LogGroupLogGroupClass = "DELIVERY"
)

type MetricTransformationUnit string

const (
	MetricTransformationUnitSeconds         MetricTransformationUnit = "Seconds"
	MetricTransformationUnitMicroseconds    MetricTransformationUnit = "Microseconds"
	MetricTransformationUnitMilliseconds    MetricTransformationUnit = "Milliseconds"
	MetricTransformationUnitBytes           MetricTransformationUnit = "Bytes"
	MetricTransformationUnitKilobytes       MetricTransformationUnit = "Kilobytes"
	MetricTransformationUnitMegabytes       MetricTransformationUnit = "Megabytes"
	MetricTransformationUnitGigabytes       MetricTransformationUnit = "Gigabytes"
	MetricTransformationUnitTerabytes       MetricTransformationUnit = "Terabytes"
	MetricTransformationUnitBits            MetricTransformationUnit = "Bits"
	MetricTransformationUnitKilobits        MetricTransformationUnit = "Kilobits"
	MetricTransformationUnitMegabits        MetricTransformationUnit = "Megabits"
	MetricTransformationUnitGigabits        MetricTransformationUnit = "Gigabits"
	MetricTransformationUnitTerabits        MetricTransformationUnit = "Terabits"
	MetricTransformationUnitPercent         MetricTransformationUnit = "Percent"
	MetricTransformationUnitCount           MetricTransformationUnit = "Count"
	MetricTransformationUnitBytesSecond     MetricTransformationUnit = "Bytes/Second"
	MetricTransformationUnitKilobytesSecond MetricTransformationUnit = "Kilobytes/Second"
	MetricTransformationUnitMegabytesSecond MetricTransformationUnit = "Megabytes/Second"
	MetricTransformationUnitGigabytesSecond MetricTransformationUnit = "Gigabytes/Second"
	MetricTransformationUnitTerabytesSecond MetricTransformationUnit = "Terabytes/Second"
	MetricTransformationUnitBitsSecond      MetricTransformationUnit = "Bits/Second"
	MetricTransformationUnitKilobitsSecond  MetricTransformationUnit = "Kilobits/Second"
	MetricTransformationUnitMegabitsSecond  MetricTransformationUnit = "Megabits/Second"
	MetricTransformationUnitGigabitsSecond  MetricTransformationUnit = "Gigabits/Second"
	MetricTransformationUnitTerabitsSecond  MetricTransformationUnit = "Terabits/Second"
	MetricTransformationUnitCountSecond     MetricTransformationUnit = "Count/Second"
	MetricTransformationUnitNone            MetricTransformationUnit = "None"
)

type QueryDefinitionQueryLanguage string

const (
	QueryDefinitionQueryLanguageCWLI QueryDefinitionQueryLanguage = "CWLI"
	QueryDefinitionQueryLanguageSQL  QueryDefinitionQueryLanguage = "SQL"
	QueryDefinitionQueryLanguagePPL  QueryDefinitionQueryLanguage = "PPL"
)

type ScheduledQueryLastExecutionStatus string

const (
	ScheduledQueryLastExecutionStatusPending      ScheduledQueryLastExecutionStatus = "Pending"
	ScheduledQueryLastExecutionStatusInvalidQuery ScheduledQueryLastExecutionStatus = "InvalidQuery"
	ScheduledQueryLastExecutionStatusComplete     ScheduledQueryLastExecutionStatus = "Complete"
	ScheduledQueryLastExecutionStatusFailed       ScheduledQueryLastExecutionStatus = "Failed"
	ScheduledQueryLastExecutionStatusTimeout      ScheduledQueryLastExecutionStatus = "Timeout"
)

type ScheduledQueryState string

const (
	ScheduledQueryStateENABLED  ScheduledQueryState = "ENABLED"
	ScheduledQueryStateDISABLED ScheduledQueryState = "DISABLED"
)

type SubscriptionFilterDistribution string

const (
	SubscriptionFilterDistributionRandom      SubscriptionFilterDistribution = "Random"
	SubscriptionFilterDistributionByLogStream SubscriptionFilterDistribution = "ByLogStream"
)

type ProcessorListToMapFlattenedElement string

const (
	ProcessorListToMapFlattenedElementFirst ProcessorListToMapFlattenedElement = "first"
	ProcessorListToMapFlattenedElementLast  ProcessorListToMapFlattenedElement = "last"
)

type EventSource string

const (
	EventSourceCloudTrail      EventSource = "CloudTrail"
	EventSourceRoute53Resolver EventSource = "Route53Resolver"
	EventSourceVPCFlow         EventSource = "VPCFlow"
	EventSourceEKSAudit        EventSource = "EKSAudit"
	EventSourceAWSWAF          EventSource = "AWSWAF"
)

type OcsfVersion string

const (
	OcsfVersionV11 OcsfVersion = "V1.1"
	OcsfVersionV15 OcsfVersion = "V1.5"
)

type TypeConverterEntryType string

const (
	TypeConverterEntryTypeBoolean TypeConverterEntryType = "boolean"
	TypeConverterEntryTypeInteger TypeConverterEntryType = "integer"
	TypeConverterEntryTypeDouble  TypeConverterEntryType = "double"
	TypeConverterEntryTypeString  TypeConverterEntryType = "string"
)
