// Code generated by go generate; DO NOT EDIT.

package iq

// The iam actions of the aws iq service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionAcceptCall                     = "iq:AcceptCall"
	ActionApprovePaymentRequest          = "iq:ApprovePaymentRequest"
	ActionApproveProposal                = "iq:ApproveProposal"
	ActionArchiveConversation            = "iq:ArchiveConversation"
	ActionCompleteProposal               = "iq:CompleteProposal"
	ActionCreateConversation             = "iq:CreateConversation"
	ActionCreateExpert                   = "iq:CreateExpert"
	ActionCreateListing                  = "iq:CreateListing"
	ActionCreateMilestoneProposal        = "iq:CreateMilestoneProposal"
	ActionCreatePaymentRequest           = "iq:CreatePaymentRequest"
	ActionCreateProject                  = "iq:CreateProject"
	ActionCreateRequest                  = "iq:CreateRequest"
	ActionCreateScheduledProposal        = "iq:CreateScheduledProposal"
	ActionCreateSeller                   = "iq:CreateSeller"
	ActionCreateUpfrontProposal          = "iq:CreateUpfrontProposal"
	ActionDeclineCall                    = "iq:DeclineCall"
	ActionDeleteAttachment               = "iq:DeleteAttachment"
	ActionDisableIndividualPublicProfile = "iq:DisableIndividualPublicProfile"
	ActionDownloadAttachment             = "iq:DownloadAttachment"
	ActionEnableIndividualPublicProfile  = "iq:EnableIndividualPublicProfile"
	ActionEndCall                        = "iq:EndCall"
	ActionGetBuyer                       = "iq:GetBuyer"
	ActionGetCall                        = "iq:GetCall"
	ActionGetChatInfo                    = "iq:GetChatInfo"
	ActionGetChatMessages                = "iq:GetChatMessages"
	ActionGetChatToken                   = "iq:GetChatToken"
	ActionGetCompanyChatMessages         = "iq:GetCompanyChatMessages"
	ActionGetCompanyProfile              = "iq:GetCompanyProfile"
	ActionGetConversation                = "iq:GetConversation"
	ActionGetExpert                      = "iq:GetExpert"
	ActionGetListing                     = "iq:GetListing"
	ActionGetMarketplaceSeller           = "iq:GetMarketplaceSeller"
	ActionGetPaymentRequest              = "iq:GetPaymentRequest"
	ActionGetProposal                    = "iq:GetProposal"
	ActionGetRequest                     = "iq:GetRequest"
	ActionGetReview                      = "iq:GetReview"
	ActionHideRequest                    = "iq:HideRequest"
	ActionInitiateCall                   = "iq:InitiateCall"
	ActionLinkAwsCertification           = "iq:LinkAwsCertification"
	ActionListAttachments                = "iq:ListAttachments"
	ActionListConversations              = "iq:ListConversations"
	ActionListExpertAccessLogs           = "iq:ListExpertAccessLogs"
	ActionListListings                   = "iq:ListListings"
	ActionListPaymentRequests            = "iq:ListPaymentRequests"
	ActionListProposals                  = "iq:ListProposals"
	ActionListRequests                   = "iq:ListRequests"
	ActionListReviews                    = "iq:ListReviews"
	ActionMarkChatMessageRead            = "iq:MarkChatMessageRead"
	ActionRejectPaymentRequest           = "iq:RejectPaymentRequest"
	ActionRejectProposal                 = "iq:RejectProposal"
	ActionSendCompanyChatMessage         = "iq:SendCompanyChatMessage"
	ActionSendIndividualChatMessage      = "iq:SendIndividualChatMessage"
	ActionUnarchiveConversation          = "iq:UnarchiveConversation"
	ActionUnlinkAwsCertification         = "iq:UnlinkAwsCertification"
	ActionUpdateCompanyProfile           = "iq:UpdateCompanyProfile"
	ActionUpdateConversationMembers      = "iq:UpdateConversationMembers"
	ActionUpdateExpert                   = "iq:UpdateExpert"
	ActionUpdateListing                  = "iq:UpdateListing"
	ActionUpdateRequest                  = "iq:UpdateRequest"
	ActionUploadAttachment               = "iq:UploadAttachment"
	ActionWithdrawPaymentRequest         = "iq:WithdrawPaymentRequest"
	ActionWithdrawProposal               = "iq:WithdrawProposal"
	ActionWriteReview                    = "iq:WriteReview"
)

// ActionsList are the list actions, as classified by aws.
var ActionsList = []string{
	ActionListAttachments,
}

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionDownloadAttachment,
	ActionGetBuyer,
	ActionGetCall,
	ActionGetChatInfo,
	ActionGetChatMessages,
	ActionGetChatToken,
	ActionGetCompanyChatMessages,
	ActionGetCompanyProfile,
	ActionGetConversation,
	ActionGetExpert,
	ActionGetListing,
	ActionGetMarketplaceSeller,
	ActionGetPaymentRequest,
	ActionGetProposal,
	ActionGetRequest,
	ActionGetReview,
	ActionListConversations,
	ActionListExpertAccessLogs,
	ActionListListings,
	ActionListPaymentRequests,
	ActionListProposals,
	ActionListRequests,
	ActionListReviews,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionAcceptCall,
	ActionApprovePaymentRequest,
	ActionApproveProposal,
	ActionArchiveConversation,
	ActionCompleteProposal,
	ActionCreateConversation,
	ActionCreateExpert,
	ActionCreateListing,
	ActionCreateMilestoneProposal,
	ActionCreatePaymentRequest,
	ActionCreateProject,
	ActionCreateRequest,
	ActionCreateScheduledProposal,
	ActionCreateSeller,
	ActionCreateUpfrontProposal,
	ActionDeclineCall,
	ActionDeleteAttachment,
	ActionDisableIndividualPublicProfile,
	ActionEnableIndividualPublicProfile,
	ActionEndCall,
	ActionHideRequest,
	ActionInitiateCall,
	ActionLinkAwsCertification,
	ActionMarkChatMessageRead,
	ActionRejectPaymentRequest,
	ActionRejectProposal,
	ActionSendCompanyChatMessage,
	ActionSendIndividualChatMessage,
	ActionUnarchiveConversation,
	ActionUnlinkAwsCertification,
	ActionUpdateCompanyProfile,
	ActionUpdateConversationMembers,
	ActionUpdateExpert,
	ActionUpdateListing,
	ActionUpdateRequest,
	ActionUploadAttachment,
	ActionWithdrawPaymentRequest,
	ActionWithdrawProposal,
	ActionWriteReview,
}
