// Code generated by go generate; DO NOT EDIT.

package monitron

// The iam actions of the aws monitron service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionAssociateProjectAdminUser       = "monitron:AssociateProjectAdminUser"
	ActionCreateProject                   = "monitron:CreateProject"
	ActionCreateProjectUserAssociation    = "monitron:CreateProjectUserAssociation"
	ActionCreateUserAccessRoleAssociation = "monitron:CreateUserAccessRoleAssociation"
	ActionDeleteProject                   = "monitron:DeleteProject"
	ActionDeleteProjectUserAssociation    = "monitron:DeleteProjectUserAssociation"
	ActionDeleteUserAccessRoleAssociation = "monitron:DeleteUserAccessRoleAssociation"
	ActionDisassociateProjectAdminUser    = "monitron:DisassociateProjectAdminUser"
	ActionGetProject                      = "monitron:GetProject"
	ActionGetProjectAdminUser             = "monitron:GetProjectAdminUser"
	ActionListProjectAdminUsers           = "monitron:ListProjectAdminUsers"
	ActionListProjectUserAssociations     = "monitron:ListProjectUserAssociations"
	ActionListProjects                    = "monitron:ListProjects"
	ActionListTagsForResource             = "monitron:ListTagsForResource"
	ActionListUserAccessRoleAssociations  = "monitron:ListUserAccessRoleAssociations"
	ActionTagResource                     = "monitron:TagResource"
	ActionUntagResource                   = "monitron:UntagResource"
	ActionUpdateProject                   = "monitron:UpdateProject"
)

// ActionsList are the list actions, as classified by aws.
var ActionsList = []string{
	ActionListProjectUserAssociations,
	ActionListProjects,
	ActionListUserAccessRoleAssociations,
}

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionGetProject,
	ActionGetProjectAdminUser,
	ActionListTagsForResource,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionCreateProject,
	ActionDeleteProject,
	ActionUpdateProject,
}

// ActionsPermissions are the permissions actions, as classified by aws.
var ActionsPermissions = []string{
	ActionAssociateProjectAdminUser,
	ActionCreateProjectUserAssociation,
	ActionCreateUserAccessRoleAssociation,
	ActionDeleteProjectUserAssociation,
	ActionDeleteUserAccessRoleAssociation,
	ActionDisassociateProjectAdminUser,
	ActionListProjectAdminUsers,
}

// ActionsTagging are the tagging actions, as classified by aws.
var ActionsTagging = []string{
	ActionTagResource,
	ActionUntagResource,
}
