// Code generated by go generate; DO NOT EDIT.

// Package amplifyuibuilder holds the cloud control resources of the aws amplifyuibuilder service.
package amplifyuibuilder

import "encoding/json"

type Predicate struct {
	And         []Predicate `json:"And,omitempty"`
	Field       *string     `json:"Field,omitempty"`
	Operand     *string     `json:"Operand,omitempty"`
	OperandType *string     `json:"OperandType,omitempty"`
	Operator    *string     `json:"Operator,omitempty"`
	Or          []Predicate `json:"Or,omitempty"`
}

type ComponentBindingPropertiesValueProperties struct {
	Bucket        *string     `json:"Bucket,omitempty"`
	DefaultValue  *string     `json:"DefaultValue,omitempty"`
	Field         *string     `json:"Field,omitempty"`
	Key           *string     `json:"Key,omitempty"`
	Model         *string     `json:"Model,omitempty"`
	Predicates    []Predicate `json:"Predicates,omitempty"`
	SlotName      *string     `json:"SlotName,omitempty"`
	UserAttribute *string     `json:"UserAttribute,omitempty"`
}

type ComponentBindingPropertiesValue struct {
	BindingProperties *ComponentBindingPropertiesValueProperties `json:"BindingProperties,omitempty"`
	DefaultValue      *string                                    `json:"DefaultValue,omitempty"`
	Type              *string                                    `json:"Type,omitempty"`
}

type ComponentPropertyBindingProperties struct {
	Field    *string `json:"Field,omitempty"`
	Property *string `json:"Property,omitempty"`
}

type FormBindingElement struct {
	Element  *string `json:"Element,omitempty"`
	Property *string `json:"Property,omitempty"`
}

type ComponentConditionProperty struct {
	Else        *ComponentProperty `json:"Else,omitempty"`
	Field       *string            `json:"Field,omitempty"`
	Operand     *string            `json:"Operand,omitempty"`
	OperandType *string            `json:"OperandType,omitempty"`
	Operator    *string            `json:"Operator,omitempty"`
	Property    *string            `json:"Property,omitempty"`
	Then        *ComponentProperty `json:"Then,omitempty"`
}

type ComponentProperty struct {
	BindingProperties           *ComponentPropertyBindingProperties `json:"BindingProperties,omitempty"`
	Bindings                    map[string]FormBindingElement       `json:"Bindings,omitempty"`
	CollectionBindingProperties *ComponentPropertyBindingProperties `json:"CollectionBindingProperties,omitempty"`
	ComponentName               *string                             `json:"ComponentName,omitempty"`
	Concat                      []ComponentProperty                 `json:"Concat,omitempty"`
	Condition                   *ComponentConditionProperty         `json:"Condition,omitempty"`
	Configured                  *bool                               `json:"Configured,omitempty"`
	DefaultValue                *string                             `json:"DefaultValue,omitempty"`
	Event                       *string                             `json:"Event,omitempty"`
	ImportedValue               *string                             `json:"ImportedValue,omitempty"`
	Model                       *string                             `json:"Model,omitempty"`
	Property                    *string                             `json:"Property,omitempty"`
	Type                        *string                             `json:"Type,omitempty"`
	UserAttribute               *string                             `json:"UserAttribute,omitempty"`
	Value                       *string                             `json:"Value,omitempty"`
}

type MutationActionSetStateParameter struct {
	ComponentName *string            `json:"ComponentName,omitempty"`
	Property      *string            `json:"Property,omitempty"`
	Set           *ComponentProperty `json:"Set,omitempty"`
}

type ActionParameters struct {
	Anchor *ComponentProperty               `json:"Anchor,omitempty"`
	Fields map[string]ComponentProperty     `json:"Fields,omitempty"`
	Global *ComponentProperty               `json:"Global,omitempty"`
	Id     *ComponentProperty               `json:"Id,omitempty"`
	Model  *string                          `json:"Model,omitempty"`
	State  *MutationActionSetStateParameter `json:"State,omitempty"`
	Target *ComponentProperty               `json:"Target,omitempty"`
	Type   *ComponentProperty               `json:"Type,omitempty"`
	Url    *ComponentProperty               `json:"Url,omitempty"`
}

type ComponentEvent struct {
	Action       *string           `json:"Action,omitempty"`
	BindingEvent *string           `json:"BindingEvent,omitempty"`
	Parameters   *ActionParameters `json:"Parameters,omitempty"`
}

type ComponentChild struct {
	Children      []ComponentChild             `json:"Children,omitempty"`
	ComponentType *string                      `json:"ComponentType,omitempty"`
	Events        map[string]ComponentEvent    `json:"Events,omitempty"`
	Name          *string                      `json:"Name,omitempty"`
	Properties    map[string]ComponentProperty `json:"Properties,omitempty"`
	SourceId      *string                      `json:"SourceId,omitempty"`
}

type SortProperty struct {
	Direction *SortDirection `json:"Direction,omitempty"`
	Field     *string        `json:"Field,omitempty"`
}

type ComponentDataConfiguration struct {
	Identifiers []string       `json:"Identifiers,omitempty"`
	Model       *string        `json:"Model,omitempty"`
	Predicate   *Predicate     `json:"Predicate,omitempty"`
	Sort        []SortProperty `json:"Sort,omitempty"`
}

type ComponentVariant struct {
	Overrides     map[string]map[string]string `json:"Overrides,omitempty"`
	VariantValues map[string]string            `json:"VariantValues,omitempty"`
}

type Component struct {
	AppId                *string                                    `json:"AppId,omitempty"`
	BindingProperties    map[string]ComponentBindingPropertiesValue `json:"BindingProperties,omitempty"`
	Children             []ComponentChild                           `json:"Children,omitempty"`
	CollectionProperties map[string]ComponentDataConfiguration      `json:"CollectionProperties,omitempty"`
	ComponentType        *string                                    `json:"ComponentType,omitempty"`
	CreatedAt            *string                                    `json:"CreatedAt,omitempty"`
	EnvironmentName      *string                                    `json:"EnvironmentName,omitempty"`
	Events               map[string]ComponentEvent                  `json:"Events,omitempty"`
	Id                   *string                                    `json:"Id,omitempty"`
	ModifiedAt           *string                                    `json:"ModifiedAt,omitempty"`
	Name                 *string                                    `json:"Name,omitempty"`
	Overrides            map[string]map[string]string               `json:"Overrides,omitempty"`
	Properties           map[string]ComponentProperty               `json:"Properties,omitempty"`
	SchemaVersion        *string                                    `json:"SchemaVersion,omitempty"`
	SourceId             *string                                    `json:"SourceId,omitempty"`
	Tags                 map[string]string                          `json:"Tags,omitempty"`
	Variants             []ComponentVariant                         `json:"Variants,omitempty"`
}

func (Component) CloudJamType() string { return "AWS::AmplifyUIBuilder::Component" }

type FormButton struct {
	Children *string         `json:"Children,omitempty"`
	Excluded *bool           `json:"Excluded,omitempty"`
	Position json.RawMessage `json:"Position,omitempty"`
}

type FormCTA struct {
	Cancel   *FormButton          `json:"Cancel,omitempty"`
	Clear    *FormButton          `json:"Clear,omitempty"`
	Position *FormButtonsPosition `json:"Position,omitempty"`
	Submit   *FormButton          `json:"Submit,omitempty"`
}

type FormDataTypeConfig struct {
	DataSourceType *FormDataSourceType `json:"DataSourceType,omitempty"`
	DataTypeName   *string             `json:"DataTypeName,omitempty"`
}

type FileUploaderFieldConfig struct {
	AcceptedFileTypes []string            `json:"AcceptedFileTypes,omitempty"`
	AccessLevel       *StorageAccessLevel `json:"AccessLevel,omitempty"`
	IsResumable       *bool               `json:"IsResumable,omitempty"`
	MaxFileCount      *float64            `json:"MaxFileCount,omitempty"`
	MaxSize           *float64            `json:"MaxSize,omitempty"`
	ShowThumbnails    *bool               `json:"ShowThumbnails,omitempty"`
}

type FormInputBindingPropertiesValueProperties struct {
	Model *string `json:"Model,omitempty"`
}

type FormInputBindingPropertiesValue struct {
	BindingProperties *FormInputBindingPropertiesValueProperties `json:"BindingProperties,omitempty"`
	Type              *string                                    `json:"Type,omitempty"`
}

type FormInputValuePropertyBindingProperties struct {
	Field    *string `json:"Field,omitempty"`
	Property *string `json:"Property,omitempty"`
}

type FormInputValueProperty struct {
	BindingProperties *FormInputValuePropertyBindingProperties `json:"BindingProperties,omitempty"`
	Concat            []FormInputValueProperty                 `json:"Concat,omitempty"`
	Value             *string                                  `json:"Value,omitempty"`
}

type ValueMapping struct {
	DisplayValue *FormInputValueProperty `json:"DisplayValue,omitempty"`
	Value        *FormInputValueProperty `json:"Value,omitempty"`
}

type ValueMappings struct {
	BindingProperties map[string]FormInputBindingPropertiesValue `json:"BindingProperties,omitempty"`
	Values            []ValueMapping                             `json:"Values,omitempty"`
}

type FieldInputConfig struct {
	DefaultChecked     *bool                    `json:"DefaultChecked,omitempty"`
	DefaultCountryCode *string                  `json:"DefaultCountryCode,omitempty"`
	DefaultValue       *string                  `json:"DefaultValue,omitempty"`
	DescriptiveText    *string                  `json:"DescriptiveText,omitempty"`
	FileUploaderConfig *FileUploaderFieldConfig `json:"FileUploaderConfig,omitempty"`
	IsArray            *bool                    `json:"IsArray,omitempty"`
	MaxValue           *float64                 `json:"MaxValue,omitempty"`
	MinValue           *float64                 `json:"MinValue,omitempty"`
	Name               *string                  `json:"Name,omitempty"`
	Placeholder        *string                  `json:"Placeholder,omitempty"`
	ReadOnly           *bool                    `json:"ReadOnly,omitempty"`
	Required           *bool                    `json:"Required,omitempty"`
	Step               *float64                 `json:"Step,omitempty"`
	Type               *string                  `json:"Type,omitempty"`
	Value              *string                  `json:"Value,omitempty"`
	ValueMappings      *ValueMappings           `json:"ValueMappings,omitempty"`
}

type FieldValidationConfiguration struct {
	NumValues         []float64 `json:"NumValues,omitempty"`
	StrValues         []string  `json:"StrValues,omitempty"`
	Type              *string   `json:"Type,omitempty"`
	ValidationMessage *string   `json:"ValidationMessage,omitempty"`
}

type FieldConfig struct {
	Excluded    *bool                          `json:"Excluded,omitempty"`
	InputType   *FieldInputConfig              `json:"InputType,omitempty"`
	Label       *string                        `json:"Label,omitempty"`
	Position    json.RawMessage                `json:"Position,omitempty"`
	Validations []FieldValidationConfiguration `json:"Validations,omitempty"`
}

type SectionalElement struct {
	Excluded    *bool           `json:"Excluded,omitempty"`
	Level       *float64        `json:"Level,omitempty"`
	Orientation *string         `json:"Orientation,omitempty"`
	Position    json.RawMessage `json:"Position,omitempty"`
	Text        *string         `json:"Text,omitempty"`
	Type        *string         `json:"Type,omitempty"`
}

type FormStyle struct {
	HorizontalGap json.RawMessage `json:"HorizontalGap,omitempty"`
	OuterPadding  json.RawMessage `json:"OuterPadding,omitempty"`
	VerticalGap   json.RawMessage `json:"VerticalGap,omitempty"`
}

type Form struct {
	AppId             *string                     `json:"AppId,omitempty"`
	Cta               *FormCTA                    `json:"Cta,omitempty"`
	DataType          *FormDataTypeConfig         `json:"DataType,omitempty"`
	EnvironmentName   *string                     `json:"EnvironmentName,omitempty"`
	Fields            map[string]FieldConfig      `json:"Fields,omitempty"`
	FormActionType    *FormActionType             `json:"FormActionType,omitempty"`
	Id                *string                     `json:"Id,omitempty"`
	LabelDecorator    *LabelDecorator             `json:"LabelDecorator,omitempty"`
	Name              *string                     `json:"Name,omitempty"`
	SchemaVersion     *string                     `json:"SchemaVersion,omitempty"`
	SectionalElements map[string]SectionalElement `json:"SectionalElements,omitempty"`
	Style             *FormStyle                  `json:"Style,omitempty"`
	Tags              map[string]string           `json:"Tags,omitempty"`
}

func (Form) CloudJamType() string { return "AWS::AmplifyUIBuilder::Form" }

type ThemeValue struct {
	Children []ThemeValues `json:"Children,omitempty"`
	Value    *string       `json:"Value,omitempty"`
}

type ThemeValues struct {
	Key   *string     `json:"Key,omitempty"`
	Value *ThemeValue `json:"Value,omitempty"`
}

type Theme struct {
	AppId           *string           `json:"AppId,omitempty"`
	CreatedAt       *string           `json:"CreatedAt,omitempty"`
	EnvironmentName *string           `json:"EnvironmentName,omitempty"`
	Id              *string           `json:"Id,omitempty"`
	ModifiedAt      *string           `json:"ModifiedAt,omitempty"`
	Name            *string           `json:"Name,omitempty"`
	Overrides       []ThemeValues     `json:"Overrides,omitempty"`
	Tags            map[string]string `json:"Tags,omitempty"`
	Values          []ThemeValues     `json:"Values,omitempty"`
}

func (Theme) CloudJamType() string { return "AWS::AmplifyUIBuilder::Theme" }

type SortDirection string

const (
	SortDirectionASC  SortDirection = "ASC"
	SortDirectionDESC SortDirection = "DESC"
)

type FormButtonsPosition string

const (
	FormButtonsPositionTop          FormButtonsPosition = "top"
	FormButtonsPositionBottom       FormButtonsPosition = "bottom"
	FormButtonsPositionTopAndBottom FormButtonsPosition = "top_and_bottom"
)

type FormDataSourceType string

const (
	FormDataSourceTypeDataStore FormDataSourceType = "DataStore"
	FormDataSourceTypeCustom    FormDataSourceType = "Custom"
)

type StorageAccessLevel string

const (
	StorageAccessLevelPublic    StorageAccessLevel = "public"
	StorageAccessLevelProtected StorageAccessLevel = "protected"
	StorageAccessLevelPrivate   StorageAccessLevel = "private"
)

type FormActionType string

const (
	FormActionTypeCreate FormActionType = "create"
	FormActionTypeUpdate FormActionType = "update"
)

type LabelDecorator string

const (
	LabelDecoratorRequired LabelDecorator = "required"
	LabelDecoratorOptional LabelDecorator = "optional"
	LabelDecoratorNone     LabelDecorator = "none"
)
