// Code generated by go generate; DO NOT EDIT.

package networkmanagerchat

// The iam actions of the aws networkmanager-chat service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionCancelMessageResponse      = "networkmanager-chat:CancelMessageResponse"
	ActionCreateConversation         = "networkmanager-chat:CreateConversation"
	ActionDeleteConversation         = "networkmanager-chat:DeleteConversation"
	ActionListConversationMessages   = "networkmanager-chat:ListConversationMessages"
	ActionListConversations          = "networkmanager-chat:ListConversations"
	ActionNotifyConversationIsActive = "networkmanager-chat:NotifyConversationIsActive"
	ActionSendConversationMessage    = "networkmanager-chat:SendConversationMessage"
)

// ActionsList are the list actions, as classified by aws.
var ActionsList = []string{
	ActionListConversationMessages,
	ActionListConversations,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionCancelMessageResponse,
	ActionCreateConversation,
	ActionDeleteConversation,
	ActionNotifyConversationIsActive,
	ActionSendConversationMessage,
}
