// Code generated by go generate; DO NOT EDIT.

package cases

// The iam actions of the aws cases service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionBatchGetCaseRule          = "cases:BatchGetCaseRule"
	ActionBatchGetField             = "cases:BatchGetField"
	ActionBatchPutFieldOptions      = "cases:BatchPutFieldOptions"
	ActionCreateCase                = "cases:CreateCase"
	ActionCreateCaseRule            = "cases:CreateCaseRule"
	ActionCreateDomain              = "cases:CreateDomain"
	ActionCreateField               = "cases:CreateField"
	ActionCreateLayout              = "cases:CreateLayout"
	ActionCreateRelatedItem         = "cases:CreateRelatedItem"
	ActionCreateTemplate            = "cases:CreateTemplate"
	ActionDeleteCase                = "cases:DeleteCase"
	ActionDeleteCaseRule            = "cases:DeleteCaseRule"
	ActionDeleteDomain              = "cases:DeleteDomain"
	ActionDeleteField               = "cases:DeleteField"
	ActionDeleteLayout              = "cases:DeleteLayout"
	ActionDeleteRelatedItem         = "cases:DeleteRelatedItem"
	ActionDeleteTemplate            = "cases:DeleteTemplate"
	ActionGetCase                   = "cases:GetCase"
	ActionGetCaseAuditEvents        = "cases:GetCaseAuditEvents"
	ActionGetCaseEventConfiguration = "cases:GetCaseEventConfiguration"
	ActionGetDomain                 = "cases:GetDomain"
	ActionGetLayout                 = "cases:GetLayout"
	ActionGetTemplate               = "cases:GetTemplate"
	ActionListCaseRules             = "cases:ListCaseRules"
	ActionListCasesForContact       = "cases:ListCasesForContact"
	ActionListDomains               = "cases:ListDomains"
	ActionListFieldOptions          = "cases:ListFieldOptions"
	ActionListFields                = "cases:ListFields"
	ActionListLayouts               = "cases:ListLayouts"
	ActionListTagsForResource       = "cases:ListTagsForResource"
	ActionListTemplates             = "cases:ListTemplates"
	ActionPutCaseEventConfiguration = "cases:PutCaseEventConfiguration"
	ActionSearchAllRelatedItems     = "cases:SearchAllRelatedItems"
	ActionSearchCases               = "cases:SearchCases"
	ActionSearchRelatedItems        = "cases:SearchRelatedItems"
	ActionTagResource               = "cases:TagResource"
	ActionUntagResource             = "cases:UntagResource"
	ActionUpdateCase                = "cases:UpdateCase"
	ActionUpdateCaseRule            = "cases:UpdateCaseRule"
	ActionUpdateField               = "cases:UpdateField"
	ActionUpdateLayout              = "cases:UpdateLayout"
	ActionUpdateRelatedItem         = "cases:UpdateRelatedItem"
	ActionUpdateTemplate            = "cases:UpdateTemplate"
)

// ActionsList are the list actions, as classified by aws.
var ActionsList = []string{
	ActionListCaseRules,
	ActionListCasesForContact,
	ActionListDomains,
	ActionListFieldOptions,
	ActionListFields,
	ActionListLayouts,
	ActionListTemplates,
}

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionBatchGetCaseRule,
	ActionBatchGetField,
	ActionGetCase,
	ActionGetCaseAuditEvents,
	ActionGetCaseEventConfiguration,
	ActionGetDomain,
	ActionGetLayout,
	ActionGetTemplate,
	ActionListTagsForResource,
	ActionSearchAllRelatedItems,
	ActionSearchCases,
	ActionSearchRelatedItems,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionBatchPutFieldOptions,
	ActionCreateCase,
	ActionCreateCaseRule,
	ActionCreateDomain,
	ActionCreateField,
	ActionCreateLayout,
	ActionCreateRelatedItem,
	ActionCreateTemplate,
	ActionDeleteCase,
	ActionDeleteCaseRule,
	ActionDeleteDomain,
	ActionDeleteField,
	ActionDeleteLayout,
	ActionDeleteRelatedItem,
	ActionDeleteTemplate,
	ActionPutCaseEventConfiguration,
	ActionUpdateCase,
	ActionUpdateCaseRule,
	ActionUpdateField,
	ActionUpdateLayout,
	ActionUpdateRelatedItem,
	ActionUpdateTemplate,
}

// ActionsTagging are the tagging actions, as classified by aws.
var ActionsTagging = []string{
	ActionTagResource,
	ActionUntagResource,
}

// The condition keys of the aws cases service.
const (
	ConditionKeyCreatedBy       = "cases:CreatedBy"
	ConditionKeyRelatedItemType = "cases:RelatedItemType"
	ConditionKeyConnectUserArn  = "connect:UserArn"
)
