// Code generated by go generate; DO NOT EDIT.

// Package kinesisanalyticsv2 holds the cloud control resources of the aws kinesisanalyticsv2 service.
package kinesisanalyticsv2

type S3ContentLocation struct {
	BucketARN     *string `json:"BucketARN,omitempty"`
	FileKey       *string `json:"FileKey,omitempty"`
	ObjectVersion *string `json:"ObjectVersion,omitempty"`
}

type CodeContent struct {
	S3ContentLocation *S3ContentLocation `json:"S3ContentLocation,omitempty"`
	TextContent       *string            `json:"TextContent,omitempty"`
	ZipFileContent    *string            `json:"ZipFileContent,omitempty"`
}

type ApplicationCodeConfiguration struct {
	CodeContent     *CodeContent `json:"CodeContent,omitempty"`
	CodeContentType *string      `json:"CodeContentType,omitempty"`
}

type ApplicationEncryptionConfiguration struct {
	KeyId   *string `json:"KeyId,omitempty"`
	KeyType *string `json:"KeyType,omitempty"`
}

type ApplicationSnapshotConfiguration struct {
	SnapshotsEnabled *bool `json:"SnapshotsEnabled,omitempty"`
}

type ApplicationSystemRollbackConfiguration struct {
	RollbackEnabled *bool `json:"RollbackEnabled,omitempty"`
}

type PropertyGroup struct {
	PropertyGroupId *string           `json:"PropertyGroupId,omitempty"`
	PropertyMap     map[string]string `json:"PropertyMap,omitempty"`
}

type EnvironmentProperties struct {
	PropertyGroups []PropertyGroup `json:"PropertyGroups,omitempty"`
}

type CheckpointConfiguration struct {
	CheckpointInterval         *int    `json:"CheckpointInterval,omitempty"`
	CheckpointingEnabled       *bool   `json:"CheckpointingEnabled,omitempty"`
	ConfigurationType          *string `json:"ConfigurationType,omitempty"`
	MinPauseBetweenCheckpoints *int    `json:"MinPauseBetweenCheckpoints,omitempty"`
}

type MonitoringConfiguration struct {
	ConfigurationType *string `json:"ConfigurationType,omitempty"`
	LogLevel          *string `json:"LogLevel,omitempty"`
	MetricsLevel      *string `json:"MetricsLevel,omitempty"`
}

type ParallelismConfiguration struct {
	AutoScalingEnabled *bool   `json:"AutoScalingEnabled,omitempty"`
	ConfigurationType  *string `json:"ConfigurationType,omitempty"`
	Parallelism        *int    `json:"Parallelism,omitempty"`
	ParallelismPerKPU  *int    `json:"ParallelismPerKPU,omitempty"`
}

type FlinkApplicationConfiguration struct {
	CheckpointConfiguration  *CheckpointConfiguration  `json:"CheckpointConfiguration,omitempty"`
	MonitoringConfiguration  *MonitoringConfiguration  `json:"MonitoringConfiguration,omitempty"`
	ParallelismConfiguration *ParallelismConfiguration `json:"ParallelismConfiguration,omitempty"`
}

type InputParallelism struct {
	Count *int `json:"Count,omitempty"`
}

type InputLambdaProcessor struct {
	ResourceARN *string `json:"ResourceARN,omitempty"`
}

type InputProcessingConfiguration struct {
	InputLambdaProcessor *InputLambdaProcessor `json:"InputLambdaProcessor,omitempty"`
}

type RecordColumn struct {
	Mapping *string `json:"Mapping,omitempty"`
	Name    *string `json:"Name,omitempty"`
	SqlType *string `json:"SqlType,omitempty"`
}

type CSVMappingParameters struct {
	RecordColumnDelimiter *string `json:"RecordColumnDelimiter,omitempty"`
	RecordRowDelimiter    *string `json:"RecordRowDelimiter,omitempty"`
}

type JSONMappingParameters struct {
	RecordRowPath *string `json:"RecordRowPath,omitempty"`
}

type MappingParameters struct {
	CSVMappingParameters  *CSVMappingParameters  `json:"CSVMappingParameters,omitempty"`
	JSONMappingParameters *JSONMappingParameters `json:"JSONMappingParameters,omitempty"`
}

type RecordFormat struct {
	MappingParameters *MappingParameters `json:"MappingParameters,omitempty"`
	RecordFormatType  *string            `json:"RecordFormatType,omitempty"`
}

type InputSchema struct {
	RecordColumns  []RecordColumn `json:"RecordColumns,omitempty"`
	RecordEncoding *string        `json:"RecordEncoding,omitempty"`
	RecordFormat   *RecordFormat  `json:"RecordFormat,omitempty"`
}

type KinesisFirehoseInput struct {
	ResourceARN *string `json:"ResourceARN,omitempty"`
}

type KinesisStreamsInput struct {
	ResourceARN *string `json:"ResourceARN,omitempty"`
}

type Input struct {
	InputParallelism             *InputParallelism             `json:"InputParallelism,omitempty"`
	InputProcessingConfiguration *InputProcessingConfiguration `json:"InputProcessingConfiguration,omitempty"`
	InputSchema                  *InputSchema                  `json:"InputSchema,omitempty"`
	KinesisFirehoseInput         *KinesisFirehoseInput         `json:"KinesisFirehoseInput,omitempty"`
	KinesisStreamsInput          *KinesisStreamsInput          `json:"KinesisStreamsInput,omitempty"`
	NamePrefix                   *string                       `json:"NamePrefix,omitempty"`
}

type SqlApplicationConfiguration struct {
	Inputs []Input `json:"Inputs,omitempty"`
}

type VpcConfiguration struct {
	SecurityGroupIds []string `json:"SecurityGroupIds,omitempty"`
	SubnetIds        []string `json:"SubnetIds,omitempty"`
}

type GlueDataCatalogConfiguration struct {
	DatabaseARN *string `json:"DatabaseARN,omitempty"`
}

type CatalogConfiguration struct {
	GlueDataCatalogConfiguration *GlueDataCatalogConfiguration `json:"GlueDataCatalogConfiguration,omitempty"`
}

type MavenReference struct {
	ArtifactId *string `json:"ArtifactId,omitempty"`
	GroupId    *string `json:"GroupId,omitempty"`
	Version    *string `json:"Version,omitempty"`
}

type CustomArtifactConfiguration struct {
	ArtifactType      *string            `json:"ArtifactType,omitempty"`
	MavenReference    *MavenReference    `json:"MavenReference,omitempty"`
	S3ContentLocation *S3ContentLocation `json:"S3ContentLocation,omitempty"`
}

type S3ContentBaseLocation struct {
	BasePath  *string `json:"BasePath,omitempty"`
	BucketARN *string `json:"BucketARN,omitempty"`
}

type DeployAsApplicationConfiguration struct {
	S3ContentLocation *S3ContentBaseLocation `json:"S3ContentLocation,omitempty"`
}

type ZeppelinMonitoringConfiguration struct {
	LogLevel *string `json:"LogLevel,omitempty"`
}

type ZeppelinApplicationConfiguration struct {
	CatalogConfiguration             *CatalogConfiguration             `json:"CatalogConfiguration,omitempty"`
	CustomArtifactsConfiguration     []CustomArtifactConfiguration     `json:"CustomArtifactsConfiguration,omitempty"`
	DeployAsApplicationConfiguration *DeployAsApplicationConfiguration `json:"DeployAsApplicationConfiguration,omitempty"`
	MonitoringConfiguration          *ZeppelinMonitoringConfiguration  `json:"MonitoringConfiguration,omitempty"`
}

type ApplicationConfiguration struct {
	ApplicationCodeConfiguration           *ApplicationCodeConfiguration           `json:"ApplicationCodeConfiguration,omitempty"`
	ApplicationEncryptionConfiguration     *ApplicationEncryptionConfiguration     `json:"ApplicationEncryptionConfiguration,omitempty"`
	ApplicationSnapshotConfiguration       *ApplicationSnapshotConfiguration       `json:"ApplicationSnapshotConfiguration,omitempty"`
	ApplicationSystemRollbackConfiguration *ApplicationSystemRollbackConfiguration `json:"ApplicationSystemRollbackConfiguration,omitempty"`
	EnvironmentProperties                  *EnvironmentProperties                  `json:"EnvironmentProperties,omitempty"`
	FlinkApplicationConfiguration          *FlinkApplicationConfiguration          `json:"FlinkApplicationConfiguration,omitempty"`
	SqlApplicationConfiguration            *SqlApplicationConfiguration            `json:"SqlApplicationConfiguration,omitempty"`
	VpcConfigurations                      []VpcConfiguration                      `json:"VpcConfigurations,omitempty"`
	ZeppelinApplicationConfiguration       *ZeppelinApplicationConfiguration       `json:"ZeppelinApplicationConfiguration,omitempty"`
}

type ApplicationMaintenanceConfiguration struct {
	ApplicationMaintenanceWindowStartTime *string `json:"ApplicationMaintenanceWindowStartTime,omitempty"`
}

type ApplicationRestoreConfiguration struct {
	ApplicationRestoreType *string `json:"ApplicationRestoreType,omitempty"`
	SnapshotName           *string `json:"SnapshotName,omitempty"`
}

type FlinkRunConfiguration struct {
	AllowNonRestoredState *bool `json:"AllowNonRestoredState,omitempty"`
}

type RunConfiguration struct {
	ApplicationRestoreConfiguration *ApplicationRestoreConfiguration `json:"ApplicationRestoreConfiguration,omitempty"`
	FlinkRunConfiguration           *FlinkRunConfiguration           `json:"FlinkRunConfiguration,omitempty"`
}

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Application struct {
	ApplicationConfiguration            *ApplicationConfiguration            `json:"ApplicationConfiguration,omitempty"`
	ApplicationDescription              *string                              `json:"ApplicationDescription,omitempty"`
	ApplicationMaintenanceConfiguration *ApplicationMaintenanceConfiguration `json:"ApplicationMaintenanceConfiguration,omitempty"`
	ApplicationMode                     *string                              `json:"ApplicationMode,omitempty"`
	ApplicationName                     *string                              `json:"ApplicationName,omitempty"`
	RunConfiguration                    *RunConfiguration                    `json:"RunConfiguration,omitempty"`
	RuntimeEnvironment                  *string                              `json:"RuntimeEnvironment,omitempty"`
	ServiceExecutionRole                *string                              `json:"ServiceExecutionRole,omitempty"`
	Tags                                []Tag                                `json:"Tags,omitempty"`
}

func (Application) CloudControlType() string { return "AWS::KinesisAnalyticsV2::Application" }

type CloudWatchLoggingOption struct {
	LogStreamARN *string `json:"LogStreamARN,omitempty"`
}

type ApplicationCloudWatchLoggingOption struct {
	ApplicationName         *string                  `json:"ApplicationName,omitempty"`
	CloudWatchLoggingOption *CloudWatchLoggingOption `json:"CloudWatchLoggingOption,omitempty"`
	Id                      *string                  `json:"Id,omitempty"`
}

func (ApplicationCloudWatchLoggingOption) CloudControlType() string {
	return "AWS::KinesisAnalyticsV2::ApplicationCloudWatchLoggingOption"
}

type DestinationSchema struct {
	RecordFormatType *string `json:"RecordFormatType,omitempty"`
}

type KinesisFirehoseOutput struct {
	ResourceARN *string `json:"ResourceARN,omitempty"`
}

type KinesisStreamsOutput struct {
	ResourceARN *string `json:"ResourceARN,omitempty"`
}

type LambdaOutput struct {
	ResourceARN *string `json:"ResourceARN,omitempty"`
}

type Output struct {
	DestinationSchema     *DestinationSchema     `json:"DestinationSchema,omitempty"`
	KinesisFirehoseOutput *KinesisFirehoseOutput `json:"KinesisFirehoseOutput,omitempty"`
	KinesisStreamsOutput  *KinesisStreamsOutput  `json:"KinesisStreamsOutput,omitempty"`
	LambdaOutput          *LambdaOutput          `json:"LambdaOutput,omitempty"`
	Name                  *string                `json:"Name,omitempty"`
}

type ApplicationOutput struct {
	ApplicationName *string `json:"ApplicationName,omitempty"`
	Id              *string `json:"Id,omitempty"`
	Output          *Output `json:"Output,omitempty"`
}

func (ApplicationOutput) CloudControlType() string {
	return "AWS::KinesisAnalyticsV2::ApplicationOutput"
}

type ApplicationReferenceDataSourceRecordColumn struct {
	Mapping *string `json:"Mapping,omitempty"`
	Name    *string `json:"Name,omitempty"`
	SqlType *string `json:"SqlType,omitempty"`
}

type ApplicationReferenceDataSourceCSVMappingParameters struct {
	RecordColumnDelimiter *string `json:"RecordColumnDelimiter,omitempty"`
	RecordRowDelimiter    *string `json:"RecordRowDelimiter,omitempty"`
}

type ApplicationReferenceDataSourceJSONMappingParameters struct {
	RecordRowPath *string `json:"RecordRowPath,omitempty"`
}

type ApplicationReferenceDataSourceMappingParameters struct {
	CSVMappingParameters  *ApplicationReferenceDataSourceCSVMappingParameters  `json:"CSVMappingParameters,omitempty"`
	JSONMappingParameters *ApplicationReferenceDataSourceJSONMappingParameters `json:"JSONMappingParameters,omitempty"`
}

type ApplicationReferenceDataSourceRecordFormat struct {
	MappingParameters *ApplicationReferenceDataSourceMappingParameters `json:"MappingParameters,omitempty"`
	RecordFormatType  *string                                          `json:"RecordFormatType,omitempty"`
}

type ReferenceSchema struct {
	RecordColumns  []ApplicationReferenceDataSourceRecordColumn `json:"RecordColumns,omitempty"`
	RecordEncoding *string                                      `json:"RecordEncoding,omitempty"`
	RecordFormat   *ApplicationReferenceDataSourceRecordFormat  `json:"RecordFormat,omitempty"`
}

type S3ReferenceDataSource struct {
	BucketARN *string `json:"BucketARN,omitempty"`
	FileKey   *string `json:"FileKey,omitempty"`
}

type ReferenceDataSource struct {
	ReferenceSchema       *ReferenceSchema       `json:"ReferenceSchema,omitempty"`
	S3ReferenceDataSource *S3ReferenceDataSource `json:"S3ReferenceDataSource,omitempty"`
	TableName             *string                `json:"TableName,omitempty"`
}

type ApplicationReferenceDataSource struct {
	ApplicationName     *string              `json:"ApplicationName,omitempty"`
	Id                  *string              `json:"Id,omitempty"`
	ReferenceDataSource *ReferenceDataSource `json:"ReferenceDataSource,omitempty"`
}

func (ApplicationReferenceDataSource) CloudControlType() string {
	return "AWS::KinesisAnalyticsV2::ApplicationReferenceDataSource"
}
