// Code generated by go generate; DO NOT EDIT.

package pcaconnectorad

// The iam actions of the aws pca-connector-ad service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionCreateConnector                       = "pca-connector-ad:CreateConnector"
	ActionCreateDirectoryRegistration           = "pca-connector-ad:CreateDirectoryRegistration"
	ActionCreateServicePrincipalName            = "pca-connector-ad:CreateServicePrincipalName"
	ActionCreateTemplate                        = "pca-connector-ad:CreateTemplate"
	ActionCreateTemplateGroupAccessControlEntry = "pca-connector-ad:CreateTemplateGroupAccessControlEntry"
	ActionDeleteConnector                       = "pca-connector-ad:DeleteConnector"
	ActionDeleteDirectoryRegistration           = "pca-connector-ad:DeleteDirectoryRegistration"
	ActionDeleteServicePrincipalName            = "pca-connector-ad:DeleteServicePrincipalName"
	ActionDeleteTemplate                        = "pca-connector-ad:DeleteTemplate"
	ActionDeleteTemplateGroupAccessControlEntry = "pca-connector-ad:DeleteTemplateGroupAccessControlEntry"
	ActionGetConnector                          = "pca-connector-ad:GetConnector"
	ActionGetDirectoryRegistration              = "pca-connector-ad:GetDirectoryRegistration"
	ActionGetServicePrincipalName               = "pca-connector-ad:GetServicePrincipalName"
	ActionGetTemplate                           = "pca-connector-ad:GetTemplate"
	ActionGetTemplateGroupAccessControlEntry    = "pca-connector-ad:GetTemplateGroupAccessControlEntry"
	ActionListConnectors                        = "pca-connector-ad:ListConnectors"
	ActionListDirectoryRegistrations            = "pca-connector-ad:ListDirectoryRegistrations"
	ActionListServicePrincipalNames             = "pca-connector-ad:ListServicePrincipalNames"
	ActionListTagsForResource                   = "pca-connector-ad:ListTagsForResource"
	ActionListTemplateGroupAccessControlEntries = "pca-connector-ad:ListTemplateGroupAccessControlEntries"
	ActionListTemplates                         = "pca-connector-ad:ListTemplates"
	ActionTagResource                           = "pca-connector-ad:TagResource"
	ActionUntagResource                         = "pca-connector-ad:UntagResource"
	ActionUpdateTemplate                        = "pca-connector-ad:UpdateTemplate"
	ActionUpdateTemplateGroupAccessControlEntry = "pca-connector-ad:UpdateTemplateGroupAccessControlEntry"
)

// ActionsList are the list actions, as classified by aws.
var ActionsList = []string{
	ActionListConnectors,
	ActionListDirectoryRegistrations,
	ActionListServicePrincipalNames,
	ActionListTemplateGroupAccessControlEntries,
	ActionListTemplates,
}

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionGetConnector,
	ActionGetDirectoryRegistration,
	ActionGetServicePrincipalName,
	ActionGetTemplate,
	ActionGetTemplateGroupAccessControlEntry,
	ActionListTagsForResource,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionCreateConnector,
	ActionCreateDirectoryRegistration,
	ActionCreateServicePrincipalName,
	ActionCreateTemplate,
	ActionCreateTemplateGroupAccessControlEntry,
	ActionDeleteConnector,
	ActionDeleteDirectoryRegistration,
	ActionDeleteServicePrincipalName,
	ActionDeleteTemplate,
	ActionDeleteTemplateGroupAccessControlEntry,
	ActionUpdateTemplate,
	ActionUpdateTemplateGroupAccessControlEntry,
}

// ActionsTagging are the tagging actions, as classified by aws.
var ActionsTagging = []string{
	ActionTagResource,
	ActionUntagResource,
}
