// Code generated by go generate; DO NOT EDIT.

package ssmincidents

// The iam actions of the aws ssm-incidents service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionBatchGetIncidentFindings = "ssm-incidents:BatchGetIncidentFindings"
	ActionCreateReplicationSet     = "ssm-incidents:CreateReplicationSet"
	ActionCreateResponsePlan       = "ssm-incidents:CreateResponsePlan"
	ActionCreateTimelineEvent      = "ssm-incidents:CreateTimelineEvent"
	ActionDeleteIncidentRecord     = "ssm-incidents:DeleteIncidentRecord"
	ActionDeleteReplicationSet     = "ssm-incidents:DeleteReplicationSet"
	ActionDeleteResourcePolicy     = "ssm-incidents:DeleteResourcePolicy"
	ActionDeleteResponsePlan       = "ssm-incidents:DeleteResponsePlan"
	ActionDeleteTimelineEvent      = "ssm-incidents:DeleteTimelineEvent"
	ActionGetIncidentRecord        = "ssm-incidents:GetIncidentRecord"
	ActionGetReplicationSet        = "ssm-incidents:GetReplicationSet"
	ActionGetResourcePolicies      = "ssm-incidents:GetResourcePolicies"
	ActionGetResponsePlan          = "ssm-incidents:GetResponsePlan"
	ActionGetTimelineEvent         = "ssm-incidents:GetTimelineEvent"
	ActionListIncidentFindings     = "ssm-incidents:ListIncidentFindings"
	ActionListIncidentRecords      = "ssm-incidents:ListIncidentRecords"
	ActionListRelatedItems         = "ssm-incidents:ListRelatedItems"
	ActionListReplicationSets      = "ssm-incidents:ListReplicationSets"
	ActionListResponsePlans        = "ssm-incidents:ListResponsePlans"
	ActionListTagsForResource      = "ssm-incidents:ListTagsForResource"
	ActionListTimelineEvents       = "ssm-incidents:ListTimelineEvents"
	ActionPutResourcePolicy        = "ssm-incidents:PutResourcePolicy"
	ActionStartIncident            = "ssm-incidents:StartIncident"
	ActionTagResource              = "ssm-incidents:TagResource"
	ActionUntagResource            = "ssm-incidents:UntagResource"
	ActionUpdateDeletionProtection = "ssm-incidents:UpdateDeletionProtection"
	ActionUpdateIncidentRecord     = "ssm-incidents:UpdateIncidentRecord"
	ActionUpdateRelatedItems       = "ssm-incidents:UpdateRelatedItems"
	ActionUpdateReplicationSet     = "ssm-incidents:UpdateReplicationSet"
	ActionUpdateResponsePlan       = "ssm-incidents:UpdateResponsePlan"
	ActionUpdateTimelineEvent      = "ssm-incidents:UpdateTimelineEvent"
)

// ActionsList are the list actions, as classified by aws.
var ActionsList = []string{
	ActionListIncidentFindings,
	ActionListIncidentRecords,
	ActionListRelatedItems,
	ActionListReplicationSets,
	ActionListResponsePlans,
	ActionListTimelineEvents,
}

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionBatchGetIncidentFindings,
	ActionGetIncidentRecord,
	ActionGetReplicationSet,
	ActionGetResourcePolicies,
	ActionGetResponsePlan,
	ActionGetTimelineEvent,
	ActionListTagsForResource,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionCreateReplicationSet,
	ActionCreateResponsePlan,
	ActionCreateTimelineEvent,
	ActionDeleteIncidentRecord,
	ActionDeleteReplicationSet,
	ActionDeleteResponsePlan,
	ActionDeleteTimelineEvent,
	ActionStartIncident,
	ActionUpdateDeletionProtection,
	ActionUpdateIncidentRecord,
	ActionUpdateRelatedItems,
	ActionUpdateReplicationSet,
	ActionUpdateResponsePlan,
	ActionUpdateTimelineEvent,
}

// ActionsPermissions are the permissions actions, as classified by aws.
var ActionsPermissions = []string{
	ActionDeleteResourcePolicy,
	ActionPutResourcePolicy,
}

// ActionsTagging are the tagging actions, as classified by aws.
var ActionsTagging = []string{
	ActionTagResource,
	ActionUntagResource,
}
