// Code generated by go generate; DO NOT EDIT.

// Package servicecatalogappregistry holds the cloud control resources of the aws servicecatalogappregistry service.
package servicecatalogappregistry

type Application struct {
	ApplicationName     *string           `json:"ApplicationName,omitempty"`
	ApplicationTagKey   *string           `json:"ApplicationTagKey,omitempty"`
	ApplicationTagValue *string           `json:"ApplicationTagValue,omitempty"`
	Arn                 *string           `json:"Arn,omitempty"`
	Description         *string           `json:"Description,omitempty"`
	Id                  *string           `json:"Id,omitempty"`
	Name                *string           `json:"Name,omitempty"`
	Tags                map[string]string `json:"Tags,omitempty"`
}

func (Application) CloudControlType() string { return "AWS::ServiceCatalogAppRegistry::Application" }

type AttributeGroup struct {
	Arn         *string           `json:"Arn,omitempty"`
	Attributes  map[string]any    `json:"Attributes,omitempty"`
	Description *string           `json:"Description,omitempty"`
	Id          *string           `json:"Id,omitempty"`
	Name        *string           `json:"Name,omitempty"`
	Tags        map[string]string `json:"Tags,omitempty"`
}

func (AttributeGroup) CloudControlType() string {
	return "AWS::ServiceCatalogAppRegistry::AttributeGroup"
}

type AttributeGroupAssociation struct {
	Application       *string `json:"Application,omitempty"`
	ApplicationArn    *string `json:"ApplicationArn,omitempty"`
	AttributeGroup    *string `json:"AttributeGroup,omitempty"`
	AttributeGroupArn *string `json:"AttributeGroupArn,omitempty"`
}

func (AttributeGroupAssociation) CloudControlType() string {
	return "AWS::ServiceCatalogAppRegistry::AttributeGroupAssociation"
}

type ResourceAssociation struct {
	Application    *string `json:"Application,omitempty"`
	ApplicationArn *string `json:"ApplicationArn,omitempty"`
	Resource       *string `json:"Resource,omitempty"`
	ResourceArn    *string `json:"ResourceArn,omitempty"`
	ResourceType   *string `json:"ResourceType,omitempty"`
}

func (ResourceAssociation) CloudControlType() string {
	return "AWS::ServiceCatalogAppRegistry::ResourceAssociation"
}
