// Code generated by go generate; DO NOT EDIT.

// Package opensearchservice holds the cloud control resources of the aws opensearchservice service.
package opensearchservice

import "encoding/json"

type AppConfig struct {
	Key   *AppConfigType `json:"Key,omitempty"`
	Value *string        `json:"Value,omitempty"`
}

type DataSource struct {
	DataSourceArn         json.RawMessage `json:"DataSourceArn,omitempty"`
	DataSourceDescription *string         `json:"DataSourceDescription,omitempty"`
}

type ApplicationIamIdentityCenterOptions struct {
	Enabled                                *bool           `json:"Enabled,omitempty"`
	IamIdentityCenterInstanceArn           json.RawMessage `json:"IamIdentityCenterInstanceArn,omitempty"`
	IamRoleForIdentityCenterApplicationArn *string         `json:"IamRoleForIdentityCenterApplicationArn,omitempty"`
}

type Tag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type Application struct {
	AppConfigs               []AppConfig                          `json:"AppConfigs,omitempty"`
	Arn                      *string                              `json:"Arn,omitempty"`
	DataSources              []DataSource                         `json:"DataSources,omitempty"`
	Endpoint                 *string                              `json:"Endpoint,omitempty"`
	IamIdentityCenterOptions *ApplicationIamIdentityCenterOptions `json:"IamIdentityCenterOptions,omitempty"`
	Id                       *string                              `json:"Id,omitempty"`
	KmsKeyArn                *string                              `json:"KmsKeyArn,omitempty"`
	Name                     *string                              `json:"Name,omitempty"`
	Tags                     []Tag                                `json:"Tags,omitempty"`
}

func (Application) CloudJamType() string { return "AWS::OpenSearchService::Application" }

type S3VectorsEngine struct {
	Enabled *bool `json:"Enabled,omitempty"`
}

type ServerlessVectorAcceleration struct {
	Enabled *bool `json:"Enabled,omitempty"`
}

type AIMLOptions struct {
	S3VectorsEngine              *S3VectorsEngine              `json:"S3VectorsEngine,omitempty"`
	ServerlessVectorAcceleration *ServerlessVectorAcceleration `json:"ServerlessVectorAcceleration,omitempty"`
}

type IAMFederationOptions struct {
	Enabled    *bool   `json:"Enabled,omitempty"`
	RolesKey   *string `json:"RolesKey,omitempty"`
	SubjectKey *string `json:"SubjectKey,omitempty"`
}

type JWTOptions struct {
	Enabled    *bool   `json:"Enabled,omitempty"`
	PublicKey  *string `json:"PublicKey,omitempty"`
	RolesKey   *string `json:"RolesKey,omitempty"`
	SubjectKey *string `json:"SubjectKey,omitempty"`
}

type MasterUserOptions struct {
	MasterUserARN      *string `json:"MasterUserARN,omitempty"`
	MasterUserName     *string `json:"MasterUserName,omitempty"`
	MasterUserPassword *string `json:"MasterUserPassword,omitempty"`
}

type Idp struct {
	EntityId        *string `json:"EntityId,omitempty"`
	MetadataContent *string `json:"MetadataContent,omitempty"`
}

type SAMLOptions struct {
	Enabled               *bool   `json:"Enabled,omitempty"`
	Idp                   *Idp    `json:"Idp,omitempty"`
	MasterBackendRole     *string `json:"MasterBackendRole,omitempty"`
	MasterUserName        *string `json:"MasterUserName,omitempty"`
	RolesKey              *string `json:"RolesKey,omitempty"`
	SessionTimeoutMinutes *int    `json:"SessionTimeoutMinutes,omitempty"`
	SubjectKey            *string `json:"SubjectKey,omitempty"`
}

type AdvancedSecurityOptionsInput struct {
	AnonymousAuthDisableDate    *string               `json:"AnonymousAuthDisableDate,omitempty"`
	AnonymousAuthEnabled        *bool                 `json:"AnonymousAuthEnabled,omitempty"`
	Enabled                     *bool                 `json:"Enabled,omitempty"`
	IAMFederationOptions        *IAMFederationOptions `json:"IAMFederationOptions,omitempty"`
	InternalUserDatabaseEnabled *bool                 `json:"InternalUserDatabaseEnabled,omitempty"`
	JWTOptions                  *JWTOptions           `json:"JWTOptions,omitempty"`
	MasterUserOptions           *MasterUserOptions    `json:"MasterUserOptions,omitempty"`
	SAMLOptions                 *SAMLOptions          `json:"SAMLOptions,omitempty"`
}

type AutomatedSnapshotPauseOptions struct {
	Enabled   *bool   `json:"Enabled,omitempty"`
	EndTime   *string `json:"EndTime,omitempty"`
	StartTime *string `json:"StartTime,omitempty"`
}

type ColdStorageOptions struct {
	Enabled *bool `json:"Enabled,omitempty"`
}

type NodeConfig struct {
	Count   *int    `json:"Count,omitempty"`
	Enabled *bool   `json:"Enabled,omitempty"`
	Type    *string `json:"Type,omitempty"`
}

type NodeOption struct {
	NodeConfig *NodeConfig         `json:"NodeConfig,omitempty"`
	NodeType   *NodeOptionNodeType `json:"NodeType,omitempty"`
}

type ZoneAwarenessConfig struct {
	AvailabilityZoneCount *int `json:"AvailabilityZoneCount,omitempty"`
}

type ClusterConfig struct {
	ColdStorageOptions        *ColdStorageOptions  `json:"ColdStorageOptions,omitempty"`
	DedicatedMasterCount      *int                 `json:"DedicatedMasterCount,omitempty"`
	DedicatedMasterEnabled    *bool                `json:"DedicatedMasterEnabled,omitempty"`
	DedicatedMasterType       *string              `json:"DedicatedMasterType,omitempty"`
	InstanceCount             *int                 `json:"InstanceCount,omitempty"`
	InstanceType              *string              `json:"InstanceType,omitempty"`
	MultiAZWithStandbyEnabled *bool                `json:"MultiAZWithStandbyEnabled,omitempty"`
	NodeOptions               []NodeOption         `json:"NodeOptions,omitempty"`
	WarmCount                 *int                 `json:"WarmCount,omitempty"`
	WarmEnabled               *bool                `json:"WarmEnabled,omitempty"`
	WarmType                  *string              `json:"WarmType,omitempty"`
	ZoneAwarenessConfig       *ZoneAwarenessConfig `json:"ZoneAwarenessConfig,omitempty"`
	ZoneAwarenessEnabled      *bool                `json:"ZoneAwarenessEnabled,omitempty"`
}

type CognitoOptions struct {
	Enabled        *bool   `json:"Enabled,omitempty"`
	IdentityPoolId *string `json:"IdentityPoolId,omitempty"`
	RoleArn        *string `json:"RoleArn,omitempty"`
	UserPoolId     *string `json:"UserPoolId,omitempty"`
}

type DeploymentStrategyOptions struct {
	DeploymentStrategy *DeploymentStrategyOptionsDeploymentStrategy `json:"DeploymentStrategy,omitempty"`
}

type DomainEndpointOptions struct {
	CustomEndpoint               *string `json:"CustomEndpoint,omitempty"`
	CustomEndpointCertificateArn *string `json:"CustomEndpointCertificateArn,omitempty"`
	CustomEndpointEnabled        *bool   `json:"CustomEndpointEnabled,omitempty"`
	EnforceHTTPS                 *bool   `json:"EnforceHTTPS,omitempty"`
	TLSSecurityPolicy            *string `json:"TLSSecurityPolicy,omitempty"`
}

type EBSOptions struct {
	EBSEnabled *bool   `json:"EBSEnabled,omitempty"`
	Iops       *int    `json:"Iops,omitempty"`
	Throughput *int    `json:"Throughput,omitempty"`
	VolumeSize *int    `json:"VolumeSize,omitempty"`
	VolumeType *string `json:"VolumeType,omitempty"`
}

type EncryptionAtRestOptions struct {
	Enabled  *bool   `json:"Enabled,omitempty"`
	KmsKeyId *string `json:"KmsKeyId,omitempty"`
}

type IdentityCenterOptions struct {
	EnabledAPIAccess             *bool              `json:"EnabledAPIAccess,omitempty"`
	IdentityCenterApplicationARN *string            `json:"IdentityCenterApplicationARN,omitempty"`
	IdentityCenterInstanceARN    *string            `json:"IdentityCenterInstanceARN,omitempty"`
	IdentityStoreId              *string            `json:"IdentityStoreId,omitempty"`
	RolesKey                     *RolesKeyIdcType   `json:"RolesKey,omitempty"`
	SubjectKey                   *SubjectKeyIdcType `json:"SubjectKey,omitempty"`
}

type LogPublishingOption struct {
	CloudWatchLogsLogGroupArn *string `json:"CloudWatchLogsLogGroupArn,omitempty"`
	Enabled                   *bool   `json:"Enabled,omitempty"`
}

type NodeToNodeEncryptionOptions struct {
	Enabled *bool `json:"Enabled,omitempty"`
}

type WindowStartTime struct {
	Hours   *int `json:"Hours,omitempty"`
	Minutes *int `json:"Minutes,omitempty"`
}

type OffPeakWindow struct {
	WindowStartTime *WindowStartTime `json:"WindowStartTime,omitempty"`
}

type OffPeakWindowOptions struct {
	Enabled       *bool          `json:"Enabled,omitempty"`
	OffPeakWindow *OffPeakWindow `json:"OffPeakWindow,omitempty"`
}

type ServiceSoftwareOptions struct {
	AutomatedUpdateDate *string `json:"AutomatedUpdateDate,omitempty"`
	Cancellable         *bool   `json:"Cancellable,omitempty"`
	CurrentVersion      *string `json:"CurrentVersion,omitempty"`
	Description         *string `json:"Description,omitempty"`
	NewVersion          *string `json:"NewVersion,omitempty"`
	OptionalDeployment  *bool   `json:"OptionalDeployment,omitempty"`
	UpdateAvailable     *bool   `json:"UpdateAvailable,omitempty"`
	UpdateStatus        *string `json:"UpdateStatus,omitempty"`
}

type SnapshotOptions struct {
	AutomatedSnapshotStartHour *int `json:"AutomatedSnapshotStartHour,omitempty"`
}

type SoftwareUpdateOptions struct {
	AutoSoftwareUpdateEnabled *bool `json:"AutoSoftwareUpdateEnabled,omitempty"`
}

type DomainTag struct {
	Key   *string `json:"Key,omitempty"`
	Value *string `json:"Value,omitempty"`
}

type VPCOptions struct {
	EgressEnabled    *bool    `json:"EgressEnabled,omitempty"`
	SecurityGroupIds []string `json:"SecurityGroupIds,omitempty"`
	SubnetIds        []string `json:"SubnetIds,omitempty"`
}

type Domain struct {
	AIMLOptions                   *AIMLOptions                   `json:"AIMLOptions,omitempty"`
	AccessPolicies                map[string]any                 `json:"AccessPolicies,omitempty"`
	AdvancedOptions               map[string]string              `json:"AdvancedOptions,omitempty"`
	AdvancedSecurityOptions       *AdvancedSecurityOptionsInput  `json:"AdvancedSecurityOptions,omitempty"`
	Arn                           *string                        `json:"Arn,omitempty"`
	AutomatedSnapshotPauseOptions *AutomatedSnapshotPauseOptions `json:"AutomatedSnapshotPauseOptions,omitempty"`
	ClusterConfig                 *ClusterConfig                 `json:"ClusterConfig,omitempty"`
	CognitoOptions                *CognitoOptions                `json:"CognitoOptions,omitempty"`
	DeploymentStrategyOptions     *DeploymentStrategyOptions     `json:"DeploymentStrategyOptions,omitempty"`
	DomainArn                     *string                        `json:"DomainArn,omitempty"`
	DomainEndpoint                *string                        `json:"DomainEndpoint,omitempty"`
	DomainEndpointOptions         *DomainEndpointOptions         `json:"DomainEndpointOptions,omitempty"`
	DomainEndpointV2              *string                        `json:"DomainEndpointV2,omitempty"`
	DomainEndpoints               map[string]string              `json:"DomainEndpoints,omitempty"`
	DomainName                    *string                        `json:"DomainName,omitempty"`
	EBSOptions                    *EBSOptions                    `json:"EBSOptions,omitempty"`
	EncryptionAtRestOptions       *EncryptionAtRestOptions       `json:"EncryptionAtRestOptions,omitempty"`
	EngineMode                    *DomainEngineMode              `json:"EngineMode,omitempty"`
	EngineVersion                 *string                        `json:"EngineVersion,omitempty"`
	IPAddressType                 *string                        `json:"IPAddressType,omitempty"`
	Id                            *string                        `json:"Id,omitempty"`
	IdentityCenterOptions         *IdentityCenterOptions         `json:"IdentityCenterOptions,omitempty"`
	LogPublishingOptions          map[string]LogPublishingOption `json:"LogPublishingOptions,omitempty"`
	NodeToNodeEncryptionOptions   *NodeToNodeEncryptionOptions   `json:"NodeToNodeEncryptionOptions,omitempty"`
	OffPeakWindowOptions          *OffPeakWindowOptions          `json:"OffPeakWindowOptions,omitempty"`
	ServiceSoftwareOptions        *ServiceSoftwareOptions        `json:"ServiceSoftwareOptions,omitempty"`
	SkipShardMigrationWait        *bool                          `json:"SkipShardMigrationWait,omitempty"`
	SnapshotOptions               *SnapshotOptions               `json:"SnapshotOptions,omitempty"`
	SoftwareUpdateOptions         *SoftwareUpdateOptions         `json:"SoftwareUpdateOptions,omitempty"`
	Tags                          []DomainTag                    `json:"Tags,omitempty"`
	UseCase                       *DomainUseCase                 `json:"UseCase,omitempty"`
	VPCOptions                    *VPCOptions                    `json:"VPCOptions,omitempty"`
}

func (Domain) CloudJamType() string { return "AWS::OpenSearchService::Domain" }

type AppConfigType string

const (
	AppConfigTypeOpensearchDashboardsDashboardAdminUsers  AppConfigType = "opensearchDashboards.dashboardAdmin.users"
	AppConfigTypeOpensearchDashboardsDashboardAdminGroups AppConfigType = "opensearchDashboards.dashboardAdmin.groups"
)

type NodeOptionNodeType string

const (
	NodeOptionNodeTypeCoordinator NodeOptionNodeType = "coordinator"
)

type DeploymentStrategyOptionsDeploymentStrategy string

const (
	DeploymentStrategyOptionsDeploymentStrategyDefault           DeploymentStrategyOptionsDeploymentStrategy = "Default"
	DeploymentStrategyOptionsDeploymentStrategyCapacityOptimized DeploymentStrategyOptionsDeploymentStrategy = "CapacityOptimized"
)

type DomainEngineMode string

const (
	DomainEngineModeGENERAL   DomainEngineMode = "GENERAL"
	DomainEngineModeOPTIMIZED DomainEngineMode = "OPTIMIZED"
)

type RolesKeyIdcType string

const (
	RolesKeyIdcTypeGroupName RolesKeyIdcType = "GroupName"
	RolesKeyIdcTypeGroupId   RolesKeyIdcType = "GroupId"
)

type SubjectKeyIdcType string

const (
	SubjectKeyIdcTypeUserName SubjectKeyIdcType = "UserName"
	SubjectKeyIdcTypeUserId   SubjectKeyIdcType = "UserId"
	SubjectKeyIdcTypeEmail    SubjectKeyIdcType = "Email"
)

type DomainUseCase string

const (
	DomainUseCaseSEARCH        DomainUseCase = "SEARCH"
	DomainUseCaseVECTOR        DomainUseCase = "VECTOR"
	DomainUseCaseOBSERVABILITY DomainUseCase = "OBSERVABILITY"
	DomainUseCaseMIXED         DomainUseCase = "MIXED"
)
