// Code generated by go generate; DO NOT EDIT.

package sdb

// The iam actions of the aws sdb service. They are untyped so they can be
// used wherever a policy.Action is expected without importing anything.
const (
	ActionBatchDeleteAttributes = "sdb:BatchDeleteAttributes"
	ActionBatchPutAttributes    = "sdb:BatchPutAttributes"
	ActionCreateDomain          = "sdb:CreateDomain"
	ActionDeleteAttributes      = "sdb:DeleteAttributes"
	ActionDeleteDomain          = "sdb:DeleteDomain"
	ActionDomainMetadata        = "sdb:DomainMetadata"
	ActionGetAttributes         = "sdb:GetAttributes"
	ActionGetExport             = "sdb:GetExport"
	ActionListDomains           = "sdb:ListDomains"
	ActionListExports           = "sdb:ListExports"
	ActionPutAttributes         = "sdb:PutAttributes"
	ActionSelect                = "sdb:Select"
	ActionStartDomainExport     = "sdb:StartDomainExport"
)

// ActionsList are the list actions, as classified by aws.
var ActionsList = []string{
	ActionListDomains,
	ActionListExports,
}

// ActionsRead are the read actions, as classified by aws.
var ActionsRead = []string{
	ActionDomainMetadata,
	ActionGetAttributes,
	ActionGetExport,
	ActionSelect,
}

// ActionsWrite are the write actions, as classified by aws.
var ActionsWrite = []string{
	ActionBatchDeleteAttributes,
	ActionBatchPutAttributes,
	ActionCreateDomain,
	ActionDeleteAttributes,
	ActionDeleteDomain,
	ActionPutAttributes,
	ActionStartDomainExport,
}
